import type { MarketplaceOffer } from "@payn/types";

export const catalogExpansionOffers: MarketplaceOffer[] = [

  // ═══════════════════════════════════════════════════
  // BANKING — traditional banks (0 offers existed before)
  // ═══════════════════════════════════════════════════
  {
    id: "banking-ing-direct",
    slug: "ing-direct-banking",
    category: "banking",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "BE", "AT", "LU"],
    providerMark: "ING",
    providerName: "ING",
    title: "ING Direct Account",
    subtitle: "One of Europe's largest direct banks. Free everyday account with mobile-first banking, instant payments, and no monthly fees.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Countries", value: "8 European markets" },
      { label: "SEPA transfers", value: "Instant" },
    ],
    bestFor: ["No monthly fee", "EU-wide", "Mobile-first"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://www.ing.nl/particulier/betalen/betaalrekening/index.html",
    affiliateLink: "https://www.ing.nl/particulier/betalen/betaalrekening/index.html",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["banking", "traditional bank", "ING", "free account"] },
  },
  {
    id: "banking-santander-current",
    slug: "santander-current-account",
    category: "banking",
    countryCodes: ["ES", "UK", "PT", "DE", "IT", "FR"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander Current Account",
    subtitle: "Retail current account from one of Europe's largest banks. Available across six countries with a well-known brand and branch network.",
    metrics: [
      { label: "Monthly fee", value: "Free (conditions apply)" },
      { label: "Countries", value: "ES, UK, PT, DE, IT, FR" },
      { label: "Cards", value: "Debit + optional credit" },
    ],
    bestFor: ["EU-wide", "Branch access", "Established bank"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.santander.co.uk/personal/current-accounts",
    affiliateLink: "https://www.santander.co.uk/personal/current-accounts",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["banking", "current account", "Santander"] },
  },
  {
    id: "banking-bbva-cuenta",
    slug: "bbva-cuenta-corriente",
    category: "banking",
    countryCodes: ["ES", "IT"],
    providerMark: "BBVA",
    providerName: "BBVA",
    title: "BBVA Cuenta Online",
    subtitle: "Spanish digital-first current account with no maintenance fees, instant transfers, and a clean mobile app backed by a major European bank.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "ATM withdrawals", value: "Free at BBVA ATMs" },
      { label: "Online banking", value: "Full mobile and web app" },
    ],
    bestFor: ["Spain", "No maintenance fee", "Digital banking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://www.bbva.es/personas/productos/cuentas/cuenta-online-sin-comisiones.html",
    affiliateLink: "https://www.bbva.es/personas/productos/cuentas/cuenta-online-sin-comisiones.html",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "Spain", "BBVA", "cuenta online"] },
  },
  {
    id: "banking-bnp-paribas-hello",
    slug: "bnp-paribas-hello-bank",
    category: "banking",
    countryCodes: ["FR", "BE", "DE", "AT", "IT"],
    providerMark: "BNP",
    providerName: "BNP Paribas",
    title: "Hello bank! by BNP Paribas",
    subtitle: "Digital bank subsidiary of BNP Paribas. Full account functionality, mobile-first UX, and the backing of one of Europe's largest financial groups.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Countries", value: "FR, BE, DE, AT, IT" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["France", "Digital banking", "BNP backing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://www.hellobank.fr/offres/cartes/hello-prime/",
    affiliateLink: "https://www.hellobank.fr/offres/cartes/hello-prime/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["banking", "France", "BNP Paribas", "hello bank"] },
  },
  {
    id: "banking-barclays-uk",
    slug: "barclays-current-account",
    category: "banking",
    countryCodes: ["UK"],
    providerMark: "BAR",
    providerName: "Barclays",
    title: "Barclays Current Account",
    subtitle: "UK's established high-street bank with a strong digital app, broad ATM network, and access to mortgages, savings, and insurance.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Overdraft", value: "From 24.9% EAR" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["UK residents", "High-street access", "Full banking services"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://www.barclays.co.uk/current-accounts/",
    affiliateLink: "https://www.barclays.co.uk/current-accounts/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "UK bank", "Barclays", "high-street"] },
  },
  {
    id: "banking-nationwide-uk",
    slug: "nationwide-flex-account",
    category: "banking",
    countryCodes: ["UK"],
    providerMark: "NW",
    providerName: "Nationwide",
    title: "Nationwide FlexDirect",
    subtitle: "UK's leading building society. FlexDirect offers 5% AER on balances up to GBP 1,500 for the first year and a full current account.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Interest (Y1)", value: "5% AER on up to GBP 1,500" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["UK residents", "In-credit interest", "Building society trust"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://www.nationwide.co.uk/current-accounts/",
    affiliateLink: "https://www.nationwide.co.uk/current-accounts/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "UK bank", "Nationwide", "interest account"] },
  },
  {
    id: "banking-deutsche-bank-de",
    slug: "deutsche-bank-girokonto",
    category: "banking",
    countryCodes: ["DE"],
    providerMark: "DB",
    providerName: "Deutsche Bank",
    title: "Deutsche Bank Girokonto",
    subtitle: "Germany's largest private bank. Full-service current account with a strong mobile app, branch network, and access to credit and investment products.",
    metrics: [
      { label: "Monthly fee", value: "From EUR 0 (conditions)" },
      { label: "ATM network", value: "CashGroup (fee-free)" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["Germany", "Branch access", "Full service banking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.74,
    providerWebsiteUrl: "https://www.deutsche-bank.de/pk/konten-und-karten/konten/bestkonto.html",
    affiliateLink: "https://www.deutsche-bank.de/pk/konten-und-karten/konten/bestkonto.html",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "Germany", "Deutsche Bank", "Girokonto"] },
  },
  {
    id: "banking-societe-generale-fr",
    slug: "societe-generale-compte",
    category: "banking",
    countryCodes: ["FR"],
    providerMark: "SG",
    providerName: "Société Générale",
    title: "Société Générale Compte Courant",
    subtitle: "France's third-largest bank with a modern digital app, full branch network, and strong product breadth from savings to mortgages.",
    metrics: [
      { label: "Monthly fee", value: "EUR 7.50" },
      { label: "Cards", value: "Visa Classic included" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["France", "Full-service bank", "Branch access"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.72,
    providerWebsiteUrl: "https://particuliers.sg.fr/banque-quotidien/comptes-bancaires/",
    affiliateLink: "https://particuliers.sg.fr/banque-quotidien/comptes-bancaires/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "France", "Société Générale"] },
  },
  {
    id: "banking-caixabank-es",
    slug: "caixabank-cuenta-dia",
    category: "banking",
    countryCodes: ["ES", "PT"],
    providerMark: "CX",
    providerName: "CaixaBank",
    title: "CaixaBank Cuenta Día",
    subtitle: "Spain's largest bank by assets with a strong digital proposition, broad ATM network, and full retail banking services.",
    metrics: [
      { label: "Monthly fee", value: "Free (salary/salary conditions)" },
      { label: "Countries", value: "Spain and Portugal" },
      { label: "ATM network", value: "Largest Spanish ATM network" },
    ],
    bestFor: ["Spain", "No fee (salary)", "Largest ATM network"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://www.dayonecaixabank.es/",
    affiliateLink: "https://www.dayonecaixabank.es/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "Spain", "CaixaBank"] },
  },
  {
    id: "banking-intesa-sanpaolo-it",
    slug: "intesa-sanpaolo-conto",
    category: "banking",
    countryCodes: ["IT"],
    providerMark: "IS",
    providerName: "Intesa Sanpaolo",
    title: "Intesa Sanpaolo Conto Corrente",
    subtitle: "Italy's largest banking group with a strong app, broad ATM coverage, and full-service retail banking from insurance to investments.",
    metrics: [
      { label: "Monthly fee", value: "From EUR 0 (conditions)" },
      { label: "ATM access", value: "60,000+ Intesa ATMs" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["Italy", "Branch access", "Full banking services"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.73,
    providerWebsiteUrl: "https://www.intesasanpaolo.com/it/persone/conti-correnti/xme-conto.html",
    affiliateLink: "https://www.intesasanpaolo.com/it/persone/conti-correnti/xme-conto.html",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "Italy", "Intesa Sanpaolo"] },
  },
  {
    id: "banking-unicredit-eu",
    slug: "unicredit-banking",
    category: "banking",
    countryCodes: ["IT", "DE", "AT", "HR", "CZ", "RO"],
    providerMark: "UC",
    providerName: "UniCredit",
    title: "UniCredit Personal Banking",
    subtitle: "Pan-European banking group with strong presence in Italy, Germany, and Austria. Full account services with digital and branch access.",
    metrics: [
      { label: "Countries", value: "IT, DE, AT + Central/Eastern EU" },
      { label: "Cards", value: "Debit and credit options" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["Italy", "Germany", "European mobility"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.75,
    providerWebsiteUrl: "https://www.unicredit.it/it/privati/conti-correnti/my-genius.html",
    affiliateLink: "https://www.unicredit.it/it/privati/conti-correnti/my-genius.html",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["banking", "UniCredit", "Italy", "Germany"] },
  },
  {
    id: "banking-millennium-pt",
    slug: "millennium-bcp-banking",
    category: "banking",
    countryCodes: ["PT"],
    providerMark: "MB",
    providerName: "Millennium BCP",
    title: "Millennium BCP Conta Activa",
    subtitle: "Portugal's largest private bank. Digital-first current account with fee-free conditions for salary customers and broad ATM access.",
    metrics: [
      { label: "Monthly fee", value: "Free (salary conditions)" },
      { label: "ATM access", value: "Multibanco network" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["Portugal", "Salary account", "Multibanco access"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    providerWebsiteUrl: "https://www.millenniumbcp.pt/pt/particulares/contas/",
    affiliateLink: "https://www.millenniumbcp.pt/pt/particulares/contas/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["banking", "Portugal", "Millennium BCP"] },
  },

  // ═══════════════════════════════════════════════════
  // EXCHANGE — XE Personal + XE Business (FinanceAds)
  // ═══════════════════════════════════════════════════
  {
    id: "exchange-xe-personal",
    slug: "xe-personal-exchange",
    category: "exchange",
    countryCodes: ["EU", "UK"],
    providerMark: "XE",
    providerName: "XE",
    title: "XE Personal Currency Exchange",
    subtitle: "Live mid-market rates, rate alerts, and international transfers for individuals. One of the world's most-trusted currency tools.",
    metrics: [
      { label: "Rate type", value: "Mid-market with transparent margin" },
      { label: "Currencies", value: "130+" },
      { label: "Rate alerts", value: "Free email and app alerts" },
    ],
    bestFor: ["Rate alerts", "Mid-market rate", "Currency tracking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://www.xe.com/personal-money-transfer/",
    affiliateLink: "https://www.xe.com/personal-money-transfer/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", monetized: false, affiliate: true, isPartner: true, searchTags: ["exchange", "currency", "XE", "rate alerts", "fx"] },
  },
  {
    id: "exchange-xe-business",
    slug: "xe-business-exchange",
    category: "exchange",
    countryCodes: ["EU", "UK"],
    providerMark: "XE",
    providerName: "XE",
    title: "XE Business FX",
    subtitle: "Business-grade FX and international payments with competitive rates, batch payment tools, and dedicated account management.",
    metrics: [
      { label: "Rate type", value: "Competitive business FX rates" },
      { label: "Currencies", value: "130+" },
      { label: "Batch payments", value: "Supported" },
    ],
    bestFor: ["Business FX", "Batch payments", "Competitive rates"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://www.xe.com/business/",
    affiliateLink: "https://www.xe.com/business/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", monetized: false, affiliate: true, isPartner: true, searchTags: ["exchange", "business fx", "XE Business", "international payments"] },
  },

  // ═══════════════════════════════════════════════════
  // BUDGETING — Snoop (FinanceAds) + extra offers
  // ═══════════════════════════════════════════════════
  {
    id: "budgeting-snoop",
    slug: "snoop-budgeting",
    category: "budgeting",
    countryCodes: ["UK"],
    providerMark: "SN",
    providerName: "Snoop",
    title: "Snoop Money App",
    subtitle: "UK money-saving app that connects to your bank accounts and finds savings on bills, subscriptions, and daily spending. Free to use.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Bank connections", value: "Open banking (UK)" },
      { label: "Bill savings", value: "Average GBP 1,500/year found" },
    ],
    bestFor: ["UK residents", "Bill savings", "Spending insights"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    providerWebsiteUrl: "https://snoop.app/features/",
    affiliateLink: "https://snoop.app/features/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", monetized: false, affiliate: true, isPartner: true, searchTags: ["budgeting", "money saving", "Snoop", "open banking", "UK"] },
  },
  {
    id: "budgeting-cleo",
    slug: "cleo-ai-budgeting",
    category: "budgeting",
    countryCodes: ["UK", "EU"],
    providerMark: "CL",
    providerName: "Cleo",
    title: "Cleo AI Assistant",
    subtitle: "AI-powered money assistant that analyses your spending, helps with budgeting, and provides a savings-challenge mode. Popular with younger users.",
    metrics: [
      { label: "Monthly fee", value: "Free (Plus from GBP 5.99)" },
      { label: "AI features", value: "Chat-based spending insights" },
      { label: "Savings mode", value: "Automated round-ups" },
    ],
    bestFor: ["AI budgeting", "Spending insights", "Gen Z"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://web.meetcleo.com/features/",
    affiliateLink: "https://web.meetcleo.com/features/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["budgeting", "AI assistant", "Cleo", "spending insights"] },
  },
  {
    id: "budgeting-chip",
    slug: "chip-auto-savings",
    category: "budgeting",
    countryCodes: ["UK"],
    providerMark: "CH",
    providerName: "Chip",
    title: "Chip Auto-Savings",
    subtitle: "UK auto-savings app that calculates what you can afford to save and moves it automatically. Investment options and competitive interest rates.",
    metrics: [
      { label: "Monthly fee", value: "Free (premium from GBP 3)" },
      { label: "Interest (instant)", value: "Up to 4.84% AER" },
      { label: "Auto-save", value: "AI-calculated savings" },
    ],
    bestFor: ["Auto-savings", "UK residents", "High interest"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.chip.co.uk/features/",
    affiliateLink: "https://www.chip.co.uk/features/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["budgeting", "auto-savings", "Chip", "UK"] },
  },

  // ═══════════════════════════════════════════════════
  // KIDS — additional offers (GoHenry already updated above)
  // ═══════════════════════════════════════════════════
  {
    id: "kids-natwest-rooster",
    slug: "natwest-rooster-money",
    category: "kids",
    countryCodes: ["UK"],
    providerMark: "RO",
    providerName: "Rooster Money",
    title: "Rooster Money by NatWest",
    subtitle: "Pocket money app backed by NatWest. Digital allowance management, chore tracking, savings goals, and a pre-paid Visa card for ages 6–18.",
    metrics: [
      { label: "Monthly fee", value: "Free (app) / GBP 1.99 (card)" },
      { label: "Age range", value: "6–18" },
      { label: "Bank backing", value: "NatWest" },
    ],
    bestFor: ["UK kids", "Chore tracking", "NatWest customers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.roostermoney.com/features/",
    affiliateLink: "https://www.roostermoney.com/features/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["kids", "pocket money", "NatWest", "Rooster Money"] },
  },
  {
    id: "kids-starling-kite",
    slug: "starling-kite-kids",
    category: "kids",
    countryCodes: ["UK"],
    providerMark: "SK",
    providerName: "Starling Kite",
    title: "Starling Kite",
    subtitle: "Pre-paid card for ages 6–16 linked to a parent's Starling account. Real-time spending notifications, spending controls, and weekly allowance automation.",
    metrics: [
      { label: "Monthly fee", value: "GBP 2/month" },
      { label: "Age range", value: "6–16" },
      { label: "Controls", value: "Real-time parental controls" },
    ],
    bestFor: ["Starling customers", "Ages 6–16", "Real-time controls"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://www.starlingbank.com/current-account/children/",
    affiliateLink: "https://www.starlingbank.com/current-account/children/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["kids", "Starling", "Kite", "children's card"] },
  },
  {
    id: "kids-pixpay-fr",
    slug: "pixpay-kids-france",
    category: "kids",
    countryCodes: ["FR", "ES", "IT", "BE"],
    providerMark: "PX",
    providerName: "PixPay",
    title: "PixPay",
    subtitle: "European pocket money app for teens (10–18) with a pre-paid Mastercard, parental controls, and spending coaching. Built for the continental European market.",
    metrics: [
      { label: "Monthly fee", value: "EUR 2.99" },
      { label: "Age range", value: "10–18" },
      { label: "Countries", value: "FR, ES, IT, BE" },
    ],
    bestFor: ["European teens", "Continental Europe", "Parental oversight"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://www.pixpay.fr/fonctionnalites/",
    affiliateLink: "https://www.pixpay.fr/fonctionnalites/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "France", "European teens", "PixPay"] },
  },

  // ═══════════════════════════════════════════════════
  // CRYPTO — expanded (was only 3 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "crypto-kraken-spot",
    slug: "kraken-crypto-spot",
    category: "crypto",
    countryCodes: ["EU", "UK"],
    providerMark: "KR",
    providerName: "Kraken",
    title: "Kraken Crypto Exchange",
    subtitle: "Established crypto exchange with low fees, staking rewards, and 220+ coins. Regulated in multiple EU jurisdictions. Trusted by 10M+ users.",
    metrics: [
      { label: "Fee", value: "From 0.16% maker / 0.26% taker" },
      { label: "Coins", value: "220+" },
      { label: "Staking", value: "Up to 21% APY" },
    ],
    bestFor: ["Low fees", "Staking", "Regulated exchange"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    providerWebsiteUrl: "https://www.kraken.com/features/fee-schedule",
    affiliateLink: "https://www.kraken.com/features/fee-schedule",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", searchTags: ["crypto", "exchange", "Kraken", "staking", "low fees"] },
  },
  {
    id: "crypto-coinbase-eu",
    slug: "coinbase-crypto-eu",
    category: "crypto",
    countryCodes: ["EU", "UK"],
    providerMark: "CB",
    providerName: "Coinbase",
    title: "Coinbase Crypto",
    subtitle: "World's most recognised crypto platform. Buy, sell, and stake 260+ assets with a simple interface and strong regulatory standing in Europe.",
    metrics: [
      { label: "Fee", value: "1.49% for bank buys" },
      { label: "Assets", value: "260+" },
      { label: "Earn", value: "Staking and rewards" },
    ],
    bestFor: ["Beginner friendly", "Regulated", "Staking rewards"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://www.coinbase.com/explore",
    affiliateLink: "https://www.coinbase.com/explore",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", searchTags: ["crypto", "Coinbase", "bitcoin", "staking"] },
  },
  {
    id: "crypto-binance-eu",
    slug: "binance-eu-crypto",
    category: "crypto",
    countryCodes: ["EU"],
    providerMark: "BN",
    providerName: "Binance",
    title: "Binance EU",
    subtitle: "World's largest crypto exchange by volume. Widest asset selection, low fees from 0.1%, and deep liquidity across spot and advanced markets.",
    metrics: [
      { label: "Fee", value: "From 0.10%" },
      { label: "Assets", value: "350+" },
      { label: "Volume", value: "World's largest exchange" },
    ],
    bestFor: ["Active traders", "Lowest fees", "Wide asset choice"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.binance.com/en-EU",
    affiliateLink: "https://www.binance.com/en-EU/register",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "Binance", "trading", "spot market"] },
  },
  {
    id: "crypto-ledger-hardware",
    slug: "ledger-hardware-wallet",
    category: "crypto",
    countryCodes: ["EU", "UK"],
    providerMark: "LD",
    providerName: "Ledger",
    title: "Ledger Nano Hardware Wallet",
    subtitle: "Industry-leading hardware wallet for self-custodying Bitcoin, Ethereum, and 5,500+ crypto assets. Ledger Nano S Plus from EUR 79.",
    metrics: [
      { label: "Price", value: "From EUR 79 (Nano S Plus)" },
      { label: "Assets", value: "5,500+" },
      { label: "Security", value: "Certified secure chip (CC EAL5+)" },
    ],
    bestFor: ["Self-custody", "Cold storage", "Maximum security"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.ledger.com/store/",
    affiliateLink: "https://www.ledger.com/store/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", searchTags: ["crypto", "hardware wallet", "Ledger", "cold storage", "security"] },
  },
  {
    id: "crypto-bitpanda-eu",
    slug: "bitpanda-crypto-eu",
    category: "crypto",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda Crypto",
    subtitle: "Austrian crypto and investing platform. Buy Bitcoin, Ethereum and 400+ assets with EUR. Recurring plans, staking, and regulated under EU MiCA.",
    metrics: [
      { label: "Spread", value: "~1% (included in quote)" },
      { label: "Assets", value: "400+" },
      { label: "Recurring", value: "Crypto savings plans" },
    ],
    bestFor: ["Euro users", "Regulated platform", "Recurring crypto"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.bitpanda.com/en/crypto",
    affiliateLink: "https://www.bitpanda.com/en/crypto",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "Bitpanda", "MiCA regulated", "Austria", "recurring"] },
  },

  // ═══════════════════════════════════════════════════
  // SAVINGS — additional offers (had 6, adding more for coverage)
  // ═══════════════════════════════════════════════════
  {
    id: "savings-ing-nl",
    slug: "ing-savings-nl",
    category: "savings",
    countryCodes: ["NL", "DE", "BE"],
    providerMark: "ING",
    providerName: "ING",
    title: "ING Savings Account",
    subtitle: "Simple savings account from ING with competitive rates and SEPA-wide access. No monthly fees, easy to open alongside an ING current account.",
    metrics: [
      { label: "AER", value: "Competitive rate (check live)" },
      { label: "Minimum", value: "EUR 0" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["ING customers", "Netherlands", "No-minimum savings"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://www.ing.nl/particulier/sparen",
    affiliateLink: "https://www.ing.nl/particulier/sparen",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "ING", "Netherlands", "deposit"] },
  },
  {
    id: "savings-santander-uk",
    slug: "santander-uk-savings",
    category: "savings",
    countryCodes: ["UK"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander UK Savings",
    subtitle: "UK savings accounts from Santander with competitive easy-access and fixed-term options. FSCS protected up to GBP 85,000.",
    metrics: [
      { label: "Easy access AER", value: "Competitive (check live)" },
      { label: "Fixed term", value: "1-year ISA available" },
      { label: "Protection", value: "FSCS GBP 85,000" },
    ],
    bestFor: ["UK residents", "ISA wrapper", "Fixed-term savings"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://www.santander.co.uk/personal/savings",
    affiliateLink: "https://www.santander.co.uk/personal/savings",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "local", searchTags: ["savings", "Santander", "UK", "ISA"] },
  },

  // ═══════════════════════════════════════════════════
  // NEOBANKS — extra European coverage
  // ═══════════════════════════════════════════════════
  {
    id: "neobank-vivid-de",
    slug: "vivid-money-neobank",
    category: "neobanks",
    countryCodes: ["DE", "ES", "FR", "IT", "PT", "NL"],
    providerMark: "VV",
    providerName: "Vivid Money",
    title: "Vivid Money",
    subtitle: "German neobank combining everyday banking with investing and cashback. Free account with EUR 100 cashback voucher for new customers.",
    metrics: [
      { label: "Monthly fee", value: "Free (Prime from EUR 9.90)" },
      { label: "Cashback", value: "Up to 10% on partner brands" },
      { label: "Investing", value: "Built-in stocks and ETFs" },
    ],
    bestFor: ["Germany", "Cashback", "Banking + investing combo"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://vivid.money/en-de/pricing/",
    affiliateLink: "https://vivid.money/en-de/pricing/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "Germany", "Vivid Money", "cashback"] },
  },

  // ═══════════════════════════════════════════════════
  // BUSINESS — Wise Business already updated, extra offers
  // ═══════════════════════════════════════════════════
  {
    id: "business-wise-eu",
    slug: "wise-business-account",
    category: "business",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Business Account",
    subtitle: "Multi-currency business account for paying international suppliers, receiving foreign currency revenue, and managing FX in one place.",
    metrics: [
      { label: "Currencies", value: "50+ currencies" },
      { label: "FX fee", value: "From 0.35%" },
      { label: "Monthly fee", value: "No monthly fee" },
    ],
    bestFor: ["International payments", "Multi-currency", "No monthly fee"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://wise.com/business",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676594T",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", monetized: false, affiliate: true, isPartner: true, searchTags: ["business", "Wise Business", "international payments", "multi-currency"] },
  },

  // ═══════════════════════════════════════════════════
  // BUSINESS — additional providers
  // ═══════════════════════════════════════════════════
  {
    id: "business-qonto-eu",
    slug: "qonto-business-account",
    category: "business",
    countryCodes: ["FR", "DE", "ES", "IT", "PT", "NL", "BE", "AT"],
    providerMark: "Q",
    providerName: "Qonto",
    title: "Qonto Business Account",
    subtitle: "European neobank built for SMEs and freelancers. IBAN in 5 minutes, expense tracking, team cards, and seamless accounting integrations.",
    metrics: [
      { label: "Monthly fee", value: "From €9/month" },
      { label: "Countries", value: "FR, DE, ES, IT, PT, NL, BE, AT" },
      { label: "Team cards", value: "Unlimited" },
    ],
    bestFor: ["SMEs", "Expense management", "Accounting integrations"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://qonto.com",
    affiliateLink: "https://qonto.com",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Qonto", "SME", "neobank", "expense management"] },
  },
  {
    id: "business-tide-uk-de",
    slug: "tide-business-account",
    category: "business",
    countryCodes: ["UK", "DE"],
    providerMark: "T",
    providerName: "Tide",
    title: "Tide Business Account",
    subtitle: "UK-based business banking platform with a free tier, instant account opening, invoice tools, and FSCS-protected accounts via Banking Circle.",
    metrics: [
      { label: "Monthly fee", value: "Free (paid plans available)" },
      { label: "Countries", value: "UK, DE" },
      { label: "Invoicing", value: "Built-in" },
    ],
    bestFor: ["UK businesses", "Free tier", "Invoicing tools"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.tide.co/business-bank-account/",
    affiliateLink: "https://www.tide.co/business-bank-account/",
    updatedAt: "2026-05-19T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Tide", "UK business", "SME", "free account"] },
  },
  {
    id: "business-starling-business-uk",
    slug: "starling-business-account",
    category: "business",
    countryCodes: ["UK"],
    providerMark: "SB",
    providerName: "Starling Bank",
    title: "Starling Business Account",
    subtitle: "Award-winning UK business account with no monthly fees, integrated bookkeeping via FreeAgent, and a full-featured mobile app.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "FCA regulated", value: "Yes" },
      { label: "Bookkeeping", value: "FreeAgent integration" },
    ],
    bestFor: ["UK SMEs", "No monthly fee", "FCA regulated"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://www.starlingbank.com/business-account/",
    affiliateLink: "https://www.starlingbank.com/business-account/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Starling", "UK business", "free account", "FCA"] },
  },
  {
    id: "business-mettle-uk",
    slug: "mettle-business-account",
    category: "business",
    countryCodes: ["UK"],
    providerMark: "M",
    providerName: "Mettle",
    title: "Mettle Business Account",
    subtitle: "Free UK business account by NatWest Group with built-in FreeAgent accounting, sole trader support, and a clean mobile experience.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Accounting", value: "FreeAgent included" },
      { label: "Backed by", value: "NatWest Group" },
    ],
    bestFor: ["Sole traders", "Freelancers", "Free accounting"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://mettle.co.uk",
    affiliateLink: "https://mettle.co.uk",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Mettle", "UK business", "sole trader", "freelancer"] },
  },
  {
    id: "business-finom-eu",
    slug: "finom-business-account",
    category: "business",
    countryCodes: ["DE", "NL", "FR", "IT", "ES", "PT"],
    providerMark: "F",
    providerName: "Finom",
    title: "Finom Business Account",
    subtitle: "European business account for freelancers and SMEs with a free tier, instant IBAN, cashback on card spend, and built-in invoicing.",
    metrics: [
      { label: "Monthly fee", value: "Free (paid plans available)" },
      { label: "Cashback", value: "Up to 3%" },
      { label: "Invoicing", value: "Built-in" },
    ],
    bestFor: ["Freelancers", "Cashback", "EU coverage"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://finom.co",
    affiliateLink: "https://finom.co",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Finom", "SME", "cashback", "freelancer"] },
  },
  {
    id: "business-anna-uk",
    slug: "anna-money-business-account",
    category: "business",
    countryCodes: ["UK"],
    providerMark: "A",
    providerName: "Anna Money",
    title: "Anna Money Business Account",
    subtitle: "UK business account with automated bookkeeping, VAT filing, invoicing, and a Mastercard debit card. Built for freelancers and small businesses.",
    metrics: [
      { label: "Monthly fee", value: "Free (paid plans available)" },
      { label: "Tax tools", value: "VAT filing built-in" },
      { label: "Invoicing", value: "Automated" },
    ],
    bestFor: ["UK freelancers", "VAT filing", "Automated bookkeeping"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://anna.money/business-account",
    affiliateLink: "https://anna.money/business-account",
    updatedAt: "2026-05-19T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Anna Money", "UK business", "VAT", "bookkeeping"] },
  },
  {
    id: "business-holvi-eu",
    slug: "holvi-business-account",
    category: "business",
    countryCodes: ["FI", "DE", "AT", "BE", "EE", "IE"],
    providerMark: "H",
    providerName: "Holvi",
    title: "Holvi Business Account",
    subtitle: "Finnish fintech business account for self-employed professionals. Includes invoicing, online store, expense tracking, and a Mastercard.",
    metrics: [
      { label: "Monthly fee", value: "From €9/month" },
      { label: "Invoicing", value: "Built-in" },
      { label: "Online store", value: "Included" },
    ],
    bestFor: ["Self-employed", "Invoicing", "Nordic markets"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://holvi.com",
    affiliateLink: "https://holvi.com",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "Holvi", "Finland", "self-employed", "invoicing"] },
  },
  {
    id: "business-n26-business-eu",
    slug: "n26-business-account",
    category: "business",
    countryCodes: ["DE", "FR", "ES", "IT", "NL", "PT", "AT", "BE", "IE"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Business Account",
    subtitle: "Mobile-first European business account with cashback on purchases, free foreign currency spending, and a clean banking app. No monthly fee on the basic plan.",
    metrics: [
      { label: "Monthly fee", value: "Free (paid plans available)" },
      { label: "Cashback", value: "0.1% on card spend" },
      { label: "Foreign spending", value: "No FX fees" },
    ],
    bestFor: ["EU freelancers", "No FX fees", "Mobile banking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://n26.com/business",
    affiliateLink: "https://n26.com/business",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: false, affiliate: true, searchTags: ["business", "N26 Business", "EU", "cashback", "neobank"] },
  },

  // ═══════════════════════════════════════════════════
  // TRANSFERS — extra coverage beyond Wise
  // ═══════════════════════════════════════════════════
  {
    id: "transfers-xe-personal",
    slug: "xe-international-transfer",
    category: "transfers",
    countryCodes: ["EU", "UK"],
    providerMark: "XE",
    providerName: "XE",
    title: "XE International Transfer",
    subtitle: "Trusted currency service with competitive rates on international transfers. Rate alerts, 130+ currencies, and no transfer fees for personal accounts.",
    metrics: [
      { label: "Transfer fee", value: "No fee (spread applies)" },
      { label: "Currencies", value: "130+" },
      { label: "Rate alerts", value: "Free" },
    ],
    bestFor: ["No transfer fee", "Rate alerts", "Large transfers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://www.xe.com/send-money/",
    affiliateLink: "https://www.xe.com/send-money/",
    updatedAt: "2026-05-11T00:00:00Z",
    attributes: { availability: "international", monetized: false, affiliate: true, isPartner: true, searchTags: ["transfers", "XE", "international", "no fee"] },
  },
];
