import type { MarketplaceOffer, MarketplaceOfferAttributes } from "@payn/types";

type LoanSeed = {
  id: string;
  slug: string;
  providerMark: string;
  providerName: string;
  title: string;
  subtitle: string;
  countryCodes: string[];
  providerWebsiteUrl: string;
  affiliateLink?: string;
  affiliatePriorityScore: number;
  apr: string;
  amount: string;
  term: string;
  bestFor: string[];
  attributes?: MarketplaceOfferAttributes;
};

type CardSeed = {
  id: string;
  slug: string;
  providerMark: string;
  providerName: string;
  title: string;
  subtitle: string;
  countryCodes: string[];
  providerWebsiteUrl: string;
  affiliateLink?: string;
  affiliatePriorityScore: number;
  annualFee: string;
  fxFee: string;
  cashback: string;
  atm: string;
  bestFor: string[];
  attributes?: MarketplaceOfferAttributes;
};

type TransferSeed = {
  id: string;
  slug: string;
  providerMark: string;
  providerName: string;
  title: string;
  subtitle: string;
  countryCodes: string[];
  providerWebsiteUrl: string;
  affiliateLink?: string;
  affiliatePriorityScore: number;
  fee: string;
  speed: string;
  currencies: string;
  bestFor: string[];
  attributes?: MarketplaceOfferAttributes;
};

type ExchangeSeed = {
  id: string;
  slug: string;
  providerMark: string;
  providerName: string;
  title: string;
  subtitle: string;
  countryCodes: string[];
  providerWebsiteUrl: string;
  affiliateLink?: string;
  affiliatePriorityScore: number;
  spread: string;
  execution: string;
  currencies: string;
  bestFor: string[];
  attributes?: MarketplaceOfferAttributes;
};

function buildLoanOffer(seed: LoanSeed): MarketplaceOffer {
  return {
    id: seed.id,
    slug: seed.slug,
    category: "loans",
    countryCodes: seed.countryCodes,
    providerMark: seed.providerMark,
    providerName: seed.providerName,
    title: seed.title,
    subtitle: seed.subtitle,
    metrics: [
      { label: "APR", value: seed.apr },
      { label: "Amount", value: seed.amount },
      { label: "Term", value: seed.term },
    ],
    bestFor: seed.bestFor,
    providerWebsiteUrl: seed.providerWebsiteUrl,
    affiliateLink: seed.affiliateLink ?? seed.providerWebsiteUrl,
    linkType: "affiliate_redirect",
    affiliatePriorityScore: seed.affiliatePriorityScore,
    updatedAt: "2026-03-31T00:00:00Z",
    attributes: seed.attributes,
  };
}

function buildCardOffer(seed: CardSeed): MarketplaceOffer {
  return {
    id: seed.id,
    slug: seed.slug,
    category: "cards",
    countryCodes: seed.countryCodes,
    providerMark: seed.providerMark,
    providerName: seed.providerName,
    title: seed.title,
    subtitle: seed.subtitle,
    metrics: [
      { label: "Annual fee", value: seed.annualFee },
      { label: "FX fee", value: seed.fxFee },
      { label: "Cashback", value: seed.cashback },
      { label: "ATM", value: seed.atm },
    ],
    bestFor: seed.bestFor,
    providerWebsiteUrl: seed.providerWebsiteUrl,
    affiliateLink: seed.affiliateLink ?? seed.providerWebsiteUrl,
    linkType: "affiliate_redirect",
    affiliatePriorityScore: seed.affiliatePriorityScore,
    updatedAt: "2026-03-31T00:00:00Z",
    attributes: seed.attributes,
  };
}

function buildTransferOffer(seed: TransferSeed): MarketplaceOffer {
  return {
    id: seed.id,
    slug: seed.slug,
    category: "transfers",
    countryCodes: seed.countryCodes,
    providerMark: seed.providerMark,
    providerName: seed.providerName,
    title: seed.title,
    subtitle: seed.subtitle,
    metrics: [
      { label: "Fee", value: seed.fee },
      { label: "Speed", value: seed.speed },
      { label: "Currencies", value: seed.currencies },
    ],
    bestFor: seed.bestFor,
    providerWebsiteUrl: seed.providerWebsiteUrl,
    affiliateLink: seed.affiliateLink ?? seed.providerWebsiteUrl,
    linkType: "affiliate_redirect",
    affiliatePriorityScore: seed.affiliatePriorityScore,
    updatedAt: "2026-03-31T00:00:00Z",
    attributes: seed.attributes,
  };
}

function buildExchangeOffer(seed: ExchangeSeed): MarketplaceOffer {
  return {
    id: seed.id,
    slug: seed.slug,
    category: "exchange",
    countryCodes: seed.countryCodes,
    providerMark: seed.providerMark,
    providerName: seed.providerName,
    title: seed.title,
    subtitle: seed.subtitle,
    metrics: [
      { label: "Spread", value: seed.spread },
      { label: "Execution", value: seed.execution },
      { label: "Currencies", value: seed.currencies },
    ],
    bestFor: seed.bestFor,
    providerWebsiteUrl: seed.providerWebsiteUrl,
    affiliateLink: seed.affiliateLink ?? seed.providerWebsiteUrl,
    linkType: "affiliate_redirect",
    affiliatePriorityScore: seed.affiliatePriorityScore,
    updatedAt: "2026-03-31T00:00:00Z",
    attributes: seed.attributes,
  };
}

const loanSeeds: LoanSeed[] = [
  {
    id: "loan-credit-agricole-personal",
    slug: "credit-agricole-personal-loan",
    providerMark: "CA",
    providerName: "Credit Agricole",
    title: "Credit Agricole Personal Loan",
    subtitle: "Large-bank personal borrowing with branch-backed support, clearer repayment ranges, and broad household use cases.",
    countryCodes: ["FR", "IT", "PL"],
    providerWebsiteUrl: "https://www.credit-agricole.fr/particulier/credit/credit-personnel.html",
    affiliatePriorityScore: 0.8,
    apr: "4.2% - 9.4%",
    amount: "EUR 3,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["Large banks", "Household expenses", "Advisor support"],
    attributes: { minAmount: 3000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-raiffeisen-flex",
    slug: "raiffeisen-flex-loan",
    providerMark: "RF",
    providerName: "Raiffeisen Bank",
    title: "Raiffeisen Flex Loan",
    subtitle: "Central European personal lending with clean monthly planning and stronger regional coverage for salaried borrowers.",
    countryCodes: ["AT", "DE", "IT", "RO"],
    providerWebsiteUrl: "https://www.raiffeisen.at",
    affiliateLink: "https://www.raiffeisen.at",
    affiliatePriorityScore: 0.77,
    apr: "4.8% - 10.9%",
    amount: "EUR 2,500 - 60,000",
    term: "12 - 96 months",
    bestFor: ["Central Europe", "Stable income", "Longer terms"],
    attributes: { minAmount: 2500, maxAmount: 60000, minTermMonths: 12, maxTermMonths: 96, feeProfile: "medium" },
  },
  {
    id: "loan-younited-credit-plus",
    slug: "younited-credit-plus",
    providerMark: "YC",
    providerName: "Younited Credit",
    title: "Younited Credit Plus",
    subtitle: "Digital consumer lending focused on quick pre-checks, transparent repayments, and wider marketplace-style availability.",
    countryCodes: ["FR", "ES", "IT", "PT"],
    providerWebsiteUrl: "https://www.younited-credit.com/credit",
    affiliateLink: "https://www.younited-credit.com/credit",
    affiliatePriorityScore: 0.84,
    apr: "3.9% - 14.5%",
    amount: "EUR 1,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["Digital-first", "Fast pre-check", "Broad borrowing range"],
    attributes: { minAmount: 1000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "low" },
  },
  {
    id: "loan-ferratum-prime",
    slug: "ferratum-prime-loan",
    providerMark: "FE",
    providerName: "Ferratum",
    title: "Ferratum Prime Loan",
    subtitle: "Mobile-led consumer lending built around quicker approvals and smaller personal borrowing needs.",
    countryCodes: ["DE", "ES", "NL", "PL"],
    providerWebsiteUrl: "https://www.multitude.com/",
    affiliateLink: "https://www.multitude.com/",
    affiliatePriorityScore: 0.73,
    apr: "7.5% - 18.9%",
    amount: "EUR 500 - 15,000",
    term: "6 - 48 months",
    bestFor: ["Smaller loans", "Quick check", "Mobile users"],
    attributes: { minAmount: 500, maxAmount: 15000, minTermMonths: 6, maxTermMonths: 48, feeProfile: "medium" },
  },
  {
    id: "loan-bondora-go-grow-credit",
    slug: "bondora-go-grow-credit",
    providerMark: "BO",
    providerName: "Bondora",
    title: "Bondora Consumer Credit",
    subtitle: "Baltic-rooted digital lending with straightforward online checks and a clean self-service flow.",
    countryCodes: ["EE", "FI", "ES"],
    providerWebsiteUrl: "https://bondora.com/en/",
    affiliatePriorityScore: 0.74,
    apr: "6.9% - 17.9%",
    amount: "EUR 1,000 - 25,000",
    term: "12 - 60 months",
    bestFor: ["Online self-service", "Smaller amounts", "Nordics and Baltics"],
    attributes: { minAmount: 1000, maxAmount: 25000, minTermMonths: 12, maxTermMonths: 60, feeProfile: "medium" },
  },
  {
    id: "loan-credit-mutuel-budget",
    slug: "credit-mutuel-budget-loan",
    providerMark: "CM",
    providerName: "Credit Mutuel",
    title: "Credit Mutuel Budget Loan",
    subtitle: "Traditional French lending with structured budgeting support and clearer repayment planning for mainstream households.",
    countryCodes: ["FR", "BE"],
    providerWebsiteUrl: "https://www.creditmutuel.fr",
    affiliatePriorityScore: 0.78,
    apr: "4.4% - 9.8%",
    amount: "EUR 3,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["France", "Household expenses", "Mainstream borrowing"],
    attributes: { minAmount: 3000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-cetelem-personal",
    slug: "cetelem-personal-credit",
    providerMark: "CT",
    providerName: "Cetelem",
    title: "Cetelem Personal Credit",
    subtitle: "Consumer-focused personal lending with fast digital pre-approval and broader retail-finance familiarity.",
    countryCodes: ["FR", "ES", "IT", "PT"],
    providerWebsiteUrl: "https://www.cetelem.fr/credit-personnel",
    affiliateLink: "https://www.creditmutuel.fr",
    affiliatePriorityScore: 0.79,
    apr: "5.2% - 14.2%",
    amount: "EUR 1,500 - 40,000",
    term: "12 - 72 months",
    bestFor: ["Consumer credit", "Retail finance", "Fast pre-approval"],
    attributes: { minAmount: 1500, maxAmount: 40000, minTermMonths: 12, maxTermMonths: 72, feeProfile: "medium" },
  },
  {
    id: "loan-oney-cash",
    slug: "oney-cash-loan",
    providerMark: "ON",
    providerName: "Oney",
    title: "Oney Cash Loan",
    subtitle: "French consumer-finance lender oriented toward medium-size household borrowing and fast online checks.",
    countryCodes: ["FR", "ES", "PT"],
    providerWebsiteUrl: "https://www.oney.fr",
    affiliatePriorityScore: 0.72,
    apr: "5.9% - 16.5%",
    amount: "EUR 1,000 - 25,000",
    term: "6 - 60 months",
    bestFor: ["Medium amounts", "Household spending", "Simple online flow"],
    attributes: { minAmount: 1000, maxAmount: 25000, minTermMonths: 6, maxTermMonths: 60, feeProfile: "medium" },
  },
  {
    id: "loan-caixabank-personal",
    slug: "caixabank-personal-loan",
    providerMark: "CX",
    providerName: "CaixaBank",
    title: "CaixaBank Personal Loan",
    subtitle: "Large Iberian bank with strong digital onboarding and clearer pricing for salaried borrowers.",
    countryCodes: ["ES", "PT"],
    providerWebsiteUrl: "https://www.caixabank.es/particular/prestamos/",
    affiliatePriorityScore: 0.81,
    apr: "4.7% - 10.6%",
    amount: "EUR 3,000 - 60,000",
    term: "12 - 96 months",
    bestFor: ["Spain", "Large purchases", "Digital onboarding"],
    attributes: { minAmount: 3000, maxAmount: 60000, minTermMonths: 12, maxTermMonths: 96, feeProfile: "medium" },
  },
  {
    id: "loan-pko-cash",
    slug: "pko-cash-loan",
    providerMark: "PK",
    providerName: "PKO Bank Polski",
    title: "PKO Cash Loan",
    subtitle: "Large Central European bank offering broad personal-loan ranges and strong local distribution.",
    countryCodes: ["PL"],
    providerWebsiteUrl: "https://www.pkobp.pl/",
    affiliatePriorityScore: 0.71,
    apr: "5.4% - 12.2%",
    amount: "EUR 1,000 - 45,000",
    term: "12 - 84 months",
    bestFor: ["Poland", "Large bank trust", "Broad ranges"],
    attributes: { minAmount: 1000, maxAmount: 45000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-mbank-ready",
    slug: "mbank-ready-loan",
    providerMark: "MB",
    providerName: "mBank",
    title: "mBank Ready Loan",
    subtitle: "Digital banking loan flow with a cleaner mobile journey and faster pre-qualification.",
    countryCodes: ["PL", "CZ", "SK"],
    providerWebsiteUrl: "https://www.mbank.pl/indywidualny/kredyty/kredyt-gotowkowy/",
    affiliatePriorityScore: 0.75,
    apr: "5.0% - 13.4%",
    amount: "EUR 1,000 - 30,000",
    term: "12 - 72 months",
    bestFor: ["Mobile users", "Fast pre-check", "Central Europe"],
    attributes: { minAmount: 1000, maxAmount: 30000, minTermMonths: 12, maxTermMonths: 72, feeProfile: "low" },
  },
  {
    id: "loan-postbank-comfort",
    slug: "postbank-comfort-loan",
    providerMark: "PB",
    providerName: "Postbank",
    title: "Postbank Comfort Loan",
    subtitle: "German consumer loan built around predictable payments and branch-backed reassurance.",
    countryCodes: ["DE"],
    providerWebsiteUrl: "https://www.postbank.de",
    affiliatePriorityScore: 0.74,
    apr: "4.9% - 10.9%",
    amount: "EUR 3,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["Germany", "Predictable repayments", "Branch support"],
    attributes: { minAmount: 3000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-bank-norwegian-flex",
    slug: "bank-norwegian-flex-loan",
    providerMark: "BN",
    providerName: "Bank Norwegian",
    title: "Bank Norwegian Flex Loan",
    subtitle: "Nordic digital lending with travel-linked customer familiarity and a straightforward online flow.",
    countryCodes: ["NO", "SE", "DK", "FI"],
    providerWebsiteUrl: "https://www.banknorwegian.com/personalloans/",
    affiliateLink: "https://www.pkobp.pl/",
    affiliatePriorityScore: 0.76,
    apr: "6.1% - 15.9%",
    amount: "EUR 1,000 - 35,000",
    term: "12 - 60 months",
    bestFor: ["Nordics", "Online borrowing", "Flexible amounts"],
    attributes: { minAmount: 1000, maxAmount: 35000, minTermMonths: 12, maxTermMonths: 60, feeProfile: "medium" },
  },
  {
    id: "loan-aion-bank-personal",
    slug: "aion-bank-personal-loan",
    providerMark: "AI",
    providerName: "Aion Bank",
    title: "Aion Bank Personal Loan",
    subtitle: "Subscription-style digital bank with faster onboarding and app-based borrowing management.",
    countryCodes: ["BE", "PL", "DE"],
    providerWebsiteUrl: "https://www.aion.eu/personal/loans/",
    affiliatePriorityScore: 0.72,
    apr: "5.7% - 13.9%",
    amount: "EUR 1,000 - 25,000",
    term: "12 - 60 months",
    bestFor: ["Digital banking", "App-first", "Mid-size borrowing"],
    attributes: { minAmount: 1000, maxAmount: 25000, minTermMonths: 12, maxTermMonths: 60, feeProfile: "low" },
  },
  {
    id: "loan-seb-consumer",
    slug: "seb-consumer-loan",
    providerMark: "SEB",
    providerName: "SEB",
    title: "SEB Consumer Loan",
    subtitle: "Nordic bank lending for larger planned expenses with a stronger cross-border banking footprint.",
    countryCodes: ["SE", "LT", "LV", "EE"],
    providerWebsiteUrl: "https://www.seb.se/",
    affiliateLink: "https://www.seb.se/",
    affiliatePriorityScore: 0.75,
    apr: "4.8% - 10.6%",
    amount: "EUR 2,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["Nordics and Baltics", "Large planned expenses", "Bank trust"],
    attributes: { minAmount: 2000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-op-flex",
    slug: "op-flex-loan",
    providerMark: "OP",
    providerName: "OP Financial Group",
    title: "OP Flex Loan",
    subtitle: "Finnish personal loan route with strong digital service and wider regional trust.",
    countryCodes: ["FI"],
    providerWebsiteUrl: "https://www.op.fi",
    affiliatePriorityScore: 0.73,
    apr: "5.1% - 11.4%",
    amount: "EUR 2,000 - 40,000",
    term: "12 - 72 months",
    bestFor: ["Finland", "Digital servicing", "Bank-backed"],
    attributes: { minAmount: 2000, maxAmount: 40000, minTermMonths: 12, maxTermMonths: 72, feeProfile: "medium" },
  },
  {
    id: "loan-rabobank-personal",
    slug: "rabobank-personal-loan",
    providerMark: "RB",
    providerName: "Rabobank",
    title: "Rabobank Personal Loan",
    subtitle: "Dutch bank lending for established customers who want broader repayment flexibility and clearer household budgeting.",
    countryCodes: ["NL"],
    providerWebsiteUrl: "https://www.rabobank.nl/particulieren/lenen/persoonlijke-lening/",
    affiliatePriorityScore: 0.74,
    apr: "4.6% - 9.7%",
    amount: "EUR 3,000 - 60,000",
    term: "12 - 96 months",
    bestFor: ["Netherlands", "Household budgeting", "Flexible repayment"],
    attributes: { minAmount: 3000, maxAmount: 60000, minTermMonths: 12, maxTermMonths: 96, feeProfile: "medium" },
  },
  {
    id: "loan-intesa-xme",
    slug: "intesa-xme-loan",
    providerMark: "IS",
    providerName: "Intesa Sanpaolo",
    title: "Intesa XME Loan",
    subtitle: "Italian consumer lending with broader branch access and a stronger home-market position for mainstream borrowing.",
    countryCodes: ["IT"],
    providerWebsiteUrl: "https://www.intesasanpaolo.com",
    affiliatePriorityScore: 0.74,
    apr: "4.9% - 10.8%",
    amount: "EUR 2,000 - 50,000",
    term: "12 - 84 months",
    bestFor: ["Italy", "Mainstream borrowing", "Large bank trust"],
    attributes: { minAmount: 2000, maxAmount: 50000, minTermMonths: 12, maxTermMonths: 84, feeProfile: "medium" },
  },
  {
    id: "loan-cofidis-personal",
    slug: "cofidis-personal-loan",
    providerMark: "CO",
    providerName: "Cofidis",
    title: "Cofidis Personal Loan",
    subtitle: "Digital consumer lender with fast decisioning and smaller-balance personal borrowing across several EU markets.",
    countryCodes: ["FR", "ES", "IT", "BE", "PT"],
    providerWebsiteUrl: "https://www.cofidis.fr/credit-personnel.html",
    affiliateLink: "https://www.op.fi",
    affiliatePriorityScore: 0.78,
    apr: "6.0% - 16.8%",
    amount: "EUR 500 - 35,000",
    term: "6 - 72 months",
    bestFor: ["Quick decisions", "Smaller balances", "Multi-market"],
    attributes: { minAmount: 500, maxAmount: 35000, minTermMonths: 6, maxTermMonths: 72, feeProfile: "medium" },
  },
  {
    id: "loan-creditea-instant",
    slug: "creditea-instant-loan",
    providerMark: "CR",
    providerName: "Creditea",
    title: "Creditea Instant Loan",
    subtitle: "App-first revolving credit style personal borrowing for smaller needs and faster approvals.",
    countryCodes: ["ES", "PT", "PL", "CZ"],
    providerWebsiteUrl: "https://www.creditea.com/en/personal-loans/",
    affiliateLink: "https://www.creditea.com/en/personal-loans/",
    affiliatePriorityScore: 0.69,
    apr: "8.9% - 19.9%",
    amount: "EUR 300 - 10,000",
    term: "3 - 36 months",
    bestFor: ["Small amounts", "Fast approval", "App-first"],
    attributes: { minAmount: 300, maxAmount: 10000, minTermMonths: 3, maxTermMonths: 36, feeProfile: "premium" },
  },
  {
    id: "loan-cec-bank-personal",
    slug: "cec-bank-personal-loan",
    providerMark: "CEC",
    providerName: "CEC Bank",
    title: "CEC Bank Personal Loan",
    subtitle: "Romanian retail-bank lending with a strong local footprint and broader branch reassurance.",
    countryCodes: ["RO"],
    providerWebsiteUrl: "https://www.cec.ro/produse-si-servicii/credite-persoane-fizice/",
    affiliatePriorityScore: 0.66,
    apr: "5.8% - 12.8%",
    amount: "EUR 1,000 - 30,000",
    term: "12 - 72 months",
    bestFor: ["Romania", "Branch confidence", "Mainstream borrowing"],
    attributes: { minAmount: 1000, maxAmount: 30000, minTermMonths: 12, maxTermMonths: 72, feeProfile: "medium" },
  },
];

const cardSeeds: CardSeed[] = [
  {
    id: "card-paysera-visa",
    slug: "paysera-visa-card",
    providerMark: "PY",
    providerName: "Paysera",
    title: "Paysera Visa Card",
    subtitle: "Low-cost multi-currency spending card with lighter foreign exchange fees and app-based balance control.",
    countryCodes: ["LT", "LV", "EE", "DE", "ES"],
    providerWebsiteUrl: "https://www.paysera.com/v2/en-GB/payment-card",
    affiliateLink: "https://www.cec.ro/produse-si-servicii/credite-persoane-fizice/",
    affiliatePriorityScore: 0.72,
    annualFee: "EUR 0",
    fxFee: "0.25%",
    cashback: "0%",
    atm: "Free up to EUR 600",
    bestFor: ["Travel", "Lower FX", "Multi-currency"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0.25, cashbackPercent: 0, atmFreeLimit: 600, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-vivid-prime",
    slug: "vivid-prime-card",
    providerMark: "VV",
    providerName: "Vivid",
    title: "Vivid Prime Card",
    subtitle: "Fintech card focused on cashback pockets, lighter FX costs, and app-based budgeting.",
    countryCodes: ["DE", "ES", "IT", "NL"],
    providerWebsiteUrl: "https://vivid.money/en-eu/personal/",
    affiliateLink: "https://vivid.money/en-eu/personal/",
    affiliatePriorityScore: 0.76,
    annualFee: "EUR 0 - 9.90/mo",
    fxFee: "0% - 0.5%",
    cashback: "Up to 1%",
    atm: "Free up to EUR 1,000",
    bestFor: ["Cashback", "App-first", "Travel spending"],
    attributes: { annualFeeAmount: 119, fxFeePercent: 0.5, cashbackPercent: 1, atmFreeLimit: 1000, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-lunar-standard",
    slug: "lunar-standard-card",
    providerMark: "LU",
    providerName: "Lunar",
    title: "Lunar Standard Card",
    subtitle: "Nordic spending card with budgeting tools and travel-friendly day-to-day banking features.",
    countryCodes: ["DK", "SE", "NO"],
    providerWebsiteUrl: "https://www.lunar.app/cards/",
    affiliatePriorityScore: 0.73,
    annualFee: "EUR 0",
    fxFee: "0.5%",
    cashback: "0%",
    atm: "Free up to EUR 400",
    bestFor: ["Nordics", "Budgeting", "Everyday banking"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0.5, cashbackPercent: 0, atmFreeLimit: 400, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-tomorrow-change",
    slug: "tomorrow-change-card",
    providerMark: "TM",
    providerName: "Tomorrow Bank",
    title: "Tomorrow Change Card",
    subtitle: "Sustainability-focused debit card with everyday spending tools and cleaner subscription-led benefits.",
    countryCodes: ["DE", "AT", "IT"],
    providerWebsiteUrl: "https://tomorrow.one/",
    affiliatePriorityScore: 0.7,
    annualFee: "EUR 0 - 8/mo",
    fxFee: "0%",
    cashback: "0%",
    atm: "Free up to EUR 500",
    bestFor: ["Sustainable banking", "Travel", "Subscription perks"],
    attributes: { annualFeeAmount: 96, fxFeePercent: 0, cashbackPercent: 0, atmFreeLimit: 500, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-monzo-flex",
    slug: "monzo-flex-card",
    providerMark: "MZ",
    providerName: "Monzo",
    title: "Monzo Flex Card",
    subtitle: "UK spending card with instalment flexibility, strong app UX, and travel-friendly everyday use.",
    countryCodes: ["UK"],
    providerWebsiteUrl: "https://monzo.com/features/monzo-flex/",
    affiliatePriorityScore: 0.77,
    annualFee: "GBP 0",
    fxFee: "0%",
    cashback: "0%",
    atm: "Free up to GBP 200",
    bestFor: ["Travel", "App UX", "Flexible spend"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0, cashbackPercent: 0, atmFreeLimit: 230, cardType: "credit", feeProfile: "low" },
  },
  {
    id: "card-starling-personal",
    slug: "starling-personal-card",
    providerMark: "ST",
    providerName: "Starling Bank",
    title: "Starling Personal Card",
    subtitle: "Clean mobile-first bank card with fee-light spending abroad and a strong trust profile in the UK.",
    countryCodes: ["UK"],
    providerWebsiteUrl: "https://www.starlingbank.com/current-account/",
    affiliatePriorityScore: 0.76,
    annualFee: "GBP 0",
    fxFee: "0%",
    cashback: "0%",
    atm: "Fee-light worldwide ATM access",
    bestFor: ["Travel", "Mobile banking", "No annual fee"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0, cashbackPercent: 0, atmFreeLimit: 350, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-plutus-rewards",
    slug: "plutus-rewards-card",
    providerMark: "PL",
    providerName: "Plutus",
    title: "Plutus Rewards Card",
    subtitle: "Crypto-linked spending card paying rewards in PLU, Plutus's native token. Headline cashback rates scale by subscription tier and PLU staking. The earned value depends on PLU's market price, which is volatile.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.plutus.it/perks",
    affiliateLink: "https://www.plutus.it/perks",
    affiliatePriorityScore: 0.69,
    annualFee: "EUR 0 - 14.99/mo",
    fxFee: "0.5%",
    // CAT.8 — Was "Up to 3%" — that's the entry-tier rate. The
    // headline number Plutus actually promotes is "up to 9% in PLU"
    // (requires top tier subscription + significant PLU staking).
    // Either number is misleading on its own without the token-
    // volatility disclosure. Show the tier and the token together.
    cashback: "3% (Standard) – up to 9% (top tier) — paid in PLU token",
    atm: "Free up to EUR 250",
    bestFor: ["Crypto support", "PLU holders", "Enthusiasts"],
    // CAT.8 — cashbackPercent kept at 3 (the entry-tier rate, what the
    // ranking comparator uses); the 9% upper bound is documented in
    // the `cashback` metric string instead of attributes since the
    // shared MarketplaceOfferAttributes shape doesn't model a range.
    attributes: { annualFeeAmount: 180, fxFeePercent: 0.5, cashbackPercent: 3, atmFreeLimit: 250, cardType: "debit", cryptoSupport: true, feeProfile: "medium" },
  },
  {
    id: "card-soldo-business-lite",
    slug: "soldo-business-lite",
    providerMark: "SO",
    providerName: "Soldo",
    title: "Soldo Business Lite",
    subtitle: "Expense-management card with cleaner team controls, budgeting pockets, and business travel handling.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.soldo.com/en-gb/pricing/",
    affiliateLink: "https://www.soldo.com/en-gb/pricing/",
    affiliatePriorityScore: 0.68,
    annualFee: "EUR 0 - 6/mo per user",
    fxFee: "1%",
    cashback: "0%",
    atm: "Business ATM access",
    bestFor: ["Business spend", "Team cards", "Budget control"],
    attributes: { annualFeeAmount: 72, fxFeePercent: 1, cashbackPercent: 0, atmFreeLimit: 0, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-nickel-classic",
    slug: "nickel-classic-card",
    providerMark: "NK",
    providerName: "Nickel",
    title: "Nickel Classic Card",
    subtitle: "Accessible retail-banking card with lighter onboarding requirements and straightforward everyday spending.",
    countryCodes: ["FR", "ES", "PT", "BE"],
    providerWebsiteUrl: "https://nickel.eu",
    affiliateLink: "https://nickel.eu",
    affiliatePriorityScore: 0.67,
    annualFee: "EUR 25 / year",
    fxFee: "1%",
    cashback: "0%",
    atm: "Domestic ATM access",
    bestFor: ["Easy opening", "Everyday spend", "Retail access"],
    attributes: { annualFeeAmount: 25, fxFeePercent: 1, cashbackPercent: 0, atmFreeLimit: 0, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-boursobank-ultim",
    slug: "boursobank-ultim-card",
    providerMark: "BB",
    providerName: "BoursoBank",
    title: "BoursoBank Ultim",
    subtitle: "French online-banking card with strong travel positioning and low-friction everyday banking.",
    countryCodes: ["FR"],
    providerWebsiteUrl: "https://www.boursobank.com/",
    affiliatePriorityScore: 0.79,
    annualFee: "EUR 0",
    fxFee: "0%",
    cashback: "0%",
    atm: "Fee-light worldwide ATM access",
    bestFor: ["Travel", "France", "No annual fee"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0, cashbackPercent: 0, atmFreeLimit: 300, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-sogexia-premium",
    slug: "sogexia-premium-card",
    providerMark: "SG",
    providerName: "Sogexia",
    title: "Sogexia Premium Card",
    subtitle: "Alternative multi-currency payment card with strong spend controls and simpler cross-border access.",
    countryCodes: ["FR", "IT", "ES", "DE"],
    providerWebsiteUrl: "https://sogexia.com",
    affiliateLink: "https://sogexia.com",
    affiliatePriorityScore: 0.66,
    annualFee: "EUR 0 - 9.90/mo",
    fxFee: "0.75%",
    cashback: "0%",
    atm: "Free up to EUR 300",
    bestFor: ["Alternative banking", "Multi-currency", "Controls"],
    attributes: { annualFeeAmount: 119, fxFeePercent: 0.75, cashbackPercent: 0, atmFreeLimit: 300, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-trade-republic-card",
    slug: "trade-republic-card",
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Card",
    subtitle: "1% Saveback on every spend, dropped straight into an investing plan. Pairs with Trade Republic's 4% rate on uninvested cash.",
    countryCodes: ["DE", "FR", "IT", "ES", "PT"],
    providerWebsiteUrl: "https://traderepublic.com/en-de/card",
    affiliateLink: "https://traderepublic.com/en-de/card",
    affiliatePriorityScore: 0.78,
    annualFee: "EUR 0",
    fxFee: "0%",
    cashback: "1% Saveback",
    atm: "Free up to EUR 100",
    bestFor: ["1% Saveback", "Pairs with 4% cash rate", "Travel"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0, cashbackPercent: 1, atmFreeLimit: 100, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-c24-smart",
    slug: "c24-smart-card",
    providerMark: "C24",
    providerName: "C24 Bank",
    title: "C24 Smart Card",
    subtitle: "German mobile-banking card with everyday budgeting and fee-light European spending.",
    countryCodes: ["DE"],
    providerWebsiteUrl: "https://www.c24bank.de/girokonto/",
    affiliatePriorityScore: 0.71,
    annualFee: "EUR 0",
    fxFee: "0%",
    cashback: "0%",
    atm: "Free in euro area",
    bestFor: ["Germany", "Budgeting", "No annual fee"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0, cashbackPercent: 0, atmFreeLimit: 200, cardType: "debit", feeProfile: "low" },
  },
  {
    id: "card-openbank-visa",
    slug: "openbank-visa-card",
    providerMark: "OB",
    providerName: "Openbank",
    title: "Openbank Visa Card",
    subtitle: "Santander-backed online bank card with stronger travel simplicity and mainstream banking trust.",
    countryCodes: ["ES", "PT", "NL"],
    providerWebsiteUrl: "https://www.openbank.es",
    affiliatePriorityScore: 0.72,
    annualFee: "EUR 0",
    fxFee: "0.5%",
    cashback: "0%",
    atm: "Free at Santander ATMs",
    bestFor: ["Spain", "Bank trust", "Travel simplicity"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 0.5, cashbackPercent: 0, atmFreeLimit: 250, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-aion-everyday",
    slug: "aion-everyday-card",
    providerMark: "AI",
    providerName: "Aion Bank",
    title: "Aion Everyday Card",
    subtitle: "Subscription-based digital bank card with stronger multi-currency support and app-led controls.",
    countryCodes: ["BE", "PL", "DE"],
    providerWebsiteUrl: "https://www.aion.eu/personal/",
    affiliatePriorityScore: 0.69,
    annualFee: "EUR 0 - 4.99/mo",
    fxFee: "0.3%",
    cashback: "0%",
    atm: "Free up to EUR 400",
    bestFor: ["Multi-currency", "App-first", "Everyday spend"],
    attributes: { annualFeeAmount: 60, fxFeePercent: 0.3, cashbackPercent: 0, atmFreeLimit: 400, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-lydia-noir",
    slug: "lydia-noir-card",
    providerMark: "LY",
    providerName: "Lydia",
    title: "Lydia Noir Card",
    subtitle: "French social-finance card with instant spend alerts and cleaner app-led money movement.",
    countryCodes: ["FR"],
    providerWebsiteUrl: "https://www.sumeria.eu/",
    affiliatePriorityScore: 0.64,
    annualFee: "EUR 0 - 7.90/mo",
    fxFee: "1%",
    cashback: "0%",
    atm: "Free up to EUR 250",
    bestFor: ["France", "App-led banking", "Instant alerts"],
    attributes: { annualFeeAmount: 95, fxFeePercent: 1, cashbackPercent: 0, atmFreeLimit: 250, cardType: "debit", feeProfile: "medium" },
  },
  {
    id: "card-bank-norwegian-credit",
    slug: "bank-norwegian-credit-card",
    providerMark: "BN",
    providerName: "Bank Norwegian",
    title: "Bank Norwegian Credit Card",
    subtitle: "Travel-oriented Nordic credit card with reward positioning and lower friction abroad.",
    countryCodes: ["NO", "SE", "DK", "FI"],
    providerWebsiteUrl: "https://www.banknorwegian.com/creditcard/",
    affiliateLink: "https://www.aion.eu/personal/",
    affiliatePriorityScore: 0.74,
    annualFee: "EUR 0",
    fxFee: "1.75%",
    cashback: "CashPoints rewards",
    atm: "Fee-based worldwide ATM access",
    bestFor: ["Travel rewards", "Nordics", "Credit line"],
    attributes: { annualFeeAmount: 0, fxFeePercent: 1.75, cashbackPercent: 0.5, atmFreeLimit: 0, cardType: "credit", feeProfile: "medium" },
  },
];

const transferSeeds: TransferSeed[] = [
  {
    id: "transfer-paysend-global",
    slug: "paysend-global-transfer",
    providerMark: "PS",
    providerName: "PaySend",
    title: "PaySend Global Transfer",
    subtitle: "Card-to-card and bank transfer flow with clear corridor pricing and a strong Europe-to-global consumer focus.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://paysend.com",
    affiliatePriorityScore: 0.76,
    fee: "From EUR 1.50",
    speed: "Minutes",
    currencies: "50+",
    bestFor: ["Card transfers", "Fixed fee", "Consumer remittance"],
    attributes: { feeProfile: "low", availability: "international", searchTags: ["fixed fee", "card to card", "consumer remittance"] },
  },
  {
    id: "transfer-moneygram-online",
    slug: "moneygram-online-transfer",
    providerMark: "MG",
    providerName: "MoneyGram",
    title: "MoneyGram Online Transfer",
    subtitle: "Established cash and digital remittance network with broad payout options and rapid collection routes.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.moneygram.com",
    affiliatePriorityScore: 0.72,
    fee: "From EUR 2.99",
    speed: "Minutes",
    currencies: "30+",
    bestFor: ["Cash pickup", "Wide payout network", "Urgent transfers"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["cash pickup", "remittance", "urgent transfer"] },
  },
  {
    id: "transfer-ofx-global",
    slug: "ofx-global-transfer",
    providerMark: "OFX",
    providerName: "OFX",
    title: "OFX Global Transfer",
    subtitle: "FX-led international transfer route focused on larger amounts and cleaner rate visibility.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.ofx.com",
    affiliatePriorityScore: 0.74,
    fee: "EUR 0 - 15",
    speed: "1-2 days",
    currencies: "50+",
    bestFor: ["Larger transfers", "FX focus", "Rate visibility"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["larger transfers", "fx rates", "bank transfer"] },
  },
  {
    id: "transfer-skrill-money",
    slug: "skrill-money-transfer",
    providerMark: "SK",
    providerName: "Skrill",
    title: "Skrill Money Transfer",
    subtitle: "Digital wallet-linked transfer route with a consumer remittance focus and broad payout coverage.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.skrill.com",
    affiliatePriorityScore: 0.68,
    fee: "Variable by corridor",
    speed: "Minutes - 1 day",
    currencies: "40+",
    bestFor: ["Wallet users", "Remittance", "Digital-first"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["wallet", "remittance", "digital-first"] },
  },
  {
    id: "transfer-torfx-personal",
    slug: "torfx-personal-transfer",
    providerMark: "TF",
    providerName: "TorFX",
    title: "TorFX Personal Transfer",
    subtitle: "Broker-style FX transfer route for larger personal transfers where dealer support matters.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.torfx.com/",
    affiliatePriorityScore: 0.66,
    fee: "No transfer fee on larger amounts",
    speed: "1-2 days",
    currencies: "40+",
    bestFor: ["Large transfers", "Dealer support", "Property payments"],
    attributes: { feeProfile: "low", availability: "international", searchTags: ["larger transfers", "property", "dealer support"] },
  },
  {
    id: "transfer-atlantic-money",
    slug: "atlantic-money-transfer",
    providerMark: "AM",
    providerName: "Atlantic Money",
    title: "Atlantic Money Transfer",
    subtitle: "Flat-fee transfer route aimed at larger cross-border moves with simpler pricing logic.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://atlanticmoney.com/send-money",
    affiliatePriorityScore: 0.73,
    fee: "Flat EUR 3",
    speed: "1-2 days",
    currencies: "Major pairs",
    bestFor: ["Flat fee", "Larger amounts", "Simple pricing"],
    attributes: { feeProfile: "low", availability: "international", searchTags: ["flat fee", "large amount", "simple pricing"] },
  },
  {
    id: "transfer-small-world-remit",
    slug: "small-world-remit",
    providerMark: "SW",
    providerName: "Small World",
    title: "Small World Remit",
    subtitle: "Global remittance network with bank deposit and cash payout coverage across popular consumer corridors.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.smallworldfs.com/",
    affiliatePriorityScore: 0.67,
    fee: "Corridor-based fee",
    speed: "Minutes - 1 day",
    currencies: "90+ countries",
    bestFor: ["Remittance corridors", "Cash and bank payout", "Family support"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["remittance", "cash payout", "family support"] },
  },
];

const exchangeSeeds: ExchangeSeed[] = [
  {
    id: "exchange-ofx-direct",
    slug: "ofx-direct-fx",
    providerMark: "OFX",
    providerName: "OFX",
    title: "OFX Direct FX",
    subtitle: "Larger-ticket currency exchange with dealer support and cleaner rate visibility for planned transfers.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.ofx.com/",
    affiliatePriorityScore: 0.72,
    spread: "0.2% - 0.8%",
    execution: "Same day - 1 day",
    currencies: "50+",
    bestFor: ["Larger conversions", "Dealer support", "Planned FX"],
    attributes: { feeProfile: "low", availability: "international", searchTags: ["fx broker", "larger conversions", "dealer support"] },
  },
  {
    id: "exchange-saxo-fx",
    slug: "saxo-fx-access",
    providerMark: "SX",
    providerName: "Saxo",
    title: "Saxo FX Access",
    subtitle: "Brokerage-led FX access for users who want stronger tooling and broader cross-asset context.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.home.saxo/products/forex",
    affiliatePriorityScore: 0.71,
    spread: "0.15% - 0.7%",
    execution: "Live market hours",
    currencies: "180+ pairs",
    bestFor: ["Advanced users", "Market tools", "Cross-asset"],
    attributes: { feeProfile: "low", availability: "international", searchTags: ["brokerage fx", "advanced", "market tools"] },
  },
  {
    id: "exchange-currencies-direct",
    slug: "currencies-direct-fx",
    providerMark: "CD",
    providerName: "Currencies Direct",
    title: "Currencies Direct FX",
    subtitle: "Broker-style FX route for regular international payments and larger planned conversions.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.currenciesdirect.com/",
    affiliatePriorityScore: 0.68,
    spread: "0.2% - 0.9%",
    execution: "Same day - 1 day",
    currencies: "40+",
    bestFor: ["Regular FX", "Large planned conversions", "Human support"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["broker", "planned conversions", "regular fx"] },
  },
  {
    id: "exchange-monex-europe",
    slug: "monex-europe-fx",
    providerMark: "MX",
    providerName: "Monex Europe",
    title: "Monex Europe FX",
    subtitle: "Institutional-style European FX route for larger conversions, treasury-style flows, and forward needs.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.monexeurope.com/personal/",
    affiliatePriorityScore: 0.66,
    spread: "0.25% - 1%",
    execution: "Same day",
    currencies: "40+",
    bestFor: ["Treasury-style FX", "Forwards", "Larger amounts"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["forwards", "treasury", "larger fx"] },
  },
  {
    id: "exchange-ebury-fx",
    slug: "ebury-fx-account",
    providerMark: "EB",
    providerName: "Ebury",
    title: "Ebury FX Account",
    subtitle: "Business-friendly currency exchange with named-account support, forward contracts, and multi-currency settlement.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://ebury.com",
    affiliatePriorityScore: 0.65,
    spread: "Quote-based",
    execution: "Same day - 1 day",
    currencies: "130+",
    bestFor: ["Business FX", "Forward contracts", "Multi-currency accounts"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["business fx", "forwards", "multi-currency"] },
  },
  {
    id: "exchange-cornerstone-fx",
    slug: "cornerstone-fx",
    providerMark: "CS",
    providerName: "Cornerstone",
    title: "Cornerstone FX",
    subtitle: "Guided FX execution for planned international payments where rate timing and support matter.",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://cornerstonefs.com/personal/",
    affiliatePriorityScore: 0.63,
    spread: "0.3% - 1.1%",
    execution: "Same day",
    currencies: "Major pairs",
    bestFor: ["Guided execution", "Planned payments", "Rate support"],
    attributes: { feeProfile: "medium", availability: "international", searchTags: ["guided fx", "planned payments", "rate support"] },
  },
];

export const supplementalMarketplaceOffers: MarketplaceOffer[] = [
  ...loanSeeds.map(buildLoanOffer),
  ...cardSeeds.map(buildCardOffer),
  ...transferSeeds.map(buildTransferOffer),
  ...exchangeSeeds.map(buildExchangeOffer),
];
