import type { MarketplaceOffer } from "@payn/types";

export const fallbackMarketplaceOffers: MarketplaceOffer[] = [
  {
    id: "fallback-loan-revolut-flex",
    slug: "revolut-flex-loan-fallback",
    category: "loans",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Flex Loan",
    subtitle:
      "Pan-European consumer credit route shown when local loan coverage is limited.",
    metrics: [
      { label: "APR", value: "5.9% - 12.9%" },
      { label: "Amount", value: "EUR 1,000 - 35,000" },
      { label: "Term", value: "12 - 72 months" },
    ],
    bestFor: ["Broader European fallback", "Digital check", "Fast pre-approval"],
    providerWebsiteUrl: "https://www.revolut.com/personal-loans",
    affiliateLink: "https://www.revolut.com/personal-loans",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.58,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      minAmount: 1000,
      maxAmount: 35000,
      minTermMonths: 12,
      maxTermMonths: 72,
      searchTags: ["consumer loan", "fallback coverage", "personal borrowing"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-loan-n26-instalment",
    slug: "n26-instalment-loan-fallback",
    category: "loans",
    countryCodes: ["ALL_EU"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Instalment Loan",
    subtitle:
      "Digital instalment borrowing route used to keep consumer-loan comparisons populated across supported countries.",
    metrics: [
      { label: "APR", value: "6.1% - 13.8%" },
      { label: "Amount", value: "EUR 1,500 - 25,000" },
      { label: "Term", value: "12 - 60 months" },
    ],
    bestFor: ["Consumer loans", "App-led journey", "Smaller borrowing needs"],
    providerWebsiteUrl: "https://n26.com/en-eu/loans",
    affiliateLink: "https://n26.com/en-eu/loans",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.56,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      minAmount: 1500,
      maxAmount: 25000,
      minTermMonths: 12,
      maxTermMonths: 60,
      searchTags: ["consumer credit", "fallback coverage", "small-ticket financing"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-loan-younited-europe",
    slug: "younited-europe-loan-fallback",
    category: "loans",
    countryCodes: ["ALL_EU"],
    providerMark: "YC",
    providerName: "Younited Credit",
    title: "Younited Europe Route",
    subtitle:
      "Cross-border personal loan route used as a fallback when direct country coverage is limited.",
    metrics: [
      { label: "APR", value: "4.9% - 14.9%" },
      { label: "Amount", value: "EUR 1,000 - 40,000" },
      { label: "Term", value: "12 - 84 months" },
    ],
    bestFor: ["Personal borrowing", "Transparent monthly cost", "Broader European fallback"],
    providerWebsiteUrl: "https://www.younited-credit.com",
    affiliateLink: "https://www.younited-credit.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.54,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "eu_wide",
      minAmount: 1000,
      maxAmount: 40000,
      minTermMonths: 12,
      maxTermMonths: 84,
      searchTags: ["personal loan", "fallback coverage", "consumer lending"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-card-wise-multi-currency",
    slug: "wise-multi-currency-card-fallback",
    category: "cards",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "WI",
    providerName: "Wise",
    title: "Wise Multi-Currency Card",
    subtitle:
      "Cross-border card fallback shown when local card coverage is limited in your selected country.",
    metrics: [
      { label: "Annual fee", value: "EUR 0" },
      { label: "FX fee", value: "From 0.43%" },
      { label: "Cashback", value: "No cashback" },
      { label: "ATM", value: "2 withdrawals free up to EUR 200" },
    ],
    bestFor: ["Travel spend", "FX transparency", "Broader European fallback"],
    providerWebsiteUrl: "https://wise.com/card",
    affiliateLink: "https://wise.com/card",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.57,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "eu_wide",
      cardType: "debit",
      annualFeeAmount: 0,
      fxFeePercent: 0.43,
      searchTags: ["travel card", "fallback coverage", "multi-currency"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-card-revolut-premium",
    slug: "revolut-premium-card-fallback",
    category: "cards",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Premium Card",
    subtitle:
      "Digital-first premium card route used to maintain card comparison density across supported countries.",
    metrics: [
      { label: "Annual fee", value: "EUR 108 / year" },
      { label: "FX fee", value: "0% weekdays within plan limits" },
      { label: "Cashback", value: "Partner rewards" },
      { label: "ATM", value: "Higher free ATM allowance" },
    ],
    bestFor: ["Travel", "App-led controls", "Broader European fallback"],
    providerWebsiteUrl: "https://www.revolut.com/cards",
    affiliateLink: "https://www.revolut.com/cards",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.55,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      cardType: "debit",
      annualFeeAmount: 108,
      fxFeePercent: 0,
      searchTags: ["travel card", "fallback coverage", "fx card"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-card-n26-you",
    slug: "n26-you-card-fallback",
    category: "cards",
    countryCodes: ["ALL_EU"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 You Card",
    subtitle:
      "Travel-focused card fallback used when direct country card availability is limited.",
    metrics: [
      { label: "Annual fee", value: "EUR 118.80 / year" },
      { label: "FX fee", value: "0% on card spend" },
      { label: "Cashback", value: "Partner benefits" },
      { label: "ATM", value: "Worldwide ATM withdrawals" },
    ],
    bestFor: ["Travel", "FX spend", "Broader European fallback"],
    providerWebsiteUrl: "https://n26.com/en-eu/plans",
    affiliateLink: "https://n26.com/en-eu/plans",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.53,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      cardType: "debit",
      annualFeeAmount: 118.8,
      fxFeePercent: 0,
      searchTags: ["travel card", "fallback coverage", "atm access"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-transfer-wise-route",
    slug: "wise-transfer-fallback",
    category: "transfers",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "WI",
    providerName: "Wise",
    title: "Wise Transfer Route",
    subtitle:
      "Broader European transfer option shown when local country transfer density is limited.",
    metrics: [
      { label: "Fee", value: "From 0.43%" },
      { label: "Speed", value: "Same day on major corridors" },
      { label: "Currencies", value: "40+ currencies" },
    ],
    bestFor: ["Delivered amount", "FX transparency", "Broader European fallback"],
    providerWebsiteUrl: "https://wise.com/send-money",
    affiliateLink: "https://wise.com/send-money",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.58,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "international",
      searchTags: ["transfer", "fallback coverage", "same day"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-transfer-paysera-route",
    slug: "paysera-transfer-fallback",
    category: "transfers",
    countryCodes: ["ALL_EU"],
    providerMark: "PY",
    providerName: "Paysera",
    title: "Paysera Transfer",
    subtitle:
      "Pan-European transfer route used to keep send-money comparisons populated.",
    metrics: [
      { label: "Fee", value: "Low fixed fee + FX spread" },
      { label: "Speed", value: "Same day to next day" },
      { label: "Currencies", value: "30+ currencies" },
    ],
    bestFor: ["European corridors", "Low-cost transfers", "Broader European fallback"],
    providerWebsiteUrl: "https://www.paysera.com",
    affiliateLink: "https://www.paysera.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.55,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "eu_wide",
      searchTags: ["transfer", "fallback coverage", "european corridors"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-transfer-skrill-route",
    slug: "skrill-transfer-fallback",
    category: "transfers",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "SK",
    providerName: "Skrill",
    title: "Skrill Wallet Transfer",
    subtitle:
      "Wallet-led transfer route used as a backup when country-level transfer supply is thin.",
    metrics: [
      { label: "Fee", value: "Variable by route" },
      { label: "Speed", value: "Instant to same day" },
      { label: "Currencies", value: "40+ currencies" },
    ],
    bestFor: ["Wallet transfers", "Fast payout", "Broader European fallback"],
    providerWebsiteUrl: "https://www.skrill.com",
    affiliateLink: "https://www.skrill.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.52,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "international",
      searchTags: ["transfer", "fallback coverage", "wallet"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-exchange-wise-fx",
    slug: "wise-fx-fallback",
    category: "exchange",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "WI",
    providerName: "Wise",
    title: "Wise FX Conversion",
    subtitle:
      "Broader European FX route shown when direct exchange coverage is limited.",
    metrics: [
      { label: "Spread", value: "Near mid-market + fee" },
      { label: "Execution", value: "Instant quote" },
      { label: "Currencies", value: "40+ currencies" },
    ],
    bestFor: ["Transparent FX", "Broader European fallback", "Simple pricing"],
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.57,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "international",
      searchTags: ["fx", "fallback coverage", "mid-market"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-exchange-currencyfair",
    slug: "currencyfair-fx-fallback",
    category: "exchange",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "CF",
    providerName: "CurrencyFair",
    title: "CurrencyFair FX Route",
    subtitle:
      "Broker-style foreign exchange fallback shown where country-specific FX routes are limited.",
    metrics: [
      { label: "Spread", value: "From 0.45%" },
      { label: "Execution", value: "Live quote + rate alerts" },
      { label: "Currencies", value: "20+ currencies" },
    ],
    bestFor: ["Larger conversions", "Rate alerts", "Broader European fallback"],
    providerWebsiteUrl: "https://www.currencyfair.com",
    affiliateLink: "https://www.currencyfair.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.54,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "international",
      searchTags: ["fx", "fallback coverage", "broker"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-exchange-ofx",
    slug: "ofx-fx-fallback",
    category: "exchange",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "OFX",
    providerName: "OFX",
    title: "OFX Exchange Desk",
    subtitle:
      "International FX desk used to avoid empty exchange views in lower-coverage countries.",
    metrics: [
      { label: "Spread", value: "Variable by size and pair" },
      { label: "Execution", value: "Dealer support on larger trades" },
      { label: "Currencies", value: "50+ currencies" },
    ],
    bestFor: ["Larger transfers", "Dealer support", "Broader European fallback"],
    providerWebsiteUrl: "https://www.ofx.com",
    affiliateLink: "https://www.ofx.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.51,
    updatedAt: "2026-04-01T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "international",
      searchTags: ["fx", "fallback coverage", "large amount"],
      notes:
        "Shown as a broader European route when local country coverage is thin.",
    },
  },
  {
    id: "fallback-insurance-worldnomads",
    slug: "worldnomads-insurance-fallback",
    category: "insurance",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "WN",
    providerName: "WorldNomads",
    title: "WorldNomads Travel Insurance",
    subtitle:
      "International travel insurance covering medical emergencies, trip cancellation, and adventure sports. Available to residents of 130+ countries.",
    metrics: [
      { label: "Medical cover", value: "Up to USD 5m" },
      { label: "Trip cancellation", value: "Included" },
      { label: "Adventure sports", value: "200+ activities covered" },
    ],
    bestFor: ["Travel cover", "Adventure travellers", "International fallback"],
    providerWebsiteUrl: "https://www.worldnomads.com/travel-insurance",
    affiliateLink: "https://www.worldnomads.com/travel-insurance",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.55,
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: {
      feeProfile: "low",
      availability: "eu_wide",
      insuranceType: "travel",
      searchTags: ["insurance", "travel", "fallback coverage", "WorldNomads"],
      notes: "Shown as a broader European fallback when local insurance coverage is thin.",
    },
  },
  {
    id: "fallback-insurance-axa-travel",
    slug: "axa-travel-insurance-fallback",
    category: "insurance",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Travel Insurance",
    subtitle:
      "AXA group travel insurance shown as a European fallback. Covers medical emergencies, delays, and baggage loss across Europe and worldwide.",
    metrics: [
      { label: "Medical cover", value: "Up to EUR 1m" },
      { label: "Trip delay", value: "Included" },
      { label: "Annual multi-trip", value: "Available" },
    ],
    bestFor: ["Travel cover", "AXA brand", "Broader European fallback"],
    providerWebsiteUrl: "https://www.axa.com/en/insurance/travel-insurance",
    affiliateLink: "https://www.axa.com/en/insurance/travel-insurance",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.53,
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      insuranceType: "travel",
      searchTags: ["insurance", "travel", "fallback coverage", "AXA"],
      notes: "Shown as a broader European fallback when local insurance coverage is thin.",
    },
  },
  {
    id: "fallback-insurance-revolut-premium",
    slug: "revolut-premium-insurance-fallback",
    category: "insurance",
    countryCodes: ["ALL_EU", "UK"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Premium Travel Cover",
    subtitle:
      "Travel medical and disruption cover included with Revolut Premium and Metal plans. Shown as a fallback when country-specific insurance options are limited.",
    metrics: [
      { label: "Medical cover", value: "Up to EUR 10m" },
      { label: "Trip disruption", value: "Included" },
      { label: "Included with", value: "Revolut Premium / Metal" },
    ],
    bestFor: ["Revolut users", "Travel cover", "Broader European fallback"],
    providerWebsiteUrl: "https://www.revolut.com/premium",
    affiliateLink: "https://www.revolut.com/premium",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.50,
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: {
      feeProfile: "medium",
      availability: "eu_wide",
      insuranceType: "travel",
      searchTags: ["insurance", "travel", "fallback coverage", "Revolut"],
      notes: "Shown as a broader European fallback when local insurance coverage is thin.",
    },
  },
];
