import type {
  MarketplaceInsuranceType,
  MarketplaceOffer,
  MarketplaceOfferAttributes,
} from "@payn/types";
import { supplementalMarketplaceOffers } from "@/features/catalog/marketplace-expanded-offers";
import { featuredOffers as coreOffers } from "@/features/catalog/mock-data";
import { newCategoriesOffers } from "@/features/catalog/new-categories-catalog";
import { catalogExpansionOffers } from "@/features/catalog/catalog-expansion";

type InsuranceSeed = {
  id: string;
  slug: string;
  providerMark: string;
  providerName: string;
  title: string;
  subtitle: string;
  insuranceType: MarketplaceInsuranceType;
  countryCodes: string[];
  providerWebsiteUrl: string;
  affiliateLink?: string;
  affiliatePriorityScore: number;
  priceAmount: number;
  coverageAmount: number;
  medicalCoverage?: number;
  deductibleAmount?: number;
  maxTripDays?: number;
  regionCoverage?: "eu" | "worldwide" | "regional";
  activityLevel?: "basic" | "extreme";
  visaCompliant?: boolean;
  instantActivation?: boolean;
  rollingMonthly?: boolean;
  remoteWork?: string;
  digitalClaims?: string;
  familyCover?: string;
  term?: string;
  outpatient?: string;
  inpatient?: string;
  liability?: string;
  collision?: string;
  roadside?: string;
  baggage?: string;
  countriesCovered?: string;
  deviceCover?: string;
  theftLiquid?: string;
  worldwideProtection?: string;
  bestFor: string[];
  feeProfile?: MarketplaceOfferAttributes["feeProfile"];
  availability?: MarketplaceOfferAttributes["availability"];
  searchTags?: string[];
};

function formatRangeEuro(min: number, max: number) {
  return `EUR ${min.toLocaleString("en-US")} - ${max.toLocaleString("en-US")}`;
}

function formatEuroValue(value: number) {
  return `EUR ${value.toLocaleString("en-US")}`;
}

function buildInsuranceMetrics(seed: InsuranceSeed) {
  switch (seed.insuranceType) {
    case "travel":
      return [
        { label: "Price", value: `EUR ${seed.priceAmount} / trip` },
        { label: "Medical cover", value: formatEuroValue(seed.medicalCoverage ?? 1000000) },
        { label: "Trip length", value: `Up to ${seed.maxTripDays ?? 30} days` },
        { label: "Region coverage", value: seed.regionCoverage === "worldwide" ? "Worldwide" : seed.regionCoverage === "eu" ? "EU" : "Regional" },
        { label: "Baggage / delay", value: seed.baggage ?? "Included" },
      ];
    case "health":
      return [
        { label: "Monthly premium", value: `EUR ${seed.priceAmount}` },
        { label: "Outpatient", value: seed.outpatient ?? "Standard outpatient cover" },
        { label: "Inpatient", value: seed.inpatient ?? "Hospital and surgery cover" },
        { label: "Digital claims", value: seed.digitalClaims ?? "App and online claims" },
      ];
    case "life":
      return [
        { label: "Monthly premium", value: `EUR ${seed.priceAmount}` },
        { label: "Insured amount", value: formatRangeEuro(Math.round(seed.coverageAmount * 0.7), seed.coverageAmount) },
        { label: "Term", value: seed.term ?? "10 - 30 years" },
        { label: "Family cover", value: seed.familyCover ?? "Flexible beneficiary options" },
      ];
    case "auto":
      return [
        { label: "Monthly premium", value: `EUR ${seed.priceAmount}` },
        { label: "Liability", value: seed.liability ?? formatRangeEuro(seed.coverageAmount, seed.coverageAmount) },
        { label: "Collision / theft", value: seed.collision ?? "Optional add-on" },
        { label: "Roadside support", value: seed.roadside ?? "24/7 assistance" },
        { label: "Deductible", value: `From EUR ${seed.deductibleAmount ?? 250}` },
      ];
    case "nomad":
      return [
        { label: "Price", value: `USD ${seed.priceAmount} / 4 weeks` },
        { label: "Rolling monthly", value: seed.rollingMonthly ? "Monthly renewal available" : "Fixed-term option" },
        { label: "Countries covered", value: seed.countriesCovered ?? "180+ countries" },
        { label: "Medical emergencies", value: formatEuroValue(seed.medicalCoverage ?? 250000) },
        { label: "Remote work suitability", value: seed.remoteWork ?? "Built for remote workers" },
      ];
    case "device":
      return [
        { label: "Monthly premium", value: `EUR ${seed.priceAmount}` },
        { label: "Device cover", value: formatRangeEuro(Math.round(seed.coverageAmount * 0.6), seed.coverageAmount) },
        { label: "Theft / liquid", value: seed.theftLiquid ?? "Included" },
        { label: "Worldwide protection", value: seed.worldwideProtection ?? "Worldwide cover" },
        { label: "Deductible", value: `From EUR ${seed.deductibleAmount ?? 75}` },
      ];
    default:
      return [];
  }
}

function buildInsuranceOffer(seed: InsuranceSeed): MarketplaceOffer {
  return {
    id: seed.id,
    slug: seed.slug,
    category: "insurance",
    countryCodes: seed.countryCodes,
    providerMark: seed.providerMark,
    providerName: seed.providerName,
    title: seed.title,
    subtitle: seed.subtitle,
    metrics: buildInsuranceMetrics(seed),
    bestFor: seed.bestFor,
    providerWebsiteUrl: seed.providerWebsiteUrl,
    affiliateLink: seed.affiliateLink ?? seed.providerWebsiteUrl,
    linkType: "affiliate_redirect",
    affiliatePriorityScore: seed.affiliatePriorityScore,
    updatedAt: "2026-03-30T00:00:00Z",
    attributes: {
      subtype: seed.insuranceType,
      insuranceType: seed.insuranceType,
      feeProfile: seed.feeProfile ?? "medium",
      availability: seed.availability ?? "regional",
      searchTags: seed.searchTags ?? [],
      priceAmount: seed.priceAmount,
      coverageAmount: seed.coverageAmount,
      medicalCoverage: seed.medicalCoverage,
      deductibleAmount: seed.deductibleAmount,
      maxTripDays: seed.maxTripDays,
      regionCoverage: seed.regionCoverage,
      activityLevel: seed.activityLevel,
      visaCompliant: seed.visaCompliant,
      instantActivation: seed.instantActivation,
      comparisonHighlights: seed.bestFor,
    },
  };
}

const generatedInsuranceCatalog: InsuranceSeed[] = [
  {
    id: "insurance-axa-travel-plus",
    slug: "axa-travel-plus",
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Travel Plus",
    subtitle: "Structured trip cover with strong medical protection, visa-ready wording, and cleaner worldwide options.",
    insuranceType: "travel",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliateLink: "https://www.axa-schengen.com/en/",
    affiliatePriorityScore: 0.9,
    priceAmount: 22,
    coverageAmount: 5000000,
    medicalCoverage: 5000000,
    deductibleAmount: 0,
    maxTripDays: 90,
    regionCoverage: "worldwide",
    activityLevel: "basic",
    visaCompliant: true,
    instantActivation: true,
    baggage: "Baggage and delay included",
    bestFor: ["Cheapest worldwide", "Visa-ready", "High medical cover"],
    feeProfile: "low",
    availability: "international",
    searchTags: ["travel insurance", "worldwide", "visa compliant", "medical cover"],
  },
  {
    id: "insurance-allianz-travel-annual",
    slug: "allianz-travel-annual",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Travel Annual",
    subtitle: "Annual multi-trip cover for frequent travellers who want stronger baggage and disruption protection.",
    insuranceType: "travel",
    countryCodes: ["DE", "FR", "IT", "ES", "NL"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.88,
    priceAmount: 34,
    coverageAmount: 10000000,
    medicalCoverage: 10000000,
    deductibleAmount: 100,
    maxTripDays: 120,
    regionCoverage: "worldwide",
    activityLevel: "basic",
    visaCompliant: true,
    baggage: "Higher baggage and delay protection",
    bestFor: ["Frequent trips", "Higher baggage limits", "Brand trust"],
  },
  {
    id: "insurance-worldnomads-explorer",
    slug: "world-nomads-explorer",
    providerMark: "WN",
    providerName: "World Nomads",
    title: "World Nomads Explorer",
    subtitle: "Travel cover tuned for longer itineraries, gear protection, and optional activity extensions.",
    affiliateLink: "https://www.worldnomads.com/travel-insurance/",
    insuranceType: "travel",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.worldnomads.com",
    affiliatePriorityScore: 0.86,
    priceAmount: 41,
    coverageAmount: 6000000,
    medicalCoverage: 6000000,
    deductibleAmount: 75,
    maxTripDays: 180,
    regionCoverage: "worldwide",
    activityLevel: "extreme",
    visaCompliant: false,
    baggage: "Adventure gear and baggage cover",
    bestFor: ["Adventure travel", "Longer trips", "Sports extensions"],
  },
  {
    id: "insurance-ergo-travel-basic",
    slug: "ergo-travel-basic",
    providerMark: "ER",
    providerName: "ERGO",
    title: "ERGO Travel Basic",
    subtitle: "Lower-cost European travel cover with practical medical and cancellation protection.",
    insuranceType: "travel",
    countryCodes: ["DE", "AT", "IT"],
    providerWebsiteUrl: "https://www.ergo.com",
    affiliatePriorityScore: 0.79,
    priceAmount: 16,
    coverageAmount: 1000000,
    medicalCoverage: 1000000,
    deductibleAmount: 150,
    maxTripDays: 45,
    regionCoverage: "eu",
    activityLevel: "basic",
    visaCompliant: true,
    baggage: "Essential baggage and cancellation cover",
    bestFor: ["Lower price", "EU travel", "Short trips"],
    feeProfile: "low",
  },
  {
    id: "insurance-heymondo-flex-trip",
    slug: "heymondo-flex-trip",
    providerMark: "HM",
    providerName: "Heymondo",
    title: "Heymondo Flex Trip",
    subtitle: "Digital-first travel cover with app support, emergency chat, and cleaner claims flow.",
    affiliateLink: "https://heymondo.com/travel-insurance",
    insuranceType: "travel",
    countryCodes: ["ES", "PT", "IT", "FR"],
    providerWebsiteUrl: "https://heymondo.com",
    affiliatePriorityScore: 0.81,
    priceAmount: 27,
    coverageAmount: 5000000,
    medicalCoverage: 5000000,
    deductibleAmount: 0,
    maxTripDays: 90,
    regionCoverage: "worldwide",
    activityLevel: "basic",
    visaCompliant: true,
    instantActivation: true,
    baggage: "Digital claims and baggage disruption cover",
    bestFor: ["App-based claims", "Worldwide", "Digital-first"],
  },
  {
    id: "insurance-admiral-travel-max",
    slug: "admiral-travel-max",
    providerMark: "AD",
    providerName: "Admiral",
    title: "Admiral Travel Max",
    subtitle: "Travel cover for families and frequent travellers with stronger cancellation and medical limits.",
    insuranceType: "travel",
    countryCodes: ["UK", "ES", "PT", "FR"],
    providerWebsiteUrl: "https://www.admiral.com",
    affiliateLink: "https://www.admiral.com/travel-insurance",
    affiliatePriorityScore: 0.82,
    priceAmount: 29,
    coverageAmount: 10000000,
    medicalCoverage: 10000000,
    deductibleAmount: 50,
    maxTripDays: 120,
    regionCoverage: "worldwide",
    activityLevel: "basic",
    visaCompliant: true,
    baggage: "Family baggage and delay cover",
    bestFor: ["Family travel", "Medical protection", "Higher trip length"],
  },
  {
    id: "insurance-axa-health-connect",
    slug: "axa-health-connect",
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Health Connect",
    subtitle: "Health cover for cross-border living with outpatient access, inpatient support, and digital claims.",
    insuranceType: "health",
    countryCodes: ["FR", "ES", "IT", "DE"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliateLink: "https://www.axaglobalhealthcare.com/en/",
    affiliatePriorityScore: 0.88,
    priceAmount: 44,
    coverageAmount: 1000000,
    deductibleAmount: 100,
    regionCoverage: "regional",
    digitalClaims: "App and online claims",
    outpatient: "Primary and specialist care",
    inpatient: "Private room and surgery cover",
    bestFor: ["Cross-border living", "Digital claims", "Comprehensive care"],
  },
  {
    id: "insurance-allianz-health-global",
    slug: "allianz-health-global",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Health Global",
    subtitle: "Private medical insurance with broader hospital coverage and stronger global portability.",
    insuranceType: "health",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.87,
    priceAmount: 68,
    coverageAmount: 1500000,
    deductibleAmount: 250,
    regionCoverage: "worldwide",
    digitalClaims: "Dedicated app claims",
    outpatient: "Specialist, diagnostics, and therapy",
    inpatient: "Global inpatient treatment",
    bestFor: ["Worldwide care", "Hospital access", "Expat health"],
  },
  {
    id: "insurance-cigna-global-care",
    slug: "cigna-global-care",
    providerMark: "CG",
    providerName: "Cigna Global",
    title: "Cigna Global Care",
    subtitle: "International health insurance for expats and cross-border households who need broader worldwide care access.",
    insuranceType: "health",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.cignaglobal.com",
    affiliatePriorityScore: 0.86,
    priceAmount: 79,
    coverageAmount: 2000000,
    deductibleAmount: 250,
    regionCoverage: "worldwide",
    digitalClaims: "Online and assisted claims",
    outpatient: "Primary, specialist, and diagnostics",
    inpatient: "Global hospital treatment",
    bestFor: ["Expat health", "Worldwide care", "Higher limits"],
  },
  {
    id: "insurance-allianz-care-expat",
    slug: "allianz-care-expat",
    providerMark: "AC",
    providerName: "Allianz Care",
    title: "Allianz Care Expat",
    subtitle: "Portable international health cover designed for expatriates and cross-border families.",
    insuranceType: "health",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.allianzcare.com",
    affiliateLink: "https://www.allianzcare.com/en/individuals.html",
    affiliatePriorityScore: 0.85,
    priceAmount: 84,
    coverageAmount: 2500000,
    deductibleAmount: 200,
    regionCoverage: "worldwide",
    digitalClaims: "Global digital claims",
    outpatient: "Routine and specialist care",
    inpatient: "Global inpatient cover",
    bestFor: ["Portability", "Expat families", "Worldwide access"],
  },
  {
    id: "insurance-alan-smart-plus",
    slug: "alan-smart-plus",
    providerMark: "AL",
    providerName: "Alan",
    title: "Alan Smart Plus",
    subtitle: "Digital-first health insurance with cleaner reimbursements, app onboarding, and everyday care management.",
    insuranceType: "health",
    countryCodes: ["FR", "ES", "BE"],
    providerWebsiteUrl: "https://alan.com",
    affiliatePriorityScore: 0.84,
    priceAmount: 39,
    coverageAmount: 700000,
    deductibleAmount: 50,
    regionCoverage: "regional",
    digitalClaims: "Fast app reimbursements",
    outpatient: "Primary and specialist visits",
    inpatient: "Hospital recovery support",
    bestFor: ["Digital-first", "Fast reimbursements", "Everyday health cover"],
  },
  {
    id: "insurance-bupa-global-select",
    slug: "bupa-global-select",
    providerMark: "BG",
    providerName: "Bupa Global",
    title: "Bupa Global Select",
    subtitle: "International health insurance with stronger hospital access and a more premium expat positioning.",
    insuranceType: "health",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.bupaglobal.com",
    affiliatePriorityScore: 0.83,
    priceAmount: 84,
    coverageAmount: 2000000,
    deductibleAmount: 500,
    regionCoverage: "worldwide",
    digitalClaims: "Digital member services",
    outpatient: "Specialist and diagnostics",
    inpatient: "Global hospital network",
    bestFor: ["Global cover", "Premium hospitals", "Expat relocation"],
  },
  {
    id: "insurance-generali-health-balance",
    slug: "generali-health-balance",
    providerMark: "GN",
    providerName: "Generali",
    title: "Generali Health Balance",
    subtitle: "Balanced private health plan with stronger family positioning and practical claims support.",
    insuranceType: "health",
    countryCodes: ["IT", "DE", "ES", "FR"],
    providerWebsiteUrl: "https://www.generali.com",
    affiliatePriorityScore: 0.8,
    priceAmount: 52,
    coverageAmount: 900000,
    deductibleAmount: 150,
    regionCoverage: "regional",
    digitalClaims: "Online claims portal",
    outpatient: "Routine and specialist care",
    inpatient: "Inpatient treatment included",
    bestFor: ["Families", "Balanced premium", "Regional cover"],
  },
  {
    id: "insurance-ergo-health-direct",
    slug: "ergo-health-direct",
    providerMark: "ER",
    providerName: "ERGO",
    title: "ERGO Health Direct",
    subtitle: "Structured private medical cover with lower entry pricing and cleaner outpatient routing.",
    insuranceType: "health",
    countryCodes: ["DE", "AT"],
    providerWebsiteUrl: "https://www.ergo.com",
    affiliatePriorityScore: 0.78,
    priceAmount: 31,
    coverageAmount: 500000,
    deductibleAmount: 250,
    regionCoverage: "regional",
    digitalClaims: "Online claims and documents",
    outpatient: "Primary care and diagnostics",
    inpatient: "Basic inpatient cover",
    bestFor: ["Entry pricing", "Routine care", "German-speaking markets"],
    feeProfile: "low",
  },
  {
    id: "insurance-allianz-life-family",
    slug: "allianz-life-family",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Life Family",
    subtitle: "Long-term life cover for family protection with flexible term ranges and stronger insurer trust.",
    insuranceType: "life",
    countryCodes: ["DE", "FR", "IT", "ES"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.9,
    priceAmount: 28,
    coverageAmount: 500000,
    term: "10 - 30 years",
    familyCover: "Flexible beneficiary structure",
    bestFor: ["Family protection", "Long-term cover", "Established insurer"],
  },
  {
    id: "insurance-axa-life-flex",
    slug: "axa-life-flex",
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Life Flex",
    subtitle: "Flexible life cover for income protection, mortgage support, and family beneficiaries.",
    insuranceType: "life",
    countryCodes: ["FR", "ES", "IT", "DE"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliatePriorityScore: 0.87,
    priceAmount: 24,
    coverageAmount: 350000,
    term: "5 - 25 years",
    familyCover: "Mortgage and family protection options",
    bestFor: ["Mortgage cover", "Flexible term", "Lower monthly price"],
  },
  {
    id: "insurance-generali-life-balance",
    slug: "generali-life-balance",
    providerMark: "GN",
    providerName: "Generali",
    title: "Generali Life Balance",
    subtitle: "Balanced life protection plan with stronger family positioning and wider insured amount bands.",
    insuranceType: "life",
    countryCodes: ["IT", "DE", "ES", "FR"],
    providerWebsiteUrl: "https://www.generali.com",
    affiliatePriorityScore: 0.84,
    priceAmount: 26,
    coverageAmount: 400000,
    term: "10 - 30 years",
    familyCover: "Family add-on options",
    bestFor: ["Balanced life cover", "Family add-ons", "Regional availability"],
  },
  {
    id: "insurance-ergo-life-starter",
    slug: "ergo-life-starter",
    providerMark: "ER",
    providerName: "ERGO",
    title: "ERGO Life Starter",
    subtitle: "Entry-level life insurance for simpler family protection and fixed monthly affordability.",
    insuranceType: "life",
    countryCodes: ["DE", "AT"],
    providerWebsiteUrl: "https://www.ergo.com",
    affiliatePriorityScore: 0.76,
    priceAmount: 19,
    coverageAmount: 250000,
    term: "10 - 20 years",
    familyCover: "Standard beneficiary options",
    bestFor: ["Lower monthly premium", "Starter cover", "Simple setup"],
    feeProfile: "low",
  },
  {
    id: "insurance-cardif-life-protect",
    slug: "cardif-life-protect",
    providerMark: "BC",
    providerName: "Cardif",
    title: "Cardif Life Protect",
    subtitle: "Life cover positioned for family resilience, longer terms, and established underwriting support.",
    insuranceType: "life",
    countryCodes: ["FR", "BE", "LU"],
    providerWebsiteUrl: "https://bnpparibascardif.com",
    affiliatePriorityScore: 0.8,
    priceAmount: 23,
    coverageAmount: 450000,
    term: "10 - 30 years",
    familyCover: "Family and mortgage protection",
    bestFor: ["Longer term", "Mortgage-linked cover", "Established underwriting"],
  },
  {
    id: "insurance-santander-life-essential",
    slug: "santander-life-essential",
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander Life Essential",
    subtitle: "Bank-distributed life cover with straightforward monthly pricing and practical protection bands.",
    insuranceType: "life",
    countryCodes: ["ES", "PT", "UK"],
    providerWebsiteUrl: "https://www.santander.com",
    affiliatePriorityScore: 0.75,
    priceAmount: 21,
    coverageAmount: 300000,
    term: "5 - 20 years",
    familyCover: "Everyday life and family protection",
    bestFor: ["Simple bank route", "Lower ticket cover", "Everyday protection"],
  },
  {
    id: "insurance-admiral-auto-plus",
    slug: "admiral-auto-plus",
    providerMark: "AD",
    providerName: "Admiral",
    title: "Admiral Auto Plus",
    subtitle: "Motor insurance with practical roadside support, broader theft cover, and cleaner claims handling.",
    insuranceType: "auto",
    countryCodes: ["UK", "ES", "PT"],
    providerWebsiteUrl: "https://www.admiral.com",
    affiliateLink: "https://www.admiral.com/car-insurance",
    affiliatePriorityScore: 0.82,
    priceAmount: 54,
    coverageAmount: 50000000,
    deductibleAmount: 250,
    liability: "Up to EUR 50m",
    collision: "Collision and theft add-on",
    roadside: "24/7 roadside assistance",
    bestFor: ["Roadside support", "Everyday driving", "Claims handling"],
  },
  {
    id: "insurance-axa-auto-select",
    slug: "axa-auto-select",
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Auto Select",
    subtitle: "Auto cover with stronger liability limits, theft protection, and more structured deductibles.",
    insuranceType: "auto",
    countryCodes: ["FR", "ES", "IT", "DE"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliatePriorityScore: 0.83,
    priceAmount: 61,
    coverageAmount: 75000000,
    deductibleAmount: 300,
    liability: "Up to EUR 75m",
    collision: "Collision and theft included",
    roadside: "Optional premium roadside support",
    bestFor: ["Higher liability", "Theft protection", "Comprehensive cover"],
  },
  {
    id: "insurance-generali-auto-smart",
    slug: "generali-auto-smart",
    providerMark: "GN",
    providerName: "Generali",
    title: "Generali Auto Smart",
    subtitle: "Balanced motor cover for city and family drivers who want predictable monthly pricing.",
    insuranceType: "auto",
    countryCodes: ["IT", "DE", "ES", "FR"],
    providerWebsiteUrl: "https://www.generali.com",
    affiliatePriorityScore: 0.81,
    priceAmount: 48,
    coverageAmount: 50000000,
    deductibleAmount: 200,
    liability: "Up to EUR 50m",
    collision: "Optional comprehensive protection",
    roadside: "24/7 support available",
    bestFor: ["Balanced premium", "City drivers", "Family cars"],
  },
  {
    id: "insurance-allianz-auto-complete",
    slug: "allianz-auto-complete",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Auto Complete",
    subtitle: "Broader motor protection with theft, collision, and roadside support in one cleaner package.",
    insuranceType: "auto",
    countryCodes: ["DE", "FR", "IT", "ES"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.86,
    priceAmount: 66,
    coverageAmount: 100000000,
    deductibleAmount: 350,
    liability: "Up to EUR 100m",
    collision: "Collision and theft included",
    roadside: "Premium roadside support",
    bestFor: ["Full cover", "Higher liability", "Brand trust"],
  },
  {
    id: "insurance-ergo-auto-direct",
    slug: "ergo-auto-direct",
    providerMark: "ER",
    providerName: "ERGO",
    title: "ERGO Auto Direct",
    subtitle: "Lower-cost auto cover for standard drivers who want a cleaner monthly price and optional extras.",
    insuranceType: "auto",
    countryCodes: ["DE", "AT"],
    providerWebsiteUrl: "https://www.ergo.com",
    affiliatePriorityScore: 0.77,
    priceAmount: 39,
    coverageAmount: 30000000,
    deductibleAmount: 400,
    liability: "Up to EUR 30m",
    collision: "Optional collision pack",
    roadside: "Basic roadside support",
    bestFor: ["Lower price", "Standard driving", "German market"],
    feeProfile: "low",
  },
  {
    id: "insurance-zurich-auto-protect",
    slug: "zurich-auto-protect",
    providerMark: "ZU",
    providerName: "Zurich",
    title: "Zurich Auto Protect",
    subtitle: "Motor insurance with stronger theft positioning and practical deductible options for mid-range vehicles.",
    insuranceType: "auto",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.zurich.com",
    affiliatePriorityScore: 0.79,
    priceAmount: 58,
    coverageAmount: 60000000,
    deductibleAmount: 250,
    liability: "Up to EUR 60m",
    collision: "Theft and collision support",
    roadside: "Roadside and replacement car support",
    bestFor: ["Theft protection", "Mid-range vehicles", "Broader assistance"],
  },
  {
    id: "insurance-safetywing-nomad-flex",
    slug: "safetywing-nomad-flex",
    providerMark: "SW",
    providerName: "SafetyWing",
    title: "SafetyWing Nomad Flex",
    subtitle: "Rolling monthly cover for remote workers who need lighter commitment and worldwide movement.",
    insuranceType: "nomad",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://safetywing.com",
    affiliateLink: "https://safetywing.com/nomad-insurance",
    affiliatePriorityScore: 0.9,
    priceAmount: 45,
    coverageAmount: 250000,
    medicalCoverage: 250000,
    deductibleAmount: 0,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    instantActivation: true,
    countriesCovered: "180+ countries",
    remoteWork: "Built for nomads and freelancers",
    bestFor: ["Remote workers", "Worldwide", "Rolling monthly"],
    availability: "international",
  },
  {
    id: "insurance-worldnomads-nomad-explorer",
    slug: "worldnomads-nomad-explorer",
    providerMark: "WN",
    providerName: "World Nomads",
    title: "World Nomads Nomad Explorer",
    subtitle: "Broader long-stay protection for location-flexible workers who want stronger activity cover.",
    insuranceType: "nomad",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.worldnomads.com",
    affiliatePriorityScore: 0.84,
    priceAmount: 59,
    coverageAmount: 500000,
    medicalCoverage: 500000,
    deductibleAmount: 100,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    activityLevel: "extreme",
    countriesCovered: "170+ countries",
    remoteWork: "Long-stay and activity-friendly cover",
    bestFor: ["Long stays", "Activities", "Higher medical limits"],
  },
  {
    id: "insurance-genki-native",
    slug: "genki-native-cover",
    providerMark: "GK",
    providerName: "Genki",
    title: "Genki Native Cover",
    subtitle: "Nomad health and travel protection with app-first claims and longer remote-work positioning.",
    insuranceType: "nomad",
    countryCodes: ["EU"],
    providerWebsiteUrl: "https://genki.world",
    affiliatePriorityScore: 0.82,
    priceAmount: 49,
    coverageAmount: 1000000,
    medicalCoverage: 1000000,
    deductibleAmount: 50,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    instantActivation: true,
    countriesCovered: "Worldwide with exclusions",
    remoteWork: "Digital nomad-focused medical cover",
    bestFor: ["App-first claims", "Long-term nomads", "Higher medical cover"],
  },
  {
    id: "insurance-insured-nomads-remote",
    slug: "insured-nomads-remote",
    providerMark: "IN",
    providerName: "Insured Nomads",
    title: "Insured Nomads Remote",
    subtitle: "Nomad-first cover with rolling monthly access, emergency support, and longer-stay travel protection.",
    insuranceType: "nomad",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.insurednomads.com",
    affiliatePriorityScore: 0.79,
    priceAmount: 54,
    coverageAmount: 350000,
    medicalCoverage: 350000,
    deductibleAmount: 100,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    countriesCovered: "170+ countries",
    remoteWork: "Remote-work and longer-stay friendly",
    bestFor: ["Long-stay nomads", "Worldwide cover", "Emergency support"],
  },
  {
    id: "insurance-heymondo-nomad",
    slug: "heymondo-nomad",
    providerMark: "HM",
    providerName: "Heymondo",
    title: "Heymondo Nomad",
    subtitle: "Travel and medical cover for digital nomads with fast support and cleaner emergency assistance.",
    insuranceType: "nomad",
    countryCodes: ["ES", "PT", "IT", "FR"],
    providerWebsiteUrl: "https://heymondo.com",
    affiliatePriorityScore: 0.8,
    priceAmount: 52,
    coverageAmount: 750000,
    medicalCoverage: 750000,
    deductibleAmount: 75,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    countriesCovered: "Worldwide",
    remoteWork: "Digital nomad support",
    bestFor: ["Emergency assistance", "Worldwide", "Fast support"],
  },
  {
    id: "insurance-passportcard-nomad",
    slug: "passportcard-nomad",
    providerMark: "PC",
    providerName: "PassportCard",
    title: "PassportCard Nomad",
    subtitle: "Nomad-focused protection with stronger medical access and pre-paid emergency claims support.",
    insuranceType: "nomad",
    countryCodes: ["EU"],
    providerWebsiteUrl: "https://passportcard.com",
    affiliatePriorityScore: 0.78,
    priceAmount: 64,
    coverageAmount: 1000000,
    medicalCoverage: 1000000,
    deductibleAmount: 0,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    countriesCovered: "Worldwide",
    remoteWork: "Pre-paid emergency medical access",
    bestFor: ["Emergency medical support", "Worldwide", "Higher cover"],
  },
  {
    id: "insurance-allianz-nomad-global",
    slug: "allianz-nomad-global",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Nomad Global",
    subtitle: "A stronger brand-led route for long-term international movement with broader medical support.",
    insuranceType: "nomad",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.79,
    priceAmount: 72,
    coverageAmount: 1500000,
    medicalCoverage: 1500000,
    deductibleAmount: 150,
    regionCoverage: "worldwide",
    rollingMonthly: true,
    countriesCovered: "Worldwide",
    remoteWork: "Long-term movement and remote work",
    bestFor: ["Brand trust", "Long-term movement", "Higher limits"],
  },
  {
    id: "insurance-allianz-device-protect",
    slug: "allianz-device-protect",
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Device Protect",
    subtitle: "Device insurance for phones, laptops, and tablets with theft and accidental-damage cover.",
    insuranceType: "device",
    countryCodes: ["DE", "FR", "IT", "ES"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz-partners.com/en_global/products/travel.html",
    affiliatePriorityScore: 0.78,
    priceAmount: 9,
    coverageAmount: 2000,
    deductibleAmount: 75,
    regionCoverage: "worldwide",
    deviceCover: "Phone, laptop, and tablet cover",
    theftLiquid: "Theft and accidental liquid damage",
    worldwideProtection: "Worldwide protection",
    bestFor: ["Device theft", "Travel devices", "Brand trust"],
  },
  {
    id: "insurance-axa-device-flex",
    slug: "axa-device-flex",
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Device Flex",
    subtitle: "Flexible gadget cover for everyday electronics with accidental damage and theft protection.",
    insuranceType: "device",
    countryCodes: ["FR", "ES", "IT"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliatePriorityScore: 0.76,
    priceAmount: 8,
    coverageAmount: 1500,
    deductibleAmount: 50,
    regionCoverage: "regional",
    deviceCover: "Smartphone and laptop cover",
    theftLiquid: "Theft, drops, and liquid damage",
    worldwideProtection: "EU and travel protection",
    bestFor: ["Everyday devices", "Lower deductible", "Flexible cover"],
  },
  {
    id: "insurance-ergo-device-safe",
    slug: "ergo-device-safe",
    providerMark: "ER",
    providerName: "ERGO",
    title: "ERGO Device Safe",
    subtitle: "Lower-cost device insurance for standard phones and laptops with clear theft and damage wording.",
    insuranceType: "device",
    countryCodes: ["DE", "AT"],
    providerWebsiteUrl: "https://www.ergo.com",
    affiliatePriorityScore: 0.73,
    priceAmount: 6,
    coverageAmount: 1200,
    deductibleAmount: 100,
    regionCoverage: "regional",
    deviceCover: "Phone and laptop cover",
    theftLiquid: "Theft and accidental damage",
    worldwideProtection: "Regional cover",
    bestFor: ["Lower monthly price", "Simple gadget cover", "Local markets"],
    feeProfile: "low",
  },
  {
    id: "insurance-admiral-gadget-cover",
    slug: "admiral-gadget-cover",
    providerMark: "AD",
    providerName: "Admiral",
    title: "Admiral Gadget Cover",
    subtitle: "Gadget insurance with theft and travel-friendly protection for connected devices.",
    insuranceType: "device",
    countryCodes: ["UK", "ES", "PT"],
    providerWebsiteUrl: "https://www.admiral.com",
    affiliatePriorityScore: 0.74,
    priceAmount: 7,
    coverageAmount: 1800,
    deductibleAmount: 80,
    regionCoverage: "worldwide",
    deviceCover: "Mobile and gadget cover",
    theftLiquid: "Theft, cracks, and liquid damage",
    worldwideProtection: "Worldwide cover",
    bestFor: ["Travel devices", "Gadget bundles", "Theft cover"],
  },
  {
    id: "insurance-zurich-device-pro",
    slug: "zurich-device-pro",
    providerMark: "ZU",
    providerName: "Zurich",
    title: "Zurich Device Pro",
    subtitle: "Higher-limit electronics protection with broader accidental damage and travel cover.",
    insuranceType: "device",
    countryCodes: ["EU", "UK"],
    providerWebsiteUrl: "https://www.zurich.com",
    affiliatePriorityScore: 0.75,
    priceAmount: 11,
    coverageAmount: 3000,
    deductibleAmount: 100,
    regionCoverage: "worldwide",
    deviceCover: "Premium electronics cover",
    theftLiquid: "Accidental damage, theft, and liquid damage",
    worldwideProtection: "Worldwide protection",
    bestFor: ["Premium devices", "Higher limits", "Travel-friendly"],
  },
  {
    id: "insurance-orange-device-plan",
    slug: "orange-device-plan",
    providerMark: "OR",
    providerName: "Orange Protect",
    title: "Orange Device Plan",
    subtitle: "Carrier-linked gadget protection for phones and connected devices with simple monthly pricing.",
    insuranceType: "device",
    countryCodes: ["FR", "ES"],
    providerWebsiteUrl: "https://www.orange.com",
    affiliatePriorityScore: 0.7,
    priceAmount: 5,
    coverageAmount: 1200,
    deductibleAmount: 75,
    regionCoverage: "regional",
    deviceCover: "Phone and connected devices",
    theftLiquid: "Theft and breakage",
    worldwideProtection: "Regional travel protection",
    bestFor: ["Lower cost", "Phone-only cover", "Carrier-linked"],
    feeProfile: "low",
  },
];

const generatedInsuranceOffers: MarketplaceOffer[] = generatedInsuranceCatalog.map(buildInsuranceOffer);

const expandedOffers: MarketplaceOffer[] = [
  {
    id: "insurance-allianz-life-protect",
    slug: "allianz-life-protect",
    category: "insurance",
    countryCodes: ["DE", "FR", "IT", "ES"],
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Life Protect",
    subtitle:
      "Life cover designed for long-term family protection with flexible terms and clearer benefit bands across major European markets.",
    metrics: [
      { label: "Insured amount", value: "EUR 100,000 - 500,000" },
      { label: "Monthly premium", value: "EUR 19 - 62" },
      { label: "Term", value: "5 - 30 years" },
      { label: "Family cover", value: "Flexible beneficiary options" },
    ],
    bestFor: ["Family protection", "Long-term cover", "Established insurer"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.9,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "life",
      insuranceType: "life",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["life insurance", "protection", "beneficiary", "family cover"],
    },
  },
  {
    id: "insurance-axa-health-essential",
    slug: "axa-health-essential",
    category: "insurance",
    countryCodes: ["FR", "ES", "IT", "DE"],
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Health Essential",
    subtitle:
      "Private health cover with digital claims, outpatient support, and a simple plan structure for people moving between large European markets.",
    metrics: [
      { label: "Outpatient", value: "Primary and specialist care" },
      { label: "Inpatient", value: "Private room and surgery cover" },
      { label: "Digital claims", value: "App and online claims" },
      { label: "Monthly premium", value: "EUR 29 - 89" },
    ],
    bestFor: ["Health cover", "Digital claims", "Cross-border living"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliateLink: "https://www.axaglobalhealthcare.com/en/",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "health",
      insuranceType: "health",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["health insurance", "medical cover", "claims", "outpatient"],
    },
  },
  {
    id: "insurance-alan-smart-health",
    slug: "alan-smart-health",
    category: "insurance",
    countryCodes: ["FR", "ES", "BE"],
    providerMark: "AL",
    providerName: "Alan",
    title: "Alan Smart Health",
    subtitle:
      "Digital-first health insurance with fast reimbursements, virtual support, and employer-friendly health plans.",
    metrics: [
      { label: "Outpatient", value: "Primary and specialist visits" },
      { label: "Inpatient", value: "Hospital cover and recovery support" },
      { label: "Digital claims", value: "Fast app reimbursements" },
      { label: "Monthly premium", value: "EUR 34 - 71" },
    ],
    bestFor: ["Digital-first", "Fast reimbursements", "Health cover"],
    providerWebsiteUrl: "https://alan.com",
    affiliateLink: "https://alan.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "health",
      insuranceType: "health",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["health insurance", "reimbursements", "employee benefits", "digital claims"],
    },
  },
  {
    id: "insurance-admiral-travel-cover",
    slug: "admiral-travel-cover",
    category: "insurance",
    countryCodes: ["UK", "ES", "PT", "FR"],
    providerMark: "AD",
    providerName: "Admiral",
    title: "Admiral Travel Cover",
    subtitle:
      "Travel insurance built for short and long trips with strong medical limits, delay protection, and practical claims handling.",
    metrics: [
      { label: "Price", value: "EUR 18 - 46 / trip" },
      { label: "Trip length", value: "Up to 120 days" },
      { label: "Medical cover", value: "Up to EUR 10m" },
      { label: "Baggage / delay", value: "Included with travel disruption cover" },
      { label: "Region coverage", value: "Europe and worldwide options" },
    ],
    bestFor: ["Travel cover", "Medical protection", "Frequent trips"],
    providerWebsiteUrl: "https://www.admiral.com",
    affiliateLink: "https://www.admiral.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "travel",
      insuranceType: "travel",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["travel insurance", "holiday cover", "medical cover", "baggage delay"],
    },
  },
  {
    id: "insurance-generali-auto-guard",
    slug: "generali-auto-guard",
    category: "insurance",
    countryCodes: ["IT", "DE", "ES", "FR"],
    providerMark: "GN",
    providerName: "Generali",
    title: "Generali Auto Guard",
    subtitle:
      "Motor insurance focused on everyday drivers who want roadside support, strong liability limits, and broader protection options.",
    metrics: [
      { label: "Monthly premium", value: "EUR 38 - 96" },
      { label: "Liability", value: "Up to EUR 50m" },
      { label: "Collision / theft", value: "Optional comprehensive add-on" },
      { label: "Roadside support", value: "24/7 assistance" },
      { label: "Deductible", value: "From EUR 250" },
    ],
    bestFor: ["Car cover", "Roadside support", "Everyday driving"],
    providerWebsiteUrl: "https://www.generali.com",
    affiliateLink: "https://www.generali.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "auto",
      insuranceType: "auto",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["car insurance", "motor cover", "roadside assistance", "deductible"],
    },
  },
  {
    id: "insurance-safetywing-nomad",
    slug: "safetywing-nomad-insurance",
    category: "insurance",
    countryCodes: ["EU", "UK"],
    providerMark: "SW",
    providerName: "SafetyWing",
    title: "SafetyWing Nomad Insurance",
    subtitle:
      "Rolling international cover for remote workers and frequent movers who need monthly flexibility rather than a fixed-trip policy.",
    metrics: [
      { label: "Price", value: "USD 45 / 4 weeks" },
      { label: "Rolling monthly", value: "Monthly renewal while abroad" },
      { label: "Countries covered", value: "180+ countries" },
      { label: "Medical emergencies", value: "Travel medical and urgent care" },
      { label: "Remote work suitability", value: "Built for nomads and freelancers" },
    ],
    bestFor: ["Remote workers", "Travel cover", "International movement"],
    providerWebsiteUrl: "https://safetywing.com",
    affiliateLink: "https://safetywing.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "nomad",
      insuranceType: "nomad",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["nomad insurance", "remote work", "international cover", "monthly cover"],
    },
  },
  ...generatedInsuranceOffers,
  {
    id: "investment-trade-republic-core",
    slug: "trade-republic-core-invest",
    category: "investments",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Core Invest",
    subtitle:
      "Low-friction investing with ETF savings plans, stock access, and a clean workflow for long-term retail investors.",
    metrics: [
      { label: "ETF trades", value: "From EUR 1" },
      { label: "Savings plan", value: "From EUR 1" },
      { label: "Markets", value: "9 exchanges" },
    ],
    bestFor: ["ETF plans", "Long-term investing", "Recurring plans"],
    providerWebsiteUrl: "https://traderepublic.com",
    affiliateLink: "https://traderepublic.com/",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["stocks", "etf", "savings plan", "broker"],
      supportedAssets: ["spy", "qqq", "eustocks", "gold"],
      accessType: "etf_dealing",
      estimatedCostLabel: "ETF access from EUR 1",
      feeModel: "Exchange fee plus venue pricing",
      estimatedSpreadRange: "Market spread only",
      recurringSupported: true,
      minimumOrder: "EUR 1",
      minDeposit: "EUR 0",
      assetsAvailableLabel: "ETFs, stocks, ETPs",
      platformUxLevel: "beginner",
      notes: "Strong starting point for recurring ETF exposure in EUR.",
    },
  },
  {
    id: "investment-scalable-prime",
    slug: "scalable-capital-prime-broker",
    category: "investments",
    countryCodes: ["DE", "FR", "ES", "IT", "AT"],
    providerMark: "SC",
    providerName: "Scalable Capital",
    title: "Scalable Capital Prime Broker",
    subtitle:
      "A brokerage and wealth platform combining broad ETF access with recurring investing and portfolio tools.",
    metrics: [
      { label: "ETF trades", value: "From EUR 0.99" },
      { label: "Savings plan", value: "From EUR 1" },
      { label: "Custody fee", value: "EUR 0" },
    ],
    bestFor: ["ETF investors", "Portfolio building", "Recurring plans"],
    providerWebsiteUrl: "https://de.scalable.capital",
    affiliateLink: "https://www.scalable.capital/en/broker",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["broker platform", "etf", "wealth platform"],
      supportedAssets: ["spy", "qqq", "eustocks", "gold"],
      accessType: "etf_dealing",
      estimatedCostLabel: "ETF orders from EUR 0.99",
      feeModel: "Subscription or per-order pricing depending on plan",
      estimatedSpreadRange: "Market spread only",
      recurringSupported: true,
      minimumOrder: "EUR 1",
      minDeposit: "EUR 0",
      assetsAvailableLabel: "ETFs, stocks, portfolios",
      platformUxLevel: "beginner",
      notes: "Useful when you want ETF breadth with recurring plans in one place.",
    },
  },
  {
    id: "investment-etoro-multi-asset",
    slug: "etoro-multi-asset-account",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "ET",
    providerName: "eToro",
    title: "eToro Multi-Asset Account",
    subtitle:
      "A single investing account for ETFs, crypto, commodities, and macro-led access across public markets.",
    metrics: [
      { label: "Access", value: "ETFs, crypto, commodities, FX" },
      { label: "Custody fee", value: "EUR 0" },
      { label: "Markets", value: "Global listed markets" },
    ],
    bestFor: ["Multi-asset", "Cross-market discovery", "One-account access"],
    providerWebsiteUrl: "https://www.etoro.com",
    affiliateLink: "https://www.etoro.com/investing/",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["social investing", "stocks", "crypto", "platform", "commodities", "fx"],
      supportedAssets: ["btc", "eth", "spy", "qqq", "eustocks", "gold", "eurusd"],
      accessType: "multi_asset_brokerage",
      estimatedCostLabel: "Spread-based market access",
      feeModel: "Spread varies by market and route",
      estimatedSpreadRange: "~0.15% to 1.00% depending on asset",
      recurringSupported: false,
      minimumOrder: "USD 10",
      minDeposit: "USD 50",
      assetsAvailableLabel: "ETFs, crypto, commodities, FX",
      platformUxLevel: "intermediate",
      notes: "Useful when you want one route across crypto, ETFs, gold, and FX-style exposure.",
    },
  },
  {
    id: "investment-degiro-global",
    slug: "degiro-global-investor",
    category: "investments",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "PT"],
    providerMark: "DG",
    providerName: "DEGIRO",
    title: "DEGIRO Global Investor",
    subtitle:
      "A brokerage aimed at cost-aware investors who want broad exchange access and stronger market depth across Europe.",
    metrics: [
      { label: "ETF trades", value: "From EUR 1" },
      { label: "Markets", value: "50+ global exchanges" },
      { label: "Custody fee", value: "No custody fee" },
    ],
    bestFor: ["Stocks", "Low-cost trading", "Broad market access"],
    providerWebsiteUrl: "https://www.degiro.com",
    affiliateLink: "https://www.degiro.com/trading-platform",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "stocks",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["stocks", "broker", "exchange access", "etf"],
      supportedAssets: ["spy", "qqq", "eustocks", "gold"],
      accessType: "etf_dealing",
      estimatedCostLabel: "Low exchange + handling fee",
      feeModel: "Exchange fee and venue costs",
      estimatedSpreadRange: "Market spread only",
      recurringSupported: false,
      minimumOrder: "Exchange minimums apply",
      minDeposit: "EUR 0",
      assetsAvailableLabel: "ETFs, stocks, funds",
      platformUxLevel: "intermediate",
      notes: "Useful when listed-market access matters more than recurring-plan convenience.",
    },
  },
  {
    id: "investment-bitpanda-crypto-metals",
    slug: "bitpanda-crypto-metals",
    category: "investments",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda Crypto & Metals",
    subtitle:
      "Crypto and precious-metals access with recurring buys and an interface built for euro-based retail investors.",
    metrics: [
      { label: "Access", value: "Crypto and precious metals" },
      { label: "Crypto fee", value: "Included in quoted spread" },
      { label: "Savings plan", value: "Recurring buys available" },
    ],
    bestFor: ["Crypto", "Recurring buys", "Gold access"],
    providerWebsiteUrl: "https://www.bitpanda.com",
    affiliateLink: "https://www.bitpanda.com/en/stocks",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["crypto", "digital assets", "recurring buys", "metals", "gold"],
      supportedAssets: ["btc", "eth", "gold"],
      accessType: "recurring_buy",
      estimatedCostLabel: "Spread included in quote",
      feeModel: "Quoted spread with recurring-buy option",
      estimatedSpreadRange: "~0.99% to 1.49%",
      recurringSupported: true,
      minimumOrder: "EUR 1",
      minDeposit: "EUR 1",
      assetsAvailableLabel: "Crypto, metals, stocks",
      platformUxLevel: "beginner",
      notes: "Strong fit for euro-based recurring buys across crypto and metals.",
    },
  },
  {
    id: "investment-coinbase-simple",
    slug: "coinbase-simple-crypto",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "CB",
    providerName: "Coinbase",
    title: "Coinbase Simple Crypto",
    subtitle:
      "A well-known crypto platform for straightforward purchase flows, recurring orders, and brand familiarity.",
    metrics: [
      { label: "Access", value: "Major crypto assets" },
      { label: "Crypto fee", value: "Varies by transaction" },
      { label: "Savings plan", value: "Recurring buys available" },
    ],
    bestFor: ["Crypto", "Beginner access", "Recurring buys"],
    providerWebsiteUrl: "https://www.coinbase.com",
    affiliateLink: "https://www.coinbase.com/trade",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "premium",
      availability: "international",
      searchTags: ["crypto", "beginner investing", "digital assets", "recurring"],
      supportedAssets: ["btc", "eth"],
      accessType: "recurring_buy",
      estimatedCostLabel: "Quoted spread + transaction fee",
      feeModel: "Spread and transaction-based pricing",
      estimatedSpreadRange: "~0.50% to 1.50% plus fee",
      recurringSupported: true,
      minimumOrder: "EUR 2",
      minDeposit: "EUR 2",
      assetsAvailableLabel: "Major crypto assets",
      platformUxLevel: "beginner",
      notes: "Better suited to simple recurring crypto access than tight trading spreads.",
    },
  },
  {
    id: "investment-kraken-europe",
    slug: "kraken-europe-crypto",
    category: "investments",
    countryCodes: ["EU"],
    providerMark: "KR",
    providerName: "Kraken",
    title: "Kraken Europe Crypto Access",
    subtitle:
      "Crypto access with a stronger exchange-style workflow, better suited to users who care about tighter pricing and direct market access.",
    metrics: [
      { label: "Access", value: "BTC, ETH and major crypto pairs" },
      { label: "Crypto fee", value: "From 0.16% maker / 0.26% taker" },
      { label: "Savings plan", value: "Recurring buys available" },
    ],
    bestFor: ["Crypto", "Tighter pricing", "Repeat buyers"],
    providerWebsiteUrl: "https://www.kraken.com",
    affiliateLink: "https://www.kraken.com/prices/btc-bitcoin-price-chart/eur-euro",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "low",
      availability: "international",
      searchTags: ["crypto exchange", "btc", "eth", "exchange pricing"],
      supportedAssets: ["btc", "eth"],
      accessType: "spot_crypto",
      estimatedCostLabel: "Exchange-style fee from 0.16%",
      feeModel: "Maker/taker fee plus spread on simple buy flow",
      estimatedSpreadRange: "~0.20% to 0.60% on exchange flow",
      recurringSupported: true,
      minimumOrder: "EUR 10",
      minDeposit: "EUR 10",
      assetsAvailableLabel: "BTC, ETH, major crypto pairs",
      platformUxLevel: "advanced",
      notes: "Better fit when you care about tighter crypto pricing than simple retail flow.",
    },
  },
  {
    id: "investment-binance-eu",
    slug: "binance-eu-crypto-access",
    category: "investments",
    countryCodes: ["EU"],
    providerMark: "BN",
    providerName: "Binance EU",
    title: "Binance EU Crypto Access",
    subtitle:
      "Exchange-style crypto access for users who want direct market routing and a wider asset list than a basic retail buy flow.",
    metrics: [
      { label: "Access", value: "BTC, ETH and wide crypto list" },
      { label: "Crypto fee", value: "From 0.10%" },
      { label: "Markets", value: "Advanced spot routing" },
    ],
    bestFor: ["Crypto", "Lower headline fee", "Active market access"],
    providerWebsiteUrl: "https://www.binance.com/en-EU",
    affiliateLink: "https://www.binance.com/en-EU/trade/BTC_EUR",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "low",
      availability: "international",
      searchTags: ["crypto exchange", "btc", "eth", "spot market"],
      supportedAssets: ["btc", "eth"],
      accessType: "spot_crypto",
      estimatedCostLabel: "Spot fee from 0.10%",
      feeModel: "Exchange fee, spread depends on route",
      estimatedSpreadRange: "~0.10% to 0.40% on liquid pairs",
      recurringSupported: false,
      minimumOrder: "Exchange minimums apply",
      minDeposit: "Route dependent",
      assetsAvailableLabel: "BTC, ETH, wider crypto list",
      platformUxLevel: "pro",
      notes: "Useful when lower headline fee matters more than a simplified retail flow.",
    },
  },
  {
    id: "investment-trading212-market-access",
    slug: "trading-212-market-access",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "T212",
    providerName: "Trading 212",
    title: "Trading 212 Market Access",
    subtitle:
      "A clean retail brokerage for ETF and equity exposure with savings-style investing features and broad self-directed access.",
    metrics: [
      { label: "ETF trades", value: "Commission-free dealing" },
      { label: "Savings plan", value: "Recurring investing available" },
      { label: "Markets", value: "US, UK and EU listed assets" },
    ],
    bestFor: ["ETF access", "Long-term investing", "Simple interface"],
    providerWebsiteUrl: "https://www.trading212.com",
    affiliateLink: "https://www.trading212.com/invest",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "international",
      searchTags: ["etf", "stocks", "recurring investing", "broker"],
      supportedAssets: ["spy", "qqq", "eustocks", "gold"],
      accessType: "etf_dealing",
      estimatedCostLabel: "Commission-free listed access",
      feeModel: "Spread and FX costs depend on instrument and account currency",
      estimatedSpreadRange: "Market spread + FX conversion when needed",
      recurringSupported: true,
      minimumOrder: "Instrument minimums apply",
      minDeposit: "EUR 1",
      assetsAvailableLabel: "ETFs, stocks, pies",
      platformUxLevel: "beginner",
      notes: "Useful when you want low-friction ETF access with recurring investing tools.",
    },
  },
  {
    id: "investment-interactive-brokers-global",
    slug: "interactive-brokers-global-markets",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "IB",
    providerName: "Interactive Brokers",
    title: "Interactive Brokers Global Markets",
    subtitle:
      "Broad market access across ETFs, commodities, and FX for users who want deeper routing and tighter institutional-style pricing.",
    metrics: [
      { label: "Access", value: "ETFs, commodities, FX" },
      { label: "Custody fee", value: "EUR 0" },
      { label: "Markets", value: "Global exchanges and FX pairs" },
    ],
    bestFor: ["Cross-market access", "FX routing", "Cost-aware investors"],
    providerWebsiteUrl: "https://www.interactivebrokers.com",
    affiliateLink: "https://www.interactivebrokers.com/en/trading/products-stocks.php",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "international",
      searchTags: ["etf", "fx", "global markets", "brokerage"],
      supportedAssets: ["spy", "qqq", "eustocks", "gold", "eurusd"],
      accessType: "multi_asset_brokerage",
      estimatedCostLabel: "Tighter market-style pricing",
      feeModel: "Commission plus market spread",
      estimatedSpreadRange: "~0.10% to 0.50% depending on route",
      recurringSupported: false,
      minimumOrder: "Route-dependent minimums",
      minDeposit: "EUR 0",
      assetsAvailableLabel: "ETFs, equities, FX, commodities",
      platformUxLevel: "pro",
      notes: "Stronger fit when FX access and cross-market routing matter more than simplicity.",
    },
  },
  {
    id: "investment-revolut-crypto-fx",
    slug: "revolut-crypto-fx-access",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Crypto & FX Access",
    subtitle:
      "In-app crypto access and multi-currency routing for users who want a familiar interface and lightweight market access from one account.",
    metrics: [
      { label: "Access", value: "BTC, ETH and in-app FX routing" },
      { label: "Conversion fee", value: "Plan and timing dependent" },
      { label: "Savings plan", value: "Recurring crypto access available" },
    ],
    bestFor: ["Simple crypto access", "Multi-currency", "In-app routing"],
    providerWebsiteUrl: "https://www.revolut.com",
    affiliateLink: "https://www.revolut.com/stock-trading/",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.8,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["crypto", "fx", "multi-currency", "recurring crypto"],
      supportedAssets: ["btc", "eth", "eurusd"],
      accessType: "multi_currency_fx",
      estimatedCostLabel: "Plan-based spread and conversion pricing",
      feeModel: "Spread varies by asset, plan, and timing",
      estimatedSpreadRange: "~0.25% to 1.50% depending on route",
      recurringSupported: true,
      minimumOrder: "App minimums apply",
      minDeposit: "EUR 0",
      assetsAvailableLabel: "Crypto, FX, multi-currency balances",
      platformUxLevel: "beginner",
      notes: "Useful when you want simple crypto or FX access without a separate brokerage workflow.",
    },
  },
  {
    id: "investment-kraken-crypto-access",
    slug: "kraken-crypto-access",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "KR",
    providerName: "Kraken",
    title: "Kraken Crypto Access",
    subtitle:
      "Crypto trading access for BTC and ETH with deeper exchange tooling, lower-fee execution paths, and stronger active-investor workflows.",
    metrics: [
      { label: "Access", value: "BTC, ETH and major crypto pairs" },
      { label: "Fee model", value: "Low-fee exchange pricing" },
      { label: "Platform", value: "Advanced trading and pro tools" },
    ],
    bestFor: ["Crypto", "Low fees", "Pro tools"],
    providerWebsiteUrl: "https://www.kraken.com",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C5666133898T",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.9,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "crypto",
      isPartner: true,
      affiliate: true,
      monetized: true,
      riskProfile: "growth",
      feeProfile: "low",
      availability: "international",
      searchTags: ["crypto", "btc", "eth", "low fees", "pro tools"],
      supportedAssets: ["btc", "eth"],
      accessType: "spot_crypto",
      recurringSupported: true,
      minimumOrder: "Exchange minimums apply",
      minDeposit: "EUR 1",
      assetsAvailableLabel: "Crypto spot trading",
      platformUxLevel: "pro",
      notes: "Financeads affiliate link required for monetized crypto handoff.",
    },
  },
  {
    id: "investment-linxea-avenir-2",
    slug: "linxea-avenir-2",
    category: "investments",
    countryCodes: ["FR"],
    providerMark: "LX",
    providerName: "Linxea",
    title: "Linxea Avenir 2",
    subtitle:
      "French assurance vie product for long-term savings and investment insurance positioning with tax-aware wrappers and local-market fit.",
    metrics: [
      { label: "Product type", value: "Assurance vie" },
      { label: "Market", value: "France" },
      { label: "Positioning", value: "Long-term tax-efficient savings" },
    ],
    bestFor: ["Assurance vie", "Long-term savings", "Tax-efficient savings"],
    providerWebsiteUrl: "https://www.linxea.com",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C432495606T",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "assurance_vie",
      isPartner: true,
      affiliate: true,
      monetized: true,
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "local",
      searchTags: [
        "assurance vie",
        "long-term savings",
        "france",
        "investment insurance",
        "tax-efficient savings",
      ],
      accessType: "multi_asset_brokerage",
      recurringSupported: true,
      minimumOrder: "Policy minimums apply",
      minDeposit: "EUR 100",
      assetsAvailableLabel: "Insurance-wrapped long-term savings",
      platformUxLevel: "intermediate",
      notes: "French assurance vie offer routed through financeads tracking.",
    },
  },
  {
    id: "investment-iuvo-p2p-investing",
    slug: "iuvo-p2p-investing",
    category: "investments",
    countryCodes: ["DE", "EU"],
    providerMark: "IV",
    providerName: "Iuvo Group",
    title: "Iuvo P2P Investing",
    subtitle:
      "P2P investing platform focused on fixed-income style loan exposure with diversified marketplace access for Germany and wider EU users.",
    metrics: [
      { label: "Access", value: "Diversified P2P loan portfolios" },
      { label: "Return style", value: "Fixed-income marketplace exposure" },
      { label: "Market", value: "Germany and EU availability" },
    ],
    bestFor: ["P2P", "Passive income", "Fixed returns"],
    providerWebsiteUrl: "https://iuvo-group.com",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C226841413T",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "p2p",
      isPartner: true,
      affiliate: true,
      monetized: true,
      riskProfile: "balanced",
      feeProfile: "medium",
      availability: "eu_wide",
      searchTags: ["p2p", "passive income", "fixed returns", "lending marketplace", "eu investing"],
      accessType: "multi_asset_brokerage",
      recurringSupported: true,
      minimumOrder: "Platform minimums apply",
      minDeposit: "EUR 10",
      assetsAvailableLabel: "P2P lending marketplace",
      platformUxLevel: "intermediate",
      notes: "Financeads affiliate handoff for EU P2P investing.",
    },
  },
  {
    id: "investment-trezor-hardware-wallet",
    slug: "trezor-hardware-wallet",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "TZ",
    providerName: "Trezor",
    title: "Trezor Hardware Wallet",
    subtitle:
      "Offline hardware wallet for securing BTC, ETH, and broader crypto holdings when custody and cold-storage control matter more than exchange convenience.",
    metrics: [
      { label: "Security", value: "Offline cold storage" },
      { label: "Assets", value: "BTC, ETH and supported crypto assets" },
      { label: "Use case", value: "Hardware wallet self-custody" },
    ],
    bestFor: ["Crypto", "Security", "Hardware wallet"],
    providerWebsiteUrl: "https://trezor.io",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C5142119968T",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "crypto_wallet",
      isPartner: true,
      affiliate: true,
      monetized: true,
      riskProfile: "balanced",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["crypto", "security", "hardware wallet", "btc", "cold storage"],
      supportedAssets: ["btc", "eth"],
      accessType: "spot_crypto",
      recurringSupported: false,
      minimumOrder: "Device purchase required",
      minDeposit: "N/A",
      assetsAvailableLabel: "Offline crypto storage",
      platformUxLevel: "intermediate",
      notes: "Financeads affiliate link required for Trezor product handoff.",
    },
  },
];

const expandedInvestmentOffers: MarketplaceOffer[] = [
  {
    id: "investment-etoro-multi-asset",
    slug: "etoro-multi-asset",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "ET",
    providerName: "eToro",
    title: "eToro Multi-Asset Investing",
    subtitle: "Multi-asset investing access for users comparing stocks, ETFs, and crypto exposure in one account.",
    metrics: [
      { label: "Access", value: "Stocks, ETFs, crypto and copy portfolios" },
      { label: "Fee model", value: "Spread and product fees vary" },
      { label: "Minimum", value: "Low starting deposits" },
    ],
    bestFor: ["Multi-asset", "Beginner tools", "Crypto access"],
    providerWebsiteUrl: "https://www.etoro.com",
    affiliateLink: "https://www.etoro.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.8,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "brokerage",
      riskProfile: "balanced",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["stocks", "etfs", "crypto", "copy trading", "multi-asset"],
      accessType: "multi_asset_brokerage",
      recurringSupported: true,
      minDeposit: "Low minimums",
      platformUxLevel: "beginner",
    },
  },
  {
    id: "investment-scalable-capital-broker",
    slug: "scalable-capital-broker",
    category: "investments",
    countryCodes: ["DE", "EU"],
    providerMark: "SC",
    providerName: "Scalable Capital",
    title: "Scalable Capital Broker",
    subtitle: "ETF and stock brokerage with savings-plan workflows for users who want automated recurring investing.",
    metrics: [
      { label: "Access", value: "ETFs, stocks and savings plans" },
      { label: "Fee model", value: "Plan-based trading costs" },
      { label: "Recurring", value: "Savings plans supported" },
    ],
    bestFor: ["ETF plans", "Recurring buys", "Germany"],
    providerWebsiteUrl: "https://de.scalable.capital",
    affiliateLink: "https://de.scalable.capital",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "brokerage",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "eu_wide",
      searchTags: ["etf", "savings plans", "stocks", "recurring investing"],
      accessType: "etf_dealing",
      recurringSupported: true,
      minDeposit: "Low minimums",
      platformUxLevel: "beginner",
    },
  },
  {
    id: "investment-bitpanda-broker",
    slug: "bitpanda-broker",
    category: "investments",
    countryCodes: ["EU"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda Broker",
    subtitle: "European investing app for crypto, stocks, ETFs, and commodities with a clear mobile-first account flow.",
    metrics: [
      { label: "Access", value: "Crypto, stocks, ETFs and metals" },
      { label: "Fee model", value: "Spread-led pricing" },
      { label: "Minimum", value: "Fractional investing" },
    ],
    bestFor: ["Crypto", "Fractional investing", "Commodities"],
    providerWebsiteUrl: "https://www.bitpanda.com",
    affiliateLink: "https://www.bitpanda.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "crypto_broker",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "eu_wide",
      searchTags: ["crypto", "fractional", "metals", "stocks", "etfs"],
      supportedAssets: ["btc", "eth", "gold"],
      accessType: "multi_asset_brokerage",
      recurringSupported: true,
      minDeposit: "Fractional orders",
      platformUxLevel: "beginner",
    },
  },
  {
    id: "investment-freetrade-eu",
    slug: "freetrade-eu-investing",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "FT",
    providerName: "Freetrade",
    title: "Freetrade Investing",
    subtitle: "Simple stock and ETF investing for users who prioritize clean UX and long-term portfolio building.",
    metrics: [
      { label: "Access", value: "Stocks and ETFs" },
      { label: "Fee model", value: "Plan and FX costs vary" },
      { label: "Use case", value: "Long-term portfolios" },
    ],
    bestFor: ["Simple UX", "Long-term investing", "ETF access"],
    providerWebsiteUrl: "https://freetrade.io",
    affiliateLink: "https://freetrade.io",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "brokerage",
      riskProfile: "balanced",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["stocks", "etfs", "simple investing", "long-term"],
      accessType: "etf_dealing",
      recurringSupported: true,
      minDeposit: "Low minimums",
      platformUxLevel: "beginner",
    },
  },
  {
    id: "investment-xtb-invest",
    slug: "xtb-invest",
    category: "investments",
    countryCodes: ["EU", "DE", "ES", "FR", "IT", "PT"],
    providerMark: "XB",
    providerName: "XTB",
    title: "XTB Invest",
    subtitle: "European brokerage access for stocks, ETFs, and more active market users who want broader tooling.",
    metrics: [
      { label: "Access", value: "Stocks, ETFs and trading tools" },
      { label: "Fee model", value: "Product and FX costs vary" },
      { label: "Platform", value: "Advanced market tooling" },
    ],
    bestFor: ["Active investors", "European coverage", "Market tools"],
    providerWebsiteUrl: "https://www.xtb.com",
    affiliateLink: "https://www.xtb.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.75,
    updatedAt: "2026-04-30T00:00:00Z",
    attributes: {
      subtype: "brokerage",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "eu_wide",
      searchTags: ["stocks", "etfs", "active investing", "trading tools"],
      accessType: "multi_asset_brokerage",
      recurringSupported: false,
      minDeposit: "Platform minimums apply",
      platformUxLevel: "advanced",
    },
  },
];

export const marketplaceOffers = [
  ...catalogExpansionOffers,
  ...coreOffers,
  ...expandedOffers,
  ...supplementalMarketplaceOffers,
  ...expandedInvestmentOffers,
  ...newCategoriesOffers,
];
