import type { MarketplaceOffer } from "@payn/types";
import { featuredOffers as coreOffers } from "@/features/catalog/mock-data";

const expandedOffers: MarketplaceOffer[] = [
  {
    id: "insurance-allianz-life-protect",
    slug: "allianz-life-protect",
    category: "insurance",
    countryCodes: ["DE", "FR", "IT", "ES"],
    providerMark: "AZ",
    providerName: "Allianz",
    title: "Allianz Life Protect",
    subtitle:
      "Life cover designed for long-term family protection with flexible monthly premiums and clear cover bands across major European markets.",
    metrics: [
      { label: "Cover", value: "EUR 100,000 - 500,000" },
      { label: "Monthly premium", value: "EUR 19 - 62" },
      { label: "Term", value: "5 - 30 years" },
    ],
    bestFor: ["Family protection", "Long-term cover", "Established insurer"],
    providerWebsiteUrl: "https://www.allianz.com",
    affiliateLink: "https://www.allianz.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.9,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "life",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["life insurance", "protection", "beneficiary"],
    },
  },
  {
    id: "insurance-axa-health-essential",
    slug: "axa-health-essential",
    category: "insurance",
    countryCodes: ["FR", "ES", "IT", "DE"],
    providerMark: "AXA",
    providerName: "AXA",
    title: "AXA Health Essential",
    subtitle:
      "Private health cover with digital claims, outpatient support, and a simple plan structure for people moving between large European markets.",
    metrics: [
      { label: "Cover", value: "Outpatient and inpatient" },
      { label: "Monthly premium", value: "EUR 29 - 89" },
      { label: "Waiting period", value: "30 days" },
    ],
    bestFor: ["Health cover", "Digital claims", "Cross-border living"],
    providerWebsiteUrl: "https://www.axa.com",
    affiliateLink: "https://www.axa.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "health",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["health insurance", "medical cover", "claims"],
    },
  },
  {
    id: "insurance-alan-smart-health",
    slug: "alan-smart-health",
    category: "insurance",
    countryCodes: ["FR", "ES", "BE"],
    providerMark: "AL",
    providerName: "Alan",
    title: "Alan Smart Health",
    subtitle:
      "Digital-first health insurance with strong app support, simple reimbursements, and employer-friendly plan management.",
    metrics: [
      { label: "Cover", value: "Primary and specialist care" },
      { label: "Monthly premium", value: "EUR 34 - 71" },
      { label: "Waiting period", value: "14 days" },
    ],
    bestFor: ["Digital-first", "Fast reimbursements", "Health cover"],
    providerWebsiteUrl: "https://alan.com",
    affiliateLink: "https://alan.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "health",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["health insurance", "reimbursements", "employee benefits"],
    },
  },
  {
    id: "insurance-admiral-travel-cover",
    slug: "admiral-travel-cover",
    category: "insurance",
    countryCodes: ["UK", "ES", "PT", "FR"],
    providerMark: "AD",
    providerName: "Admiral",
    title: "Admiral Travel Cover",
    subtitle:
      "Travel insurance built for short and long trips with strong medical limits, gadget protection, and practical claim handling.",
    metrics: [
      { label: "Trip length", value: "Up to 120 days" },
      { label: "Cover", value: "Medical cover up to EUR 10m" },
      { label: "Excess", value: "EUR 75" },
    ],
    bestFor: ["Travel cover", "Medical protection", "Frequent trips"],
    providerWebsiteUrl: "https://www.admiral.com",
    affiliateLink: "https://www.admiral.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "travel",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["travel insurance", "holiday cover", "medical cover"],
    },
  },
  {
    id: "insurance-generali-auto-guard",
    slug: "generali-auto-guard",
    category: "insurance",
    countryCodes: ["IT", "DE", "ES", "FR"],
    providerMark: "GN",
    providerName: "Generali",
    title: "Generali Auto Guard",
    subtitle:
      "Motor insurance focused on everyday drivers who want roadside support, higher liability limits, and known European underwriting.",
    metrics: [
      { label: "Liability", value: "Up to EUR 50m" },
      { label: "Roadside", value: "24/7 assistance" },
      { label: "Monthly premium", value: "EUR 34 - 91" },
    ],
    bestFor: ["Car cover", "Roadside support", "Everyday driving"],
    providerWebsiteUrl: "https://www.generali.com",
    affiliateLink: "https://www.generali.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "car",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["car insurance", "motor cover", "roadside assistance"],
    },
  },
  {
    id: "insurance-safetywing-nomad",
    slug: "safetywing-nomad-insurance",
    category: "insurance",
    countryCodes: ["EU", "UK"],
    providerMark: "SW",
    providerName: "SafetyWing",
    title: "SafetyWing Nomad Insurance",
    subtitle:
      "Travel and remote work insurance for people moving across borders regularly, with monthly billing and flexible international coverage.",
    metrics: [
      { label: "Trip length", value: "Rolling monthly cover" },
      { label: "Cover", value: "Travel medical and emergencies" },
      { label: "Monthly premium", value: "From EUR 45" },
    ],
    bestFor: ["Remote workers", "Travel cover", "International movement"],
    providerWebsiteUrl: "https://safetywing.com",
    affiliateLink: "https://safetywing.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "travel",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["travel insurance", "nomad", "international cover"],
    },
  },
  {
    id: "investment-trade-republic-core",
    slug: "trade-republic-core-invest",
    category: "investments",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Core Invest",
    subtitle:
      "Low-friction investing with ETF savings plans, stock access, and a clean mobile workflow for long-term retail investors.",
    metrics: [
      { label: "ETF trades", value: "From EUR 1" },
      { label: "Savings plan", value: "From EUR 1" },
      { label: "Markets", value: "9 exchanges" },
    ],
    bestFor: ["Stocks", "ETF plans", "Long-term investing"],
    providerWebsiteUrl: "https://traderepublic.com",
    affiliateLink: "https://traderepublic.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "stocks",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["stocks", "etf", "savings plan", "broker"],
    },
  },
  {
    id: "investment-scalable-prime",
    slug: "scalable-capital-prime-broker",
    category: "investments",
    countryCodes: ["DE", "FR", "ES", "IT", "AT"],
    providerMark: "SC",
    providerName: "Scalable Capital",
    title: "Scalable Capital Prime Broker",
    subtitle:
      "A brokerage and wealth platform combining broad ETF access with recurring investing and portfolio tools.",
    metrics: [
      { label: "ETF trades", value: "From EUR 0.99" },
      { label: "Savings plan", value: "From EUR 1" },
      { label: "Custody fee", value: "EUR 0" },
    ],
    bestFor: ["ETF investors", "Portfolio building", "Recurring plans"],
    providerWebsiteUrl: "https://de.scalable.capital",
    affiliateLink: "https://de.scalable.capital",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["broker platform", "etf", "wealth platform"],
    },
  },
  {
    id: "investment-etoro-multi-asset",
    slug: "etoro-multi-asset-account",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "ET",
    providerName: "eToro",
    title: "eToro Multi-Asset Account",
    subtitle:
      "A single investing account for stocks, ETFs, and crypto with social discovery and strong cross-market availability.",
    metrics: [
      { label: "Access", value: "Stocks, ETFs, crypto" },
      { label: "Custody fee", value: "EUR 0" },
      { label: "Markets", value: "Global listed markets" },
    ],
    bestFor: ["Multi-asset", "Crypto access", "Cross-market investing"],
    providerWebsiteUrl: "https://www.etoro.com",
    affiliateLink: "https://www.etoro.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "platforms",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "international",
      searchTags: ["social investing", "stocks", "crypto", "platform"],
    },
  },
  {
    id: "investment-degiro-global",
    slug: "degiro-global-investor",
    category: "investments",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "PT"],
    providerMark: "DG",
    providerName: "DEGIRO",
    title: "DEGIRO Global Investor",
    subtitle:
      "A brokerage aimed at cost-aware investors who want broad exchange access and stronger market depth across Europe.",
    metrics: [
      { label: "ETF trades", value: "From EUR 1" },
      { label: "Markets", value: "50+ global exchanges" },
      { label: "Custody fee", value: "No custody fee" },
    ],
    bestFor: ["Stocks", "Low-cost trading", "Broad market access"],
    providerWebsiteUrl: "https://www.degiro.com",
    affiliateLink: "https://www.degiro.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-25T00:00:00Z",
    attributes: {
      subtype: "stocks",
      riskProfile: "balanced",
      feeProfile: "low",
      availability: "regional",
      searchTags: ["stocks", "broker", "exchange access"],
    },
  },
  {
    id: "investment-bitpanda-crypto",
    slug: "bitpanda-crypto-portfolio",
    category: "investments",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda Crypto Portfolio",
    subtitle:
      "Crypto-focused investing with recurring buys, multi-asset access, and a simple experience for retail users across Europe.",
    metrics: [
      { label: "Access", value: "Crypto and digital assets" },
      { label: "Crypto fee", value: "Included in quoted spread" },
      { label: "Savings plan", value: "Recurring buys available" },
    ],
    bestFor: ["Crypto", "Recurring buys", "Retail investing"],
    providerWebsiteUrl: "https://www.bitpanda.com",
    affiliateLink: "https://www.bitpanda.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "medium",
      availability: "regional",
      searchTags: ["crypto", "digital assets", "recurring buys"],
    },
  },
  {
    id: "investment-coinbase-simple",
    slug: "coinbase-simple-crypto",
    category: "investments",
    countryCodes: ["EU", "UK"],
    providerMark: "CB",
    providerName: "Coinbase",
    title: "Coinbase Simple Crypto",
    subtitle:
      "A well-known crypto platform for users who want straightforward purchase flows, recurring orders, and strong brand recognition.",
    metrics: [
      { label: "Access", value: "Major crypto assets" },
      { label: "Crypto fee", value: "Varies by transaction" },
      { label: "Savings plan", value: "Recurring buys available" },
    ],
    bestFor: ["Crypto", "Beginner access", "Recurring buys"],
    providerWebsiteUrl: "https://www.coinbase.com",
    affiliateLink: "https://www.coinbase.com",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    updatedAt: "2026-03-24T00:00:00Z",
    attributes: {
      subtype: "crypto",
      riskProfile: "growth",
      feeProfile: "premium",
      availability: "international",
      searchTags: ["crypto", "beginner investing", "digital assets"],
    },
  },
];

export const marketplaceOffers = [...coreOffers, ...expandedOffers];
