import type { MarketplaceOffer } from "@payn/types";

export const featuredOffers: MarketplaceOffer[] = [
  {
    id: "offer-loan-northlake-flex",
    slug: "northlake-flex-loan",
    category: "loans",
    countryCodes: ["DE", "ES", "NL"],
    providerMark: "NL",
    providerName: "NorthLake Finance",
    title: "Flexible personal loan",
    subtitle: "For borrowers who want a broad range, fixed repayments, and a fully digital application flow.",
    metrics: [
      { label: "APR", value: "6.9% - 11.4%" },
      { label: "Amount range", value: "EUR 5k - 45k" },
      { label: "Term", value: "24 - 84 months" },
    ],
    bestFor: ["Debt consolidation", "Large purchases", "Digital application"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://example.com/provider",
    affiliateLink: "https://example.com/affiliate",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "offer-loan-cedar-fixed",
    slug: "cedar-fixed-rate-loan",
    category: "loans",
    countryCodes: ["DE", "AT"],
    providerMark: "CC",
    providerName: "Cedar Credit",
    title: "Fixed-rate consolidation loan",
    subtitle: "Built for borrowers prioritizing predictable monthly payments and faster approval for refinancing.",
    metrics: [
      { label: "APR", value: "5.8% - 10.2%" },
      { label: "Amount range", value: "EUR 3k - 35k" },
      { label: "Term", value: "12 - 72 months" },
    ],
    bestFor: ["Debt consolidation", "Fixed repayments", "Fast decision"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://example.com/provider",
    affiliateLink: "https://example.com/affiliate",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "offer-loan-horizon-everyday",
    slug: "horizon-everyday-loan",
    category: "loans",
    countryCodes: ["ES", "PT", "IT"],
    providerMark: "HB",
    providerName: "Horizon Bank",
    title: "Everyday personal loan",
    subtitle: "Balanced pricing and flexible terms for planned spending, home updates, and other personal projects.",
    metrics: [
      { label: "APR", value: "7.4% - 13.1%" },
      { label: "Amount range", value: "EUR 2.5k - 25k" },
      { label: "Term", value: "12 - 60 months" },
    ],
    bestFor: ["Home improvements", "Large purchases", "Branch support"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    providerWebsiteUrl: "https://example.com/provider",
    affiliateLink: "https://example.com/affiliate",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "offer-loan-solidarity-large",
    slug: "solidarity-large-purchase-loan",
    category: "loans",
    countryCodes: ["NL", "BE", "FR"],
    providerMark: "SL",
    providerName: "Solidarity Lending",
    title: "Large purchase loan",
    subtitle: "Designed for higher borrowing amounts with longer repayment windows and transparent prepayment terms.",
    metrics: [
      { label: "APR", value: "6.4% - 12.6%" },
      { label: "Amount range", value: "EUR 7.5k - 50k" },
      { label: "Term", value: "24 - 96 months" },
    ],
    bestFor: ["Large purchases", "Longer term", "Prepayment flexibility"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.67,
    providerWebsiteUrl: "https://example.com/provider",
    affiliateLink: "https://example.com/affiliate",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "offer-card-smart-travel",
    slug: "smart-travel-card",
    category: "cards",
    countryCodes: ["EU", "UK"],
    providerMark: "AB",
    providerName: "Atlas Bank",
    title: "Travel rewards card",
    subtitle: "Rewards-focused card with fee visibility, travel protections, and mobile-first servicing.",
    metrics: [
      { label: "Representative APR", value: "24.9%" },
      { label: "Credit limit", value: "Up to EUR 12k" },
      { label: "Annual fee", value: "EUR 0 - 120" },
    ],
    bestFor: ["Travel spend", "Points", "Premium support"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.63,
    providerWebsiteUrl: "https://example.com/provider",
    affiliateLink: "https://example.com/affiliate",
    updatedAt: "2026-03-23T00:00:00Z",
  },
];
