import type { MarketplaceOffer } from "@payn/types";

export const featuredOffers: MarketplaceOffer[] = [
  // ═══════════════════════════════════════════════════
  // LOANS (17 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "loan-klarna-flex",
    slug: "klarna-flexible-loan",
    category: "loans",
    countryCodes: ["DE", "SE", "FI", "NO"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Flexible Loan",
    subtitle: "Buy now, pay later pioneer offering flexible personal loans with instant decisions and no hidden fees across Nordic and DACH markets.",
    metrics: [
      { label: "APR", value: "3.9% – 11.9%" },
      { label: "Amount", value: "EUR 500 – 50,000" },
      { label: "Term", value: "6 – 72 months" },
    ],
    bestFor: ["BNPL users", "Instant decision", "Flexible repayment"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/loans",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "loan-n26-personal",
    slug: "n26-personal-loan",
    category: "loans",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Personal Loan",
    subtitle: "Fully digital personal loan from one of Europe's leading neobanks. Apply in minutes, receive funds within 24 hours.",
    metrics: [
      { label: "APR", value: "4.5% – 12.5%" },
      { label: "Amount", value: "EUR 1,000 – 25,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["Digital application", "Fast funding", "No branch needed"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/loans",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "loan-zopa-fixed",
    slug: "zopa-fixed-rate-loan",
    category: "loans",
    countryCodes: ["UK"],
    providerMark: "ZP",
    providerName: "Zopa",
    title: "Zopa Fixed Rate Loan",
    subtitle: "Award-winning UK lender offering competitive fixed rates with no early repayment fees. Excellent for debt consolidation.",
    metrics: [
      { label: "APR", value: "6.9% – 14.9%" },
      { label: "Amount", value: "GBP 1,000 – 35,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["Debt consolidation", "Fixed payments", "No early fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://zopa.com",
    affiliateLink: "https://zopa.com/loans",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "loan-ing-personal",
    slug: "ing-personal-loan",
    category: "loans",
    countryCodes: ["DE", "NL", "BE", "ES"],
    providerMark: "ING",
    providerName: "ING",
    title: "ING Personal Loan",
    subtitle: "Established European bank offering competitive rates with the trust of a tier-1 banking institution. Ideal for larger borrowing amounts.",
    metrics: [
      { label: "APR", value: "4.99% – 9.99%" },
      { label: "Amount", value: "EUR 5,000 – 65,000" },
      { label: "Term", value: "24 – 84 months" },
    ],
    bestFor: ["Large amounts", "Bank-grade trust", "Long term"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://ing.com",
    affiliateLink: "https://ing.com/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-santander-consumer",
    slug: "santander-consumer-loan",
    category: "loans",
    countryCodes: ["DE", "ES", "UK", "PT"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander Consumer Loan",
    subtitle: "Major European bank with branch and digital access. Competitive rates for existing customers and strong multi-market presence.",
    metrics: [
      { label: "APR", value: "5.4% – 11.2%" },
      { label: "Amount", value: "EUR 3,000 – 50,000" },
      { label: "Term", value: "12 – 72 months" },
    ],
    bestFor: ["Existing customers", "Branch support", "Multi-country"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://santander.com",
    affiliateLink: "https://santander.com/loans",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "loan-bunq-green",
    slug: "bunq-green-loan",
    category: "loans",
    countryCodes: ["NL", "DE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Green Loan",
    subtitle: "Sustainability-focused neobank offering personal loans where a portion supports environmental initiatives. Fully mobile experience.",
    metrics: [
      { label: "APR", value: "5.9% – 13.5%" },
      { label: "Amount", value: "EUR 1,000 – 30,000" },
      { label: "Term", value: "12 – 48 months" },
    ],
    bestFor: ["Eco-conscious", "Mobile-first", "Quick approval"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-bbva-online",
    slug: "bbva-online-loan",
    category: "loans",
    countryCodes: ["ES", "PT"],
    providerMark: "BBVA",
    providerName: "BBVA",
    title: "BBVA Online Personal Loan",
    subtitle: "Spain's digital banking leader with competitive rates for Iberian markets. Strong online application flow with real-time approval.",
    metrics: [
      { label: "APR", value: "5.1% – 10.8%" },
      { label: "Amount", value: "EUR 3,000 – 60,000" },
      { label: "Term", value: "12 – 96 months" },
    ],
    bestFor: ["Spain residents", "Large purchases", "Digital banking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://bbva.es",
    affiliateLink: "https://bbva.es/loans",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "loan-bnp-classic",
    slug: "bnp-paribas-classic-loan",
    category: "loans",
    countryCodes: ["FR", "BE", "LU"],
    providerMark: "BNP",
    providerName: "BNP Paribas",
    title: "BNP Paribas Personal Loan",
    subtitle: "France's largest bank offering premium loan products with comprehensive insurance options and dedicated advisor support.",
    metrics: [
      { label: "APR", value: "3.9% – 8.9%" },
      { label: "Amount", value: "EUR 5,000 – 75,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["French residents", "High amounts", "Advisor support"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://bnpparibas.fr",
    affiliateLink: "https://bnpparibas.fr/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-db-direct",
    slug: "deutsche-bank-direct-loan",
    category: "loans",
    countryCodes: ["DE", "AT"],
    providerMark: "DB",
    providerName: "Deutsche Bank",
    title: "Deutsche Bank Direct Loan",
    subtitle: "Germany's premier bank offering competitive fixed-rate loans with straightforward online application and branch consultation options.",
    metrics: [
      { label: "APR", value: "4.2% – 9.5%" },
      { label: "Amount", value: "EUR 5,000 – 80,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["German residents", "High amounts", "Bank trust"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://deutsche-bank.de",
    affiliateLink: "https://deutsche-bank.de/loans",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "loan-revolut-flex",
    slug: "revolut-flexible-loan",
    category: "loans",
    countryCodes: ["UK", "IE", "LT"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Flexible Loan",
    subtitle: "Fintech giant offering quick personal loans via app with instant approval for eligible customers. Seamless repayment from Revolut account.",
    metrics: [
      { label: "APR", value: "5.9% – 15.9%" },
      { label: "Amount", value: "GBP 1,000 – 20,000" },
      { label: "Term", value: "6 – 60 months" },
    ],
    bestFor: ["App-based", "Instant decision", "Existing users"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/loans",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "loan-monese-quick",
    slug: "monese-quick-loan",
    category: "loans",
    countryCodes: ["UK", "DE", "FR", "IT"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Quick Loan",
    subtitle: "Designed for mobile banking users needing fast access to credit. Simple application for newcomers and expats in Europe.",
    metrics: [
      { label: "APR", value: "8.9% – 19.9%" },
      { label: "Amount", value: "EUR 500 – 10,000" },
      { label: "Term", value: "6 – 36 months" },
    ],
    bestFor: ["Expats", "Newcomers", "Small amounts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.68,
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/loans",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "loan-barclays-personal",
    slug: "barclays-personal-loan",
    category: "loans",
    countryCodes: ["UK"],
    providerMark: "BC",
    providerName: "Barclays",
    title: "Barclays Personal Loan",
    subtitle: "One of the UK's most trusted banks. Competitive rates for existing account holders with flexible repayment and overpayment options.",
    metrics: [
      { label: "APR", value: "6.1% – 13.9%" },
      { label: "Amount", value: "GBP 1,000 – 50,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["UK residents", "Existing customers", "Large amounts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://barclays.co.uk",
    affiliateLink: "https://barclays.co.uk/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-abn-amro-personal",
    slug: "abn-amro-personal-loan",
    category: "loans",
    countryCodes: ["NL", "BE"],
    providerMark: "ABN",
    providerName: "ABN AMRO",
    title: "ABN AMRO Personal Loan",
    subtitle: "Leading Dutch bank with excellent rates for home improvements and large purchases. Trusted institution with strong digital tools.",
    metrics: [
      { label: "APR", value: "4.5% – 8.9%" },
      { label: "Amount", value: "EUR 5,000 – 75,000" },
      { label: "Term", value: "24 – 120 months" },
    ],
    bestFor: ["Dutch residents", "Home improvements", "Low rates"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://abnamro.nl",
    affiliateLink: "https://abnamro.nl/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-unicredit-personal",
    slug: "unicredit-personal-loan",
    category: "loans",
    countryCodes: ["IT", "DE", "AT"],
    providerMark: "UC",
    providerName: "UniCredit",
    title: "UniCredit Personal Loan",
    subtitle: "Italy's largest bank offering flexible loan products across Central and Southern Europe with competitive rates and multi-language support.",
    metrics: [
      { label: "APR", value: "5.2% – 11.5%" },
      { label: "Amount", value: "EUR 3,000 – 50,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["Italian residents", "Multi-language", "Flexible terms"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://unicredit.it",
    affiliateLink: "https://unicredit.it/loans",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "loan-wise-personal",
    slug: "wise-personal-credit",
    category: "loans",
    countryCodes: ["UK"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Personal Credit",
    subtitle: "The international money platform now offering personal credit lines for UK customers. Transparent fees, no surprises.",
    metrics: [
      { label: "APR", value: "7.9% – 16.9%" },
      { label: "Amount", value: "GBP 1,000 – 15,000" },
      { label: "Term", value: "12 – 48 months" },
    ],
    bestFor: ["Transparent fees", "International users", "Digital-first"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/credit",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "loan-rabobank-personal",
    slug: "rabobank-personal-loan",
    category: "loans",
    countryCodes: ["NL"],
    providerMark: "RB",
    providerName: "Rabobank",
    title: "Rabobank Personal Loan",
    subtitle: "Cooperative Dutch bank with some of the lowest rates in the Netherlands. Strong customer service and sustainable banking focus.",
    metrics: [
      { label: "APR", value: "3.5% – 7.9%" },
      { label: "Amount", value: "EUR 2,500 – 50,000" },
      { label: "Term", value: "12 – 120 months" },
    ],
    bestFor: ["Lowest rates", "Dutch market", "Sustainable banking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://rabobank.nl",
    affiliateLink: "https://rabobank.nl/loans",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "loan-curve-credit",
    slug: "curve-credit-line",
    category: "loans",
    countryCodes: ["UK"],
    providerMark: "CV",
    providerName: "Curve",
    title: "Curve Credit Line",
    subtitle: "Short-term revolving credit linked to your Curve card. Ideal for managing cash flow across multiple payment cards.",
    metrics: [
      { label: "APR", value: "12.9% – 21.9%" },
      { label: "Amount", value: "GBP 500 – 5,000" },
      { label: "Term", value: "Revolving" },
    ],
    bestFor: ["Cash flow", "Card consolidation", "Revolving credit"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.65,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/credit",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ═══════════════════════════════════════════════════
  // CREDIT CARDS (17 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "card-revolut-metal",
    slug: "revolut-metal-card",
    category: "cards",
    countryCodes: ["UK", "EU"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Metal Card",
    subtitle: "Premium metal card with cashback on all spending, lounge access, and no FX fees on any currency. The fintech flagship card.",
    metrics: [
      { label: "Cashback", value: "Up to 1%" },
      { label: "FX Fee", value: "0%" },
      { label: "Monthly fee", value: "EUR 13.99" },
    ],
    bestFor: ["Travel", "Cashback", "No FX fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/metal",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "card-n26-you",
    slug: "n26-you-card",
    category: "cards",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 You Card",
    subtitle: "Premium debit card with travel insurance, free ATM withdrawals worldwide, and no FX markup. Available in custom colors.",
    metrics: [
      { label: "FX Fee", value: "0%" },
      { label: "ATM", value: "Free worldwide" },
      { label: "Monthly fee", value: "EUR 9.90" },
    ],
    bestFor: ["Travel insurance", "Free ATM", "Custom design"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/you",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "card-wise-debit",
    slug: "wise-debit-card",
    category: "cards",
    countryCodes: ["UK", "EU"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Multi-Currency Card",
    subtitle: "Hold and spend in 40+ currencies at the real exchange rate. No annual fee, transparent conversion at the mid-market rate.",
    metrics: [
      { label: "FX Fee", value: "0.35% – 1%" },
      { label: "Currencies", value: "40+" },
      { label: "Annual fee", value: "EUR 0" },
    ],
    bestFor: ["Multi-currency", "Mid-market rate", "No annual fee"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/card",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "card-bunq-travel",
    slug: "bunq-travel-card",
    category: "cards",
    countryCodes: ["NL", "DE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Travel Card",
    subtitle: "Green bank card with zero FX fees, instant notifications, and the option to plant trees with every purchase you make.",
    metrics: [
      { label: "FX Fee", value: "0%" },
      { label: "Trees planted", value: "Per EUR 100" },
      { label: "Monthly fee", value: "EUR 8.99" },
    ],
    bestFor: ["Eco-friendly", "Zero FX", "Instant alerts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/travel",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "card-curve-all-in-one",
    slug: "curve-all-in-one-card",
    category: "cards",
    countryCodes: ["UK", "EU"],
    providerMark: "CV",
    providerName: "Curve",
    title: "Curve All-In-One Card",
    subtitle: "Consolidate all your cards into one. Swap transactions between cards after purchase with Go Back in Time feature.",
    metrics: [
      { label: "Cards linked", value: "Unlimited" },
      { label: "Cashback", value: "Up to 1%" },
      { label: "Monthly fee", value: "Free / EUR 9.99" },
    ],
    bestFor: ["Card consolidation", "Go Back in Time", "Cashback"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/card",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "card-klarna-spending",
    slug: "klarna-spending-card",
    category: "cards",
    countryCodes: ["DE", "SE", "UK"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Card",
    subtitle: "Interest-free card for online and in-store purchases. Split payments automatically into 3 installments with no extra cost.",
    metrics: [
      { label: "Interest", value: "0% (Pay in 3)" },
      { label: "Credit limit", value: "Up to EUR 5,000" },
      { label: "Annual fee", value: "EUR 0" },
    ],
    bestFor: ["BNPL", "Interest-free", "Online shopping"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/card",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "card-monese-premium",
    slug: "monese-premium-card",
    category: "cards",
    countryCodes: ["UK", "DE", "FR", "IT"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Premium Card",
    subtitle: "Designed for people moving to a new country. No credit check, instant account, free international transfers up to a limit.",
    metrics: [
      { label: "FX Fee", value: "0% (up to limit)" },
      { label: "Setup", value: "No credit check" },
      { label: "Monthly fee", value: "EUR 7.95" },
    ],
    bestFor: ["Expats", "No credit check", "Quick setup"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.72,
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/premium",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "card-barclaycard-rewards",
    slug: "barclaycard-rewards-visa",
    category: "cards",
    countryCodes: ["UK"],
    providerMark: "BC",
    providerName: "Barclaycard",
    title: "Barclaycard Rewards Visa",
    subtitle: "Earn cashback on every purchase with one of the UK's most established credit card issuers. No annual fee, contactless enabled.",
    metrics: [
      { label: "Cashback", value: "0.25% uncapped" },
      { label: "APR", value: "24.9% representative" },
      { label: "Annual fee", value: "GBP 0" },
    ],
    bestFor: ["UK cashback", "No annual fee", "Established issuer"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://barclaycard.co.uk",
    affiliateLink: "https://barclaycard.co.uk/rewards",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "card-revolut-standard",
    slug: "revolut-standard-card",
    category: "cards",
    countryCodes: ["UK", "EU"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Standard Card",
    subtitle: "Free card with smart budgeting, instant spending notifications, and fee-free spending up to a monthly FX limit.",
    metrics: [
      { label: "FX Fee", value: "0% (up to limit)" },
      { label: "ATM", value: "EUR 200/mo free" },
      { label: "Monthly fee", value: "EUR 0" },
    ],
    bestFor: ["Free card", "Budgeting", "Starter fintech"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/standard",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "card-n26-metal",
    slug: "n26-metal-card",
    category: "cards",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Metal Card",
    subtitle: "Premium stainless steel card with comprehensive travel and purchase insurance, priority support, and exclusive partner offers.",
    metrics: [
      { label: "Cashback", value: "0.5% selected" },
      { label: "Insurance", value: "Comprehensive" },
      { label: "Monthly fee", value: "EUR 16.90" },
    ],
    bestFor: ["Premium metal", "Full insurance", "Priority support"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/metal",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "card-santander-123",
    slug: "santander-123-credit",
    category: "cards",
    countryCodes: ["UK", "ES"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander 1|2|3 Credit Card",
    subtitle: "Earn cashback on fuel, commuting, and supermarket spending. 0% purchase offer for the first 20 months.",
    metrics: [
      { label: "Cashback", value: "Up to 3%" },
      { label: "0% period", value: "20 months" },
      { label: "Annual fee", value: "GBP 36" },
    ],
    bestFor: ["Supermarket cashback", "0% purchases", "Fuel rewards"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.75,
    providerWebsiteUrl: "https://santander.co.uk",
    affiliateLink: "https://santander.co.uk/123",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "card-wise-business",
    slug: "wise-business-card",
    category: "cards",
    countryCodes: ["UK", "EU"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Business Card",
    subtitle: "For freelancers and small businesses. Spend in any currency at the real exchange rate with easy expense management.",
    metrics: [
      { label: "FX Fee", value: "0.35% – 1%" },
      { label: "Currencies", value: "40+" },
      { label: "Monthly fee", value: "EUR 0" },
    ],
    bestFor: ["Freelancers", "Business expenses", "Multi-currency"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/business-card",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "card-ing-credit",
    slug: "ing-credit-card",
    category: "cards",
    countryCodes: ["NL", "DE", "BE"],
    providerMark: "ING",
    providerName: "ING",
    title: "ING Credit Card",
    subtitle: "Straightforward credit card from a major European bank with worldwide acceptance and integrated mobile banking.",
    metrics: [
      { label: "FX Fee", value: "1.5%" },
      { label: "Credit limit", value: "Up to EUR 10,000" },
      { label: "Annual fee", value: "EUR 25" },
    ],
    bestFor: ["Bank reliability", "High limit", "Worldwide use"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    providerWebsiteUrl: "https://ing.com",
    affiliateLink: "https://ing.com/cards",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "card-bunq-easy-green",
    slug: "bunq-easy-green-card",
    category: "cards",
    countryCodes: ["NL", "DE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Easy Green Card",
    subtitle: "Plant a tree with every EUR 100 spent. Zero FX fees, sub-accounts, and an app designed for conscious spending.",
    metrics: [
      { label: "FX Fee", value: "0%" },
      { label: "Sub-accounts", value: "25" },
      { label: "Monthly fee", value: "EUR 17.99" },
    ],
    bestFor: ["Green banking", "Sub-accounts", "Premium eco"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.74,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/easy-green",
    updatedAt: "2026-03-22T00:00:00Z",
  },

  // ═══════════════════════════════════════════════════
  // TRANSFERS (16 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "transfer-wise-intl",
    slug: "wise-international-transfer",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise International Transfer",
    subtitle: "The gold standard for international money transfers. Real mid-market exchange rate with transparent, low fees shown upfront.",
    metrics: [
      { label: "Fee", value: "From 0.41%" },
      { label: "Speed", value: "Minutes – 2 days" },
      { label: "Corridors", value: "80+ countries" },
    ],
    bestFor: ["Best rates", "Transparent fees", "Fast delivery"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.96,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/send",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "transfer-revolut-send",
    slug: "revolut-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Money Transfer",
    subtitle: "Send money to 150+ countries with competitive rates. Free transfers between Revolut users, instant delivery available.",
    metrics: [
      { label: "Fee", value: "Free – 1.5%" },
      { label: "Speed", value: "Instant – 3 days" },
      { label: "Corridors", value: "150+ countries" },
    ],
    bestFor: ["Free P2P", "Wide coverage", "App-based"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/transfer",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "transfer-n26-moneybeam",
    slug: "n26-moneybeam-transfer",
    category: "transfers",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 MoneyBeam",
    subtitle: "Instant transfers to other N26 users and SEPA transfers across Europe. Integrated directly into your N26 banking app.",
    metrics: [
      { label: "Fee", value: "EUR 0 (SEPA)" },
      { label: "Speed", value: "Instant (N26)" },
      { label: "Corridors", value: "SEPA zone" },
    ],
    bestFor: ["SEPA transfers", "Instant P2P", "No fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/moneybeam",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "transfer-worldremit-global",
    slug: "worldremit-global-transfer",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "WR",
    providerName: "WorldRemit",
    title: "WorldRemit Global Transfer",
    subtitle: "Specialized in remittances to developing countries. Mobile money, cash pickup, and bank transfer options in 130+ countries.",
    metrics: [
      { label: "Fee", value: "From EUR 1.49" },
      { label: "Speed", value: "Minutes – 3 days" },
      { label: "Corridors", value: "130+ countries" },
    ],
    bestFor: ["Remittances", "Mobile money", "Cash pickup"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://worldremit.com",
    affiliateLink: "https://worldremit.com/send",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "transfer-bunq-intl",
    slug: "bunq-international-transfer",
    category: "transfers",
    countryCodes: ["NL", "DE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq International Transfer",
    subtitle: "Send money worldwide through the bunq app powered by Wise integration. Transparent rates with eco-friendly banking.",
    metrics: [
      { label: "Fee", value: "From 0.5%" },
      { label: "Speed", value: "1 – 2 days" },
      { label: "Corridors", value: "40+ countries" },
    ],
    bestFor: ["Wise-powered", "Green banking", "EU residents"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.75,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/transfers",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "transfer-monese-send",
    slug: "monese-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "IT"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Money Transfer",
    subtitle: "Send money to 30+ countries from your Monese account. Competitive rates for expats sending money home.",
    metrics: [
      { label: "Fee", value: "From EUR 1.50" },
      { label: "Speed", value: "1 – 3 days" },
      { label: "Corridors", value: "30+ countries" },
    ],
    bestFor: ["Expat remittances", "Simple app", "No credit check"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.67,
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/transfers",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "transfer-currencyfair-fx",
    slug: "currencyfair-transfer",
    category: "transfers",
    countryCodes: ["IE", "UK", "EU"],
    providerMark: "CF",
    providerName: "CurrencyFair",
    title: "CurrencyFair Peer Exchange",
    subtitle: "Peer-to-peer currency exchange marketplace with rates up to 8x cheaper than banks. Set your own exchange rate.",
    metrics: [
      { label: "Fee", value: "From EUR 2.50" },
      { label: "Speed", value: "1 – 2 days" },
      { label: "Corridors", value: "20+ currencies" },
    ],
    bestFor: ["P2P exchange", "Set own rate", "Large amounts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.73,
    providerWebsiteUrl: "https://currencyfair.com",
    affiliateLink: "https://currencyfair.com/send",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "transfer-xe-global",
    slug: "xe-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "XE",
    providerName: "XE",
    title: "XE Money Transfer",
    subtitle: "From the world's most trusted currency data provider. Competitive rates, no transfer fees on amounts over EUR 1,000.",
    metrics: [
      { label: "Fee", value: "EUR 0 (>1k)" },
      { label: "Speed", value: "1 – 4 days" },
      { label: "Corridors", value: "130+ currencies" },
    ],
    bestFor: ["No fee (large)", "Trusted brand", "Rate alerts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://xe.com",
    affiliateLink: "https://xe.com/send",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "transfer-remitly-express",
    slug: "remitly-express-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR"],
    providerMark: "RM",
    providerName: "Remitly",
    title: "Remitly Express Transfer",
    subtitle: "Fast, reliable remittance service with express delivery option. Popular for sending money to Asia, Africa, and Latin America.",
    metrics: [
      { label: "Fee", value: "From EUR 0.99" },
      { label: "Speed", value: "Minutes (Express)" },
      { label: "Corridors", value: "100+ countries" },
    ],
    bestFor: ["Express delivery", "Remittances", "Low minimum"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://remitly.com",
    affiliateLink: "https://remitly.com/send",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "transfer-payoneer-biz",
    slug: "payoneer-business-transfer",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "PY",
    providerName: "Payoneer",
    title: "Payoneer Business Payments",
    subtitle: "Built for freelancers and businesses receiving international payments. Multi-currency receiving accounts in USD, EUR, GBP.",
    metrics: [
      { label: "Fee", value: "Up to 2%" },
      { label: "Speed", value: "1 – 3 days" },
      { label: "Corridors", value: "190+ countries" },
    ],
    bestFor: ["Freelancers", "Business payments", "Multi-currency receive"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.74,
    providerWebsiteUrl: "https://payoneer.com",
    affiliateLink: "https://payoneer.com/send",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "transfer-western-union-instant",
    slug: "western-union-instant",
    category: "transfers",
    countryCodes: ["UK", "EU"],
    providerMark: "WU",
    providerName: "Western Union",
    title: "Western Union Instant Transfer",
    subtitle: "The world's largest money transfer network. Cash pickup available in 200+ countries with instant delivery options.",
    metrics: [
      { label: "Fee", value: "From EUR 1.90" },
      { label: "Speed", value: "Minutes" },
      { label: "Corridors", value: "200+ countries" },
    ],
    bestFor: ["Cash pickup", "Widest network", "Instant"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.70,
    providerWebsiteUrl: "https://westernunion.com",
    affiliateLink: "https://westernunion.com/send",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "transfer-santander-intl",
    slug: "santander-international-transfer",
    category: "transfers",
    countryCodes: ["ES", "UK", "PT"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander International Transfer",
    subtitle: "Free transfers between Santander accounts across countries. Competitive rates for Iberian corridor with branch support.",
    metrics: [
      { label: "Fee", value: "Free (Santander)" },
      { label: "Speed", value: "Same day – 2 days" },
      { label: "Corridors", value: "Santander network" },
    ],
    bestFor: ["Santander customers", "Spain-UK corridor", "Free internal"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.69,
    providerWebsiteUrl: "https://santander.com",
    affiliateLink: "https://santander.com/transfers",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "transfer-ing-intl",
    slug: "ing-international-transfer",
    category: "transfers",
    countryCodes: ["NL", "DE", "BE", "ES"],
    providerMark: "ING",
    providerName: "ING",
    title: "ING International Transfer",
    subtitle: "Bank-grade international transfers with SWIFT network reliability. Ideal for customers who prefer traditional banking security.",
    metrics: [
      { label: "Fee", value: "EUR 7 – 25" },
      { label: "Speed", value: "2 – 5 days" },
      { label: "Corridors", value: "SWIFT network" },
    ],
    bestFor: ["Bank security", "SWIFT reliability", "Large sums"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.65,
    providerWebsiteUrl: "https://ing.com",
    affiliateLink: "https://ing.com/transfers",
    updatedAt: "2026-03-20T00:00:00Z",
  },

  // ═══════════════════════════════════════════════════
  // EXCHANGE (16 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "exchange-wise-multi",
    slug: "wise-multi-currency-account",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Multi-Currency Account",
    subtitle: "Hold and convert between 40+ currencies at the real mid-market rate. Set rate alerts and auto-convert when rates hit your target.",
    metrics: [
      { label: "Spread", value: "0% (mid-market)" },
      { label: "Conversion fee", value: "0.35% – 1%" },
      { label: "Currencies", value: "40+" },
    ],
    bestFor: ["Mid-market rate", "Rate alerts", "Multi-currency hold"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/multi",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "exchange-revolut-fx",
    slug: "revolut-currency-exchange",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Currency Exchange",
    subtitle: "Exchange 30+ currencies in-app with competitive rates. Free exchanges up to a monthly limit, weekend markup applies.",
    metrics: [
      { label: "Spread", value: "0% (weekday)" },
      { label: "Free limit", value: "EUR 1,000/mo" },
      { label: "Currencies", value: "30+" },
    ],
    bestFor: ["Free exchanges", "Instant conversion", "App-based"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/exchange",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "exchange-n26-fx",
    slug: "n26-currency-exchange",
    category: "exchange",
    countryCodes: ["DE", "ES", "FR", "IT", "AT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Currency Exchange",
    subtitle: "In-app currency exchange for N26 customers powered by Wise. Competitive rates with transparent fee breakdown.",
    metrics: [
      { label: "Spread", value: "Wise-powered" },
      { label: "Conversion fee", value: "From 0.5%" },
      { label: "Currencies", value: "30+" },
    ],
    bestFor: ["Wise rates in-app", "N26 integration", "No extra accounts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/exchange",
    updatedAt: "2026-03-23T00:00:00Z",
  },
  {
    id: "exchange-bunq-fx",
    slug: "bunq-currency-exchange",
    category: "exchange",
    countryCodes: ["NL", "DE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Currency Exchange",
    subtitle: "Exchange currencies in the bunq app with zero FX markup for Easy Green plan users. Auto-conversion for incoming payments.",
    metrics: [
      { label: "Spread", value: "0% (Easy Green)" },
      { label: "Conversion fee", value: "Included" },
      { label: "Currencies", value: "25+" },
    ],
    bestFor: ["Zero markup", "Green subscribers", "Auto-convert"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/exchange",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "exchange-currencyfair-market",
    slug: "currencyfair-exchange-market",
    category: "exchange",
    countryCodes: ["IE", "UK", "EU"],
    providerMark: "CF",
    providerName: "CurrencyFair",
    title: "CurrencyFair Exchange Market",
    subtitle: "Set your own exchange rate and match with other users. Peer-to-peer model delivers rates up to 8x cheaper than banks.",
    metrics: [
      { label: "Spread", value: "From 0.04%" },
      { label: "Fee", value: "EUR 2.50" },
      { label: "Currencies", value: "20+" },
    ],
    bestFor: ["Set own rate", "P2P exchange", "Lowest spreads"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://currencyfair.com",
    affiliateLink: "https://currencyfair.com/exchange",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "exchange-interactive-brokers",
    slug: "interactive-brokers-fx",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "IB",
    providerName: "Interactive Brokers",
    title: "IBKR Forex Exchange",
    subtitle: "Institutional-grade FX rates accessible to retail clients. Extremely tight spreads for large volume currency conversion.",
    metrics: [
      { label: "Spread", value: "From 0.01 pip" },
      { label: "Commission", value: "USD 2/trade" },
      { label: "Currencies", value: "100+" },
    ],
    bestFor: ["Tightest spreads", "Large volumes", "Pro traders"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://interactivebrokers.com",
    affiliateLink: "https://interactivebrokers.com/fx",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "exchange-xe-rate-alerts",
    slug: "xe-rate-alerts",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "XE",
    providerName: "XE",
    title: "XE Rate Alerts & Exchange",
    subtitle: "The world's most referenced currency data. Set rate alerts for any pair and lock in rates when they hit your target.",
    metrics: [
      { label: "Spread", value: "0.5% – 1.5%" },
      { label: "Rate alerts", value: "Unlimited" },
      { label: "Currencies", value: "130+" },
    ],
    bestFor: ["Rate monitoring", "Trusted data", "Alert system"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://xe.com",
    affiliateLink: "https://xe.com/exchange",
    updatedAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "exchange-revolut-business-fx",
    slug: "revolut-business-fx",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Business FX",
    subtitle: "Business-grade currency exchange with bulk payment support and API access. Competitive rates for high-volume conversion.",
    metrics: [
      { label: "Spread", value: "From 0.2%" },
      { label: "API access", value: "Yes" },
      { label: "Currencies", value: "28+" },
    ],
    bestFor: ["Business FX", "API integration", "Bulk payments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://revolut.com/business",
    affiliateLink: "https://revolut.com/business/fx",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "exchange-klarna-fx",
    slug: "klarna-currency-exchange",
    category: "exchange",
    countryCodes: ["SE", "DE", "UK"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Currency Conversion",
    subtitle: "Transparent currency conversion when shopping internationally with Klarna. Know the exact cost before you buy.",
    metrics: [
      { label: "Spread", value: "1.5% – 2.5%" },
      { label: "Context", value: "Shopping only" },
      { label: "Currencies", value: "15+" },
    ],
    bestFor: ["Shopping abroad", "Transparent pricing", "BNPL users"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.64,
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/fx",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "exchange-monese-fx",
    slug: "monese-currency-exchange",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "IT"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Currency Exchange",
    subtitle: "In-app currency exchange for Monese users with clear rate display. Good rates for EUR, GBP, and RON conversions.",
    metrics: [
      { label: "Spread", value: "0.5% – 2%" },
      { label: "Fee", value: "Included" },
      { label: "Currencies", value: "EUR, GBP, RON" },
    ],
    bestFor: ["Expats", "Simple exchange", "EUR/GBP/RON"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.62,
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/exchange",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "exchange-bnp-fx",
    slug: "bnp-paribas-fx-services",
    category: "exchange",
    countryCodes: ["FR", "BE", "LU"],
    providerMark: "BNP",
    providerName: "BNP Paribas",
    title: "BNP Paribas FX Services",
    subtitle: "Institutional-quality FX from France's largest bank. Forward contracts and hedging for business clients, competitive spot rates.",
    metrics: [
      { label: "Spread", value: "0.3% – 1%" },
      { label: "Forwards", value: "Available" },
      { label: "Currencies", value: "50+" },
    ],
    bestFor: ["Hedging", "Business FX", "French market"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.72,
    providerWebsiteUrl: "https://bnpparibas.fr",
    affiliateLink: "https://bnpparibas.fr/fx",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "exchange-curve-smart-fx",
    slug: "curve-smart-fx",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "CV",
    providerName: "Curve",
    title: "Curve Smart FX",
    subtitle: "Automatically select the best card for each currency when spending abroad. Smart rules engine picks optimal rates per transaction.",
    metrics: [
      { label: "Spread", value: "0% (weekday)" },
      { label: "Smart rules", value: "Per currency" },
      { label: "Limit", value: "GBP 500/mo free" },
    ],
    bestFor: ["Smart routing", "Travel spending", "Card optimization"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/fx",
    updatedAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "exchange-wise-business-fx",
    slug: "wise-business-multi-currency",
    category: "exchange",
    countryCodes: ["UK", "EU"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Business Multi-Currency",
    subtitle: "Hold balances in 40+ currencies with local account details. Convert at mid-market rate with batch payment support.",
    metrics: [
      { label: "Spread", value: "0% (mid-market)" },
      { label: "Batch payments", value: "Up to 1,000" },
      { label: "Currencies", value: "40+" },
    ],
    bestFor: ["Business treasury", "Batch convert", "Local accounts"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://wise.com/business",
    affiliateLink: "https://wise.com/business/multi",
    updatedAt: "2026-03-24T00:00:00Z",
  },
  {
    id: "exchange-santander-fx",
    slug: "santander-fx-exchange",
    category: "exchange",
    countryCodes: ["ES", "UK", "PT"],
    providerMark: "SAN",
    providerName: "Santander",
    title: "Santander Currency Exchange",
    subtitle: "Exchange currencies at competitive bank rates with the security of a major institution. Preferential rates for premier customers.",
    metrics: [
      { label: "Spread", value: "0.5% – 2%" },
      { label: "Premier rate", value: "Discounted" },
      { label: "Currencies", value: "30+" },
    ],
    bestFor: ["Bank security", "Premier customers", "Spain-based"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.66,
    providerWebsiteUrl: "https://santander.com",
    affiliateLink: "https://santander.com/fx",
    updatedAt: "2026-03-20T00:00:00Z",
  },
];
