import type { MarketplaceOffer } from "@payn/types";

export const featuredOffers: MarketplaceOffer[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // LOANS (20 offers)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "offer-loans-klarna",
    slug: "klarna-personal-loan",
    category: "loans",
    countryCodes: ["DE", "SE", "AT", "FI"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Personal Loan",
    subtitle: "Flexible personal financing from one of Europe's most trusted fintech brands",
    metrics: [
      { label: "APR from", value: "3.9%" },
      { label: "Amount", value: "€1,000 – €50,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["Debt consolidation", "Digital application", "Flexible terms"],
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/loans/apply?ref=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-loans-n26",
    slug: "n26-credit-line",
    category: "loans",
    countryCodes: ["DE", "AT", "ES", "FR", "IT"],
    providerMark: "N2",
    providerName: "N26",
    title: "N26 Credit",
    subtitle: "Get pre-approved credit directly in your N26 app with instant disbursement",
    metrics: [
      { label: "APR from", value: "4.5%" },
      { label: "Amount", value: "€1,000 – €25,000" },
      { label: "Term", value: "6 – 60 months" },
    ],
    bestFor: ["Fast approval", "Digital application", "No early repayment fee"],
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/credit?partner=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-loans-zopa",
    slug: "zopa-smart-loan",
    category: "loans",
    countryCodes: ["UK"],
    providerMark: "ZO",
    providerName: "Zopa",
    title: "Zopa Smart Loan",
    subtitle: "Award-winning peer-to-peer lender now offering competitive fixed-rate personal loans",
    metrics: [
      { label: "APR from", value: "5.9%" },
      { label: "Amount", value: "£1,000 – £35,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["Debt consolidation", "Home renovation", "Low rates"],
    providerWebsiteUrl: "https://zopa.com",
    affiliateLink: "https://zopa.com/loans/apply?utm_source=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-loans-revolut",
    slug: "revolut-personal-loan",
    category: "loans",
    countryCodes: ["IE", "DE", "FR", "ES", "PT"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Personal Loan",
    subtitle: "Borrow up to €30,000 directly from the Revolut app with no hidden fees",
    metrics: [
      { label: "APR from", value: "5.5%" },
      { label: "Amount", value: "€1,000 – €30,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["Digital application", "Fast approval", "Flexible terms"],
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral/payn-loans",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-loans-bunq",
    slug: "bunq-personal-loan",
    category: "loans",
    countryCodes: ["NL", "DE", "AT", "BE", "IE"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Personal Loan",
    subtitle: "Green banking meets personal lending — plant trees while you repay your loan",
    metrics: [
      { label: "APR from", value: "6.2%" },
      { label: "Amount", value: "€2,500 – €25,000" },
      { label: "Term", value: "12 – 48 months" },
    ],
    bestFor: ["Digital application", "No early repayment fee", "Flexible terms"],
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/link/payn-loan",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.72,
    updatedAt: "2026-03-19",
  },
  {
    id: "offer-loans-monese",
    slug: "monese-micro-loan",
    category: "loans",
    countryCodes: ["UK", "FR", "DE", "IT", "ES"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Advance",
    subtitle: "Quick micro-loans for everyday needs with transparent pricing and no paperwork",
    metrics: [
      { label: "APR from", value: "9.9%" },
      { label: "Amount", value: "€500 – €5,000" },
      { label: "Term", value: "6 – 24 months" },
    ],
    bestFor: ["Fast approval", "Medical expenses", "Digital application"],
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.62,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-loans-auxmoney",
    slug: "auxmoney-p2p-loan",
    category: "loans",
    countryCodes: ["DE"],
    providerMark: "AX",
    providerName: "auxmoney",
    title: "auxmoney P2P Kredit",
    subtitle: "Germany's leading peer-to-peer lending platform — even with less-than-perfect credit",
    metrics: [
      { label: "APR from", value: "3.5%" },
      { label: "Amount", value: "€1,000 – €50,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["Debt consolidation", "Car financing", "Low rates"],
    providerWebsiteUrl: "https://auxmoney.com",
    affiliateLink: "https://auxmoney.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.85,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-loans-younited-credit",
    slug: "younited-credit-personal",
    category: "loans",
    countryCodes: ["FR", "IT", "ES", "PT"],
    providerMark: "YC",
    providerName: "Younited Credit",
    title: "Younited Credit Personal Loan",
    subtitle: "100% online credit platform regulated as a bank with instant decisions",
    metrics: [
      { label: "APR from", value: "4.2%" },
      { label: "Amount", value: "€1,000 – €50,000" },
      { label: "Term", value: "6 – 84 months" },
    ],
    bestFor: ["Home renovation", "Wedding", "Digital application"],
    providerWebsiteUrl: "https://younited-credit.com",
    affiliateLink: "https://younited-credit.com/aff/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-loans-lendico",
    slug: "lendico-smart-kredit",
    category: "loans",
    countryCodes: ["DE", "AT"],
    providerMark: "LE",
    providerName: "Lendico",
    title: "Lendico Smart Kredit",
    subtitle: "ING-backed digital lender offering some of Germany's most competitive personal loan rates",
    metrics: [
      { label: "APR from", value: "3.9%" },
      { label: "Amount", value: "€2,500 – €50,000" },
      { label: "Term", value: "24 – 96 months" },
    ],
    bestFor: ["Low rates", "Debt consolidation", "Car financing"],
    providerWebsiteUrl: "https://lendico.de",
    affiliateLink: "https://lendico.de/partner?ref=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-loans-creditplus",
    slug: "creditplus-consumer-loan",
    category: "loans",
    countryCodes: ["DE"],
    providerMark: "CP",
    providerName: "Creditplus",
    title: "Creditplus Ratenkredit",
    subtitle: "Established German consumer credit specialist with fast disbursement and fixed rates",
    metrics: [
      { label: "APR from", value: "4.9%" },
      { label: "Amount", value: "€1,000 – €75,000" },
      { label: "Term", value: "12 – 120 months" },
    ],
    bestFor: ["Car financing", "Home renovation", "Flexible terms"],
    providerWebsiteUrl: "https://creditplus.de",
    affiliateLink: "https://creditplus.de/affiliate/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.70,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-loans-consors-finanz",
    slug: "consors-finanz-personal",
    category: "loans",
    countryCodes: ["DE", "AT"],
    providerMark: "CF",
    providerName: "Consors Finanz",
    title: "Consors Finanz Privatkredit",
    subtitle: "BNP Paribas subsidiary offering flexible consumer financing across Germany and Austria",
    metrics: [
      { label: "APR from", value: "4.4%" },
      { label: "Amount", value: "€3,000 – €50,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["Home renovation", "Medical expenses", "Flexible terms"],
    providerWebsiteUrl: "https://consorsfinanz.de",
    affiliateLink: "https://consorsfinanz.de/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.74,
    updatedAt: "2026-03-16",
  },
  {
    id: "offer-loans-ing",
    slug: "ing-personal-loan",
    category: "loans",
    countryCodes: ["DE", "NL", "AT", "BE", "ES", "IT"],
    providerMark: "IG",
    providerName: "ING",
    title: "ING Privatkredit",
    subtitle: "Trusted global bank delivering competitive fixed-rate personal loans with no fees",
    metrics: [
      { label: "APR from", value: "3.7%" },
      { label: "Amount", value: "€5,000 – €65,000" },
      { label: "Term", value: "24 – 84 months" },
    ],
    bestFor: ["Low rates", "Debt consolidation", "No early repayment fee"],
    providerWebsiteUrl: "https://ing.de",
    affiliateLink: "https://ing.de/kredit?ref=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-loans-deutsche-bank",
    slug: "deutsche-bank-personal-loan",
    category: "loans",
    countryCodes: ["DE"],
    providerMark: "DB",
    providerName: "Deutsche Bank",
    title: "Deutsche Bank Privatkredit",
    subtitle: "Germany's largest bank offering premium personal loan products with fixed rates",
    metrics: [
      { label: "APR from", value: "4.9%" },
      { label: "Amount", value: "€5,000 – €75,000" },
      { label: "Term", value: "12 – 84 months" },
    ],
    bestFor: ["Home renovation", "Car financing", "Low rates"],
    providerWebsiteUrl: "https://deutsche-bank.de",
    affiliateLink: "https://deutsche-bank.de/kredit/partner?id=payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.80,
    updatedAt: "2026-03-19",
  },
  {
    id: "offer-loans-santander",
    slug: "santander-personal-loan",
    category: "loans",
    countryCodes: ["DE", "ES", "PT", "UK", "PL"],
    providerMark: "ST",
    providerName: "Santander",
    title: "Santander BestCredit",
    subtitle: "One of Europe's biggest banks with personalised rates and quick online applications",
    metrics: [
      { label: "APR from", value: "4.3%" },
      { label: "Amount", value: "€1,000 – €65,000" },
      { label: "Term", value: "12 – 96 months" },
    ],
    bestFor: ["Car financing", "Wedding", "Fast approval"],
    providerWebsiteUrl: "https://santander.de",
    affiliateLink: "https://santander.de/kredit/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-loans-bbva",
    slug: "bbva-personal-loan",
    category: "loans",
    countryCodes: ["ES", "PT", "IT"],
    providerMark: "BB",
    providerName: "BBVA",
    title: "BBVA Préstamo Online",
    subtitle: "Spain's digital banking leader with fully online loan applications and instant decisions",
    metrics: [
      { label: "APR from", value: "5.1%" },
      { label: "Amount", value: "€3,000 – €60,000" },
      { label: "Term", value: "12 – 96 months" },
    ],
    bestFor: ["Home renovation", "Digital application", "Fast approval"],
    providerWebsiteUrl: "https://bbva.es",
    affiliateLink: "https://bbva.es/prestamos?partner=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-loans-bnp-paribas",
    slug: "bnp-paribas-pret-personnel",
    category: "loans",
    countryCodes: ["FR", "BE", "IT"],
    providerMark: "BP",
    providerName: "BNP Paribas",
    title: "BNP Paribas Prêt Personnel",
    subtitle: "France's top bank with dedicated personal lending products and preferential client rates",
    metrics: [
      { label: "APR from", value: "3.9%" },
      { label: "Amount", value: "€1,500 – €75,000" },
      { label: "Term", value: "12 – 120 months" },
    ],
    bestFor: ["Low rates", "Home renovation", "Flexible terms"],
    providerWebsiteUrl: "https://mabanque.bnpparibas",
    affiliateLink: "https://mabanque.bnpparibas/pret/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-loans-cofidis",
    slug: "cofidis-personal-loan",
    category: "loans",
    countryCodes: ["FR", "ES", "PT", "IT", "BE", "PL"],
    providerMark: "CO",
    providerName: "Cofidis",
    title: "Cofidis Personal Loan",
    subtitle: "Pan-European consumer credit specialist with 30+ years of experience and fast payouts",
    metrics: [
      { label: "APR from", value: "6.9%" },
      { label: "Amount", value: "€500 – €35,000" },
      { label: "Term", value: "6 – 72 months" },
    ],
    bestFor: ["Fast approval", "Medical expenses", "Wedding"],
    providerWebsiteUrl: "https://cofidis.fr",
    affiliateLink: "https://cofidis.fr/partenaire/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.68,
    updatedAt: "2026-03-15",
  },
  {
    id: "offer-loans-cetelem",
    slug: "cetelem-consumer-credit",
    category: "loans",
    countryCodes: ["FR", "ES", "PT", "PL"],
    providerMark: "CT",
    providerName: "Cetelem",
    title: "Cetelem Crédit Conso",
    subtitle: "BNP Paribas consumer arm specialising in point-of-sale and personal credit",
    metrics: [
      { label: "APR from", value: "5.5%" },
      { label: "Amount", value: "€1,000 – €40,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["Car financing", "Digital application", "Debt consolidation"],
    providerWebsiteUrl: "https://cetelem.fr",
    affiliateLink: "https://cetelem.fr/aff?src=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.65,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-loans-ferratum",
    slug: "ferratum-quick-loan",
    category: "loans",
    countryCodes: ["DE", "FI", "SE", "PL", "ES", "FR"],
    providerMark: "FE",
    providerName: "Ferratum",
    title: "Ferratum Quick Loan",
    subtitle: "Mobile-first micro-lending for when you need funds fast — decisions in minutes",
    metrics: [
      { label: "APR from", value: "10.9%" },
      { label: "Amount", value: "€500 – €15,000" },
      { label: "Term", value: "6 – 48 months" },
    ],
    bestFor: ["Fast approval", "Digital application", "Medical expenses"],
    providerWebsiteUrl: "https://ferratum.com",
    affiliateLink: "https://ferratum.com/partners/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.58,
    updatedAt: "2026-03-14",
  },
  {
    id: "offer-loans-novum-bank",
    slug: "novum-bank-personal-loan",
    category: "loans",
    countryCodes: ["DE", "AT", "NL", "BE"],
    providerMark: "NB",
    providerName: "Novum Bank",
    title: "Novum Bank Personal Credit",
    subtitle: "Malta-licensed digital bank offering competitive cross-border personal lending in the EU",
    metrics: [
      { label: "APR from", value: "7.5%" },
      { label: "Amount", value: "€2,000 – €30,000" },
      { label: "Term", value: "12 – 60 months" },
    ],
    bestFor: ["No early repayment fee", "Digital application", "Flexible terms"],
    providerWebsiteUrl: "https://novumbank.com",
    affiliateLink: "https://novumbank.com/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.55,
    updatedAt: "2026-03-13",
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CARDS (18 offers)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "offer-cards-revolut",
    slug: "revolut-metal-card",
    category: "cards",
    countryCodes: ["DE", "UK", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "PL", "SE", "FI"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Metal Card",
    subtitle: "Premium metal card with airport lounge access, cashback, and no foreign exchange fees worldwide",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit (prepaid)" },
      { label: "Annual fee", value: "€13.99/mo" },
    ],
    bestFor: ["Travel", "No foreign fees", "Premium perks"],
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral/payn-metal",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    updatedAt: "2026-03-24",
  },
  {
    id: "offer-cards-n26",
    slug: "n26-you-card",
    category: "cards",
    countryCodes: ["DE", "AT", "FR", "ES", "IT", "NL", "BE", "IE", "PT"],
    providerMark: "N2",
    providerName: "N26",
    title: "N26 You Card",
    subtitle: "Travel-friendly debit card with comprehensive insurance package and zero FX markup",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€9.90/mo" },
    ],
    bestFor: ["Travel", "No foreign fees", "Everyday spending"],
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/r/payn-you",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-cards-curve",
    slug: "curve-all-in-one-card",
    category: "cards",
    countryCodes: ["UK", "DE", "FR", "IT", "ES", "NL", "IE", "AT", "BE", "PT", "PL", "SE", "FI"],
    providerMark: "CU",
    providerName: "Curve",
    title: "Curve All-In-One Card",
    subtitle: "Consolidate all your cards into one smart card with time-travel and cashback features",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Uses linked cards" },
      { label: "Annual fee", value: "€0 (free tier)" },
    ],
    bestFor: ["Everyday spending", "Cashback", "No foreign fees"],
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/join/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-cards-wise",
    slug: "wise-debit-card",
    category: "cards",
    countryCodes: ["UK", "DE", "FR", "ES", "NL", "AT", "BE", "IE", "IT", "PT", "SE", "FI", "PL"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Debit Card",
    subtitle: "Spend in 40+ currencies at the real mid-market exchange rate with tiny conversion fees",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit (multi-currency)" },
      { label: "Annual fee", value: "€7 one-time" },
    ],
    bestFor: ["Travel", "No foreign fees", "Online shopping"],
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/invite/payn-card",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    updatedAt: "2026-03-24",
  },
  {
    id: "offer-cards-bunq",
    slug: "bunq-easy-green-card",
    category: "cards",
    countryCodes: ["NL", "DE", "AT", "BE", "IE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Easy Green Card",
    subtitle: "The sustainable debit card that plants a tree with every €100 spent — zero FX fees included",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€17.99/mo" },
    ],
    bestFor: ["Travel", "No foreign fees", "Premium perks"],
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/link/payn-green",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.73,
    updatedAt: "2026-03-19",
  },
  {
    id: "offer-cards-monese",
    slug: "monese-classic-card",
    category: "cards",
    countryCodes: ["UK", "DE", "FR", "IT", "ES"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Classic Card",
    subtitle: "No credit check needed — open a mobile account and get your card delivered in days",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit (prepaid)" },
      { label: "Annual fee", value: "€0 (free tier)" },
    ],
    bestFor: ["Building credit", "Student", "Everyday spending"],
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.63,
    updatedAt: "2026-03-16",
  },
  {
    id: "offer-cards-barclaycard",
    slug: "barclaycard-platinum",
    category: "cards",
    countryCodes: ["UK", "DE"],
    providerMark: "BC",
    providerName: "Barclaycard",
    title: "Barclaycard Platinum",
    subtitle: "Long 0% interest period on purchases and balance transfers — ideal for spreading costs",
    metrics: [
      { label: "Representative APR", value: "21.9%" },
      { label: "Credit limit", value: "Up to £10,000" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Low APR", "Building credit", "Everyday spending"],
    providerWebsiteUrl: "https://barclaycard.co.uk",
    affiliateLink: "https://barclaycard.co.uk/apply?aff=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-cards-amex",
    slug: "amex-gold-card",
    category: "cards",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "SE"],
    providerMark: "AE",
    providerName: "American Express",
    title: "American Express Gold Card",
    subtitle: "Premium rewards card earning Membership Rewards points on every purchase with travel perks",
    metrics: [
      { label: "Representative APR", value: "28.2%" },
      { label: "Credit limit", value: "Based on profile" },
      { label: "Annual fee", value: "€140/year" },
    ],
    bestFor: ["Premium perks", "Travel", "Business expenses"],
    providerWebsiteUrl: "https://americanexpress.com",
    affiliateLink: "https://americanexpress.com/en-de/referral/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-cards-capital-one",
    slug: "capital-one-classic-eu",
    category: "cards",
    countryCodes: ["UK"],
    providerMark: "C1",
    providerName: "Capital One (EU)",
    title: "Capital One Classic Credit Card",
    subtitle: "Designed for credit builders — a simple card that reports to all three credit bureaus",
    metrics: [
      { label: "Representative APR", value: "34.9%" },
      { label: "Credit limit", value: "£200 – £1,500" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Building credit", "Student", "Everyday spending"],
    providerWebsiteUrl: "https://capitalone.co.uk",
    affiliateLink: "https://capitalone.co.uk/apply?ref=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.67,
    updatedAt: "2026-03-15",
  },
  {
    id: "offer-cards-ing",
    slug: "ing-visa-card",
    category: "cards",
    countryCodes: ["DE", "NL", "AT", "BE", "ES"],
    providerMark: "IG",
    providerName: "ING",
    title: "ING Visa Card",
    subtitle: "Free debit Visa included with every ING current account — worldwide ATM withdrawals included",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Everyday spending", "No foreign fees", "Travel"],
    providerWebsiteUrl: "https://ing.de",
    affiliateLink: "https://ing.de/girokonto?partner=payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-cards-deutsche-bank",
    slug: "deutsche-bank-mastercard-travel",
    category: "cards",
    countryCodes: ["DE"],
    providerMark: "DB",
    providerName: "Deutsche Bank",
    title: "Deutsche Bank Mastercard Travel",
    subtitle: "Earn miles on every purchase with comprehensive travel insurance and lounge access",
    metrics: [
      { label: "Representative APR", value: "14.9%" },
      { label: "Credit limit", value: "Up to €10,000" },
      { label: "Annual fee", value: "€139/year" },
    ],
    bestFor: ["Travel", "Premium perks", "Business expenses"],
    providerWebsiteUrl: "https://deutsche-bank.de",
    affiliateLink: "https://deutsche-bank.de/kreditkarte/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.75,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-cards-santander",
    slug: "santander-1plus-visa",
    category: "cards",
    countryCodes: ["DE", "ES", "PT", "UK", "PL"],
    providerMark: "ST",
    providerName: "Santander",
    title: "Santander 1plus Visa Card",
    subtitle: "1% cashback on everything with no annual fee and free worldwide cash withdrawals",
    metrics: [
      { label: "Representative APR", value: "13.9%" },
      { label: "Credit limit", value: "Up to €5,000" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Cashback", "No foreign fees", "Everyday spending"],
    providerWebsiteUrl: "https://santander.de",
    affiliateLink: "https://santander.de/kreditkarte/1plus?aff=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-cards-bbva",
    slug: "bbva-aqua-card",
    category: "cards",
    countryCodes: ["ES", "PT", "IT"],
    providerMark: "BB",
    providerName: "BBVA",
    title: "BBVA Aqua Card",
    subtitle: "CVV-less, numberless card with dynamic security for safe online and in-store payments",
    metrics: [
      { label: "Representative APR", value: "20.0%" },
      { label: "Credit limit", value: "Up to €6,000" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Online shopping", "Everyday spending", "Low APR"],
    providerWebsiteUrl: "https://bbva.es",
    affiliateLink: "https://bbva.es/tarjetas/aqua?ref=payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-cards-advanzia",
    slug: "advanzia-gebuhrenfrei-mastercard",
    category: "cards",
    countryCodes: ["DE", "AT", "FR", "ES", "NL", "BE"],
    providerMark: "AD",
    providerName: "Advanzia",
    title: "Advanzia Gebührenfrei Mastercard Gold",
    subtitle: "Truly fee-free gold card with travel insurance — no annual fee, no foreign transaction fee",
    metrics: [
      { label: "Representative APR", value: "22.8%" },
      { label: "Credit limit", value: "Up to €5,000" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Travel", "No foreign fees", "Low APR"],
    providerWebsiteUrl: "https://advanzia.com",
    affiliateLink: "https://gebuhrenfrei.com/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-cards-klarna",
    slug: "klarna-card",
    category: "cards",
    countryCodes: ["DE", "SE", "UK", "AT", "FI"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Card",
    subtitle: "Pay in full or spread the cost of purchases interest-free with the Klarna shopping card",
    metrics: [
      { label: "Representative APR", value: "0% (if paid on time)" },
      { label: "Credit limit", value: "Up to €2,500" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Online shopping", "Student", "Low APR"],
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/card/invite/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-cards-trade-republic",
    slug: "trade-republic-card",
    category: "cards",
    countryCodes: ["DE", "AT", "FR", "ES", "IT", "NL", "BE", "IE", "PT"],
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Card",
    subtitle: "Earn 1% saveback invested into your portfolio on every card purchase — wealth while you spend",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€0" },
    ],
    bestFor: ["Cashback", "Everyday spending", "Online shopping"],
    providerWebsiteUrl: "https://traderepublic.com",
    affiliateLink: "https://traderepublic.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-cards-vivid-money",
    slug: "vivid-money-prime-card",
    category: "cards",
    countryCodes: ["DE", "ES", "FR", "IT"],
    providerMark: "VM",
    providerName: "Vivid Money",
    title: "Vivid Money Prime Card",
    subtitle: "Up to 25% cashback at selected partners and stock rewards with every purchase",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€9.90/mo" },
    ],
    bestFor: ["Cashback", "Online shopping", "Premium perks"],
    providerWebsiteUrl: "https://vivid.money",
    affiliateLink: "https://vivid.money/r/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.69,
    updatedAt: "2026-03-16",
  },
  {
    id: "offer-cards-tomorrow",
    slug: "tomorrow-zero-card",
    category: "cards",
    countryCodes: ["DE", "AT"],
    providerMark: "TM",
    providerName: "Tomorrow",
    title: "Tomorrow Zero Card",
    subtitle: "Climate-positive banking card that offsets your entire CO2 footprint with every transaction",
    metrics: [
      { label: "Representative APR", value: "N/A" },
      { label: "Credit limit", value: "Debit" },
      { label: "Annual fee", value: "€15/mo" },
    ],
    bestFor: ["Everyday spending", "Premium perks", "Student"],
    providerWebsiteUrl: "https://tomorrow.one",
    affiliateLink: "https://tomorrow.one/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.60,
    updatedAt: "2026-03-14",
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TRANSFERS (16 offers)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "offer-transfers-wise",
    slug: "wise-international-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "SE", "FI", "PL"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise International Transfer",
    subtitle: "Send money abroad at the real mid-market rate with transparent low fees — trusted by 16M+ people",
    metrics: [
      { label: "Transfer fee", value: "From 0.41%" },
      { label: "Exchange rate markup", value: "0% (mid-market)" },
      { label: "Speed", value: "Instant – 2 days" },
    ],
    bestFor: ["Large transfers", "EUR corridors", "GBP corridors"],
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/invite/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    updatedAt: "2026-03-24",
  },
  {
    id: "offer-transfers-revolut",
    slug: "revolut-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "SE", "FI", "PL"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut Money Transfer",
    subtitle: "Send money to 150+ countries from your Revolut app with interbank rates on weekdays",
    metrics: [
      { label: "Transfer fee", value: "€0 (in plan)" },
      { label: "Exchange rate markup", value: "0% – 1.5%" },
      { label: "Speed", value: "Instant – 3 days" },
    ],
    bestFor: ["Small remittances", "EUR corridors", "Instant delivery"],
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral/payn-transfer",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-transfers-western-union",
    slug: "western-union-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "SE", "FI", "PL"],
    providerMark: "WU",
    providerName: "Western Union",
    title: "Western Union International Transfer",
    subtitle: "The world's largest money transfer network with 500k+ agent locations for cash pickup",
    metrics: [
      { label: "Transfer fee", value: "From €1.90" },
      { label: "Exchange rate markup", value: "1.5% – 3.5%" },
      { label: "Speed", value: "Minutes – 5 days" },
    ],
    bestFor: ["Cash pickup", "Small remittances", "Recurring transfers"],
    providerWebsiteUrl: "https://westernunion.com",
    affiliateLink: "https://westernunion.com/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.74,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-transfers-remitly",
    slug: "remitly-express-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE"],
    providerMark: "RM",
    providerName: "Remitly",
    title: "Remitly Express Transfer",
    subtitle: "Fast and reliable remittances to developing countries with delivery guarantees",
    metrics: [
      { label: "Transfer fee", value: "From €0.99" },
      { label: "Exchange rate markup", value: "0.5% – 2.0%" },
      { label: "Speed", value: "Minutes – 3 days" },
    ],
    bestFor: ["Small remittances", "Mobile wallet", "Cash pickup"],
    providerWebsiteUrl: "https://remitly.com",
    affiliateLink: "https://remitly.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-transfers-worldremit",
    slug: "worldremit-global-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "IE", "SE", "FI"],
    providerMark: "WR",
    providerName: "WorldRemit",
    title: "WorldRemit Global Transfer",
    subtitle: "Digital-first remittance service supporting mobile money, bank transfer, and cash pickup",
    metrics: [
      { label: "Transfer fee", value: "From €1.49" },
      { label: "Exchange rate markup", value: "0.7% – 2.5%" },
      { label: "Speed", value: "Instant – 3 days" },
    ],
    bestFor: ["Mobile wallet", "Small remittances", "Bank deposit"],
    providerWebsiteUrl: "https://worldremit.com",
    affiliateLink: "https://worldremit.com/invite/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.72,
    updatedAt: "2026-03-19",
  },
  {
    id: "offer-transfers-ofx",
    slug: "ofx-large-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "NL", "IE"],
    providerMark: "OX",
    providerName: "OFX",
    title: "OFX Large Value Transfer",
    subtitle: "Specialist in large international transfers with dedicated dealers and no transfer fees",
    metrics: [
      { label: "Transfer fee", value: "€0" },
      { label: "Exchange rate markup", value: "0.2% – 1.0%" },
      { label: "Speed", value: "1 – 3 days" },
    ],
    bestFor: ["Large transfers", "Business transfers", "Recurring transfers"],
    providerWebsiteUrl: "https://ofx.com",
    affiliateLink: "https://ofx.com/en/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.81,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-transfers-currencyfair",
    slug: "currencyfair-peer-transfer",
    category: "transfers",
    countryCodes: ["IE", "UK", "DE", "FR", "NL", "AT", "BE"],
    providerMark: "CF",
    providerName: "CurrencyFair",
    title: "CurrencyFair Peer-to-Peer Transfer",
    subtitle: "Peer-to-peer currency exchange marketplace offering interbank-beating rates",
    metrics: [
      { label: "Transfer fee", value: "From €3" },
      { label: "Exchange rate markup", value: "0.05% – 0.45%" },
      { label: "Speed", value: "1 – 2 days" },
    ],
    bestFor: ["Large transfers", "EUR corridors", "Recurring transfers"],
    providerWebsiteUrl: "https://currencyfair.com",
    affiliateLink: "https://currencyfair.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.70,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-transfers-azimo",
    slug: "azimo-instant-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "PL"],
    providerMark: "AZ",
    providerName: "Azimo",
    title: "Azimo Instant Transfer",
    subtitle: "Papaya Global-backed remittance app with instant delivery to mobile wallets worldwide",
    metrics: [
      { label: "Transfer fee", value: "From €0.99" },
      { label: "Exchange rate markup", value: "0.5% – 2.0%" },
      { label: "Speed", value: "Instant – 2 days" },
    ],
    bestFor: ["Instant delivery", "Mobile wallet", "Small remittances"],
    providerWebsiteUrl: "https://azimo.com",
    affiliateLink: "https://azimo.com/invite/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.66,
    updatedAt: "2026-03-16",
  },
  {
    id: "offer-transfers-moneygram",
    slug: "moneygram-global-send",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "PL"],
    providerMark: "MG",
    providerName: "MoneyGram",
    title: "MoneyGram Global Send",
    subtitle: "Reach 200+ countries with cash pickup at 350k+ locations or direct to bank accounts",
    metrics: [
      { label: "Transfer fee", value: "From €1.99" },
      { label: "Exchange rate markup", value: "1.0% – 3.0%" },
      { label: "Speed", value: "Minutes – 3 days" },
    ],
    bestFor: ["Cash pickup", "Small remittances", "Bank deposit"],
    providerWebsiteUrl: "https://moneygram.com",
    affiliateLink: "https://moneygram.com/partners/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.69,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-transfers-skrill",
    slug: "skrill-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "PL", "SE", "FI"],
    providerMark: "SK",
    providerName: "Skrill",
    title: "Skrill Money Transfer",
    subtitle: "Paysafe-owned digital wallet with international transfers and crypto on/off ramp",
    metrics: [
      { label: "Transfer fee", value: "From 1.45%" },
      { label: "Exchange rate markup", value: "1.5% – 3.99%" },
      { label: "Speed", value: "Instant – 2 days" },
    ],
    bestFor: ["Instant delivery", "Mobile wallet", "EUR corridors"],
    providerWebsiteUrl: "https://skrill.com",
    affiliateLink: "https://skrill.com/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.61,
    updatedAt: "2026-03-15",
  },
  {
    id: "offer-transfers-paysend",
    slug: "paysend-global-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "IE", "PL"],
    providerMark: "PS",
    providerName: "PaySend",
    title: "PaySend Global Transfer",
    subtitle: "Flat-fee card-to-card international transfers in 100+ countries for just €1.50",
    metrics: [
      { label: "Transfer fee", value: "€1.50 flat" },
      { label: "Exchange rate markup", value: "0.5% – 2.0%" },
      { label: "Speed", value: "Instant – 2 days" },
    ],
    bestFor: ["Small remittances", "Instant delivery", "Recurring transfers"],
    providerWebsiteUrl: "https://paysend.com",
    affiliateLink: "https://paysend.com/refer/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.64,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-transfers-xe",
    slug: "xe-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "NL", "AT", "IE", "SE"],
    providerMark: "XE",
    providerName: "Xe",
    title: "Xe Money Transfer",
    subtitle: "From the trusted exchange rate brand — competitive rates with no transfer fees on large amounts",
    metrics: [
      { label: "Transfer fee", value: "€0 (over €500)" },
      { label: "Exchange rate markup", value: "0.3% – 1.2%" },
      { label: "Speed", value: "1 – 4 days" },
    ],
    bestFor: ["Large transfers", "Business transfers", "GBP corridors"],
    providerWebsiteUrl: "https://xe.com",
    affiliateLink: "https://xe.com/send/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-transfers-small-world",
    slug: "small-world-remittance",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "BE", "NL"],
    providerMark: "SW",
    providerName: "Small World",
    title: "Small World Remittance",
    subtitle: "Affordable remittance service specialising in corridors to Africa, Asia, and Latin America",
    metrics: [
      { label: "Transfer fee", value: "From €0" },
      { label: "Exchange rate markup", value: "0.8% – 2.5%" },
      { label: "Speed", value: "Instant – 3 days" },
    ],
    bestFor: ["Small remittances", "Cash pickup", "Bank deposit"],
    providerWebsiteUrl: "https://smallworldfs.com",
    affiliateLink: "https://smallworldfs.com/referral/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.59,
    updatedAt: "2026-03-14",
  },
  {
    id: "offer-transfers-torfx",
    slug: "torfx-international-payment",
    category: "transfers",
    countryCodes: ["UK", "IE"],
    providerMark: "TF",
    providerName: "TorFX",
    title: "TorFX International Payment",
    subtitle: "Award-winning FX broker with personal account managers and competitive corporate rates",
    metrics: [
      { label: "Transfer fee", value: "€0" },
      { label: "Exchange rate markup", value: "0.2% – 0.8%" },
      { label: "Speed", value: "1 – 2 days" },
    ],
    bestFor: ["Large transfers", "Business transfers", "GBP corridors"],
    providerWebsiteUrl: "https://torfx.com",
    affiliateLink: "https://torfx.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.76,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-transfers-ria",
    slug: "ria-money-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "PL"],
    providerMark: "RI",
    providerName: "Ria",
    title: "Ria Money Transfer",
    subtitle: "Euronet subsidiary with 490k+ partner locations worldwide for fast cash pickup transfers",
    metrics: [
      { label: "Transfer fee", value: "From €2.00" },
      { label: "Exchange rate markup", value: "1.0% – 2.5%" },
      { label: "Speed", value: "Minutes – 2 days" },
    ],
    bestFor: ["Cash pickup", "Small remittances", "Recurring transfers"],
    providerWebsiteUrl: "https://riamoneytransfer.com",
    affiliateLink: "https://riamoneytransfer.com/aff/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.67,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-transfers-instarem",
    slug: "instarem-international-transfer",
    category: "transfers",
    countryCodes: ["UK", "DE", "FR", "NL", "IE"],
    providerMark: "IR",
    providerName: "InstaReM",
    title: "InstaReM International Transfer",
    subtitle: "Asia-Pacific focused transfer service with competitive rates for EUR and GBP corridors",
    metrics: [
      { label: "Transfer fee", value: "From 0.25%" },
      { label: "Exchange rate markup", value: "0.3% – 0.8%" },
      { label: "Speed", value: "1 – 3 days" },
    ],
    bestFor: ["Business transfers", "Large transfers", "EUR corridors"],
    providerWebsiteUrl: "https://instarem.com",
    affiliateLink: "https://instarem.com/invite/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.71,
    updatedAt: "2026-03-19",
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // EXCHANGE (15 offers)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "offer-exchange-wise",
    slug: "wise-multi-currency-account",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "SE", "FI", "PL"],
    providerMark: "WS",
    providerName: "Wise",
    title: "Wise Multi-Currency Account",
    subtitle: "Hold and convert 40+ currencies at the mid-market rate — the gold standard for FX",
    metrics: [
      { label: "Spread", value: "0.00% (mid-market)" },
      { label: "Min. amount", value: "€1" },
      { label: "Supported pairs", value: "40+ currencies" },
    ],
    bestFor: ["Multi-currency", "Competitive spreads", "Travel money"],
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/invite/payn-fx",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    updatedAt: "2026-03-24",
  },
  {
    id: "offer-exchange-revolut",
    slug: "revolut-fx-exchange",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "PT", "SE", "FI", "PL"],
    providerMark: "RV",
    providerName: "Revolut",
    title: "Revolut FX Exchange",
    subtitle: "Swap 30+ currencies in-app at interbank rates on weekdays with no hidden markups",
    metrics: [
      { label: "Spread", value: "0.00% – 1.50%" },
      { label: "Min. amount", value: "€1" },
      { label: "Supported pairs", value: "30+ currencies" },
    ],
    bestFor: ["Multi-currency", "Travel money", "Crypto exchange"],
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral/payn-exchange",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    updatedAt: "2026-03-23",
  },
  {
    id: "offer-exchange-interactive-brokers",
    slug: "interactive-brokers-fx",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "BE", "IE", "SE", "FI"],
    providerMark: "IB",
    providerName: "Interactive Brokers",
    title: "Interactive Brokers Forex",
    subtitle: "Institutional-grade FX trading with the tightest spreads in the industry and 100+ pairs",
    metrics: [
      { label: "Spread", value: "From 0.08 pips" },
      { label: "Min. amount", value: "$25,000 (or equivalent)" },
      { label: "Supported pairs", value: "100+ pairs" },
    ],
    bestFor: ["Spot trading", "Competitive spreads", "Hedging"],
    providerWebsiteUrl: "https://interactivebrokers.com",
    affiliateLink: "https://interactivebrokers.com/referral/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.84,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-exchange-saxo-bank",
    slug: "saxo-bank-fx-trading",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "NL", "AT", "BE", "IT", "ES", "SE", "FI"],
    providerMark: "SB",
    providerName: "Saxo Bank",
    title: "Saxo Bank FX Trading",
    subtitle: "Danish investment bank with advanced FX platform, research tools, and 185+ currency pairs",
    metrics: [
      { label: "Spread", value: "From 0.4 pips" },
      { label: "Min. amount", value: "€2,000" },
      { label: "Supported pairs", value: "185+ pairs" },
    ],
    bestFor: ["Spot trading", "Exotic pairs", "Forward contracts"],
    providerWebsiteUrl: "https://home.saxo",
    affiliateLink: "https://home.saxo/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.79,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-exchange-etoro",
    slug: "etoro-fx-trading",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "AT", "IE", "PL", "SE", "FI"],
    providerMark: "ET",
    providerName: "eToro",
    title: "eToro Forex Trading",
    subtitle: "Social trading platform where you can copy top FX traders and learn from the community",
    metrics: [
      { label: "Spread", value: "From 1.0 pips" },
      { label: "Min. amount", value: "€50" },
      { label: "Supported pairs", value: "49 pairs" },
    ],
    bestFor: ["Spot trading", "Multi-currency", "Competitive spreads"],
    providerWebsiteUrl: "https://etoro.com",
    affiliateLink: "https://etoro.com/people/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    updatedAt: "2026-03-22",
  },
  {
    id: "offer-exchange-n26",
    slug: "n26-currency-exchange",
    category: "exchange",
    countryCodes: ["DE", "AT", "FR", "ES", "IT", "NL", "BE", "IE", "PT"],
    providerMark: "N2",
    providerName: "N26",
    title: "N26 Currency Exchange",
    subtitle: "Exchange currencies directly in your N26 app — Metal customers get unlimited free FX",
    metrics: [
      { label: "Spread", value: "0.00% – 1.70%" },
      { label: "Min. amount", value: "€1" },
      { label: "Supported pairs", value: "30+ currencies" },
    ],
    bestFor: ["Travel money", "Multi-currency", "Competitive spreads"],
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/r/payn-fx",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-exchange-bunq",
    slug: "bunq-auto-fx",
    category: "exchange",
    countryCodes: ["NL", "DE", "AT", "BE", "IE", "FR", "ES", "IT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Auto FX",
    subtitle: "Automatic currency conversion when you pay abroad — hold multiple currency sub-accounts",
    metrics: [
      { label: "Spread", value: "0.50% – 2.00%" },
      { label: "Min. amount", value: "€1" },
      { label: "Supported pairs", value: "25+ currencies" },
    ],
    bestFor: ["Travel money", "Multi-currency", "Competitive spreads"],
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/link/payn-fx",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.65,
    updatedAt: "2026-03-17",
  },
  {
    id: "offer-exchange-currencies-direct",
    slug: "currencies-direct-fx",
    category: "exchange",
    countryCodes: ["UK", "ES", "PT", "FR", "IE"],
    providerMark: "CD",
    providerName: "Currencies Direct",
    title: "Currencies Direct FX",
    subtitle: "FCA-regulated currency specialist with no fees and competitive exchange rates for large sums",
    metrics: [
      { label: "Spread", value: "0.3% – 1.0%" },
      { label: "Min. amount", value: "€100" },
      { label: "Supported pairs", value: "40+ currencies" },
    ],
    bestFor: ["Business FX", "Forward contracts", "Large transfers"],
    providerWebsiteUrl: "https://currenciesdirect.com",
    affiliateLink: "https://currenciesdirect.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.77,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-exchange-transfergo",
    slug: "transfergo-fx-exchange",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "NL", "PL", "SE"],
    providerMark: "TG",
    providerName: "TransferGo",
    title: "TransferGo Currency Exchange",
    subtitle: "European money transfer platform with real-time exchange and low fixed fees",
    metrics: [
      { label: "Spread", value: "0.5% – 1.5%" },
      { label: "Min. amount", value: "€10" },
      { label: "Supported pairs", value: "35+ currencies" },
    ],
    bestFor: ["Multi-currency", "Competitive spreads", "EUR corridors"],
    providerWebsiteUrl: "https://transfergo.com",
    affiliateLink: "https://transfergo.com/referral/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.63,
    updatedAt: "2026-03-16",
  },
  {
    id: "offer-exchange-moneycorp",
    slug: "moneycorp-fx-services",
    category: "exchange",
    countryCodes: ["UK", "IE", "ES", "PT"],
    providerMark: "MC",
    providerName: "Moneycorp",
    title: "Moneycorp FX Services",
    subtitle: "Premium currency services for corporates and HNW individuals with dedicated dealers",
    metrics: [
      { label: "Spread", value: "0.2% – 0.7%" },
      { label: "Min. amount", value: "€500" },
      { label: "Supported pairs", value: "120+ currencies" },
    ],
    bestFor: ["Business FX", "Forward contracts", "Hedging"],
    providerWebsiteUrl: "https://moneycorp.com",
    affiliateLink: "https://moneycorp.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.73,
    updatedAt: "2026-03-19",
  },
  {
    id: "offer-exchange-hifx",
    slug: "hifx-currency-exchange",
    category: "exchange",
    countryCodes: ["UK", "IE"],
    providerMark: "HF",
    providerName: "HiFX",
    title: "HiFX Currency Exchange",
    subtitle: "Euronet-owned FX specialist offering large value transfers with locked-in rates",
    metrics: [
      { label: "Spread", value: "0.3% – 1.0%" },
      { label: "Min. amount", value: "£250" },
      { label: "Supported pairs", value: "50+ currencies" },
    ],
    bestFor: ["Large transfers", "Forward contracts", "GBP corridors"],
    providerWebsiteUrl: "https://hifx.co.uk",
    affiliateLink: "https://hifx.co.uk/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.62,
    updatedAt: "2026-03-15",
  },
  {
    id: "offer-exchange-ebury",
    slug: "ebury-business-fx",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "NL", "IT", "AT", "BE", "IE", "PT", "PL"],
    providerMark: "EB",
    providerName: "Ebury",
    title: "Ebury Business FX",
    subtitle: "Santander-backed fintech specialising in international payments and FX for SMEs",
    metrics: [
      { label: "Spread", value: "0.1% – 0.5%" },
      { label: "Min. amount", value: "€5,000" },
      { label: "Supported pairs", value: "130+ currencies" },
    ],
    bestFor: ["Business FX", "API access", "Hedging"],
    providerWebsiteUrl: "https://ebury.com",
    affiliateLink: "https://ebury.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.78,
    updatedAt: "2026-03-21",
  },
  {
    id: "offer-exchange-currencycloud",
    slug: "currencycloud-platform-fx",
    category: "exchange",
    countryCodes: ["UK", "DE", "NL", "IE"],
    providerMark: "CC",
    providerName: "CurrencyCloud",
    title: "CurrencyCloud Platform FX",
    subtitle: "Visa-owned B2B infrastructure powering FX for banks, fintechs, and platforms via API",
    metrics: [
      { label: "Spread", value: "0.1% – 0.4%" },
      { label: "Min. amount", value: "€1,000" },
      { label: "Supported pairs", value: "35+ currencies" },
    ],
    bestFor: ["API access", "Business FX", "Competitive spreads"],
    providerWebsiteUrl: "https://currencycloud.com",
    affiliateLink: "https://currencycloud.com/partners/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.75,
    updatedAt: "2026-03-20",
  },
  {
    id: "offer-exchange-kantox",
    slug: "kantox-dynamic-hedging",
    category: "exchange",
    countryCodes: ["UK", "DE", "FR", "ES", "NL", "IT", "BE"],
    providerMark: "KX",
    providerName: "Kantox",
    title: "Kantox Dynamic Hedging",
    subtitle: "BNP Paribas-backed SaaS platform automating FX risk management for mid-caps and corporates",
    metrics: [
      { label: "Spread", value: "0.05% – 0.3%" },
      { label: "Min. amount", value: "€10,000" },
      { label: "Supported pairs", value: "80+ currencies" },
    ],
    bestFor: ["Hedging", "Business FX", "API access"],
    providerWebsiteUrl: "https://kantox.com",
    affiliateLink: "https://kantox.com/partner/payn",
    linkType: "lead_capture",
    affiliatePriorityScore: 0.70,
    updatedAt: "2026-03-18",
  },
  {
    id: "offer-exchange-connectpay",
    slug: "connectpay-fx-account",
    category: "exchange",
    countryCodes: ["DE", "NL", "AT", "BE", "FR", "IT", "ES", "PL", "SE", "FI"],
    providerMark: "CP",
    providerName: "ConnectPay",
    title: "ConnectPay FX Account",
    subtitle: "Lithuanian EMI offering multi-currency IBAN accounts with real-time currency conversion",
    metrics: [
      { label: "Spread", value: "0.4% – 1.2%" },
      { label: "Min. amount", value: "€10" },
      { label: "Supported pairs", value: "28 currencies" },
    ],
    bestFor: ["Multi-currency", "Business FX", "EUR corridors"],
    providerWebsiteUrl: "https://connectpay.com",
    affiliateLink: "https://connectpay.com/partner/payn",
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.57,
    updatedAt: "2026-03-13",
  },
];
