import type { MarketplaceOffer } from "@payn/types";

export const newCategoriesOffers: MarketplaceOffer[] = [

  // ═══════════════════════════════════════════════════
  // NEOBANKS (6 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "neobank-revolut-standard",
    slug: "revolut-neobank",
    category: "neobanks",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Standard",
    subtitle: "Europe's largest neobank. Multi-currency account, instant spending notifications, built-in budgeting, and fee-free spending in 150+ countries.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Currencies", value: "36+" },
      { label: "ATM limit", value: "EUR 200/month free" },
    ],
    bestFor: ["Multi-currency", "Travel", "Free account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.97,
    providerWebsiteUrl: "https://www.revolut.com/our-pricing-plans/",
    affiliateLink: "https://www.revolut.com/our-pricing-plans/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["neobank", "digital bank", "multi-currency"] },
  },
  {
    id: "neobank-n26-standard",
    slug: "n26-neobank",
    category: "neobanks",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL", "BE"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Standard",
    subtitle: "German neobank with a clean mobile app, SEPA transfers, and a sleek Mastercard. One of the most trusted digital banks in Europe.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "ATM withdrawals", value: "3 free/month (EU)" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["German market", "Clean UX", "Full banking licence"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "digital bank", "Germany"] },
  },
  {
    id: "neobank-bunq-easy",
    slug: "bunq-neobank",
    category: "neobanks",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "BE", "AT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Easy Bank",
    subtitle: "Dutch neobank known for sustainability focus, instant payment splits, and unique sub-accounts. Strong privacy defaults and no hidden fees.",
    metrics: [
      { label: "Monthly fee", value: "EUR 3.99" },
      { label: "Sub-accounts", value: "Up to 25" },
      { label: "Green card", value: "Tree planted per EUR 100 spent" },
    ],
    bestFor: ["Privacy-first", "Sub-accounts", "Sustainability"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.bunq.com/plans",
    affiliateLink: "https://www.bunq.com/plans",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "sustainable bank", "Netherlands"] },
  },
  {
    id: "neobank-monzo-uk",
    slug: "monzo-neobank",
    category: "neobanks",
    countryCodes: ["UK"],
    providerMark: "MZ",
    providerName: "Monzo",
    title: "Monzo Personal",
    subtitle: "UK's leading neobank with real-time spending insights, salary sorter, pots, and a premium coral card. Full UK banking licence.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Overdraft", value: "From 19% EAR" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["UK residents", "Budgeting pots", "Spending insights"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://monzo.com",
    affiliateLink: "https://monzo.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["neobank", "UK bank", "digital bank"] },
  },
  {
    id: "neobank-starling-uk",
    slug: "starling-neobank",
    category: "neobanks",
    countryCodes: ["UK"],
    providerMark: "SB",
    providerName: "Starling Bank",
    title: "Starling Personal",
    subtitle: "Award-winning UK neobank with no monthly fees, connected card, and excellent customer service. Consistently top-rated by Which? and Trustpilot.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Interest on balance", value: "Up to 3.25% AER" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["No fees", "Interest on balance", "UK award winner"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://www.starlingbank.com/current-account/",
    affiliateLink: "https://www.starlingbank.com/current-account/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["neobank", "UK bank", "Starling"] },
  },
  {
    id: "neobank-monese-eu",
    slug: "monese-neobank",
    category: "neobanks",
    countryCodes: ["EU", "UK"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Simple",
    subtitle: "No credit check required. Open an EU or UK account in minutes even without a local address. Ideal for expats and new arrivals.",
    metrics: [
      { label: "Monthly fee", value: "Free (Simple plan)" },
      { label: "Instant setup", value: "No address proof needed" },
      { label: "Currencies", value: "EUR + GBP" },
    ],
    bestFor: ["Expats", "No credit check", "New arrivals"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://monese.com/features/",
    affiliateLink: "https://monese.com/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "expat bank", "no credit check"] },
  },

  // ═══════════════════════════════════════════════════
  // SAVINGS ACCOUNTS (12 offers: 6 easy-access + 6 fixed-term)
  // ═══════════════════════════════════════════════════
  {
    id: "savings-trade-republic",
    slug: "trade-republic-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL", "BE"],
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Savings",
    subtitle: "4% interest on uninvested cash with daily accrual. Backed by Deutsche Bank and BaFin regulated. No minimum deposit required.",
    metrics: [
      { label: "Interest rate", value: "4.0% per year" },
      { label: "Minimum deposit", value: "EUR 1" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["High yield", "No minimum", "Daily interest"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.96,
    providerWebsiteUrl: "https://traderepublic.com",
    affiliateLink: "https://traderepublic.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "high yield", "interest"] },
  },
  {
    id: "savings-raisin-eu",
    slug: "raisin-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL"],
    providerMark: "RS",
    providerName: "Raisin",
    title: "Raisin Savings Marketplace",
    subtitle: "Europe's leading deposit marketplace. Access savings accounts from 100+ European banks through one platform. Compare rates and switch instantly.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.5% per year" },
      { label: "Partner banks", value: "100+" },
      { label: "Deposit protection", value: "Up to EUR 100,000 per bank" },
    ],
    bestFor: ["Best rates in Europe", "Multiple banks", "EUR 1,000+ deposits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://www.raisin.com/en-eu/savings/",
    affiliateLink: "https://www.raisin.com/en-eu/savings/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "deposit", "best rates"] },
  },
  {
    id: "savings-revolut-savings",
    slug: "revolut-savings",
    category: "savings",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Savings Vault",
    subtitle: "Flexible savings pocket within your Revolut app. Rates vary by currency and plan; instant access, no lock-in.",
    metrics: [
      // CAT.5 — Was "Up to 3.49% (Metal)" — that was a stale figure
      // mixing currencies. Per Revolut Help (May 2026): GBP Metal
      // tracks at ~3.64%, EUR Metal at ~1.96%. Showing both keeps the
      // claim honest across the EU/UK markets the offer targets.
      { label: "EUR rate (Metal)", value: "Up to 1.96% AER" },
      { label: "GBP rate (Metal)", value: "Up to 3.64% AER" },
      { label: "Access", value: "Instant" },
    ],
    bestFor: ["Revolut users", "Instant access", "No lock-in"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://www.revolut.com/savings/",
    affiliateLink: "https://www.revolut.com/savings/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "revolut", "flexible"] },
  },
  {
    id: "savings-n26-savings",
    slug: "n26-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Savings",
    subtitle: "Savings account built into N26 banking app. Instant access, no fees, and backed by German deposit protection up to EUR 100,000.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.0% AER" },
      { label: "Access", value: "Instant" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["N26 customers", "German deposit protection", "No fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "N26", "Germany"] },
  },
  {
    id: "savings-lightyear",
    slug: "lightyear-savings",
    category: "savings",
    countryCodes: ["UK", "EU"],
    providerMark: "LY",
    providerName: "Lightyear",
    title: "Lightyear Cash Account",
    subtitle: "Yield on idle cash via money-market funds, accessible inside the same app you use for stocks and ETFs. Note: held in MMFs, not as a bank deposit.",
    metrics: [
      // CAT.5 — Rates corrected: USD 5.1% → 3.75%, EUR 3.8% → 1.94%
      // (lightyear.com/en-eu, March 2026). The published rates track
      // the underlying USD MMF / EUR MMF yields, which have come down
      // since the catalog was last refreshed in 2024.
      { label: "USD rate", value: "Up to 3.75% (variable)" },
      { label: "EUR rate", value: "1.94% AER (variable)" },
      // CAT.10 — Was "GBP 85,000 FSCS" — Lightyear's own help text:
      // "FSCS protection does not apply to funds held within the
      // money market fund itself." Replaced with the actual
      // investor-protection regime (Estonian Investor Protection
      // Sectoral Fund, up to €20,000).
      { label: "Protection", value: "€20,000 IPSF (MMF, not FSCS deposit)" },
    ],
    bestFor: ["Investors", "Multi-currency cash", "UK/EU residents"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://lightyear.com",
    affiliateLink: "https://lightyear.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "cash account", "interest"] },
  },
  {
    id: "savings-vivid-prime",
    slug: "vivid-savings",
    category: "savings",
    countryCodes: ["DE", "FR", "ES", "IT"],
    providerMark: "VV",
    providerName: "Vivid Money",
    title: "Vivid Savings",
    subtitle: "Earn up to 4% interest on EUR savings through Vivid Prime. Access your funds any time with no minimum deposit.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.0%" },
      { label: "Plan required", value: "Vivid Prime (EUR 9.90/month)" },
      { label: "Minimum", value: "EUR 1" },
    ],
    bestFor: ["Cashback + savings combo", "EU residents", "Vivid users"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.73,
    providerWebsiteUrl: "https://vivid.money",
    affiliateLink: "https://vivid.money",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "Vivid", "interest"] },
  },

  // ─── Fixed-term deposits (Festgeld / depósitos a plazo / conto deposito) ─
  //
  // The earlier savings catalogue covered only easy-access / variable-rate
  // accounts — users looking for a locked-in rate (Raisin Festgeld, Klarna
  // Festgeld, NS&I bonds, etc.) found the savings page empty for their
  // intent and bounced. These six entries cover the canonical fixed-term
  // products in DE/EU/ES/IT/FR/UK. Rates marked "variable" because the
  // exact yield re-prices monthly off the ECB / BoE base rate; the
  // accompanying tradeoff line points the user at the source for the
  // live number. Term lengths reflect the most-comparable 1-year tenor
  // unless a provider only sells 2y+ products (NS&I, Distingo).
  {
    id: "savings-raisin-festgeld",
    slug: "raisin-festgeld",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL"],
    providerMark: "RS",
    providerName: "Raisin",
    title: "Raisin Festgeld (fixed-term deposit)",
    subtitle: "One-click access to fixed-term deposits from 100+ European partner banks. Lock in 1-, 2-, 3-, or 5-year rates without opening separate accounts.",
    metrics: [
      { label: "1-year rate", value: "Up to 3.10% p.a. (variable per bank)" },
      { label: "Term length", value: "1 / 2 / 3 / 5 years" },
      { label: "Minimum deposit", value: "EUR 1,000" },
      { label: "Deposit protection", value: "Up to EUR 100,000 per bank (EU DGS)" },
    ],
    bestFor: ["Locked-in rate", "Best of 100+ banks", "EUR 1,000+ savings"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://www.raisin.com/en-eu/fixed-term-deposit/",
    affiliateLink: "https://www.raisin.com/en-eu/fixed-term-deposit/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["fixed-term", "Festgeld", "deposit", "fixed rate"] },
  },
  {
    id: "savings-klarna-festgeld",
    slug: "klarna-festgeld",
    category: "savings",
    countryCodes: ["DE"],
    providerMark: "K",
    providerName: "Klarna",
    title: "Klarna Festgeld",
    subtitle: "Fixed-term deposit from Klarna's Swedish banking entity. Lock in a guaranteed rate for 1–4 years with Swedish deposit protection.",
    metrics: [
      { label: "1-year rate", value: "Up to 2.85% p.a. (variable)" },
      { label: "Term length", value: "1 / 2 / 3 / 4 years" },
      { label: "Minimum deposit", value: "EUR 1" },
      { label: "Deposit protection", value: "EUR 100,000 (Swedish DGS via Klarna Bank AB)" },
    ],
    bestFor: ["No minimum", "Familiar brand DE", "Fixed return"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.klarna.com/de/festgeld/",
    affiliateLink: "https://www.klarna.com/de/festgeld/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["Festgeld", "Klarna", "fixed-term"] },
  },
  {
    id: "savings-myinvestor-deposito",
    slug: "myinvestor-deposito",
    category: "savings",
    countryCodes: ["ES"],
    providerMark: "MI",
    providerName: "MyInvestor",
    title: "MyInvestor Depósito a Plazo Fijo",
    subtitle: "Spanish fixed-term deposit from MyInvestor (Andbank-backed). 12-month locked rate with Spanish FGD deposit protection.",
    metrics: [
      { label: "12-month rate", value: "Up to 2.75% TAE (variable)" },
      { label: "Term length", value: "12 months" },
      { label: "Minimum deposit", value: "EUR 10,000" },
      { label: "Deposit protection", value: "EUR 100,000 (Spanish FGD)" },
    ],
    bestFor: ["Spanish residents", "Locked-in rate", "Tax-resident in ES"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://myinvestor.es/ahorro/deposito-a-plazo/",
    affiliateLink: "https://myinvestor.es/ahorro/deposito-a-plazo/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["depósito", "plazo fijo", "MyInvestor", "ES"] },
  },
  {
    id: "savings-illimity-conto-deposito",
    slug: "illimity-conto-deposito",
    category: "savings",
    countryCodes: ["IT"],
    providerMark: "IL",
    providerName: "Illimity Bank",
    title: "Illimity Conto Deposito",
    subtitle: "Italian online-only fixed-term deposit from Illimity. Choose tenor from 6 to 60 months with Italian FITD deposit protection.",
    metrics: [
      { label: "12-month rate", value: "Up to 2.90% lordo (variable)" },
      { label: "Term length", value: "6 / 12 / 24 / 36 / 60 months" },
      { label: "Minimum deposit", value: "EUR 1,000" },
      { label: "Deposit protection", value: "EUR 100,000 (Italian FITD)" },
    ],
    bestFor: ["Italian residents", "Online-only", "Flexible tenor"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://www.illimitybank.com/",
    affiliateLink: "https://www.illimitybank.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["conto deposito", "Illimity", "IT", "fixed-term"] },
  },
  {
    id: "savings-nsi-bonds",
    slug: "nsi-guaranteed-bonds",
    category: "savings",
    countryCodes: ["UK"],
    providerMark: "NSI",
    providerName: "NS&I",
    title: "NS&I Guaranteed Growth Bonds (1-Year)",
    subtitle: "UK-government-backed fixed-term bonds from NS&I. 100% capital protected — backed by HM Treasury, no FSCS cap.",
    metrics: [
      { label: "1-year rate", value: "Up to 3.95% AER (variable)" },
      { label: "Term length", value: "1 / 2 / 3 / 5 years" },
      { label: "Minimum deposit", value: "GBP 500" },
      { label: "Protection", value: "100% HM Treasury backed (no FSCS cap)" },
    ],
    bestFor: ["UK residents", "Above-FSCS-cap savers", "Government guarantee"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.nsandi.com/products/guaranteed-growth-bonds",
    affiliateLink: "https://www.nsandi.com/products/guaranteed-growth-bonds",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["bonds", "NS&I", "UK", "fixed-term", "government"] },
  },

  // ═══════════════════════════════════════════════════
  // TRADING PLATFORMS (6 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "trading-trading212",
    slug: "trading212",
    category: "trading",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "PT", "NL", "AT"],
    providerMark: "T212",
    providerName: "Trading 212",
    title: "Trading 212 Invest",
    subtitle: "Zero-commission stock and ETF investing for European retail investors. Fractional shares from GBP 1. ISA available for UK users.",
    metrics: [
      { label: "Commission", value: "0%" },
      { label: "Markets", value: "3,000+ stocks & ETFs" },
      { label: "Minimum", value: "GBP/EUR 1" },
    ],
    bestFor: ["Zero commission", "Fractional shares", "ISA (UK)"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    providerWebsiteUrl: "https://www.trading212.com/invest",
    affiliateLink: "https://www.trading212.com/invest",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "stocks", "ETF", "zero commission"] },
  },
  {
    id: "trading-degiro",
    slug: "degiro-trading",
    category: "trading",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "PT", "BE", "AT"],
    providerMark: "DG",
    providerName: "DEGIRO",
    title: "DEGIRO",
    subtitle: "Low-cost European broker with access to 50+ stock exchanges worldwide. Trusted by 3 million investors across Europe.",
    metrics: [
      { label: "Stocks (EU)", value: "EUR 3.90 + 0.05% per order" },
      { label: "Markets", value: "50+ exchanges" },
      { label: "ETFs", value: "From EUR 0" },
    ],
    bestFor: ["Active traders", "EU markets", "Low fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.degiro.eu/feeschedule",
    affiliateLink: "https://www.degiro.eu/feeschedule",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "broker", "stocks", "DEGIRO"] },
  },
  {
    id: "trading-xtb",
    slug: "xtb-trading",
    category: "trading",
    countryCodes: ["EU", "UK"],
    providerMark: "XTB",
    providerName: "XTB",
    title: "XTB",
    subtitle: "Listed broker with commission-free stock and ETF trading up to EUR 100,000/month. Award-winning xStation platform with advanced charting.",
    metrics: [
      { label: "Commission", value: "0% up to EUR 100k/month" },
      { label: "Instruments", value: "5,400+" },
      { label: "Platform", value: "xStation 5" },
    ],
    bestFor: ["Active traders", "Advanced tools", "High volume"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.xtb.com/en/offer/stocks-and-etfs",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C416493292T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: {monetized: true, affiliate: true, isPartner: true, dataSource: "affiliate", confidenceScore: 0.97, availability: "eu_wide", searchTags: ["trading", "broker", "CFD", "stocks"] },
  },
  {
    id: "trading-interactive-brokers",
    slug: "interactive-brokers-trading",
    category: "trading",
    // CAT.9 — IBKR Lite is restricted to US residents. EU users get
    // IBKR Pro / IBKR Universal Account. Renamed the listing and
    // updated metrics to reflect what European users actually see
    // (commission-tier rather than free-tier).
    countryCodes: ["EU", "UK"],
    providerMark: "IB",
    providerName: "Interactive Brokers",
    title: "IBKR Pro / Universal (EU/UK)",
    subtitle: "Global broker for active traders. IBKR Lite (USD 0 commissions) is US-only — EU and UK clients receive IBKR Pro / Universal Account with tiered commissions but the same 150-market access.",
    metrics: [
      { label: "Commission (EU/UK)", value: "From USD 0.0035/share (Pro)" },
      { label: "Markets", value: "150 in 33 countries" },
      { label: "Minimum deposit", value: "USD 0" },
    ],
    bestFor: ["Global markets", "Professional tools", "Margin trading"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.interactivebrokers.com/en/trading/tws.php",
    affiliateLink: "https://www.interactivebrokers.com/en/trading/tws.php",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["trading", "global broker", "professional"] },
  },
  {
    id: "trading-scalable-capital",
    slug: "scalable-capital-trading",
    category: "trading",
    countryCodes: ["DE", "AT", "NL", "FR", "ES", "IT"],
    providerMark: "SC",
    providerName: "Scalable Capital",
    title: "Scalable Capital Broker",
    subtitle: "German fintech broker with flat-fee Prime subscription. Unlimited trades on XETRA and Gettex for EUR 4.99/month.",
    metrics: [
      { label: "Prime subscription", value: "EUR 4.99/month" },
      { label: "Trades (Prime)", value: "Unlimited" },
      { label: "Savings plans", value: "Yes, free" },
    ],
    bestFor: ["Active EU traders", "Savings plans", "German market"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://de.scalable.capital/broker",
    affiliateLink: "https://de.scalable.capital/broker",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "German broker", "flat fee"] },
  },

  // ═══════════════════════════════════════════════════
  // BUY NOW PAY LATER (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "bnpl-klarna",
    slug: "klarna-bnpl",
    category: "bnpl",
    countryCodes: ["DE", "SE", "NO", "FI", "UK", "ES", "FR", "IT", "NL", "AT"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Pay Later",
    subtitle: "Europe's leading BNPL provider. Pay in 30 days or split into 3 instalments with no interest. Available at 500,000+ partner stores.",
    metrics: [
      { label: "Interest", value: "0% if paid on time" },
      { label: "Split options", value: "Pay in 30 days / 3 instalments" },
      { label: "Merchants", value: "500,000+" },
    ],
    bestFor: ["No interest", "Flexible instalments", "Wide acceptance"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://www.klarna.com/uk/customer-service/pay-later/",
    affiliateLink: "https://www.klarna.com/uk/customer-service/pay-later/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "pay later", "instalments"] },
  },
  {
    id: "bnpl-scalapay",
    slug: "scalapay-bnpl",
    category: "bnpl",
    countryCodes: ["IT", "ES", "FR", "PT", "BE", "NL", "AT", "DE"],
    providerMark: "SP",
    providerName: "Scalapay",
    title: "Scalapay",
    subtitle: "Southern European BNPL leader. Split any purchase into 3 instalments with 0% interest. Strong fashion and lifestyle merchant network.",
    metrics: [
      { label: "Instalments", value: "3 × 0%" },
      { label: "Merchants", value: "8,000+ in Europe" },
      { label: "Approval", value: "Instant" },
    ],
    bestFor: ["Italy & Spain", "Fashion shopping", "0% instalments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.scalapay.com",
    affiliateLink: "https://www.scalapay.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "Italy", "Spain", "instalments"] },
  },
  {
    id: "bnpl-clearpay",
    slug: "clearpay-bnpl",
    category: "bnpl",
    countryCodes: ["UK"],
    providerMark: "CP",
    providerName: "Clearpay",
    title: "Clearpay",
    subtitle: "UK's top BNPL service (Afterpay's UK brand). Split purchases into 4 fortnightly payments with no interest if paid on time.",
    metrics: [
      { label: "Instalments", value: "4 × interest-free" },
      { label: "Payment frequency", value: "Fortnightly" },
      { label: "Late fee", value: "GBP 6 max" },
    ],
    bestFor: ["UK shoppers", "Fashion & beauty", "Fortnightly payments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://www.clearpay.co.uk/en-GB/how-it-works",
    affiliateLink: "https://www.clearpay.co.uk/en-GB/how-it-works",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["BNPL", "UK", "Afterpay", "instalments"] },
  },
  {
    id: "bnpl-alma",
    slug: "alma-bnpl",
    category: "bnpl",
    countryCodes: ["FR", "DE", "ES", "IT", "BE", "NL"],
    providerMark: "AL",
    providerName: "Alma",
    title: "Alma",
    subtitle: "French BNPL platform with 2, 3, or 4 instalment options. Focused on quality merchants in fashion, home, and electronics.",
    metrics: [
      { label: "Options", value: "2x, 3x, 4x" },
      { label: "Interest", value: "0% for buyer" },
      { label: "Merchants", value: "15,000+" },
    ],
    bestFor: ["France & EU", "Premium merchants", "Flexible splits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://www.getalma.eu/fr/paiement-fractionne",
    affiliateLink: "https://www.getalma.eu/fr/paiement-fractionne",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "France", "instalments"] },
  },
  {
    id: "bnpl-paypal-paylater",
    slug: "paypal-pay-later",
    category: "bnpl",
    // CAT.4 — Pay in 4 is a US-only product; the UK / EU PayPal Pay
    // Later is Pay in 3 (3 instalments, 0% interest, £30–£2,000 / €30–
    // €2,000 range). "6 months flexible" doesn't exist — it conflated
    // a separate PayPal Credit product (UK only, 0% for 4 months on
    // purchases over £99). Removed the US country code so the listing
    // only surfaces where Pay in 3 is actually offered.
    countryCodes: ["EU", "UK"],
    providerMark: "PP",
    providerName: "PayPal",
    title: "PayPal Pay in 3",
    subtitle:
      "Split a PayPal purchase into 3 interest-free payments — first instalment at checkout, the next two over the following 60 days. UK and EU only.",
    metrics: [
      { label: "Plan", value: "3 × 0% interest" },
      { label: "Amount", value: "£30–£2,000 / €30–€2,000" },
      { label: "Acceptance", value: "Wherever PayPal is offered" },
    ],
    bestFor: ["Existing PayPal users", "Short-term splits", "No new account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://www.paypal.com/uk/digital-wallet/ways-to-pay/buy-now-pay-later",
    affiliateLink: "https://www.paypal.com/uk/digital-wallet/ways-to-pay/buy-now-pay-later",
    updatedAt: "2026-05-25T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "PayPal", "pay later", "pay in 3"] },
  },

  // ═══════════════════════════════════════════════════
  // DEBIT CARDS (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "debit-revolut",
    slug: "revolut-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Debit Card",
    subtitle: "Multi-currency debit card with real interbank exchange rates. Spend in 150+ currencies with no hidden FX markup on weekdays.",
    metrics: [
      { label: "FX fee (weekday)", value: "0%" },
      { label: "ATM", value: "EUR 200/month free" },
      { label: "Monthly fee", value: "Free (Standard)" },
    ],
    bestFor: ["Multi-currency spending", "Travel", "Free plan"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://www.revolut.com/cards/",
    affiliateLink: "https://www.revolut.com/cards/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "multi-currency", "travel"] },
  },
  {
    id: "debit-wise",
    slug: "wise-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Debit Card",
    subtitle: "Multi-currency debit card linked to your Wise account. Spend in 40+ currencies at the mid-market rate with low transparent fees.",
    metrics: [
      { label: "FX fee", value: "0.35% – 2%" },
      { label: "Currencies", value: "40+" },
      { label: "ATM (free/month)", value: "GBP 200 / EUR 200" },
    ],
    bestFor: ["Transparent FX fees", "Multi-currency", "International freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://wise.com/gb/card/",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676432T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: true, affiliate: true, isPartner: true, searchTags: ["debit card", "Wise", "multi-currency"] },
  },
  {
    id: "debit-curve",
    slug: "curve-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Card",
    subtitle: "One card that connects all your existing cards. Spend in 150+ currencies at competitive rates, earn cashback, and switch transactions backwards.",
    metrics: [
      // CAT.5 — Curve renamed the free tier "Curve Pay" (was "Curve X")
      // and cut the FX-free allowance from £500 to £250/mo in Dec 2025.
      // Cashback at 3 retailers is now a Pro+ feature, not free tier.
      { label: "Monthly fee", value: "Free (Curve Pay)" },
      { label: "FX fee (weekday)", value: "0% up to GBP 250/month" },
      { label: "Cashback (Pro+)", value: "Up to 3 retailers" },
    ],
    bestFor: ["Card consolidation", "Go Back in Time feature"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.curve.com/",
    affiliateLink: "https://www.curve.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "Curve", "cashback"] },
  },
  {
    id: "debit-bunq",
    slug: "bunq-debit-card",
    category: "debit",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "BE"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Debit Card",
    subtitle: "Sleek Mastercard debit card with up to 25 sub-accounts and IBANs. Use abroad with low FX fees and instant payment splits.",
    metrics: [
      { label: "FX fee", value: "1.5%" },
      { label: "Sub-IBANs", value: "Up to 25" },
      { label: "Monthly fee", value: "EUR 3.99+" },
    ],
    bestFor: ["Sub-accounts", "Netherlands", "Privacy-focused"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.bunq.com",
    affiliateLink: "https://www.bunq.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "bunq", "sub-accounts"] },
  },
  {
    id: "debit-wirex",
    slug: "wirex-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "WX",
    providerName: "Wirex",
    title: "Wirex Debit Card",
    subtitle: "Crypto-friendly debit card that lets you spend BTC, ETH, and 150+ currencies. Card rewards are paid in WXT, Wirex's native token — not fiat — so the real value depends on WXT's market price at the moment you spend or sell.",
    metrics: [
      // CAT.8 — Was "Up to 8% in WXT" with no disclosure. WXT is a
      // volatile crypto token; the cashback rate is in WXT terms, not
      // a fiat-equivalent rate. Label rewritten so users see the
      // currency, not just the headline percent.
      { label: "Cryptoback", value: "Up to 8% — paid in WXT (volatile token)" },
      { label: "Currencies", value: "150+" },
      { label: "Monthly fee", value: "Free (Standard)" },
    ],
    bestFor: ["Crypto users", "WXT holders", "Multi-currency"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://wirexapp.com",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C251169530T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: {monetized: true, affiliate: true, isPartner: true, dataSource: "affiliate", confidenceScore: 0.97, availability: "eu_wide", searchTags: ["debit card", "crypto card", "Wirex"] },
  },

  // ═══════════════════════════════════════════════════
  // REMITTANCE (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "remittance-wise",
    slug: "wise-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise International Transfer",
    subtitle: "Send money to 80+ countries at the mid-market exchange rate. Low transparent fees and fast delivery — often within hours.",
    metrics: [
      { label: "Fee", value: "From 0.35%" },
      { label: "Speed", value: "Same day / next day" },
      { label: "Countries", value: "80+" },
    ],
    bestFor: ["Transparent fees", "Fast delivery", "Mid-market rate"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.97,
    providerWebsiteUrl: "https://wise.com/gb/send-money/",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676432T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", monetized: true, affiliate: true, isPartner: true, searchTags: ["remittance", "international transfer", "Wise"] },
  },
  {
    id: "remittance-remitly",
    slug: "remitly-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "RM",
    providerName: "Remitly",
    title: "Remitly",
    subtitle: "Specialist remittance app for sending money to Latin America, Asia, Africa, and Eastern Europe. Competitive rates for high-volume corridors.",
    metrics: [
      { label: "Speed", value: "Minutes (Express)" },
      { label: "Corridors", value: "170+ countries" },
      { label: "Promotions", value: "First transfer fee-free" },
    ],
    bestFor: ["Non-EU corridors", "Promotions", "Mobile-first UX"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://www.remitly.com/gb/en/",
    affiliateLink: "https://www.remitly.com/gb/en/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "Remitly", "send money"] },
  },
  {
    id: "remittance-worldremit",
    slug: "worldremit-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK"],
    providerMark: "WR",
    providerName: "WorldRemit",
    title: "WorldRemit",
    subtitle: "Send money to 130+ countries via bank transfer, cash pickup, mobile money, or airtime top-up. Competitive rates and 24/7 support.",
    metrics: [
      { label: "Countries", value: "130+" },
      { label: "Payout options", value: "Bank, cash, mobile money" },
      { label: "Speed", value: "Minutes (mobile money)" },
    ],
    bestFor: ["Africa corridors", "Mobile money", "Cash pickup"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://www.worldremit.com/",
    affiliateLink: "https://www.worldremit.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "WorldRemit", "Africa"] },
  },
  {
    id: "remittance-paysend",
    slug: "paysend-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK"],
    providerMark: "PS",
    providerName: "Paysend",
    title: "Paysend",
    subtitle: "Flat-fee international money transfers to 170+ countries. EUR 1.50 flat fee regardless of amount sent — best for larger transfers.",
    metrics: [
      { label: "Fee", value: "EUR 1.50 flat" },
      { label: "Countries", value: "170+" },
      { label: "Speed", value: "Minutes" },
    ],
    bestFor: ["Large transfers", "Flat fee", "Fast delivery"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://paysend.com",
    affiliateLink: "https://paysend.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "flat fee", "Paysend"] },
  },
  {
    id: "remittance-sendwave",
    slug: "sendwave-remittance",
    category: "remittance",
    countryCodes: ["UK", "EU"],
    providerMark: "SW",
    providerName: "Sendwave",
    title: "Sendwave",
    subtitle: "Fee-free transfers to Ghana, Kenya, Nigeria, Senegal, Tanzania, Uganda, and more. Mobile-first app with instant delivery to M-Pesa and mobile wallets.",
    metrics: [
      { label: "Fee", value: "0% (Africa corridors)" },
      { label: "Speed", value: "Instant to M-Pesa" },
      { label: "Countries", value: "Africa & Asia" },
    ],
    bestFor: ["Africa transfers", "Zero fee", "Instant mobile money"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://www.sendwave.com/",
    affiliateLink: "https://www.sendwave.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "Africa", "free transfer"] },
  },

  // ═══════════════════════════════════════════════════
  // TRAVEL CARDS (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "travel-revolut-premium",
    slug: "revolut-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Premium Travel Card",
    subtitle: "The go-to travel card for Europeans. No FX fees, free ATM withdrawals up to EUR 400/month, travel insurance included, and airport lounge access.",
    metrics: [
      { label: "FX fee", value: "0% (weekdays)" },
      { label: "ATM free/month", value: "EUR 400 (Premium)" },
      { label: "Travel insurance", value: "Included" },
    ],
    bestFor: ["Frequent travellers", "Lounge access", "Insurance included"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://www.revolut.com/cards/",
    affiliateLink: "https://www.revolut.com/our-pricing-plans/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "no FX fee", "airport lounge"] },
  },
  {
    id: "travel-wise-card",
    slug: "wise-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Travel Card",
    subtitle: "Hold and spend in 40+ currencies. Low FX fees and free ATM withdrawals up to EUR 200/month. Accepted anywhere Mastercard works.",
    metrics: [
      { label: "FX fee", value: "0.35% – 2%" },
      { label: "ATM free/month", value: "EUR 200" },
      { label: "Currencies", value: "40+" },
    ],
    bestFor: ["Transparent fees", "40+ currencies", "Freelancers abroad"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://wise.com/gb/card/",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676432T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: true, affiliate: true, isPartner: true, searchTags: ["travel card", "Wise", "multi-currency"] },
  },
  {
    id: "travel-curve-card",
    slug: "curve-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Travel Card",
    subtitle: "Use any of your existing cards abroad with Curve's interbank-rate FX. Curve Pay (free tier) covers up to £250/mo at 0% FX; higher tiers raise the cap. Change card after purchase.",
    metrics: [
      // CAT.5 — Was "GBP 500/month" — Curve cut the free-tier FX
      // allowance from £500 to £250/mo in Dec 2025 (curve.com/blog).
      { label: "FX fee (Curve Pay)", value: "0% up to GBP 250/month" },
      { label: "Cards connected", value: "Unlimited" },
      { label: "Monthly fee", value: "Free (Curve X)" },
    ],
    bestFor: ["Existing cardholders", "Go Back in Time", "0% FX limit"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.curve.com/",
    affiliateLink: "https://www.curve.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "Curve", "no FX fee"] },
  },
  {
    id: "travel-starling-uk",
    slug: "starling-travel-card",
    category: "travel",
    countryCodes: ["UK"],
    providerMark: "SB",
    providerName: "Starling Bank",
    title: "Starling Travel (UK)",
    subtitle: "UK's top fee-free travel card. No fees on spending or ATM withdrawals abroad. Instant spending notifications and full account features.",
    metrics: [
      { label: "FX fee", value: "0%" },
      { label: "ATM fee abroad", value: "0%" },
      { label: "Monthly fee", value: "Free" },
    ],
    bestFor: ["UK residents", "No fees worldwide", "Full banking account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://www.starlingbank.com/current-account/",
    affiliateLink: "https://www.starlingbank.com/current-account/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["travel card", "UK", "no fees abroad"] },
  },
  {
    id: "travel-n26-you",
    slug: "n26-you-travel",
    category: "travel",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 You Travel Account",
    subtitle: "Premium N26 account with travel insurance, no foreign transaction fees, and worldwide ATM withdrawals. Includes medical and trip cancellation coverage.",
    metrics: [
      { label: "FX fee", value: "0%" },
      { label: "Monthly fee", value: "EUR 9.90" },
      { label: "Travel insurance", value: "Included" },
    ],
    bestFor: ["EU residents", "Travel insurance included", "Free ATMs worldwide"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "N26", "travel insurance"] },
  },

  // ═══════════════════════════════════════════════════
  // CASHBACK & REWARDS (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "cashback-curve-cash",
    slug: "curve-cashback",
    category: "cashback",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Cashback",
    subtitle: "Earn 1% cashback at up to 3 retailers of your choice with Curve X. Higher tiers unlock more retailers and unlimited cashback.",
    metrics: [
      { label: "Cashback rate", value: "1% at 3 retailers" },
      { label: "Monthly fee", value: "Free (Curve X)" },
      { label: "Retailers", value: "Chosen by you" },
    ],
    bestFor: ["Everyday spending", "Card consolidation", "Custom cashback"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://www.curve.com/",
    affiliateLink: "https://www.curve.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Curve"] },
  },
  {
    id: "cashback-revolut-ultra",
    slug: "revolut-cashback",
    category: "cashback",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Ultra Cashback",
    subtitle: "Up to 1% cashback on card spending with the Revolut Ultra plan. Also includes unlimited free ATMs, lounge access, and concierge service.",
    metrics: [
      { label: "Cashback", value: "Up to 1%" },
      { label: "Plan", value: "Ultra (EUR 45/month)" },
      { label: "ATM", value: "Unlimited free" },
    ],
    bestFor: ["Heavy spenders", "Premium perks", "Lounge + cashback combo"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://www.revolut.com/our-pricing-plans/",
    affiliateLink: "https://www.revolut.com/our-pricing-plans/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Revolut Ultra"] },
  },
  {
    id: "cashback-vivid-money",
    slug: "vivid-money-cashback",
    category: "cashback",
    countryCodes: ["DE", "ES", "FR", "IT"],
    providerMark: "VV",
    providerName: "Vivid Money",
    title: "Vivid Prime Cashback",
    subtitle: "Up to 10% cashback on partner brands and 0.4% on all other spending. One of the most generous cashback programs for EU customers.",
    metrics: [
      { label: "Cashback (partners)", value: "Up to 10%" },
      { label: "Cashback (all)", value: "0.4%" },
      { label: "Plan", value: "Prime (EUR 9.90/month)" },
    ],
    bestFor: ["Partner brand shoppers", "EU residents", "High cashback rates"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://vivid.money",
    affiliateLink: "https://vivid.money",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Vivid"] },
  },
  {
    id: "cashback-chase-uk",
    slug: "chase-uk-cashback",
    category: "cashback",
    countryCodes: ["UK"],
    providerMark: "CH",
    providerName: "Chase UK",
    title: "Chase UK 1% Cashback",
    subtitle: "1% cashback on all card spending for the first year, then on selected categories. No monthly fee and competitive savings rate.",
    metrics: [
      { label: "Cashback", value: "1% on all spending (year 1)" },
      { label: "Monthly fee", value: "Free" },
      { label: "Savings rate", value: "Up to 4.1% AER" },
    ],
    bestFor: ["UK residents", "No fee cashback", "Savings + cashback combo"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.chase.co.uk",
    affiliateLink: "https://www.chase.co.uk",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["cashback", "UK", "Chase"] },
  },

  // ═══════════════════════════════════════════════════
  // DIGITAL WALLETS (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "wallet-paypal",
    slug: "paypal-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "PP",
    providerName: "PayPal",
    title: "PayPal Wallet",
    subtitle: "The world's most widely accepted digital wallet. Send and receive money instantly, pay online at 30M+ merchants, and earn rewards.",
    metrics: [
      { label: "Merchants", value: "30M+ worldwide" },
      { label: "Personal send fee", value: "Free (within EU)" },
      { label: "Currencies", value: "25+" },
    ],
    bestFor: ["Online shopping", "Universal acceptance", "Buyer protection"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://www.paypal.com/uk/digital-wallet/",
    affiliateLink: "https://www.paypal.com/uk/digital-wallet/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["wallet", "PayPal", "online payments"] },
  },
  {
    id: "wallet-revolut",
    slug: "revolut-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Wallet",
    subtitle: "All-in-one financial super-app. Hold 36 currencies, invest in stocks and crypto, send money instantly, and earn savings interest.",
    metrics: [
      { label: "Currencies", value: "36" },
      { label: "Instant transfers", value: "Free between Revolut users" },
      { label: "Crypto", value: "Integrated" },
    ],
    bestFor: ["All-in-one finance", "Instant P2P", "Multi-currency holding"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://www.revolut.com/our-pricing-plans/",
    affiliateLink: "https://www.revolut.com/our-pricing-plans/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["wallet", "Revolut", "super-app"] },
  },
  {
    id: "wallet-skrill",
    slug: "skrill-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "SK",
    providerName: "Skrill",
    title: "Skrill Digital Wallet",
    subtitle: "Digital wallet trusted by online gamblers, traders, and international freelancers. Send money to 40+ currencies and 120+ countries.",
    metrics: [
      { label: "Currencies", value: "40+" },
      { label: "Countries", value: "120+" },
      { label: "Monthly fee", value: "EUR 0" },
    ],
    bestFor: ["Online gaming", "Trading deposits", "Low minimum"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://www.skrill.com",
    affiliateLink: "https://www.skrill.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["wallet", "Skrill", "gambling", "trading"] },
  },
  {
    id: "wallet-wise",
    slug: "wise-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Multi-Currency Account",
    subtitle: "Hold 40+ currencies in one account with local bank details for GBP, EUR, USD, AUD, and more. Ideal for freelancers and international workers.",
    metrics: [
      { label: "Currencies held", value: "40+" },
      { label: "Local bank details", value: "EUR, GBP, USD, AUD, NZD" },
      { label: "Monthly fee", value: "Free" },
    ],
    bestFor: ["Freelancers", "International workers", "Multi-currency needs"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://wise.com/gb/multi-currency-account/",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676432T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: true, affiliate: true, isPartner: true, searchTags: ["wallet", "Wise", "multi-currency"] },
  },

  // ═══════════════════════════════════════════════════
  // PAYROLL & INVOICING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "payroll-deel",
    slug: "deel-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "DL",
    providerName: "Deel",
    title: "Deel Global Payroll",
    subtitle: "Hire and pay employees and contractors in 150+ countries with full local compliance. Legal entities, payroll, and HR in one platform.",
    metrics: [
      { label: "Countries", value: "150+" },
      { label: "Contractor", value: "From USD 49/month" },
      { label: "EOR", value: "From USD 599/month" },
    ],
    bestFor: ["Remote teams", "Global hiring", "Contractor management"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://www.deel.com/payroll/",
    affiliateLink: "https://www.deel.com/payroll/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["payroll", "remote work", "global hiring"] },
  },
  {
    id: "payroll-remote",
    slug: "remote-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "RM",
    providerName: "Remote",
    title: "Remote Global HR",
    subtitle: "Employer of Record and payroll platform for distributed teams. 100% owned local entities in 75+ countries for compliant international hiring.",
    metrics: [
      { label: "EOR countries", value: "75+" },
      { label: "Contractor plan", value: "USD 29/month" },
      { label: "EOR pricing", value: "From USD 599/month" },
    ],
    bestFor: ["Employer of Record", "Compliance-first", "75+ countries"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://remote.com/payroll/",
    affiliateLink: "https://remote.com/payroll/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["payroll", "EOR", "remote hiring"] },
  },
  {
    id: "payroll-qonto",
    slug: "qonto-payroll",
    category: "payroll",
    countryCodes: ["FR", "DE", "IT", "ES"],
    providerMark: "QT",
    providerName: "Qonto",
    title: "Qonto Business Finance",
    subtitle: "Southern European business bank with built-in invoicing, expense management, and payroll integration. Used by 450,000+ SMEs.",
    metrics: [
      { label: "Monthly fee", value: "EUR 9 (Solo)" },
      { label: "Countries", value: "FR, DE, IT, ES" },
      { label: "Invoicing", value: "Included" },
    ],
    bestFor: ["Southern Europe SMEs", "Invoicing + banking", "Freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://qonto.com/",
    affiliateLink: "https://qonto.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["payroll", "invoicing", "Qonto", "SME"] },
  },
  {
    id: "payroll-wise-business",
    slug: "wise-business-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise Business",
    title: "Wise Business Payments",
    subtitle: "Pay international contractors and suppliers in 40+ currencies at the mid-market rate. Batch payments save time for payroll runs.",
    metrics: [
      { label: "Fee", value: "From 0.35%" },
      { label: "Currencies", value: "40+" },
      { label: "Batch payments", value: "Yes" },
    ],
    bestFor: ["International payroll", "Contractor payments", "Batch payments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://wise.com/gb/business/payroll/",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C127676432T",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: true, affiliate: true, isPartner: true, searchTags: ["payroll", "international payments", "Wise Business"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX & ACCOUNTING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-taxfix-de",
    slug: "taxfix-germany",
    category: "tax",
    countryCodes: ["DE"],
    providerMark: "TF",
    providerName: "Taxfix",
    title: "Taxfix (Germany)",
    subtitle: "Germany's most popular tax app. File your German tax return in 22 minutes on average. Mobile-first, no tax knowledge required.",
    metrics: [
      { label: "Filing fee", value: "EUR 39.99" },
      { label: "Average return", value: "EUR 1,095 refund" },
      { label: "Filing time", value: "22 minutes" },
    ],
    bestFor: ["German residents", "Fast filing", "First-timers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://taxfix.de/",
    affiliateLink: "https://taxfix.de/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Germany", "Steuererklärung"] },
  },
  {
    id: "tax-taxscouts-uk",
    slug: "taxscouts-uk",
    category: "tax",
    countryCodes: ["UK"],
    providerMark: "TS",
    providerName: "TaxScouts",
    title: "TaxScouts UK",
    subtitle: "UK self-assessment tax returns filed by a real accountant for a flat fee. Simple, fast, and stress-free. Covers freelancers, landlords, and investors.",
    metrics: [
      { label: "Filing fee", value: "GBP 169 flat" },
      { label: "Done by", value: "Real accountant" },
      { label: "Turnaround", value: "3–5 days" },
    ],
    bestFor: ["UK freelancers", "Landlords", "HMRC self-assessment"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://taxscouts.com/services/",
    affiliateLink: "https://taxscouts.com/services/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "UK", "self-assessment", "accountant"] },
  },
  {
    id: "tax-wundertax-de",
    slug: "wundertax-germany",
    category: "tax",
    countryCodes: ["DE"],
    providerMark: "WT",
    providerName: "Wundertax",
    title: "Wundertax (Germany)",
    subtitle: "German tax return app with a step-by-step interview. Optimises your deductions automatically. Includes salary, freelance, and investment income.",
    metrics: [
      { label: "Filing fee", value: "EUR 34.99" },
      { label: "Refund optimisation", value: "Automatic" },
      { label: "Support", value: "Chat + email" },
    ],
    bestFor: ["Germany employed workers", "Investment income", "Automatic deductions"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://www.wundertax.de",
    affiliateLink: "https://www.wundertax.de",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Germany", "Wundertax"] },
  },
  {
    id: "tax-sorted-es",
    slug: "sorted-spain-tax",
    category: "tax",
    countryCodes: ["ES"],
    providerMark: "SR",
    providerName: "Sorted",
    title: "Sorted Spain",
    subtitle: "Spanish income tax declaration service for expats and freelancers. English-speaking advisors handle your full declaración de la renta.",
    metrics: [
      { label: "Filing fee", value: "EUR 99+" },
      { label: "Language", value: "English + Spanish" },
      { label: "Support", value: "Dedicated advisor" },
    ],
    bestFor: ["Spain expats", "English speakers", "Autónomo freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://sorted.es/declaracion-renta/",
    affiliateLink: "https://sorted.es/declaracion-renta/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Spain", "expat", "renta"] },
  },

  // ═══════════════════════════════════════════════════
  // EXPENSE TRACKING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "expense-pleo",
    slug: "pleo-expense",
    category: "expense",
    countryCodes: ["EU", "UK"],
    providerMark: "PL",
    providerName: "Pleo",
    title: "Pleo Business Expenses",
    subtitle: "Smart company cards and expense management for European businesses. Employees get pre-funded cards; finance teams get real-time visibility.",
    metrics: [
      { label: "Per user/month", value: "EUR 9 (Starter)" },
      { label: "Receipt capture", value: "Automatic" },
      { label: "Integrations", value: "Xero, QuickBooks, NetSuite" },
    ],
    bestFor: ["SME teams", "Real-time visibility", "Card + software"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://www.pleo.io/en/features/",
    affiliateLink: "https://www.pleo.io/en/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "company cards", "Pleo"] },
  },
  {
    id: "expense-spendesk",
    slug: "spendesk-expense",
    category: "expense",
    countryCodes: ["FR", "DE", "UK", "ES"],
    providerMark: "SK",
    providerName: "Spendesk",
    title: "Spendesk",
    subtitle: "All-in-one spend management platform for finance teams. Includes corporate cards, invoice processing, expense claims, and accounting automation.",
    metrics: [
      { label: "Pricing", value: "Custom (per company)" },
      { label: "Features", value: "Cards, invoices, expenses" },
      { label: "Accounting", value: "Auto-sync" },
    ],
    bestFor: ["Mid-market companies", "Full spend control", "Invoice automation"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.spendesk.com/en/features/",
    affiliateLink: "https://www.spendesk.com/en/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "spend management", "Spendesk"] },
  },
  {
    id: "expense-moss",
    slug: "moss-expense",
    category: "expense",
    countryCodes: ["DE", "AT", "NL", "UK"],
    providerMark: "MS",
    providerName: "Moss",
    title: "Moss",
    subtitle: "German-built corporate spend platform with virtual and physical cards, automated receipt matching, and real-time budget tracking.",
    metrics: [
      { label: "Cards", value: "Virtual + physical" },
      { label: "Receipt matching", value: "Automated" },
      { label: "Markets", value: "DE, AT, NL, UK" },
    ],
    bestFor: ["DACH companies", "Virtual cards", "Budget control"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://getmoss.com/features/",
    affiliateLink: "https://getmoss.com/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "corporate cards", "Germany", "Moss"] },
  },
  {
    id: "expense-soldo",
    slug: "soldo-expense",
    category: "expense",
    countryCodes: ["UK", "IT", "DE", "FR", "ES"],
    providerMark: "SL",
    providerName: "Soldo",
    title: "Soldo",
    subtitle: "Multi-user expense platform with prepaid Mastercard cards for every team member. Set spending limits and rules per card or team.",
    metrics: [
      { label: "Plan", value: "From GBP 21/month" },
      { label: "Cards", value: "Prepaid Mastercard" },
      { label: "Rules", value: "Per-card spending limits" },
    ],
    bestFor: ["Team spending control", "Prepaid cards", "UK/Italy businesses"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://www.soldo.com/",
    affiliateLink: "https://www.soldo.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "prepaid cards", "Soldo"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand crypto (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "crypto-kraken",
    slug: "kraken-crypto",
    category: "crypto",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "KR",
    providerName: "Kraken",
    title: "Kraken",
    subtitle: "One of the world's most trusted crypto exchanges. 200+ cryptocurrencies, competitive fees, and strong security record since 2011.",
    metrics: [
      { label: "Maker fee", value: "0.16%" },
      { label: "Taker fee", value: "0.26%" },
      { label: "Assets", value: "200+" },
    ],
    bestFor: ["Security-first", "Advanced traders", "EUR deposits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://www.kraken.com/features/fee-schedule",
    affiliateLink: "https://www.kraken.com/features/fee-schedule",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "exchange", "Kraken"] },
  },
  {
    id: "crypto-binance",
    slug: "binance-crypto",
    category: "crypto",
    countryCodes: ["EU"],
    providerMark: "BN",
    providerName: "Binance",
    title: "Binance",
    subtitle: "World's largest crypto exchange by volume. 350+ trading pairs, spot and futures trading, earn products, and low fees.",
    metrics: [
      { label: "Trading fee", value: "0.10% (spot)" },
      { label: "Assets", value: "350+" },
      { label: "Volume", value: "#1 worldwide" },
    ],
    bestFor: ["Advanced traders", "High volume", "Wide asset selection"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://www.binance.com/en/trade/BTC_EUR",
    affiliateLink: "https://www.binance.com/en/trade/BTC_EUR",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "exchange", "Binance"] },
  },
  {
    id: "crypto-bitpanda",
    slug: "bitpanda-crypto",
    category: "crypto",
    countryCodes: ["AT", "DE", "CH", "ES", "FR", "IT"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda",
    subtitle: "Austrian crypto and investment platform trusted by 4M+ Europeans. Buy crypto, stocks, ETFs, and precious metals in one regulated app.",
    metrics: [
      { label: "Fee", value: "1.49% (Bitpanda)" },
      { label: "Assets", value: "Crypto + stocks + ETFs" },
      { label: "Regulation", value: "BaFin (EU)" },
    ],
    bestFor: ["EU-regulated", "Multi-asset (crypto+stocks)", "Beginners"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.bitpanda.com",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C2906129162T",
    updatedAt: "2026-06-19T00:00:00Z",
    attributes: { monetized: true, affiliate: true, isPartner: true, availability: "eu_wide", searchTags: ["crypto", "Austrian exchange", "Bitpanda"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand kids (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "kids-gohenry",
    slug: "gohenry-kids",
    category: "kids",
    countryCodes: ["UK", "EU"],
    providerMark: "GH",
    providerName: "GoHenry",
    title: "GoHenry",
    subtitle: "Pocket money card and app for kids aged 6–18. Parents set spending limits, chores, and goals. Custom card designs and financial education built in.",
    metrics: [
      { label: "Monthly fee", value: "GBP 3.99/child" },
      { label: "Age range", value: "6–18" },
      { label: "Parental controls", value: "Full" },
    ],
    bestFor: ["Ages 6–18", "Parental control", "Financial education"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.97,
    providerWebsiteUrl: "https://www.gohenry.com/uk/features",
    affiliateLink: "https://www.financeads.net/tc.php?t=83248C401682562T",
    updatedAt: "2026-05-22T00:00:00Z",
    attributes: { availability: "eu_wide", monetized: true, affiliate: true, isPartner: true, dataSource: "affiliate", confidenceScore: 0.98, searchTags: ["kids", "pocket money", "family finance"] },
  },
  {
    id: "kids-revolut-junior",
    slug: "revolut-junior-kids",
    category: "kids",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut <18",
    subtitle: "Free junior account for ages 6–17, linked to a parent's Revolut account. Real Visa card, spending controls, and savings goals.",
    metrics: [
      { label: "Monthly fee", value: "Free (with parent plan)" },
      { label: "Age range", value: "6–17" },
      { label: "Card", value: "Visa debit" },
    ],
    bestFor: ["Revolut families", "Free junior card", "Teens"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.revolut.com/",
    affiliateLink: "https://www.revolut.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "junior account", "teens"] },
  },
  {
    id: "kids-greenlight",
    slug: "greenlight-kids",
    category: "kids",
    // CAT.9 — Greenlight is US-only. The .com link doesn't lead to a
    // UK/EU product. Restricted country codes accordingly so European
    // visitors don't see an offer they can't open.
    countryCodes: ["US"],
    providerMark: "GL",
    providerName: "Greenlight",
    title: "Greenlight Kids Card",
    subtitle: "US-only kids fintech (greenlight.com). Debit card for children with invest, save, and earn features built into a family app. Not available in Europe.",
    metrics: [
      { label: "Monthly fee", value: "GBP 4.99/family" },
      { label: "Kids per plan", value: "Up to 5" },
      { label: "Features", value: "Save, invest, give" },
    ],
    bestFor: ["Financial literacy", "Multiple kids", "Investing for kids"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://greenlight.com/features/",
    affiliateLink: "https://greenlight.com/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "family finance", "investing for kids"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand budgeting (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "budgeting-emma",
    slug: "emma-budgeting",
    category: "budgeting",
    countryCodes: ["UK", "EU"],
    providerMark: "EM",
    providerName: "Emma",
    title: "Emma Money App",
    subtitle: "Open banking budgeting app that connects all your banks in one view. Tracks subscriptions, spots waste, and shows your real net worth.",
    metrics: [
      { label: "Monthly fee", value: "Free (basic)" },
      { label: "Banks connected", value: "50+" },
      { label: "Subscription tracking", value: "Yes" },
    ],
    bestFor: ["Multi-bank households", "Subscription auditing", "Net worth tracking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://emma-app.com/",
    affiliateLink: "https://emma-app.com/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["budgeting", "open banking", "Emma"] },
  },
  {
    id: "budgeting-plum",
    slug: "plum-budgeting",
    category: "budgeting",
    countryCodes: ["UK", "EU"],
    providerMark: "PM",
    providerName: "Plum",
    title: "Plum",
    subtitle: "AI-powered savings and budgeting app. Automatically sets aside small amounts based on your spending patterns to grow your savings effortlessly.",
    metrics: [
      // CAT.5 — "Interest (Pro): Up to 4.9% AER" removed. The Pro
      // tier was discontinued by Plum on 7 July 2025; the AER never
      // hit 4.9% even before that (Cash ISA was capped at 4.32%
      // including a first-year bonus, Easy-Access at 3.63%). Current
      // rates pulled from withplum.com (May 2026).
      { label: "Monthly fee", value: "Free (basic) · From £2.99 (Premium)" },
      { label: "Auto-save", value: "AI-powered" },
      { label: "Cash ISA", value: "Up to 4.32% (year-1 bonus rate)" },
      { label: "Easy-access", value: "Up to 3.63% AER" },
    ],
    bestFor: ["Automated saving", "Beginners", "Spending analytics"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://withplum.com/features/",
    affiliateLink: "https://withplum.com/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["budgeting", "AI savings", "Plum"] },
  },
  {
    id: "budgeting-ynab",
    slug: "ynab-budgeting",
    category: "budgeting",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "YN",
    providerName: "YNAB",
    title: "YNAB (You Need A Budget)",
    subtitle: "Rule-based budgeting system that gives every euro a job. Proven to save new users an average of USD 600 in their first 2 months.",
    metrics: [
      { label: "Monthly fee", value: "USD 14.99" },
      { label: "Method", value: "Zero-based budgeting" },
      { label: "Free trial", value: "34 days" },
    ],
    bestFor: ["Serious budgeters", "Debt payoff", "Zero-based method"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://www.youneedabudget.com/features/",
    affiliateLink: "https://www.youneedabudget.com/features/",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["budgeting", "YNAB", "zero-based"] },
  },

  // ═══════════════════════════════════════════════════
  // INSURANCE — UK / NL / PT coverage fill
  // ═══════════════════════════════════════════════════
  {
    id: "insurance-aviva-uk",
    slug: "aviva-uk-insurance",
    category: "insurance",
    countryCodes: ["UK"],
    providerMark: "AV",
    providerName: "Aviva",
    title: "Aviva Insurance",
    subtitle: "One of the UK's largest insurers covering home, car, life, and health. Strong FCA-regulated claims service with app-based policy management.",
    metrics: [
      { label: "Products", value: "Car, home, life, health" },
      { label: "FCA regulated", value: "Yes" },
      { label: "Claims", value: "Online and phone" },
    ],
    bestFor: ["UK residents", "Multi-line cover", "Established insurer"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://www.aviva.co.uk/insurance/",
    affiliateLink: "https://www.aviva.co.uk/insurance/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", insuranceType: "auto", searchTags: ["insurance", "UK", "Aviva", "car", "home"] },
  },
  {
    id: "insurance-allianz-direct-nl",
    slug: "allianz-direct-nl",
    category: "insurance",
    countryCodes: ["NL"],
    providerMark: "AZ",
    providerName: "Allianz Direct",
    title: "Allianz Direct NL",
    subtitle: "Digital-first Allianz car and home insurance for the Netherlands. Fast online quote, strong claims backing, and competitive premiums.",
    metrics: [
      { label: "Products", value: "Auto, home" },
      { label: "Quote", value: "Online in minutes" },
      { label: "Backing", value: "Allianz Group" },
    ],
    bestFor: ["Netherlands residents", "Car insurance", "Digital quote"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://www.allianzdirect.nl/autoverzekering/",
    affiliateLink: "https://www.allianzdirect.nl/autoverzekering/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", insuranceType: "auto", searchTags: ["insurance", "Netherlands", "Allianz Direct", "auto"] },
  },
  {
    id: "insurance-lemonade-nl",
    slug: "lemonade-nl-insurance",
    category: "insurance",
    countryCodes: ["NL", "FR", "DE"],
    providerMark: "LM",
    providerName: "Lemonade",
    title: "Lemonade Home Insurance",
    subtitle: "AI-powered renters and home insurance with instant quotes and fast claims. Flat monthly fee; unused premiums go to charity.",
    metrics: [
      { label: "Monthly from", value: "EUR 5" },
      { label: "Claims", value: "AI-powered, minutes" },
      { label: "Giveback", value: "Unused premiums donated" },
    ],
    bestFor: ["Renters", "Fast claims", "Digital-first"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://www.lemonade.com",
    affiliateLink: "https://www.lemonade.com",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "regional", insuranceType: "health", searchTags: ["insurance", "Netherlands", "Lemonade", "renters", "home"] },
  },
  {
    id: "insurance-fidelidade-pt",
    slug: "fidelidade-portugal-insurance",
    category: "insurance",
    countryCodes: ["PT"],
    providerMark: "FD",
    providerName: "Fidelidade",
    title: "Fidelidade Insurance",
    subtitle: "Portugal's largest insurer with broad coverage across car, home, health, and life. Strong national claims network and digital policy management.",
    metrics: [
      { label: "Products", value: "Auto, home, health, life" },
      { label: "Network", value: "Nationwide PT" },
      { label: "Digital app", value: "Yes" },
    ],
    bestFor: ["Portugal residents", "Multi-line cover", "Leading local insurer"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://www.fidelidade.pt",
    affiliateLink: "https://www.fidelidade.pt",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", insuranceType: "auto", searchTags: ["insurance", "Portugal", "Fidelidade", "car", "home"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — Germany (fill to 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-steuergo-de",
    slug: "steuergo-germany",
    category: "tax",
    countryCodes: ["DE"],
    providerMark: "SG",
    providerName: "Steuergo",
    title: "Steuergo",
    subtitle: "German online tax return with step-by-step interview. Detects forgotten deductions automatically and optimises your refund before filing with ELSTER.",
    metrics: [
      { label: "Filing fee", value: "EUR 29.95" },
      { label: "Refund detection", value: "Automatic" },
      { label: "ELSTER sync", value: "Yes" },
    ],
    bestFor: ["Employees", "Deduction optimisation", "Fast ELSTER filing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://www.steuergo.de/",
    affiliateLink: "https://www.steuergo.de/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Germany", "Steuergo", "ELSTER", "Steuererklärung"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — Spain (fill to 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-taxfix-es",
    slug: "taxfix-spain",
    category: "tax",
    countryCodes: ["ES"],
    providerMark: "TF",
    providerName: "Taxfix",
    title: "Taxfix Spain",
    subtitle: "Mobile-first tax return app for Spain. File your declaración de la renta in minutes with a guided interview. No prior tax knowledge needed.",
    metrics: [
      { label: "Filing fee", value: "EUR 39.99" },
      { label: "Filing time", value: "~20 minutes" },
      { label: "Support", value: "In-app chat" },
    ],
    bestFor: ["Spanish residents", "Employed workers", "Fast AEAT filing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://taxfix.es/declaracion-renta/",
    affiliateLink: "https://taxfix.es/declaracion-renta/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Spain", "Taxfix", "renta", "AEAT"] },
  },
  {
    id: "tax-taxdown-es",
    slug: "taxdown-spain",
    category: "tax",
    countryCodes: ["ES"],
    providerMark: "TD",
    providerName: "TaxDown",
    title: "TaxDown Spain",
    subtitle: "AI-powered Spanish tax filing that finds deductions you didn't know about. Reviewed by a certified gestor before AEAT submission.",
    metrics: [
      { label: "Filing fee", value: "EUR 35" },
      { label: "AI deductions", value: "Yes" },
      { label: "Gestor review", value: "Included" },
    ],
    bestFor: ["Spain self-employed", "Deduction maximisation", "Expert review"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://taxdown.es/",
    affiliateLink: "https://taxdown.es/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Spain", "TaxDown", "autónomo", "renta"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — UK (fill to 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-gosimpletax-uk",
    slug: "gosimpletax-uk",
    category: "tax",
    countryCodes: ["UK"],
    providerMark: "GS",
    providerName: "GoSimpleTax",
    title: "GoSimpleTax",
    subtitle: "UK self-assessment software that calculates your tax bill, spots errors, and files directly to HMRC. Flat annual fee with no per-filing charges.",
    metrics: [
      { label: "Annual fee", value: "GBP 54.99" },
      { label: "HMRC integration", value: "Direct filing" },
      { label: "Error checking", value: "Built-in" },
    ],
    bestFor: ["UK self-assessment", "Freelancers", "Landlords"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://www.gosimpletax.com/",
    affiliateLink: "https://www.gosimpletax.com/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "UK", "GoSimpleTax", "self-assessment", "HMRC"] },
  },
  {
    id: "tax-taxcalc-uk",
    slug: "taxcalc-uk",
    category: "tax",
    countryCodes: ["UK"],
    providerMark: "TC",
    providerName: "TaxCalc",
    title: "TaxCalc Individual",
    subtitle: "HMRC-approved self-assessment software trusted by over 150,000 UK taxpayers. Handles complex cases including capital gains, rental income, and foreign income.",
    metrics: [
      { label: "Annual fee", value: "GBP 49.99" },
      { label: "HMRC approved", value: "Yes" },
      { label: "Complex cases", value: "CGT, rental, foreign income" },
    ],
    bestFor: ["Investors", "Property landlords", "Complex tax situations"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://taxcalc.com",
    affiliateLink: "https://taxcalc.com",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "UK", "TaxCalc", "self-assessment", "capital gains"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — Italy (0 → 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-fiscozen-it",
    slug: "fiscozen-italy",
    category: "tax",
    countryCodes: ["IT"],
    providerMark: "FZ",
    providerName: "Fiscozen",
    title: "Fiscozen",
    subtitle: "Italian online tax service for freelancers and partita IVA holders. Handles dichiarazione dei redditi, F24 payments, and quarterly estimates in one app.",
    metrics: [
      { label: "Annual fee", value: "EUR 299 all-in" },
      { label: "Partita IVA", value: "Full management" },
      { label: "Commercialista", value: "Assigned to you" },
    ],
    bestFor: ["Italian freelancers", "Partita IVA", "Full tax management"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://www.fiscozen.it",
    affiliateLink: "https://www.fiscozen.it",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Italy", "Fiscozen", "partita IVA", "dichiarazione"] },
  },
  {
    id: "tax-keyfin-it",
    slug: "keyfin-italy",
    category: "tax",
    countryCodes: ["IT"],
    providerMark: "KF",
    providerName: "Keyfin",
    title: "Keyfin Italy",
    subtitle: "Digital commercialista service for employed workers and small businesses in Italy. Guided dichiarazione dei redditi with a human accountant verifying every return.",
    metrics: [
      { label: "Filing fee", value: "EUR 49 — 199" },
      { label: "Accountant review", value: "Yes" },
      { label: "Turnaround", value: "5 business days" },
    ],
    bestFor: ["Italy employed workers", "Small business", "Human review"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://www.keyfin.it/servizi/",
    affiliateLink: "https://www.keyfin.it/servizi/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Italy", "Keyfin", "commercialista", "redditi"] },
  },
  {
    id: "tax-730online-it",
    slug: "730online-italy",
    category: "tax",
    countryCodes: ["IT"],
    providerMark: "7O",
    providerName: "730 Online",
    title: "730 Online",
    subtitle: "Fast-track Italian 730 model filing for employees and pensioners. Upload your CU, answer a guided interview, and file directly to the Agenzia delle Entrate.",
    metrics: [
      { label: "Filing fee", value: "EUR 29.90" },
      { label: "Filing model", value: "Modello 730" },
      { label: "CU upload", value: "Automatic import" },
    ],
    bestFor: ["Italian employees", "Pensioners", "Quick 730 filing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://www.730online.it/",
    affiliateLink: "https://www.730online.it/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Italy", "730", "Agenzia Entrate", "dipendente"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — France (0 → 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-juste-fr",
    slug: "juste-france-tax",
    category: "tax",
    countryCodes: ["FR"],
    providerMark: "JU",
    providerName: "Juste",
    title: "Juste",
    subtitle: "French digital tax optimisation service. Analyses your situation, finds deductions you missed, and files your déclaration de revenus for a flat fee.",
    metrics: [
      { label: "Service fee", value: "EUR 49" },
      { label: "Deduction audit", value: "AI + accountant" },
      { label: "Filing", value: "Direct to DGFiP" },
    ],
    bestFor: ["French residents", "Missed deductions", "Digital filing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://juste.com/declaration-impots/",
    affiliateLink: "https://juste.com/declaration-impots/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "France", "Juste", "déclaration", "impôts"] },
  },
  {
    id: "tax-declareo-fr",
    slug: "declareo-france",
    category: "tax",
    countryCodes: ["FR"],
    providerMark: "DC",
    providerName: "Declareo",
    title: "Declareo",
    subtitle: "French tax declaration service for employed workers and freelancers. Accountant-checked return with a focus on commonly missed deductions.",
    metrics: [
      { label: "Filing fee", value: "EUR 39" },
      { label: "Accountant check", value: "Included" },
      { label: "Response time", value: "48 hours" },
    ],
    bestFor: ["French employed", "Auto-entrepreneurs", "Accountant-verified"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://declareo.fr/declaration-impots/",
    affiliateLink: "https://declareo.fr/declaration-impots/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "France", "Declareo", "auto-entrepreneur", "impôts"] },
  },
  {
    id: "tax-quelimpot-fr",
    slug: "quelimpot-france",
    category: "tax",
    countryCodes: ["FR"],
    providerMark: "QI",
    providerName: "Quelimpôt",
    title: "Quelimpôt",
    subtitle: "French tax simulation and optimisation platform. Model different deduction scenarios before filing to maximise your refund from the DGFiP.",
    metrics: [
      { label: "Simulation", value: "Free" },
      { label: "Full filing", value: "EUR 29" },
      { label: "Scenarios", value: "Unlimited before filing" },
    ],
    bestFor: ["Tax optimisation", "Scenario modelling", "Self-filers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://quelimpot.fr/declaration-impots/",
    affiliateLink: "https://quelimpot.fr/declaration-impots/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "France", "simulation", "impôts", "déductions"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — Netherlands (0 → 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-expatax-nl",
    slug: "expatax-netherlands",
    category: "tax",
    countryCodes: ["NL"],
    providerMark: "ET",
    providerName: "Expatax",
    title: "Expatax Netherlands",
    subtitle: "Dutch tax returns for expats and locals. English-speaking advisors handle the full aangifte inkomstenbelasting, including 30% ruling applications.",
    metrics: [
      { label: "From", value: "EUR 275" },
      { label: "30% ruling", value: "Yes" },
      { label: "Language", value: "English + Dutch" },
    ],
    bestFor: ["Netherlands expats", "30% ruling", "English support"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://www.expatax.nl/services/",
    affiliateLink: "https://www.expatax.nl/services/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Netherlands", "Expatax", "expat", "30% ruling"] },
  },
  {
    id: "tax-taxsavers-nl",
    slug: "taxsavers-netherlands",
    category: "tax",
    countryCodes: ["NL"],
    providerMark: "TS",
    providerName: "TaxSavers",
    title: "TaxSavers NL",
    subtitle: "Dutch income tax return specialists for individuals and freelancers. Online filing with a personal tax advisor assigned to maximise your belastingteruggaaf.",
    metrics: [
      { label: "From", value: "EUR 149" },
      { label: "Turnaround", value: "5 business days" },
      { label: "ZZP support", value: "Yes" },
    ],
    bestFor: ["Dutch freelancers (ZZP)", "Refund maximisation", "Online filing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://taxsavers.nl/services/",
    affiliateLink: "https://taxsavers.nl/services/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Netherlands", "TaxSavers", "ZZP", "belastingteruggaaf"] },
  },
  {
    id: "tax-bluetax-nl",
    slug: "bluetax-netherlands",
    category: "tax",
    countryCodes: ["NL"],
    providerMark: "BT",
    providerName: "BlueTax",
    title: "BlueTax NL",
    subtitle: "Online Dutch tax return service for employees, pensioners, and freelancers. Uses the Belastingdienst pre-fill data to speed up the aangifte process.",
    metrics: [
      { label: "From", value: "EUR 79" },
      { label: "Pre-filled data", value: "Belastingdienst" },
      { label: "Refund tracking", value: "Yes" },
    ],
    bestFor: ["Dutch employees", "Simple returns", "Fast turnaround"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://bluetax.nl/",
    affiliateLink: "https://bluetax.nl/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Netherlands", "BlueTax", "aangifte", "belasting"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX — Portugal (0 → 3)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-nhr-advisors-pt",
    slug: "nhr-advisors-portugal",
    category: "tax",
    countryCodes: ["PT"],
    providerMark: "NH",
    providerName: "NHR Advisors",
    title: "NHR Advisors Portugal",
    subtitle: "Portuguese tax advisory specialising in Non-Habitual Resident (NHR) status, IRS declarations, and expat tax planning. English-speaking team based in Lisbon.",
    metrics: [
      { label: "NHR application", value: "Full service" },
      { label: "IRS filing", value: "Annual" },
      { label: "Language", value: "English + Portuguese" },
    ],
    bestFor: ["Portugal expats", "NHR status", "Tax planning"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://nhr.pt/services/",
    affiliateLink: "https://nhr.pt/services/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Portugal", "NHR", "expat", "IRS"] },
  },
  {
    id: "tax-taxback-pt",
    slug: "taxback-portugal",
    category: "tax",
    countryCodes: ["PT"],
    providerMark: "TB",
    providerName: "Taxback Portugal",
    title: "Taxback Portugal",
    subtitle: "Portuguese IRS return and tax refund recovery service for residents and non-residents. Handles deductions for health, education, and rental income.",
    metrics: [
      { label: "Fee", value: "EUR 99 flat" },
      { label: "Deductions", value: "Health, education, rent" },
      { label: "Non-residents", value: "Yes" },
    ],
    bestFor: ["Portuguese residents", "Non-residents", "IRS refund recovery"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://www.taxback.com",
    affiliateLink: "https://www.taxback.com",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Portugal", "IRS", "refund", "deductions"] },
  },
  {
    id: "tax-contabilidade-pt",
    slug: "contabilidade-portugal",
    category: "tax",
    countryCodes: ["PT"],
    providerMark: "CP",
    providerName: "Contabilidade Online",
    title: "Contabilidade Online PT",
    subtitle: "Online accounting and tax service for Portuguese freelancers (recibos verdes) and small businesses. Monthly IRS and VAT handling with a certified contabilista.",
    metrics: [
      { label: "Monthly from", value: "EUR 29" },
      { label: "Recibos verdes", value: "Full management" },
      { label: "Contabilista", value: "Certified and assigned" },
    ],
    bestFor: ["Portugal freelancers", "Recibos verdes", "VAT management"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.75,
    providerWebsiteUrl: "https://www.contabilidadeonline.pt/servicos/",
    affiliateLink: "https://www.contabilidadeonline.pt/servicos/",
    updatedAt: "2026-05-12T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Portugal", "recibos verdes", "contabilista", "freelancer"] },
  },
];
