import type { MarketplaceOffer } from "@payn/types";

export const newCategoriesOffers: MarketplaceOffer[] = [

  // ═══════════════════════════════════════════════════
  // NEOBANKS (6 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "neobank-revolut-standard",
    slug: "revolut-neobank",
    category: "neobanks",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Standard",
    subtitle: "Europe's largest neobank. Multi-currency account, instant spending notifications, built-in budgeting, and fee-free spending in 150+ countries.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Currencies", value: "36+" },
      { label: "ATM limit", value: "EUR 200/month free" },
    ],
    bestFor: ["Multi-currency", "Travel", "Free account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.97,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["neobank", "digital bank", "multi-currency"] },
  },
  {
    id: "neobank-n26-standard",
    slug: "n26-neobank",
    category: "neobanks",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL", "BE"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Standard",
    subtitle: "German neobank with a clean mobile app, SEPA transfers, and a sleek Mastercard. One of the most trusted digital banks in Europe.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "ATM withdrawals", value: "3 free/month (EU)" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["German market", "Clean UX", "Full banking licence"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/en-eu/bank-account",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "digital bank", "Germany"] },
  },
  {
    id: "neobank-bunq-easy",
    slug: "bunq-neobank",
    category: "neobanks",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "BE", "AT"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Easy Bank",
    subtitle: "Dutch neobank known for sustainability focus, instant payment splits, and unique sub-accounts. Strong privacy defaults and no hidden fees.",
    metrics: [
      { label: "Monthly fee", value: "EUR 3.99" },
      { label: "Sub-accounts", value: "Up to 25" },
      { label: "Green card", value: "Tree planted per EUR 100 spent" },
    ],
    bestFor: ["Privacy-first", "Sub-accounts", "Sustainability"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/en/personal",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "sustainable bank", "Netherlands"] },
  },
  {
    id: "neobank-monzo-uk",
    slug: "monzo-neobank",
    category: "neobanks",
    countryCodes: ["UK"],
    providerMark: "MZ",
    providerName: "Monzo",
    title: "Monzo Personal",
    subtitle: "UK's leading neobank with real-time spending insights, salary sorter, pots, and a premium coral card. Full UK banking licence.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Overdraft", value: "From 19% EAR" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["UK residents", "Budgeting pots", "Spending insights"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://monzo.com",
    affiliateLink: "https://monzo.com/current-account",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["neobank", "UK bank", "digital bank"] },
  },
  {
    id: "neobank-starling-uk",
    slug: "starling-neobank",
    category: "neobanks",
    countryCodes: ["UK"],
    providerMark: "SB",
    providerName: "Starling Bank",
    title: "Starling Personal",
    subtitle: "Award-winning UK neobank with no monthly fees, connected card, and excellent customer service. Consistently top-rated by Which? and Trustpilot.",
    metrics: [
      { label: "Monthly fee", value: "Free" },
      { label: "Interest on balance", value: "Up to 3.25% AER" },
      { label: "FSCS protection", value: "GBP 85,000" },
    ],
    bestFor: ["No fees", "Interest on balance", "UK award winner"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://starlingbank.com",
    affiliateLink: "https://starlingbank.com/current-account",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["neobank", "UK bank", "Starling"] },
  },
  {
    id: "neobank-monese-eu",
    slug: "monese-neobank",
    category: "neobanks",
    countryCodes: ["EU", "UK"],
    providerMark: "MN",
    providerName: "Monese",
    title: "Monese Simple",
    subtitle: "No credit check required. Open an EU or UK account in minutes even without a local address. Ideal for expats and new arrivals.",
    metrics: [
      { label: "Monthly fee", value: "Free (Simple plan)" },
      { label: "Instant setup", value: "No address proof needed" },
      { label: "Currencies", value: "EUR + GBP" },
    ],
    bestFor: ["Expats", "No credit check", "New arrivals"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://monese.com",
    affiliateLink: "https://monese.com/eu/en",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["neobank", "expat bank", "no credit check"] },
  },

  // ═══════════════════════════════════════════════════
  // SAVINGS ACCOUNTS (6 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "savings-trade-republic",
    slug: "trade-republic-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL", "BE"],
    providerMark: "TR",
    providerName: "Trade Republic",
    title: "Trade Republic Savings",
    subtitle: "4% interest on uninvested cash with daily accrual. Backed by Deutsche Bank and BaFin regulated. No minimum deposit required.",
    metrics: [
      { label: "Interest rate", value: "4.0% per year" },
      { label: "Minimum deposit", value: "EUR 1" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["High yield", "No minimum", "Daily interest"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.96,
    providerWebsiteUrl: "https://traderepublic.com",
    affiliateLink: "https://traderepublic.com/en-eu/savings-account",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "high yield", "interest"] },
  },
  {
    id: "savings-raisin-eu",
    slug: "raisin-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT", "NL"],
    providerMark: "RS",
    providerName: "Raisin",
    title: "Raisin Savings Marketplace",
    subtitle: "Europe's leading deposit marketplace. Access savings accounts from 100+ European banks through one platform. Compare rates and switch instantly.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.5% per year" },
      { label: "Partner banks", value: "100+" },
      { label: "Deposit protection", value: "Up to EUR 100,000 per bank" },
    ],
    bestFor: ["Best rates in Europe", "Multiple banks", "EUR 1,000+ deposits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://raisin.com",
    affiliateLink: "https://raisin.com/savings",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "deposit", "best rates"] },
  },
  {
    id: "savings-revolut-savings",
    slug: "revolut-savings",
    category: "savings",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Savings Vault",
    subtitle: "Flexible savings pocket within your Revolut app. Earn competitive interest with instant access and no lock-in period.",
    metrics: [
      { label: "Interest rate", value: "Up to 3.49% (Metal)" },
      { label: "Access", value: "Instant" },
      { label: "Minimum", value: "EUR 1" },
    ],
    bestFor: ["Revolut users", "Instant access", "No lock-in"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/savings",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "revolut", "flexible"] },
  },
  {
    id: "savings-n26-savings",
    slug: "n26-savings",
    category: "savings",
    countryCodes: ["DE", "AT", "ES", "FR", "IT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 Savings",
    subtitle: "Savings account built into N26 banking app. Instant access, no fees, and backed by German deposit protection up to EUR 100,000.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.0% AER" },
      { label: "Access", value: "Instant" },
      { label: "Deposit protection", value: "EUR 100,000" },
    ],
    bestFor: ["N26 customers", "German deposit protection", "No fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/en-eu/bank-account/savings",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "N26", "Germany"] },
  },
  {
    id: "savings-lightyear",
    slug: "lightyear-savings",
    category: "savings",
    countryCodes: ["UK", "EU"],
    providerMark: "LY",
    providerName: "Lightyear",
    title: "Lightyear Cash Account",
    subtitle: "Earn competitive interest on idle cash while having access to stocks and ETFs in the same app. FCA regulated and FSCS protected.",
    metrics: [
      { label: "Interest rate", value: "Up to 5.1% (USD)" },
      { label: "EUR rate", value: "3.8% AER" },
      { label: "Protection", value: "GBP 85,000 FSCS" },
    ],
    bestFor: ["Investors", "Multi-currency cash", "UK/EU residents"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.77,
    providerWebsiteUrl: "https://lightyear.com",
    affiliateLink: "https://lightyear.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "cash account", "interest"] },
  },
  {
    id: "savings-vivid-prime",
    slug: "vivid-savings",
    category: "savings",
    countryCodes: ["DE", "FR", "ES", "IT"],
    providerMark: "VV",
    providerName: "Vivid Money",
    title: "Vivid Savings",
    subtitle: "Earn up to 4% interest on EUR savings through Vivid Prime. Access your funds any time with no minimum deposit.",
    metrics: [
      { label: "Interest rate", value: "Up to 4.0%" },
      { label: "Plan required", value: "Vivid Prime (EUR 9.90/month)" },
      { label: "Minimum", value: "EUR 1" },
    ],
    bestFor: ["Cashback + savings combo", "EU residents", "Vivid users"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.73,
    providerWebsiteUrl: "https://vivid.money",
    affiliateLink: "https://vivid.money/en/prime",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["savings", "Vivid", "interest"] },
  },

  // ═══════════════════════════════════════════════════
  // TRADING PLATFORMS (6 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "trading-trading212",
    slug: "trading212",
    category: "trading",
    countryCodes: ["UK", "DE", "FR", "ES", "IT", "PT", "NL", "AT"],
    providerMark: "T212",
    providerName: "Trading 212",
    title: "Trading 212 Invest",
    subtitle: "Zero-commission stock and ETF investing for European retail investors. Fractional shares from GBP 1. ISA available for UK users.",
    metrics: [
      { label: "Commission", value: "0%" },
      { label: "Markets", value: "3,000+ stocks & ETFs" },
      { label: "Minimum", value: "GBP/EUR 1" },
    ],
    bestFor: ["Zero commission", "Fractional shares", "ISA (UK)"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.94,
    providerWebsiteUrl: "https://trading212.com",
    affiliateLink: "https://trading212.com/invite/ref",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "stocks", "ETF", "zero commission"] },
  },
  {
    id: "trading-etoro",
    slug: "etoro-trading",
    category: "trading",
    countryCodes: ["EU", "UK"],
    providerMark: "ET",
    providerName: "eToro",
    title: "eToro Stock Trading",
    subtitle: "Social trading platform to buy real stocks, ETFs, and crypto. Copy top traders automatically. Used by 35 million investors worldwide.",
    metrics: [
      { label: "Commission", value: "0% on stocks" },
      { label: "Copy trading", value: "Yes" },
      { label: "Minimum deposit", value: "USD 50" },
    ],
    bestFor: ["Copy trading", "Beginners", "Social investing"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://etoro.com",
    affiliateLink: "https://etoro.com/trading/stocks",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "copy trading", "social investing"] },
  },
  {
    id: "trading-degiro",
    slug: "degiro-trading",
    category: "trading",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "PT", "BE", "AT"],
    providerMark: "DG",
    providerName: "DEGIRO",
    title: "DEGIRO",
    subtitle: "Low-cost European broker with access to 50+ stock exchanges worldwide. Trusted by 3 million investors across Europe.",
    metrics: [
      { label: "Stocks (EU)", value: "EUR 3.90 + 0.05% per order" },
      { label: "Markets", value: "50+ exchanges" },
      { label: "ETFs", value: "From EUR 0" },
    ],
    bestFor: ["Active traders", "EU markets", "Low fees"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://degiro.eu",
    affiliateLink: "https://degiro.eu/core/signup/full",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "broker", "stocks", "DEGIRO"] },
  },
  {
    id: "trading-xtb",
    slug: "xtb-trading",
    category: "trading",
    countryCodes: ["EU", "UK"],
    providerMark: "XTB",
    providerName: "XTB",
    title: "XTB",
    subtitle: "Listed broker with commission-free stock and ETF trading up to EUR 100,000/month. Award-winning xStation platform with advanced charting.",
    metrics: [
      { label: "Commission", value: "0% up to EUR 100k/month" },
      { label: "Instruments", value: "5,400+" },
      { label: "Platform", value: "xStation 5" },
    ],
    bestFor: ["Active traders", "Advanced tools", "High volume"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://xtb.com",
    affiliateLink: "https://xtb.com/en",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "broker", "CFD", "stocks"] },
  },
  {
    id: "trading-interactive-brokers",
    slug: "interactive-brokers-trading",
    category: "trading",
    countryCodes: ["EU", "UK"],
    providerMark: "IB",
    providerName: "Interactive Brokers",
    title: "IBKR Lite",
    subtitle: "Global broker trusted by professional and active traders. Access 150 markets in 33 countries. Competitive margin rates and comprehensive tools.",
    metrics: [
      { label: "Commission (US stocks)", value: "USD 0 (Lite)" },
      { label: "Markets", value: "150 in 33 countries" },
      { label: "Minimum deposit", value: "USD 0" },
    ],
    bestFor: ["Global markets", "Professional tools", "Margin trading"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://interactivebrokers.com",
    affiliateLink: "https://interactivebrokers.com/mkt/?src=googlechrome",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["trading", "global broker", "professional"] },
  },
  {
    id: "trading-scalable-capital",
    slug: "scalable-capital-trading",
    category: "trading",
    countryCodes: ["DE", "AT", "NL", "FR", "ES", "IT"],
    providerMark: "SC",
    providerName: "Scalable Capital",
    title: "Scalable Capital Broker",
    subtitle: "German fintech broker with flat-fee Prime subscription. Unlimited trades on XETRA and Gettex for EUR 4.99/month.",
    metrics: [
      { label: "Prime subscription", value: "EUR 4.99/month" },
      { label: "Trades (Prime)", value: "Unlimited" },
      { label: "Savings plans", value: "Yes, free" },
    ],
    bestFor: ["Active EU traders", "Savings plans", "German market"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://scalable.capital",
    affiliateLink: "https://scalable.capital/en/broker",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["trading", "German broker", "flat fee"] },
  },

  // ═══════════════════════════════════════════════════
  // BUY NOW PAY LATER (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "bnpl-klarna",
    slug: "klarna-bnpl",
    category: "bnpl",
    countryCodes: ["DE", "SE", "NO", "FI", "UK", "ES", "FR", "IT", "NL", "AT"],
    providerMark: "KL",
    providerName: "Klarna",
    title: "Klarna Pay Later",
    subtitle: "Europe's leading BNPL provider. Pay in 30 days or split into 3 instalments with no interest. Available at 500,000+ partner stores.",
    metrics: [
      { label: "Interest", value: "0% if paid on time" },
      { label: "Split options", value: "Pay in 30 days / 3 instalments" },
      { label: "Merchants", value: "500,000+" },
    ],
    bestFor: ["No interest", "Flexible instalments", "Wide acceptance"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://klarna.com",
    affiliateLink: "https://klarna.com/us/klarna-app",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "pay later", "instalments"] },
  },
  {
    id: "bnpl-scalapay",
    slug: "scalapay-bnpl",
    category: "bnpl",
    countryCodes: ["IT", "ES", "FR", "PT", "BE", "NL", "AT", "DE"],
    providerMark: "SP",
    providerName: "Scalapay",
    title: "Scalapay",
    subtitle: "Southern European BNPL leader. Split any purchase into 3 instalments with 0% interest. Strong fashion and lifestyle merchant network.",
    metrics: [
      { label: "Instalments", value: "3 × 0%" },
      { label: "Merchants", value: "8,000+ in Europe" },
      { label: "Approval", value: "Instant" },
    ],
    bestFor: ["Italy & Spain", "Fashion shopping", "0% instalments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://scalapay.com",
    affiliateLink: "https://scalapay.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "Italy", "Spain", "instalments"] },
  },
  {
    id: "bnpl-clearpay",
    slug: "clearpay-bnpl",
    category: "bnpl",
    countryCodes: ["UK"],
    providerMark: "CP",
    providerName: "Clearpay",
    title: "Clearpay",
    subtitle: "UK's top BNPL service (Afterpay's UK brand). Split purchases into 4 fortnightly payments with no interest if paid on time.",
    metrics: [
      { label: "Instalments", value: "4 × interest-free" },
      { label: "Payment frequency", value: "Fortnightly" },
      { label: "Late fee", value: "GBP 6 max" },
    ],
    bestFor: ["UK shoppers", "Fashion & beauty", "Fortnightly payments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://clearpay.co.uk",
    affiliateLink: "https://clearpay.co.uk",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["BNPL", "UK", "Afterpay", "instalments"] },
  },
  {
    id: "bnpl-alma",
    slug: "alma-bnpl",
    category: "bnpl",
    countryCodes: ["FR", "DE", "ES", "IT", "BE", "NL"],
    providerMark: "AL",
    providerName: "Alma",
    title: "Alma",
    subtitle: "French BNPL platform with 2, 3, or 4 instalment options. Focused on quality merchants in fashion, home, and electronics.",
    metrics: [
      { label: "Options", value: "2x, 3x, 4x" },
      { label: "Interest", value: "0% for buyer" },
      { label: "Merchants", value: "15,000+" },
    ],
    bestFor: ["France & EU", "Premium merchants", "Flexible splits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://getalma.eu",
    affiliateLink: "https://getalma.eu",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["BNPL", "France", "instalments"] },
  },
  {
    id: "bnpl-paypal-paylater",
    slug: "paypal-pay-later",
    category: "bnpl",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "PP",
    providerName: "PayPal",
    title: "PayPal Pay Later",
    subtitle: "Split PayPal purchases into 4 interest-free payments or 6 months of flexible monthly payments. Works everywhere PayPal is accepted.",
    metrics: [
      { label: "Option 1", value: "Pay in 4 × 0%" },
      { label: "Option 2", value: "6 months flexible" },
      { label: "Acceptance", value: "Everywhere PayPal works" },
    ],
    bestFor: ["Existing PayPal users", "Widest acceptance", "No new account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://paypal.com",
    affiliateLink: "https://paypal.com/webapps/mpp/pay-later",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["BNPL", "PayPal", "pay later"] },
  },

  // ═══════════════════════════════════════════════════
  // DEBIT CARDS (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "debit-revolut",
    slug: "revolut-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Debit Card",
    subtitle: "Multi-currency debit card with real interbank exchange rates. Spend in 150+ currencies with no hidden FX markup on weekdays.",
    metrics: [
      { label: "FX fee (weekday)", value: "0%" },
      { label: "ATM", value: "EUR 200/month free" },
      { label: "Monthly fee", value: "Free (Standard)" },
    ],
    bestFor: ["Multi-currency spending", "Travel", "Free plan"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/referral",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "multi-currency", "travel"] },
  },
  {
    id: "debit-wise",
    slug: "wise-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Debit Card",
    subtitle: "Multi-currency debit card linked to your Wise account. Spend in 40+ currencies at the mid-market rate with low transparent fees.",
    metrics: [
      { label: "FX fee", value: "0.35% – 2%" },
      { label: "Currencies", value: "40+" },
      { label: "ATM (free/month)", value: "GBP 200 / EUR 200" },
    ],
    bestFor: ["Transparent FX fees", "Multi-currency", "International freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/gb/card",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "Wise", "multi-currency"] },
  },
  {
    id: "debit-curve",
    slug: "curve-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Card",
    subtitle: "One card that connects all your existing cards. Spend in 150+ currencies at competitive rates, earn cashback, and switch transactions backwards.",
    metrics: [
      { label: "Monthly fee", value: "Free (Curve X)" },
      { label: "FX fee (weekday)", value: "0% up to GBP 500/month" },
      { label: "Cashback", value: "Up to 3 retailers" },
    ],
    bestFor: ["Card consolidation", "Cashback", "Go Back in Time feature"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://www.curve.com/join/payn",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "Curve", "cashback"] },
  },
  {
    id: "debit-bunq",
    slug: "bunq-debit-card",
    category: "debit",
    countryCodes: ["NL", "DE", "FR", "ES", "IT", "BE"],
    providerMark: "BQ",
    providerName: "bunq",
    title: "bunq Debit Card",
    subtitle: "Sleek Mastercard debit card with up to 25 sub-accounts and IBANs. Use abroad with low FX fees and instant payment splits.",
    metrics: [
      { label: "FX fee", value: "1.5%" },
      { label: "Sub-IBANs", value: "Up to 25" },
      { label: "Monthly fee", value: "EUR 3.99+" },
    ],
    bestFor: ["Sub-accounts", "Netherlands", "Privacy-focused"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://bunq.com",
    affiliateLink: "https://bunq.com/en/personal",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "bunq", "sub-accounts"] },
  },
  {
    id: "debit-wirex",
    slug: "wirex-debit-card",
    category: "debit",
    countryCodes: ["EU", "UK"],
    providerMark: "WX",
    providerName: "Wirex",
    title: "Wirex Debit Card",
    subtitle: "Crypto-friendly debit card that lets you spend BTC, ETH, and 150+ currencies. Earn crypto rewards on every card purchase.",
    metrics: [
      { label: "Cryptoback", value: "Up to 8% in WXT" },
      { label: "Currencies", value: "150+" },
      { label: "Monthly fee", value: "Free (Standard)" },
    ],
    bestFor: ["Crypto users", "Crypto rewards", "Multi-currency"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://wirexapp.com",
    affiliateLink: "https://wirexapp.com/en/card",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["debit card", "crypto card", "Wirex"] },
  },

  // ═══════════════════════════════════════════════════
  // REMITTANCE (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "remittance-wise",
    slug: "wise-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise International Transfer",
    subtitle: "Send money to 80+ countries at the mid-market exchange rate. Low transparent fees and fast delivery — often within hours.",
    metrics: [
      { label: "Fee", value: "From 0.35%" },
      { label: "Speed", value: "Same day / next day" },
      { label: "Countries", value: "80+" },
    ],
    bestFor: ["Transparent fees", "Fast delivery", "Mid-market rate"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.97,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/send-money",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "international transfer", "Wise"] },
  },
  {
    id: "remittance-remitly",
    slug: "remitly-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "RM",
    providerName: "Remitly",
    title: "Remitly",
    subtitle: "Specialist remittance app for sending money to Latin America, Asia, Africa, and Eastern Europe. Competitive rates for high-volume corridors.",
    metrics: [
      { label: "Speed", value: "Minutes (Express)" },
      { label: "Corridors", value: "170+ countries" },
      { label: "Promotions", value: "First transfer fee-free" },
    ],
    bestFor: ["Non-EU corridors", "Promotions", "Mobile-first UX"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://remitly.com",
    affiliateLink: "https://remitly.com/eu/en",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "Remitly", "send money"] },
  },
  {
    id: "remittance-worldremit",
    slug: "worldremit-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK"],
    providerMark: "WR",
    providerName: "WorldRemit",
    title: "WorldRemit",
    subtitle: "Send money to 130+ countries via bank transfer, cash pickup, mobile money, or airtime top-up. Competitive rates and 24/7 support.",
    metrics: [
      { label: "Countries", value: "130+" },
      { label: "Payout options", value: "Bank, cash, mobile money" },
      { label: "Speed", value: "Minutes (mobile money)" },
    ],
    bestFor: ["Africa corridors", "Mobile money", "Cash pickup"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://worldremit.com",
    affiliateLink: "https://worldremit.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "WorldRemit", "Africa"] },
  },
  {
    id: "remittance-paysend",
    slug: "paysend-remittance",
    category: "remittance",
    countryCodes: ["EU", "UK"],
    providerMark: "PS",
    providerName: "Paysend",
    title: "Paysend",
    subtitle: "Flat-fee international money transfers to 170+ countries. EUR 1.50 flat fee regardless of amount sent — best for larger transfers.",
    metrics: [
      { label: "Fee", value: "EUR 1.50 flat" },
      { label: "Countries", value: "170+" },
      { label: "Speed", value: "Minutes" },
    ],
    bestFor: ["Large transfers", "Flat fee", "Fast delivery"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://paysend.com",
    affiliateLink: "https://paysend.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "flat fee", "Paysend"] },
  },
  {
    id: "remittance-sendwave",
    slug: "sendwave-remittance",
    category: "remittance",
    countryCodes: ["UK", "EU"],
    providerMark: "SW",
    providerName: "Sendwave",
    title: "Sendwave",
    subtitle: "Fee-free transfers to Ghana, Kenya, Nigeria, Senegal, Tanzania, Uganda, and more. Mobile-first app with instant delivery to M-Pesa and mobile wallets.",
    metrics: [
      { label: "Fee", value: "0% (Africa corridors)" },
      { label: "Speed", value: "Instant to M-Pesa" },
      { label: "Countries", value: "Africa & Asia" },
    ],
    bestFor: ["Africa transfers", "Zero fee", "Instant mobile money"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.78,
    providerWebsiteUrl: "https://sendwave.com",
    affiliateLink: "https://sendwave.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["remittance", "Africa", "free transfer"] },
  },

  // ═══════════════════════════════════════════════════
  // TRAVEL CARDS (5 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "travel-revolut-premium",
    slug: "revolut-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Premium Travel Card",
    subtitle: "The go-to travel card for Europeans. No FX fees, free ATM withdrawals up to EUR 400/month, travel insurance included, and airport lounge access.",
    metrics: [
      { label: "FX fee", value: "0% (weekdays)" },
      { label: "ATM free/month", value: "EUR 400 (Premium)" },
      { label: "Travel insurance", value: "Included" },
    ],
    bestFor: ["Frequent travellers", "Lounge access", "Insurance included"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.95,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/travel-card",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "no FX fee", "airport lounge"] },
  },
  {
    id: "travel-wise-card",
    slug: "wise-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Travel Card",
    subtitle: "Hold and spend in 40+ currencies. Low FX fees and free ATM withdrawals up to EUR 200/month. Accepted anywhere Mastercard works.",
    metrics: [
      { label: "FX fee", value: "0.35% – 2%" },
      { label: "ATM free/month", value: "EUR 200" },
      { label: "Currencies", value: "40+" },
    ],
    bestFor: ["Transparent fees", "40+ currencies", "Freelancers abroad"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/gb/card",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "Wise", "multi-currency"] },
  },
  {
    id: "travel-curve-card",
    slug: "curve-travel-card",
    category: "travel",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Travel Card",
    subtitle: "Use any of your existing cards abroad with Curve's interbank-rate FX. No FX markup up to GBP 500/month. Change card after purchase.",
    metrics: [
      { label: "FX fee", value: "0% up to GBP 500/month" },
      { label: "Cards connected", value: "Unlimited" },
      { label: "Monthly fee", value: "Free (Curve X)" },
    ],
    bestFor: ["Existing cardholders", "Go Back in Time", "0% FX limit"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/travel",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "Curve", "no FX fee"] },
  },
  {
    id: "travel-starling-uk",
    slug: "starling-travel-card",
    category: "travel",
    countryCodes: ["UK"],
    providerMark: "SB",
    providerName: "Starling Bank",
    title: "Starling Travel (UK)",
    subtitle: "UK's top fee-free travel card. No fees on spending or ATM withdrawals abroad. Instant spending notifications and full account features.",
    metrics: [
      { label: "FX fee", value: "0%" },
      { label: "ATM fee abroad", value: "0%" },
      { label: "Monthly fee", value: "Free" },
    ],
    bestFor: ["UK residents", "No fees worldwide", "Full banking account"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://starlingbank.com",
    affiliateLink: "https://starlingbank.com/travel-card",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["travel card", "UK", "no fees abroad"] },
  },
  {
    id: "travel-n26-you",
    slug: "n26-you-travel",
    category: "travel",
    countryCodes: ["DE", "AT", "ES", "FR", "IT", "PT"],
    providerMark: "N26",
    providerName: "N26",
    title: "N26 You Travel Account",
    subtitle: "Premium N26 account with travel insurance, no foreign transaction fees, and worldwide ATM withdrawals. Includes medical and trip cancellation coverage.",
    metrics: [
      { label: "FX fee", value: "0%" },
      { label: "Monthly fee", value: "EUR 9.90" },
      { label: "Travel insurance", value: "Included" },
    ],
    bestFor: ["EU residents", "Travel insurance included", "Free ATMs worldwide"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://n26.com",
    affiliateLink: "https://n26.com/en-eu/bank-account/n26-you",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["travel card", "N26", "travel insurance"] },
  },

  // ═══════════════════════════════════════════════════
  // CASHBACK & REWARDS (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "cashback-curve-cash",
    slug: "curve-cashback",
    category: "cashback",
    countryCodes: ["EU", "UK"],
    providerMark: "CRV",
    providerName: "Curve",
    title: "Curve Cashback",
    subtitle: "Earn 1% cashback at up to 3 retailers of your choice with Curve X. Higher tiers unlock more retailers and unlimited cashback.",
    metrics: [
      { label: "Cashback rate", value: "1% at 3 retailers" },
      { label: "Monthly fee", value: "Free (Curve X)" },
      { label: "Retailers", value: "Chosen by you" },
    ],
    bestFor: ["Everyday spending", "Card consolidation", "Custom cashback"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://curve.com",
    affiliateLink: "https://curve.com/cashback",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Curve"] },
  },
  {
    id: "cashback-revolut-ultra",
    slug: "revolut-cashback",
    category: "cashback",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Ultra Cashback",
    subtitle: "Up to 1% cashback on card spending with the Revolut Ultra plan. Also includes unlimited free ATMs, lounge access, and concierge service.",
    metrics: [
      { label: "Cashback", value: "Up to 1%" },
      { label: "Plan", value: "Ultra (EUR 45/month)" },
      { label: "ATM", value: "Unlimited free" },
    ],
    bestFor: ["Heavy spenders", "Premium perks", "Lounge + cashback combo"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/ultra",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Revolut Ultra"] },
  },
  {
    id: "cashback-vivid-money",
    slug: "vivid-money-cashback",
    category: "cashback",
    countryCodes: ["DE", "ES", "FR", "IT"],
    providerMark: "VV",
    providerName: "Vivid Money",
    title: "Vivid Prime Cashback",
    subtitle: "Up to 10% cashback on partner brands and 0.4% on all other spending. One of the most generous cashback programs for EU customers.",
    metrics: [
      { label: "Cashback (partners)", value: "Up to 10%" },
      { label: "Cashback (all)", value: "0.4%" },
      { label: "Plan", value: "Prime (EUR 9.90/month)" },
    ],
    bestFor: ["Partner brand shoppers", "EU residents", "High cashback rates"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://vivid.money",
    affiliateLink: "https://vivid.money/en/cashback",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["cashback", "rewards", "Vivid"] },
  },
  {
    id: "cashback-chase-uk",
    slug: "chase-uk-cashback",
    category: "cashback",
    countryCodes: ["UK"],
    providerMark: "CH",
    providerName: "Chase UK",
    title: "Chase UK 1% Cashback",
    subtitle: "1% cashback on all card spending for the first year, then on selected categories. No monthly fee and competitive savings rate.",
    metrics: [
      { label: "Cashback", value: "1% on all spending (year 1)" },
      { label: "Monthly fee", value: "Free" },
      { label: "Savings rate", value: "Up to 4.1% AER" },
    ],
    bestFor: ["UK residents", "No fee cashback", "Savings + cashback combo"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://chase.co.uk",
    affiliateLink: "https://chase.co.uk",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["cashback", "UK", "Chase"] },
  },

  // ═══════════════════════════════════════════════════
  // DIGITAL WALLETS (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "wallet-paypal",
    slug: "paypal-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "PP",
    providerName: "PayPal",
    title: "PayPal Wallet",
    subtitle: "The world's most widely accepted digital wallet. Send and receive money instantly, pay online at 30M+ merchants, and earn rewards.",
    metrics: [
      { label: "Merchants", value: "30M+ worldwide" },
      { label: "Personal send fee", value: "Free (within EU)" },
      { label: "Currencies", value: "25+" },
    ],
    bestFor: ["Online shopping", "Universal acceptance", "Buyer protection"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.92,
    providerWebsiteUrl: "https://paypal.com",
    affiliateLink: "https://paypal.com/eu/digital-wallet",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["wallet", "PayPal", "online payments"] },
  },
  {
    id: "wallet-revolut",
    slug: "revolut-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut Wallet",
    subtitle: "All-in-one financial super-app. Hold 36 currencies, invest in stocks and crypto, send money instantly, and earn savings interest.",
    metrics: [
      { label: "Currencies", value: "36" },
      { label: "Instant transfers", value: "Free between Revolut users" },
      { label: "Crypto", value: "Integrated" },
    ],
    bestFor: ["All-in-one finance", "Instant P2P", "Multi-currency holding"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/wallet",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["wallet", "Revolut", "super-app"] },
  },
  {
    id: "wallet-skrill",
    slug: "skrill-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "SK",
    providerName: "Skrill",
    title: "Skrill Digital Wallet",
    subtitle: "Digital wallet trusted by online gamblers, traders, and international freelancers. Send money to 40+ currencies and 120+ countries.",
    metrics: [
      { label: "Currencies", value: "40+" },
      { label: "Countries", value: "120+" },
      { label: "Monthly fee", value: "EUR 0" },
    ],
    bestFor: ["Online gaming", "Trading deposits", "Low minimum"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.76,
    providerWebsiteUrl: "https://skrill.com",
    affiliateLink: "https://skrill.com/en/signup",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["wallet", "Skrill", "gambling", "trading"] },
  },
  {
    id: "wallet-wise",
    slug: "wise-wallet",
    category: "wallets",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise",
    title: "Wise Multi-Currency Account",
    subtitle: "Hold 40+ currencies in one account with local bank details for GBP, EUR, USD, AUD, and more. Ideal for freelancers and international workers.",
    metrics: [
      { label: "Currencies held", value: "40+" },
      { label: "Local bank details", value: "EUR, GBP, USD, AUD, NZD" },
      { label: "Monthly fee", value: "Free" },
    ],
    bestFor: ["Freelancers", "International workers", "Multi-currency needs"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/gb/send-money",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["wallet", "Wise", "multi-currency"] },
  },

  // ═══════════════════════════════════════════════════
  // PAYROLL & INVOICING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "payroll-deel",
    slug: "deel-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "DL",
    providerName: "Deel",
    title: "Deel Global Payroll",
    subtitle: "Hire and pay employees and contractors in 150+ countries with full local compliance. Legal entities, payroll, and HR in one platform.",
    metrics: [
      { label: "Countries", value: "150+" },
      { label: "Contractor", value: "From USD 49/month" },
      { label: "EOR", value: "From USD 599/month" },
    ],
    bestFor: ["Remote teams", "Global hiring", "Contractor management"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.93,
    providerWebsiteUrl: "https://deel.com",
    affiliateLink: "https://deel.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["payroll", "remote work", "global hiring"] },
  },
  {
    id: "payroll-remote",
    slug: "remote-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "RM",
    providerName: "Remote",
    title: "Remote Global HR",
    subtitle: "Employer of Record and payroll platform for distributed teams. 100% owned local entities in 75+ countries for compliant international hiring.",
    metrics: [
      { label: "EOR countries", value: "75+" },
      { label: "Contractor plan", value: "USD 29/month" },
      { label: "EOR pricing", value: "From USD 599/month" },
    ],
    bestFor: ["Employer of Record", "Compliance-first", "75+ countries"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.89,
    providerWebsiteUrl: "https://remote.com",
    affiliateLink: "https://remote.com/hr-payroll",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["payroll", "EOR", "remote hiring"] },
  },
  {
    id: "payroll-qonto",
    slug: "qonto-payroll",
    category: "payroll",
    countryCodes: ["FR", "DE", "IT", "ES"],
    providerMark: "QT",
    providerName: "Qonto",
    title: "Qonto Business Finance",
    subtitle: "Southern European business bank with built-in invoicing, expense management, and payroll integration. Used by 450,000+ SMEs.",
    metrics: [
      { label: "Monthly fee", value: "EUR 9 (Solo)" },
      { label: "Countries", value: "FR, DE, IT, ES" },
      { label: "Invoicing", value: "Included" },
    ],
    bestFor: ["Southern Europe SMEs", "Invoicing + banking", "Freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.85,
    providerWebsiteUrl: "https://qonto.com",
    affiliateLink: "https://qonto.com/en",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["payroll", "invoicing", "Qonto", "SME"] },
  },
  {
    id: "payroll-wise-business",
    slug: "wise-business-payroll",
    category: "payroll",
    countryCodes: ["EU", "UK"],
    providerMark: "W",
    providerName: "Wise Business",
    title: "Wise Business Payments",
    subtitle: "Pay international contractors and suppliers in 40+ currencies at the mid-market rate. Batch payments save time for payroll runs.",
    metrics: [
      { label: "Fee", value: "From 0.35%" },
      { label: "Currencies", value: "40+" },
      { label: "Batch payments", value: "Yes" },
    ],
    bestFor: ["International payroll", "Contractor payments", "Batch payments"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.84,
    providerWebsiteUrl: "https://wise.com",
    affiliateLink: "https://wise.com/business/payroll",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["payroll", "international payments", "Wise Business"] },
  },

  // ═══════════════════════════════════════════════════
  // TAX & ACCOUNTING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "tax-taxfix-de",
    slug: "taxfix-germany",
    category: "tax",
    countryCodes: ["DE"],
    providerMark: "TF",
    providerName: "Taxfix",
    title: "Taxfix (Germany)",
    subtitle: "Germany's most popular tax app. File your German tax return in 22 minutes on average. Mobile-first, no tax knowledge required.",
    metrics: [
      { label: "Filing fee", value: "EUR 39.99" },
      { label: "Average return", value: "EUR 1,095 refund" },
      { label: "Filing time", value: "22 minutes" },
    ],
    bestFor: ["German residents", "Fast filing", "First-timers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://taxfix.de",
    affiliateLink: "https://taxfix.de",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Germany", "Steuererklärung"] },
  },
  {
    id: "tax-taxscouts-uk",
    slug: "taxscouts-uk",
    category: "tax",
    countryCodes: ["UK"],
    providerMark: "TS",
    providerName: "TaxScouts",
    title: "TaxScouts UK",
    subtitle: "UK self-assessment tax returns filed by a real accountant for a flat fee. Simple, fast, and stress-free. Covers freelancers, landlords, and investors.",
    metrics: [
      { label: "Filing fee", value: "GBP 169 flat" },
      { label: "Done by", value: "Real accountant" },
      { label: "Turnaround", value: "3–5 days" },
    ],
    bestFor: ["UK freelancers", "Landlords", "HMRC self-assessment"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://taxscouts.com",
    affiliateLink: "https://taxscouts.com/uk",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "UK", "self-assessment", "accountant"] },
  },
  {
    id: "tax-wundertax-de",
    slug: "wundertax-germany",
    category: "tax",
    countryCodes: ["DE"],
    providerMark: "WT",
    providerName: "Wundertax",
    title: "Wundertax (Germany)",
    subtitle: "German tax return app with a step-by-step interview. Optimises your deductions automatically. Includes salary, freelance, and investment income.",
    metrics: [
      { label: "Filing fee", value: "EUR 34.99" },
      { label: "Refund optimisation", value: "Automatic" },
      { label: "Support", value: "Chat + email" },
    ],
    bestFor: ["Germany employed workers", "Investment income", "Automatic deductions"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://wundertax.de",
    affiliateLink: "https://wundertax.de",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Germany", "Wundertax"] },
  },
  {
    id: "tax-sorted-es",
    slug: "sorted-spain-tax",
    category: "tax",
    countryCodes: ["ES"],
    providerMark: "SR",
    providerName: "Sorted",
    title: "Sorted Spain",
    subtitle: "Spanish income tax declaration service for expats and freelancers. English-speaking advisors handle your full declaración de la renta.",
    metrics: [
      { label: "Filing fee", value: "EUR 99+" },
      { label: "Language", value: "English + Spanish" },
      { label: "Support", value: "Dedicated advisor" },
    ],
    bestFor: ["Spain expats", "English speakers", "Autónomo freelancers"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://sorted.es",
    affiliateLink: "https://sorted.es",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "local", searchTags: ["tax", "Spain", "expat", "renta"] },
  },

  // ═══════════════════════════════════════════════════
  // EXPENSE TRACKING (4 offers)
  // ═══════════════════════════════════════════════════
  {
    id: "expense-pleo",
    slug: "pleo-expense",
    category: "expense",
    countryCodes: ["EU", "UK"],
    providerMark: "PL",
    providerName: "Pleo",
    title: "Pleo Business Expenses",
    subtitle: "Smart company cards and expense management for European businesses. Employees get pre-funded cards; finance teams get real-time visibility.",
    metrics: [
      { label: "Per user/month", value: "EUR 9 (Starter)" },
      { label: "Receipt capture", value: "Automatic" },
      { label: "Integrations", value: "Xero, QuickBooks, NetSuite" },
    ],
    bestFor: ["SME teams", "Real-time visibility", "Card + software"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://pleo.io",
    affiliateLink: "https://pleo.io",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "company cards", "Pleo"] },
  },
  {
    id: "expense-spendesk",
    slug: "spendesk-expense",
    category: "expense",
    countryCodes: ["FR", "DE", "UK", "ES"],
    providerMark: "SK",
    providerName: "Spendesk",
    title: "Spendesk",
    subtitle: "All-in-one spend management platform for finance teams. Includes corporate cards, invoice processing, expense claims, and accounting automation.",
    metrics: [
      { label: "Pricing", value: "Custom (per company)" },
      { label: "Features", value: "Cards, invoices, expenses" },
      { label: "Accounting", value: "Auto-sync" },
    ],
    bestFor: ["Mid-market companies", "Full spend control", "Invoice automation"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://spendesk.com",
    affiliateLink: "https://spendesk.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "spend management", "Spendesk"] },
  },
  {
    id: "expense-moss",
    slug: "moss-expense",
    category: "expense",
    countryCodes: ["DE", "AT", "NL", "UK"],
    providerMark: "MS",
    providerName: "Moss",
    title: "Moss",
    subtitle: "German-built corporate spend platform with virtual and physical cards, automated receipt matching, and real-time budget tracking.",
    metrics: [
      { label: "Cards", value: "Virtual + physical" },
      { label: "Receipt matching", value: "Automated" },
      { label: "Markets", value: "DE, AT, NL, UK" },
    ],
    bestFor: ["DACH companies", "Virtual cards", "Budget control"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.82,
    providerWebsiteUrl: "https://getmoss.com",
    affiliateLink: "https://getmoss.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "corporate cards", "Germany", "Moss"] },
  },
  {
    id: "expense-soldo",
    slug: "soldo-expense",
    category: "expense",
    countryCodes: ["UK", "IT", "DE", "FR", "ES"],
    providerMark: "SL",
    providerName: "Soldo",
    title: "Soldo",
    subtitle: "Multi-user expense platform with prepaid Mastercard cards for every team member. Set spending limits and rules per card or team.",
    metrics: [
      { label: "Plan", value: "From GBP 21/month" },
      { label: "Cards", value: "Prepaid Mastercard" },
      { label: "Rules", value: "Per-card spending limits" },
    ],
    bestFor: ["Team spending control", "Prepaid cards", "UK/Italy businesses"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://soldo.com",
    affiliateLink: "https://soldo.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["expense", "prepaid cards", "Soldo"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand crypto (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "crypto-kraken",
    slug: "kraken-crypto",
    category: "crypto",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "KR",
    providerName: "Kraken",
    title: "Kraken",
    subtitle: "One of the world's most trusted crypto exchanges. 200+ cryptocurrencies, competitive fees, and strong security record since 2011.",
    metrics: [
      { label: "Maker fee", value: "0.16%" },
      { label: "Taker fee", value: "0.26%" },
      { label: "Assets", value: "200+" },
    ],
    bestFor: ["Security-first", "Advanced traders", "EUR deposits"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.91,
    providerWebsiteUrl: "https://kraken.com",
    affiliateLink: "https://kraken.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "exchange", "Kraken"] },
  },
  {
    id: "crypto-binance",
    slug: "binance-crypto",
    category: "crypto",
    countryCodes: ["EU"],
    providerMark: "BN",
    providerName: "Binance",
    title: "Binance",
    subtitle: "World's largest crypto exchange by volume. 350+ trading pairs, spot and futures trading, earn products, and low fees.",
    metrics: [
      { label: "Trading fee", value: "0.10% (spot)" },
      { label: "Assets", value: "350+" },
      { label: "Volume", value: "#1 worldwide" },
    ],
    bestFor: ["Advanced traders", "High volume", "Wide asset selection"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.88,
    providerWebsiteUrl: "https://binance.com",
    affiliateLink: "https://binance.com/en/register",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "exchange", "Binance"] },
  },
  {
    id: "crypto-bitpanda",
    slug: "bitpanda-crypto",
    category: "crypto",
    countryCodes: ["AT", "DE", "CH", "ES", "FR", "IT"],
    providerMark: "BP",
    providerName: "Bitpanda",
    title: "Bitpanda",
    subtitle: "Austrian crypto and investment platform trusted by 4M+ Europeans. Buy crypto, stocks, ETFs, and precious metals in one regulated app.",
    metrics: [
      { label: "Fee", value: "1.49% (Bitpanda)" },
      { label: "Assets", value: "Crypto + stocks + ETFs" },
      { label: "Regulation", value: "BaFin (EU)" },
    ],
    bestFor: ["EU-regulated", "Multi-asset (crypto+stocks)", "Beginners"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.86,
    providerWebsiteUrl: "https://bitpanda.com",
    affiliateLink: "https://bitpanda.com/en",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["crypto", "Austrian exchange", "Bitpanda"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand kids (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "kids-gohenry",
    slug: "gohenry-kids",
    category: "kids",
    countryCodes: ["UK", "EU"],
    providerMark: "GH",
    providerName: "GoHenry",
    title: "GoHenry",
    subtitle: "Pocket money card and app for kids aged 6–18. Parents set spending limits, chores, and goals. Custom card designs and financial education built in.",
    metrics: [
      { label: "Monthly fee", value: "GBP 3.99/child" },
      { label: "Age range", value: "6–18" },
      { label: "Parental controls", value: "Full" },
    ],
    bestFor: ["Ages 6–18", "Parental control", "Financial education"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.90,
    providerWebsiteUrl: "https://gohenry.com",
    affiliateLink: "https://gohenry.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "pocket money", "family finance"] },
  },
  {
    id: "kids-revolut-junior",
    slug: "revolut-junior-kids",
    category: "kids",
    countryCodes: ["EU", "UK"],
    providerMark: "R",
    providerName: "Revolut",
    title: "Revolut <18",
    subtitle: "Free junior account for ages 6–17, linked to a parent's Revolut account. Real Visa card, spending controls, and savings goals.",
    metrics: [
      { label: "Monthly fee", value: "Free (with parent plan)" },
      { label: "Age range", value: "6–17" },
      { label: "Card", value: "Visa debit" },
    ],
    bestFor: ["Revolut families", "Free junior card", "Teens"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.87,
    providerWebsiteUrl: "https://revolut.com",
    affiliateLink: "https://revolut.com/under18",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "junior account", "teens"] },
  },
  {
    id: "kids-greenlight",
    slug: "greenlight-kids",
    category: "kids",
    countryCodes: ["UK", "EU"],
    providerMark: "GL",
    providerName: "Greenlight",
    title: "Greenlight Kids Card",
    subtitle: "US-origin kids fintech now expanding in Europe. Debit card for children with invest, save, and earn features built into a family app.",
    metrics: [
      { label: "Monthly fee", value: "GBP 4.99/family" },
      { label: "Kids per plan", value: "Up to 5" },
      { label: "Features", value: "Save, invest, give" },
    ],
    bestFor: ["Financial literacy", "Multiple kids", "Investing for kids"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.80,
    providerWebsiteUrl: "https://greenlight.com",
    affiliateLink: "https://greenlight.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["kids", "family finance", "investing for kids"] },
  },

  // ═══════════════════════════════════════════════════
  // ADDITIONAL: expand budgeting (3 more)
  // ═══════════════════════════════════════════════════
  {
    id: "budgeting-emma",
    slug: "emma-budgeting",
    category: "budgeting",
    countryCodes: ["UK", "EU"],
    providerMark: "EM",
    providerName: "Emma",
    title: "Emma Money App",
    subtitle: "Open banking budgeting app that connects all your banks in one view. Tracks subscriptions, spots waste, and shows your real net worth.",
    metrics: [
      { label: "Monthly fee", value: "Free (basic)" },
      { label: "Banks connected", value: "50+" },
      { label: "Subscription tracking", value: "Yes" },
    ],
    bestFor: ["Multi-bank households", "Subscription auditing", "Net worth tracking"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.83,
    providerWebsiteUrl: "https://emma-app.com",
    affiliateLink: "https://emma-app.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["budgeting", "open banking", "Emma"] },
  },
  {
    id: "budgeting-plum",
    slug: "plum-budgeting",
    category: "budgeting",
    countryCodes: ["UK", "EU"],
    providerMark: "PM",
    providerName: "Plum",
    title: "Plum",
    subtitle: "AI-powered savings and budgeting app. Automatically sets aside small amounts based on your spending patterns to grow your savings effortlessly.",
    metrics: [
      { label: "Monthly fee", value: "Free (basic)" },
      { label: "Auto-save", value: "AI-powered" },
      { label: "Interest (Pro)", value: "Up to 4.9% AER" },
    ],
    bestFor: ["Automated saving", "Beginners", "Spending analytics"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.81,
    providerWebsiteUrl: "https://withplum.com",
    affiliateLink: "https://withplum.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "eu_wide", searchTags: ["budgeting", "AI savings", "Plum"] },
  },
  {
    id: "budgeting-ynab",
    slug: "ynab-budgeting",
    category: "budgeting",
    countryCodes: ["EU", "UK", "US"],
    providerMark: "YN",
    providerName: "YNAB",
    title: "YNAB (You Need A Budget)",
    subtitle: "Rule-based budgeting system that gives every euro a job. Proven to save new users an average of USD 600 in their first 2 months.",
    metrics: [
      { label: "Monthly fee", value: "USD 14.99" },
      { label: "Method", value: "Zero-based budgeting" },
      { label: "Free trial", value: "34 days" },
    ],
    bestFor: ["Serious budgeters", "Debt payoff", "Zero-based method"],
    linkType: "affiliate_redirect",
    affiliatePriorityScore: 0.79,
    providerWebsiteUrl: "https://ynab.com",
    affiliateLink: "https://ynab.com",
    updatedAt: "2026-05-01T00:00:00Z",
    attributes: { availability: "international", searchTags: ["budgeting", "YNAB", "zero-based"] },
  },
];
