export type UrlType = "PRODUCT" | "CATEGORY_LANDING" | "PRICING";

export type ProviderEntry = {
  rank: string;
  provider: string;
  product: string;
  category: string;
  markets: string[];
  headline_metric: string;
  amount_limit: string;
  term: string;
  fx_fee: string;
  atm_fee: string;
  cashback_reward: string;
  best_for: string;
  pros: string;
  watch_out: string;
  provider_url: string;
  url_type: UrlType;
  url_verified_at: string;
};

const V = "2026-05-12";

export const providerCatalogue: ProviderEntry[] = [

  // ─── BANKING ──────────────────────────────────────────────────────────────

  { rank: "DE-1", provider: "ING", product: "Girokonto", category: "banking", markets: ["DE"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free DE ATMs", cashback_reward: "-", best_for: "Free German IBAN", pros: "No fees with any salary credit; top-rated German app.", watch_out: "FX fee applies on non-EUR transactions.", provider_url: "https://www.ing.de/girokonto/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "DE-2", provider: "DKB", product: "Aktivkunde Girokonto", category: "banking", markets: ["DE"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Free worldwide ATMs", pros: "Visa debit with 0% FX and free global ATMs for Aktivkunde.", watch_out: "Aktivkunde status requires €700/mo inflow or active use.", provider_url: "https://www.dkb.de/privatkunden/dkb-girokonto/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-3", provider: "Deutsche Bank", product: "BestKonto", category: "banking", markets: ["DE"], headline_metric: "€0/mo (salary)", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free DE network", cashback_reward: "-", best_for: "Incumbent with branches", pros: "Extensive branch network; waived fee with salary deposit.", watch_out: "€9.90/mo without qualifying salary.", provider_url: "https://www.deutsche-bank.de/pk/konto-und-karte/konten-im-ueberblick/konten-im-vergleich.html", url_type: "CATEGORY_LANDING", url_verified_at: V },
  { rank: "DE-4", provider: "comdirect", product: "Girokonto Aktiv", category: "banking", markets: ["DE"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.90%", atm_fee: "Free DE Visa ATMs", cashback_reward: "-", best_for: "Bank + broker combo", pros: "Integrated brokerage; free with any activity.", watch_out: "Commerzbank-owned; app less polished than N26.", provider_url: "https://www.comdirect.de/girokonto/", url_type: "PRODUCT", url_verified_at: "" },

  { rank: "ES-1", provider: "BBVA", product: "Cuenta Online Sin Comisiones", category: "banking", markets: ["ES"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free BBVA ATMs", cashback_reward: "-", best_for: "Top Spanish incumbent", pros: "No fees, no minimum balance; excellent mobile app.", watch_out: "Limited English support; EU-only ATM free tier.", provider_url: "PENDING_DEEP_LINK", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-2", provider: "CaixaBank", product: "Cuenta DayOne", category: "banking", markets: ["ES"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free CaixaBank ATMs", cashback_reward: "-", best_for: "Youth & new residents", pros: "Zero-fee account with CaixaBank's dense ATM network.", watch_out: "DayOne targets 18-35 age group; adults may get upsold.", provider_url: "https://www.dayonecaixabank.es/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-3", provider: "Banco Sabadell", product: "Cuenta Online Sabadell", category: "banking", markets: ["ES"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free Sabadell ATMs", cashback_reward: "-", best_for: "Free with direct deposit", pros: "No fees with domiciled payroll or bills.", watch_out: "Fee applies without qualifying activity.", provider_url: "https://www.bancsabadell.com/cs/Satellite/SabAtl/Cuenta-online-Sabadell/6000007855815/es/", url_type: "PRODUCT", url_verified_at: "" },

  { rank: "IT-1", provider: "Fineco", product: "Conto Fineco", category: "banking", markets: ["IT"], headline_metric: "€0 yr1 / €3.95/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU ATMs", cashback_reward: "-", best_for: "Bank + broker in one", pros: "Best-in-class Italian bank-broker; free first year.", watch_out: "Monthly fee applies from year two unless actively trading.", provider_url: "https://finecobank.com/it/public/conto-corrente/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-2", provider: "Intesa Sanpaolo", product: "XME Conto", category: "banking", markets: ["IT"], headline_metric: "€0–5/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free IT network", cashback_reward: "-", best_for: "Italy's largest bank", pros: "Widest branch/ATM coverage in Italy; solid mobile app.", watch_out: "Fees depend on tier; can be complex to navigate.", provider_url: "https://www.intesasanpaolo.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-3", provider: "UniCredit", product: "My Genius", category: "banking", markets: ["IT"], headline_metric: "€0–8/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU network", cashback_reward: "-", best_for: "Modular account", pros: "Customise services; pan-European ATM coverage.", watch_out: "Price adds up quickly with optional modules.", provider_url: "https://www.unicredit.it", url_type: "PRODUCT", url_verified_at: "" },

  { rank: "FR-1", provider: "Boursorama Banque", product: "Welcome Account", category: "banking", markets: ["FR"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU ATMs", cashback_reward: "-", best_for: "France's cheapest bank", pros: "Largest online bank in France; zero fees, no conditions.", watch_out: "Phone support limited; no physical branches.", provider_url: "https://www.boursobank.com/banque/carte-bancaire-gratuite-welcome", url_type: "PRODUCT", url_verified_at: V },
  { rank: "FR-2", provider: "BNP Paribas", product: "Esprit Libre", category: "banking", markets: ["FR"], headline_metric: "€0–9/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free BNP ATMs", cashback_reward: "-", best_for: "Big-bank safety net", pros: "Nationwide branch network; premium tier with Visa Infinite.", watch_out: "Fees required unless salary or savings threshold met.", provider_url: "https://mabanque.bnpparibas/fr/compte-bancaire/offre-esprit-libre", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-3", provider: "Crédit Agricole", product: "Compte EKO", category: "banking", markets: ["FR"], headline_metric: "€2/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free CA ATMs", cashback_reward: "-", best_for: "Low-cost bundled account", pros: "Flat €2/mo with card; no income conditions.", watch_out: "No overdraft facility on EKO tier.", provider_url: "https://www.credit-agricole.fr/particulier/compte/comptes-pour-tous/eko.html", url_type: "PRODUCT", url_verified_at: "" },

  { rank: "UK-1", provider: "Chase UK", product: "Chase Account", category: "banking", markets: ["UK"], headline_metric: "£0/mo + 1% cashback", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "1% on everyday spend", best_for: "Best free UK account", pros: "1% cashback yr1, 0% FX, free global ATMs — all on a free account.", watch_out: "Cashback capped at £15/mo; 1% drops to 0.5% after year one.", provider_url: "https://www.chase.co.uk/gb/en/product/chase-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-2", provider: "Starling Bank", product: "Personal Account", category: "banking", markets: ["UK"], headline_metric: "£0/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Best-rated UK app", pros: "Award-winning app, 0% FX, real-time spending insights.", watch_out: "No physical branches; no credit products in-house.", provider_url: "https://www.starlingbank.com/current-account/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-3", provider: "Lloyds Bank", product: "Classic Account", category: "banking", markets: ["UK"], headline_metric: "£0/mo", amount_limit: "-", term: "-", fx_fee: "2.99%", atm_fee: "Free UK ATMs", cashback_reward: "-", best_for: "Trusted incumbent", pros: "Large UK branch network; overdraft available.", watch_out: "High FX fees; app rated below digital-first rivals.", provider_url: "https://www.lloydsbank.com/current-accounts/all-accounts/classic-account.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-4", provider: "NatWest", product: "Reward Current Account", category: "banking", markets: ["UK"], headline_metric: "£2/mo", amount_limit: "-", term: "-", fx_fee: "2.75%", atm_fee: "Free UK ATMs", cashback_reward: "1–15% at retailers", best_for: "Cashback on bills", pros: "Cashback on 9 monthly direct debits; large branch network.", watch_out: "£2/mo fee; FX charges apply abroad.", provider_url: "https://personal.natwest.com/personal/current-accounts/reward.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-5", provider: "HSBC UK", product: "Advance Account", category: "banking", markets: ["UK"], headline_metric: "£0/mo", amount_limit: "-", term: "-", fx_fee: "2.75%", atm_fee: "Free UK ATMs", cashback_reward: "-", best_for: "Global bank access", pros: "Global HSBC network; expat and international transfers easy.", watch_out: "Requires £1,750/mo inflow to avoid fee.", provider_url: "https://www.hsbc.co.uk/current-accounts/products/advance/", url_type: "PRODUCT", url_verified_at: "" },

  { rank: "NL-1", provider: "ING NL", product: "Betaalrekening", category: "banking", markets: ["NL"], headline_metric: "€0–2.95/mo", amount_limit: "-", term: "-", fx_fee: "1.90%", atm_fee: "Free NL ATMs", cashback_reward: "-", best_for: "Largest Dutch bank", pros: "Free with salary; widest ATM network in NL.", watch_out: "Fee without salary; FX fees apply.", provider_url: "https://www.ing.nl/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-2", provider: "Knab", product: "Knab Free", category: "banking", markets: ["NL"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free NL ATMs", cashback_reward: "-", best_for: "Free Dutch IBAN", pros: "No monthly fee; clean app; Aegon-backed.", watch_out: "Limited product range beyond current account.", provider_url: "https://www.knab.nl/betaalrekening/knab-free", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-3", provider: "ABN AMRO", product: "Basis Pakket", category: "banking", markets: ["NL"], headline_metric: "€2.95/mo", amount_limit: "-", term: "-", fx_fee: "1.90%", atm_fee: "Free NL ATMs", cashback_reward: "-", best_for: "Big-bank Netherlands", pros: "Strong brand, full branch network, robust online banking.", watch_out: "No free tier; FX fees apply.", provider_url: "https://www.abnamro.nl/nl/prive/betalen/betaalpakketten/index.html", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "NL-4", provider: "Rabobank", product: "Direct Pakket", category: "banking", markets: ["NL"], headline_metric: "€2.35/mo", amount_limit: "-", term: "-", fx_fee: "1.90%", atm_fee: "Free NL ATMs", cashback_reward: "-", best_for: "Co-op with full service", pros: "Largest farm/SME bank NL; strong community focus.", watch_out: "Monthly fee applies from day one.", provider_url: "https://www.rabobank.nl/particulieren/betalen/betaalpakketten", url_type: "CATEGORY_LANDING", url_verified_at: "" },

  { rank: "PT-1", provider: "ActivoBank", product: "Conta ActivoBank", category: "banking", markets: ["PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free PT ATMs", cashback_reward: "-", best_for: "Best free PT account", pros: "No fees, no conditions; BCP-backed digital bank.", watch_out: "Limited branch presence; digital-only service model.", provider_url: "https://www.activobank.pt/pt/public/conta-ordenado", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-2", provider: "Novo Banco", product: "Conta Ordenado", category: "banking", markets: ["PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free PT ATMs", cashback_reward: "-", best_for: "Salary account PT", pros: "Free with salary domiciliation; extensive PT branch network.", watch_out: "Fee applies without salary transfer.", provider_url: "https://www.novobanco.pt/particulares/contas/conta-ordenado", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-3", provider: "Millennium BCP", product: "Conta Frequente", category: "banking", markets: ["PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free PT ATMs", cashback_reward: "-", best_for: "Portugal's top private bank", pros: "Largest private bank PT; solid digital + branch coverage.", watch_out: "Account conditions reviewed annually.", provider_url: "https://ind.millenniumbcp.pt/pt/Particulares/contas/Pages/conta-frequente.aspx", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-4", provider: "Caixa Geral de Depósitos", product: "Conta Caixa", category: "banking", markets: ["PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free PT ATMs", cashback_reward: "-", best_for: "State-owned safe harbour", pros: "State-guaranteed bank; universal acceptance in PT.", watch_out: "Digital experience lags behind digital-first rivals.", provider_url: "https://www.cgd.pt/Particulares/Contas/Pages/Conta-Caixa-Easy.aspx", url_type: "CATEGORY_LANDING", url_verified_at: "" },

  // ─── NEOBANKS ─────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Revolut", product: "Standard / Premium / Metal / Ultra", category: "neobanks", markets: ["INT"], headline_metric: "€0–45/mo", amount_limit: "-", term: "-", fx_fee: "0% (plan limits)", atm_fee: "€200–2000/mo free", cashback_reward: "Up to 1% (Metal)", best_for: "Most features per £", pros: "50M+ users; widest feature set including stock trading, crypto, insurance.", watch_out: "Weekend FX markup on Standard; customer service delays.", provider_url: "https://www.revolut.com/our-pricing-plans/", url_type: "PRICING", url_verified_at: V },
  { rank: "INT-2", provider: "Wise", product: "Wise Account", category: "neobanks", markets: ["INT"], headline_metric: "No monthly fee", amount_limit: "-", term: "-", fx_fee: "Mid-market rate", atm_fee: "£200/mo free", cashback_reward: "-", best_for: "Lowest FX cost", pros: "True mid-market rate for 40+ currencies; transparent fees.", watch_out: "Not a full bank; no interest unless via Wise Interest.", provider_url: "https://wise.com/gb/multi-currency-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "DE-1", provider: "N26", product: "Standard / Smart / You / Metal", category: "neobanks", markets: ["DE", "IT", "ES", "FR", "PT"], headline_metric: "€0–16.90/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "3 free/mo (Standard)", cashback_reward: "-", best_for: "Sleekest EU neobank", pros: "German banking licence; clean UX; instant spending notifications.", watch_out: "No cash deposits; limited customer support tier on free plan.", provider_url: "https://n26.com/en-eu/pricing", url_type: "PRICING", url_verified_at: V },
  { rank: "NL-1", provider: "bunq", product: "Easy Savings / Easy Money / Easy Green", category: "neobanks", markets: ["NL", "DE", "FR", "IT", "ES"], headline_metric: "€4.99–17.99/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "Saveback 0.5%", best_for: "Multi-IBAN power users", pros: "8 IBANs, joint accounts, and 2.46% savings — all on one app.", watch_out: "Paid plans only; no truly free tier.", provider_url: "https://www.bunq.com/plans", url_type: "PRICING", url_verified_at: V },
  { rank: "DE-2", provider: "Trade Republic", product: "Trade Republic Card", category: "neobanks", markets: ["DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "1% Saveback to ETF", best_for: "Invest + bank in one", pros: "2% on uninvested cash; 1% cashback reinvested to ETF portfolio.", watch_out: "Primarily a broker; banking features are secondary.", provider_url: "https://traderepublic.com/card", url_type: "PRODUCT", url_verified_at: V },
  { rank: "DE-3", provider: "Vivid Money", product: "Vivid Standard / Plus / Prime", category: "neobanks", markets: ["DE", "FR", "IT", "ES"], headline_metric: "€0–9.99/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "€200/mo free", cashback_reward: "Up to 25% at partners", best_for: "Cashback neobank", pros: "Partner cashback up to 25%; Solaris-backed German IBAN.", watch_out: "Cashback only at partner merchants; free tier has low ATM allowance.", provider_url: "https://vivid.money", url_type: "PRICING", url_verified_at: "" },
  { rank: "DE-4", provider: "C24 Bank", product: "Smart / Plus / Max", category: "neobanks", markets: ["DE"], headline_metric: "€0–9.90/mo", amount_limit: "-", term: "-", fx_fee: "1.75%", atm_fee: "Free DE ATMs", cashback_reward: "-", best_for: "Check24 ecosystem", pros: "Tight integration with Check24 comparison tools.", watch_out: "Limited to Germany; FX fees apply.", provider_url: "https://www.c24bank.de/girokonto/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "UK-1", provider: "Monzo", product: "Free / Plus / Premium / Perks", category: "neobanks", markets: ["UK"], headline_metric: "£0–17/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "£200/mo free (Plus+)", cashback_reward: "Up to 1% (Perks)", best_for: "Best UK money app", pros: "Pots, roundups, bill splitting; most-loved UK app.", watch_out: "Free ATM allowance outside UK limited on free tier.", provider_url: "https://monzo.com", url_type: "PRICING", url_verified_at: "" },
  { rank: "UK-2", provider: "Starling Bank", product: "Personal Current Account", category: "neobanks", markets: ["UK"], headline_metric: "£0/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Free UK current account", pros: "Full UK banking licence; 0% FX; free worldwide ATMs.", watch_out: "No premium tiers with travel perks unlike Monzo.", provider_url: "https://www.starlingbank.com/current-account/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-1", provider: "Nickel", product: "Nickel Standard / Chrome / Metal", category: "neobanks", markets: ["FR", "ES", "IT", "PT", "BE"], headline_metric: "€1.50–11.90/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU ATMs", cashback_reward: "-", best_for: "Open to everyone", pros: "No income or credit checks; open at any tabac shop.", watch_out: "Not a full bank account; spending limits apply.", provider_url: "https://nickel.eu", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "FR-2", provider: "Helios", product: "Compte Courant Éthique", category: "neobanks", markets: ["FR"], headline_metric: "€7/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU ATMs", cashback_reward: "-", best_for: "Ethical / green banking", pros: "Deposits fund only renewable energy; B Corp certified.", watch_out: "Premium price for ethical stance; no free tier.", provider_url: "https://helios.do/fr/compte-courant", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-1", provider: "Hype", product: "Hype Start / Plus / Premium", category: "neobanks", markets: ["IT"], headline_metric: "€0–9.90/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free IT ATMs", cashback_reward: "Up to 10% at partners", best_for: "Italian mobile bank", pros: "Largest Italian neobank; cashback at 2,500 Italian retailers.", watch_out: "Banca Sella-backed; FX fees on non-EUR.", provider_url: "https://www.hype.it/scopri-hype/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "IT-2", provider: "Buddybank", product: "Conto Più", category: "neobanks", markets: ["IT"], headline_metric: "€9.90/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Premium concierge", pros: "24/7 concierge; UniCredit-backed; 0% FX.", watch_out: "Paid from day one; niche proposition.", provider_url: "https://www.buddybank.com/it/buddybank-conto.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-1", provider: "Openbank", product: "Cuenta Open", category: "neobanks", markets: ["ES", "PT", "DE", "NL"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Santander digital", pros: "Santander-backed; 0% FX globally; growing EU footprint.", watch_out: "Less fintech-polished than Revolut; Santander branding.", provider_url: "https://www.openbank.es/cuentas/cuenta-corriente", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-2", provider: "imagin", product: "Cuenta Imagin", category: "neobanks", markets: ["ES"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free CaixaBank ATMs", cashback_reward: "-", best_for: "Youth segment ES", pros: "CaixaBank-backed; strong app; youth lifestyle perks.", watch_out: "Targets under-35s; limited for older customers.", provider_url: "https://imagin.app/web/imagin/cuenta", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-1", provider: "Moey!", product: "Cartão Moey", category: "neobanks", markets: ["PT"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free PT ATMs", cashback_reward: "-", best_for: "Free PT digital account", pros: "Crédito Agrícola-backed; free account with Visa debit.", watch_out: "Feature set thinner than international neobanks.", provider_url: "https://www.moey.pt/cartao", url_type: "PRODUCT", url_verified_at: "" },

  // ─── SAVINGS ──────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Trade Republic", product: "Cash Interest", category: "savings", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "INT"], headline_metric: "2.00% p.a.", amount_limit: "€50,000", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Instant savings yield", pros: "2% on uninvested cash with instant access; no separate savings account needed.", watch_out: "Rate is variable and linked to ECB policy; not FSCS/DGS protected.", provider_url: "https://traderepublic.com/en-de/interest", url_type: "PRODUCT", url_verified_at: V },
  { rank: "INT-2", provider: "Raisin", product: "Savings Marketplace", category: "savings", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "UK"], headline_metric: "Up to 3.80% p.a.", amount_limit: "Up to €100k", term: "Flexible–5 yrs", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Best rate marketplace", pros: "100+ partner banks; single KYC for all; up to 3.80% easy access.", watch_out: "Rates change daily; some partners require notice periods.", provider_url: "https://www.raisin.com/en-eu/savings/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-3", provider: "Revolut", product: "Savings Vault", category: "savings", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "Up to 4.25% p.a.", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "In-app savings tier", pros: "Easy to open within the Revolut app; rate scales with plan tier.", watch_out: "Higher rates locked to Metal/Ultra subscribers only.", provider_url: "https://www.revolut.com/savings/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-1", provider: "Scalable Capital", product: "PRIME+ Cash Interest", category: "savings", markets: ["DE", "AT"], headline_metric: "Variable (ECB linked)", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Invest + save together", pros: "Cash earns interest inside the brokerage account; no extra account needed.", watch_out: "Requires PRIME+ subscription at €4.99/mo.", provider_url: "https://de.scalable.capital/prime-broker", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-2", provider: "Klarna", product: "Klarna Sparkonto (Hochzinskonto)", category: "savings", markets: ["DE"], headline_metric: "Up to 3.30% p.a.", amount_limit: "€100,000", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Easy access DE", pros: "BNPL giant's savings arm; competitive easy-access rate.", watch_out: "Rate is promotional and variable.", provider_url: "https://www.klarna.com/de/sparen/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Chase UK", product: "Chase Saver Account", category: "savings", markets: ["UK"], headline_metric: "4.10% AER", amount_limit: "£500,000", term: "Easy access", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Top UK easy access", pros: "Competitive rate with instant access; £85k FSCS protected.", watch_out: "Rate tracks base rate; JPMorgan may reprice quickly.", provider_url: "https://www.chase.co.uk/gb/en/product/chase-saver-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-2", provider: "Atom Bank", product: "Instant Saver", category: "savings", markets: ["UK"], headline_metric: "4.85% AER", amount_limit: "£100,000", term: "Easy access", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Highest easy-access UK", pros: "Consistently top-of-table for easy access; app-only simplicity.", watch_out: "App-only; no branch or phone banking.", provider_url: "https://www.atombank.co.uk/savings/instant-saver/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-3", provider: "Marcus by Goldman Sachs", product: "Online Savings Account", category: "savings", markets: ["UK"], headline_metric: "4.75% AER", amount_limit: "£250,000", term: "Easy access", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Goldman Sachs backing", pros: "Highly competitive rate; Goldman Sachs balance sheet; FSCS protected.", watch_out: "No current account; savings-only product.", provider_url: "https://www.marcus.co.uk/uk/en/savings/online-savings-account", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-4", provider: "Trading 212", product: "Cash ISA / Interest", category: "savings", markets: ["UK"], headline_metric: "Up to 5.10% AER", amount_limit: "£20,000/yr (ISA)", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "ISA + high rate", pros: "Leading rate on Cash ISA; integrates with invest account.", watch_out: "ISA allowance limits; rate variable.", provider_url: "https://www.trading212.com/cash-isa", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-1", provider: "Livret A", product: "Livret A (state savings)", category: "savings", markets: ["FR"], headline_metric: "2.40% (regulated)", amount_limit: "€22,950", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Risk-free FR savings", pros: "State-guaranteed; tax-free; available at any French bank.", watch_out: "Capped at €22,950; rate set by government every 6 months.", provider_url: "https://www.service-public.fr/particuliers/vosdroits/F2365", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-1", provider: "MyInvestor", product: "Cuenta Remunerada", category: "savings", markets: ["ES"], headline_metric: "3.05% p.a.", amount_limit: "€1,000,000", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Best easy-access ES", pros: "Andbank-backed; top rate for Spanish residents; no notice period.", watch_out: "Rate is promotional; may step down after introductory period.", provider_url: "https://myinvestor.es/cuenta-remunerada/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-2", provider: "Pibank", product: "Cuenta Pibank", category: "savings", markets: ["ES"], headline_metric: "3.00% p.a.", amount_limit: "€100,000", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Simple ES savings", pros: "Pichincha-backed; straightforward 3% with no conditions.", watch_out: "Smaller brand; less name recognition in ES market.", provider_url: "https://www.pibank.es/cuenta-pibank", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-1", provider: "Banca Mediolanum", product: "Conto Mediolanum", category: "savings", markets: ["IT"], headline_metric: "Variable", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Premium IT savings", pros: "Bundled bank + insurance products; strong network of financial advisors.", watch_out: "Rate varies; tied to advisor relationship model.", provider_url: "https://www.bancamediolanum.it/prodotti/conto-mediolanum/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-2", provider: "Illimity Bank", product: "Conto Premium", category: "savings", markets: ["IT"], headline_metric: "Variable", amount_limit: "-", term: "Flexible–24 mo", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Digital-only IT savings", pros: "Competitive fixed-term options; fully online, no branches.", watch_out: "Newer brand; less established than Mediolanum.", provider_url: "https://www.illimitybank.com/it/private/conto-premium", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "bunq", product: "Easy Savings", category: "savings", markets: ["NL", "DE", "FR", "IT", "ES"], headline_metric: "2.46% p.a.", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Neobank savings NL", pros: "Up to 2.46% on Easy Money+; integrated with bunq current account.", watch_out: "Requires paid bunq subscription to access higher rates.", provider_url: "https://www.bunq.com/savings", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-1", provider: "ActivoBank", product: "Conta Poupança", category: "savings", markets: ["PT"], headline_metric: "Variable", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Hassle-free PT savings", pros: "BCP-owned digital bank; easy online opening, no branch needed.", watch_out: "Rates change with ECB; not always market-leading.", provider_url: "https://www.activobank.pt/pt/public/poupanca", url_type: "PRODUCT", url_verified_at: "" },

  // ─── DEBIT CARDS ──────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Wise", product: "Wise Card", category: "debit", markets: ["INT"], headline_metric: "Mid-market FX", amount_limit: "-", term: "-", fx_fee: "0.35–1% conversion", atm_fee: "£200/mo free", cashback_reward: "-", best_for: "Cheapest FX debit", pros: "True mid-market rate in 40+ currencies; transparent fee on every transaction.", watch_out: "One-off card fee €9; ATM free allowance limited.", provider_url: "https://wise.com/gb/card/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "INT-2", provider: "Revolut", product: "Revolut Card", category: "debit", markets: ["INT"], headline_metric: "0% FX (plan limits)", amount_limit: "-", term: "-", fx_fee: "0% (in-plan limits)", atm_fee: "€200–2000/mo free", cashback_reward: "-", best_for: "Travel debit card", pros: "0% FX within monthly allowance; accepted anywhere Mastercard/Visa.", watch_out: "Weekend FX markup on Standard plan; spending limits apply.", provider_url: "https://www.revolut.com/cards/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "DE-1", provider: "DKB", product: "DKB Visa Debitkarte", category: "debit", markets: ["DE"], headline_metric: "0% FX (Aktivkunde)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Free global debit DE", pros: "Zero FX, free worldwide ATMs for Aktivkunde — all free.", watch_out: "Aktivkunde status required; debit (not credit) card.", provider_url: "https://www.dkb.de/privatkunden/visa-debitkarte/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-2", provider: "Trade Republic", product: "Trade Republic Card", category: "debit", markets: ["DE", "FR", "IT", "ES", "NL"], headline_metric: "0% FX + 1% Saveback", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "1% Saveback to ETF", best_for: "Invest while spending", pros: "0% FX and 1% of every spend reinvested to ETF plan automatically.", watch_out: "Cashback goes to ETF, not cash — requires investment mindset.", provider_url: "https://traderepublic.com/card", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-1", provider: "Chase UK", product: "Chase Debit Card", category: "debit", markets: ["UK"], headline_metric: "0% FX + 1% cashback", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "1% on everyday spend", best_for: "Best UK debit card", pros: "1% cashback (capped £15/mo), 0% FX, free worldwide ATMs — all free.", watch_out: "Cashback drops after year one; JPMorgan may change terms.", provider_url: "https://www.chase.co.uk/gb/en/product/chase-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-2", provider: "Starling Bank", product: "Starling Debit", category: "debit", markets: ["UK"], headline_metric: "0% FX worldwide", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Award-winning UK debit", pros: "0% FX, free worldwide ATMs, real-time notifications.", watch_out: "No cashback; purely functional travel card.", provider_url: "https://www.starlingbank.com/current-account/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-1", provider: "Boursorama Banque", product: "Welcome Visa", category: "debit", markets: ["FR"], headline_metric: "€0/mo", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "Free EU ATMs", cashback_reward: "-", best_for: "Free French debit", pros: "Free card, no conditions; BoursoBank's entry account.", watch_out: "FX fees apply outside EUR zone.", provider_url: "https://www.boursobank.com/banque-au-quotidien/cartes-bancaires/welcome/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "bunq", product: "bunq Travel Card", category: "debit", markets: ["NL", "DE", "FR", "IT", "ES"], headline_metric: "0% FX", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Travel debit EU", pros: "0% FX on any plan; included with bunq subscription.", watch_out: "Requires paid bunq plan; not a standalone card.", provider_url: "https://www.bunq.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-1", provider: "Openbank", product: "Tarjeta Open Débito", category: "debit", markets: ["ES"], headline_metric: "0% FX", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Free Spanish debit", pros: "Santander-backed; 0% FX globally; no annual fee.", watch_out: "Openbank account required to get the card.", provider_url: "https://www.openbank.es", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-3", provider: "Curve", product: "Curve Card", category: "debit", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "0% FX (limits)", amount_limit: "-", term: "-", fx_fee: "0% (in limits)", atm_fee: "€200/mo free", cashback_reward: "1% at 3 retailers", best_for: "All-cards-in-one", pros: "Link all existing cards; Go Back in Time feature to switch card post-spend.", watch_out: "FX limits apply; some banks block Curve.", provider_url: "https://www.curve.com/", url_type: "PRICING", url_verified_at: "" },

  // ─── TRANSFERS ────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Wise", product: "Wise Transfer", category: "transfers", markets: ["INT"], headline_metric: "~0.41% + small fixed fee", amount_limit: "Up to £1M+", term: "-", fx_fee: "Mid-market rate", atm_fee: "-", cashback_reward: "-", best_for: "Cheapest international", pros: "True mid-market rate; 160+ countries; transparent fee upfront.", watch_out: "Speed varies by corridor; bank-to-bank not instant everywhere.", provider_url: "https://wise.com/gb/send-money/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "INT-2", provider: "Revolut", product: "International Transfer", category: "transfers", markets: ["INT"], headline_metric: "0% (plan limits)", amount_limit: "-", term: "-", fx_fee: "0% in limits", atm_fee: "-", cashback_reward: "-", best_for: "Free within plan", pros: "Instant between Revolut users; 160+ countries from the app.", watch_out: "Outside plan allowance: 0.5% markup; weekend surcharge applies.", provider_url: "https://www.revolut.com/transfer-money-abroad/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Atlantic Money", product: "Atlantic Transfer", category: "transfers", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "£/€3 flat fee", amount_limit: "Up to £1M", term: "-", fx_fee: "Mid-market rate", atm_fee: "-", cashback_reward: "-", best_for: "Large transfer value", pros: "Flat £3/€3 fee regardless of amount — unbeatable for large transfers.", watch_out: "Minimum £/€10,000 to be cost-competitive vs Wise.", provider_url: "https://atlanticmoney.com/send-money", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-3", provider: "XE", product: "XE Money Transfer", category: "transfers", markets: ["INT"], headline_metric: "0% margin on FX", amount_limit: "Up to £350,000", term: "-", fx_fee: "Rate includes small margin", atm_fee: "-", cashback_reward: "-", best_for: "FX rate focus", pros: "XE rate engine; 130+ countries; rate hold available.", watch_out: "Hidden margin in rate; best for larger amounts.", provider_url: "https://www.xe.com/send-money/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-4", provider: "Remitly", product: "Remitly Express", category: "transfers", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Fast delivery options", pros: "Express delivery often under 1 hour; 100+ destination countries.", watch_out: "Economy option cheaper but 3-5 days; fees vary widely by corridor.", provider_url: "https://www.remitly.com/gb/en/how-it-works", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "WorldRemit", product: "WorldRemit Transfer", category: "transfers", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Mobile money delivery", pros: "Mobile wallet delivery in 50+ countries; cash pickup option.", watch_out: "Fees less predictable than Wise; rate varies by corridor.", provider_url: "https://www.worldremit.com/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-6", provider: "Paysend", product: "Paysend Global Transfer", category: "transfers", markets: ["INT"], headline_metric: "£1.50 fixed fee", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Card-to-card speed", pros: "Card-to-card in minutes; flat fee; 170+ countries.", watch_out: "FX margin embedded in rate; not mid-market.", provider_url: "https://paysend.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-7", provider: "CurrencyFair", product: "CurrencyFair Transfer", category: "transfers", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "~0.45% + €3 fee", amount_limit: "-", term: "-", fx_fee: "~0.45%", atm_fee: "-", cashback_reward: "-", best_for: "Peer-matched FX", pros: "Peer-to-peer matching can beat market rate; good for regular transfers.", watch_out: "Marketplace liquidity varies; best rates not always available.", provider_url: "https://www.currencyfair.com/exchange/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-8", provider: "Western Union", product: "WU Online Transfer", category: "transfers", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Cash pickup global", pros: "500,000+ agent locations worldwide; cash pickup instant.", watch_out: "Higher fees than digital-first rivals; FX rate less competitive.", provider_url: "https://www.westernunion.com/gb/en/send-money/", url_type: "PRODUCT", url_verified_at: "" },

  // ─── REMITTANCE ───────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Remitly", product: "Remitly", category: "remittance", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Fast diaspora transfers", pros: "Express under 1h; 100+ countries; mobile wallet delivery.", watch_out: "Fees vary widely; Economy cheaper but slow.", provider_url: "https://www.remitly.com/gb/en/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-2", provider: "WorldRemit", product: "WorldRemit", category: "remittance", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Mobile money delivery", pros: "Mobile wallet in 50+ countries; cash pickup option.", watch_out: "Fees less predictable than Wise.", provider_url: "https://www.worldremit.com/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-3", provider: "TaptapSend", product: "TaptapSend", category: "remittance", markets: ["INT"], headline_metric: "0% fees (most corridors)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Free Africa transfers", pros: "Zero fees to Africa and South Asia; rapid delivery.", watch_out: "Coverage limited; not all corridors supported.", provider_url: "https://www.taptapsend.com/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-4", provider: "Ria Money Transfer", product: "Ria", category: "remittance", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Global reach", pros: "Top 3 globally by volume; 165+ countries; cash pickup + bank.", watch_out: "Fees and rates less transparent than digital-first.", provider_url: "https://www.riamoneytransfer.com/en-gb/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "TransferGo", product: "TransferGo", category: "remittance", markets: ["INT"], headline_metric: "Variable (corridor)", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "CEE corridors", pros: "Specialists in Eastern European corridors; fast delivery.", watch_out: "Coverage thinner outside CEE compared to major players.", provider_url: "https://www.transfergo.com/en", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-6", provider: "Sendwave", product: "Sendwave", category: "remittance", markets: ["UK", "DE", "FR"], headline_metric: "0% fees", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Africa & Bangladesh", pros: "Zero fees to Africa and Bangladesh; instant mobile delivery.", watch_out: "Geographically limited to select corridors only.", provider_url: "https://www.sendwave.com/", url_type: "PRODUCT", url_verified_at: "" },

  // ─── EXCHANGE ─────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Wise", product: "Multi-currency Account", category: "exchange", markets: ["INT"], headline_metric: "Mid-market rate", amount_limit: "-", term: "-", fx_fee: "0.35–1% conversion", atm_fee: "-", cashback_reward: "-", best_for: "Lowest FX cost", pros: "True mid-market rate; hold 40+ currencies; convert instantly.", watch_out: "Small fee on every conversion; not zero-cost.", provider_url: "https://wise.com/gb/multi-currency-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "INT-2", provider: "Revolut", product: "Currency Exchange", category: "exchange", markets: ["INT"], headline_metric: "0% (plan limits)", amount_limit: "-", term: "-", fx_fee: "0% in limits", atm_fee: "-", cashback_reward: "-", best_for: "Instant in-app FX", pros: "Instant FX within plan allowance; 30+ currencies.", watch_out: "Weekend markup; limits exceeded = 0.5% fee.", provider_url: "https://www.revolut.com/currency-converter/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-3", provider: "CurrencyFair", product: "Peer-to-Peer FX", category: "exchange", markets: ["INT"], headline_metric: "~0.45% spread", amount_limit: "-", term: "-", fx_fee: "~0.45%", atm_fee: "-", cashback_reward: "-", best_for: "Beat the market rate", pros: "Peer-matched rates can beat interbank; great for regular transfers.", watch_out: "Liquidity varies; best rates not guaranteed.", provider_url: "https://www.currencyfair.com/personal/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-4", provider: "XE", product: "XE Currency Transfer", category: "exchange", markets: ["INT"], headline_metric: "Small margin on rate", amount_limit: "Up to £350,000", term: "-", fx_fee: "Margin in rate", atm_fee: "-", cashback_reward: "-", best_for: "Rate transparency", pros: "The original FX rate provider; good for large transfers.", watch_out: "Fee embedded in rate rather than quoted separately.", provider_url: "https://www.xe.com/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "Moneycorp", product: "Moneycorp Personal FX", category: "exchange", markets: ["UK", "DE", "FR", "ES", "IT"], headline_metric: "Bespoke rate", amount_limit: "-", term: "-", fx_fee: "Margin in rate", atm_fee: "-", cashback_reward: "-", best_for: "Large FX volumes", pros: "Dedicated dealer for large transfers; forward contracts available.", watch_out: "Not competitive on small amounts; relationship-driven.", provider_url: "https://www.moneycorp.com/en-gb/personal/", url_type: "PRODUCT", url_verified_at: "" },

  // ─── TRAVEL CARDS ─────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Wise", product: "Wise Card", category: "travel", markets: ["INT"], headline_metric: "Mid-market FX", amount_limit: "-", term: "-", fx_fee: "0.35–1%", atm_fee: "£200/mo free", cashback_reward: "-", best_for: "Cheapest travel card", pros: "True mid-market rate globally; accepted everywhere Visa is.", watch_out: "Conversion fee applies; not zero-cost unlike Revolut in limits.", provider_url: "https://wise.com/gb/card/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "INT-2", provider: "Revolut", product: "Revolut Card", category: "travel", markets: ["INT"], headline_metric: "0% FX (plan limits)", amount_limit: "-", term: "-", fx_fee: "0% in limits", atm_fee: "€200–2000/mo free", cashback_reward: "-", best_for: "Most popular travel card", pros: "0% FX within limits; accepted globally; instant freeze/unfreeze.", watch_out: "Weekend markup on Standard; limits on free ATM.", provider_url: "https://www.revolut.com/cards/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "UK-1", provider: "Chase UK", product: "Chase Debit", category: "travel", markets: ["UK"], headline_metric: "0% FX worldwide", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "1% cashback", best_for: "Best UK travel debit", pros: "0% FX, free global ATMs, 1% cashback — all on a free account.", watch_out: "UK-only account; cashback capped at £15/mo.", provider_url: "https://www.chase.co.uk/gb/en/product/chase-account/", url_type: "PRODUCT", url_verified_at: V },
  { rank: "UK-2", provider: "Halifax", product: "Clarity Credit Card", category: "travel", markets: ["UK"], headline_metric: "0% FX + 0% cash advance", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "0% abroad", cashback_reward: "-", best_for: "0% overseas credit card", pros: "No FX fees, no cash advance fee abroad — rare for a credit card.", watch_out: "Interest on cash withdrawals starts immediately (no interest-free period).", provider_url: "https://www.halifax.co.uk/creditcards/clarity-credit-card.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-3", provider: "Starling Bank", product: "Starling Debit", category: "travel", markets: ["UK"], headline_metric: "0% FX worldwide", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Award-winning travel debit", pros: "0% FX, free ATMs globally, real-time notifications.", watch_out: "No credit card features; debit only.", provider_url: "https://www.starlingbank.com/current-account/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-1", provider: "DKB", product: "DKB Visa", category: "travel", markets: ["DE"], headline_metric: "0% FX (Aktivkunde)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "German free travel card", pros: "0% FX, free worldwide ATMs for Aktivkunde — completely free.", watch_out: "Aktivkunde status required; debit card only.", provider_url: "https://www.dkb.de/privatkunden/visa-debitkarte/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-1", provider: "Boursorama Banque", product: "Visa Ultim", category: "travel", markets: ["FR"], headline_metric: "0% FX worldwide", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "Best French travel card", pros: "0% FX, free global ATMs; Boursobank's premium free tier.", watch_out: "Visa Ultim requires income conditions.", provider_url: "https://www.boursobank.com/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "bunq", product: "bunq Travel Card", category: "travel", markets: ["NL", "DE", "FR", "IT", "ES"], headline_metric: "0% FX", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "Free worldwide", cashback_reward: "-", best_for: "EU travel card", pros: "0% FX globally; included with bunq plan.", watch_out: "Paid bunq plan required.", provider_url: "https://www.bunq.com", url_type: "PRODUCT", url_verified_at: "" },

  // ─── LOANS ────────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Younited Credit", product: "Younited Personal Loan", category: "loans", markets: ["FR", "IT", "ES", "PT", "DE"], headline_metric: "3.9%–24.9% APR", amount_limit: "€1,000–€50,000", term: "6–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Pan-EU digital lender", pros: "Instant decision online; competitive APR for good credit across 5 markets.", watch_out: "Rate heavily depends on credit score; higher end for lower scores.", provider_url: "https://www.younited-credit.com/credit", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-1", provider: "ING", product: "ING Ratenkredit", category: "loans", markets: ["DE"], headline_metric: "3.99%–11.99% APR", amount_limit: "€5,000–€50,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Trusted DE bank loan", pros: "ING brand; no early repayment fee; fully online application.", watch_out: "Best rates require excellent Schufa score.", provider_url: "https://www.ing.de/kredit/ratenkredit/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-2", provider: "Auxmoney", product: "Auxmoney P2P Loan", category: "loans", markets: ["DE"], headline_metric: "3.72%–19.9% APR", amount_limit: "€1,000–€50,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "P2P for thin credit", pros: "Peer-funded; accessible to self-employed and non-standard borrowers.", watch_out: "Funding not guaranteed; can take days to fund.", provider_url: "https://www.auxmoney.com/kredit", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-3", provider: "Smava", product: "Smava Loan Marketplace", category: "loans", markets: ["DE"], headline_metric: "0.69%–19.9% APR", amount_limit: "€500–€120,000", term: "12–144 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Compare DE lenders", pros: "50+ lenders compared; soft check before hard pull; rate guarantee.", watch_out: "Aggregator — final rate set by underlying lender.", provider_url: "https://www.smava.de/kredit/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "FR-1", provider: "Cofidis", product: "Prêt Personnel Cofidis", category: "loans", markets: ["FR", "ES", "IT", "PT"], headline_metric: "Variable APR", amount_limit: "€1,000–€35,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Established FR lender", pros: "Established consumer lender; fast decisions online.", watch_out: "APR varies significantly; high end for low-credit applicants.", provider_url: "https://www.cofidis.fr/credit-personnel.html", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "FR-2", provider: "Cetelem", product: "Prêt Personnel Cetelem", category: "loans", markets: ["FR", "IT", "ES", "PT"], headline_metric: "Variable APR", amount_limit: "€500–€75,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "BNP-backed lending", pros: "BNP Paribas-owned; large origination volume; multiple product tiers.", watch_out: "Rates not always transparent upfront; check TAEG.", provider_url: "https://www.cetelem.fr/credit-personnel", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-1", provider: "Findomestic", product: "Prestito Personale", category: "loans", markets: ["IT"], headline_metric: "Variable APR", amount_limit: "€1,000–€30,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Top IT consumer lender", pros: "BNP-owned; widely available in Italy; fast online approval.", watch_out: "Rate varies; check TAEG carefully.", provider_url: "https://www.findomestic.it/prestiti/prestito-personale", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-2", provider: "Agos", product: "Agos Prestito Personale", category: "loans", markets: ["IT"], headline_metric: "Variable APR", amount_limit: "€1,000–€30,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "CA-backed IT loans", pros: "Crédit Agricole joint venture; strong distribution in IT.", watch_out: "Complex product range; compare TAEG carefully.", provider_url: "https://www.agos.it/prestiti/prestito-personale", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-1", provider: "Cofidis España", product: "Préstamo Proyecto", category: "loans", markets: ["ES"], headline_metric: "Variable APR", amount_limit: "€3,000–€30,000", term: "24–96 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Fast Spanish loan", pros: "Instant decision online; established brand in Spain.", watch_out: "High end of APR range for lower credit scores.", provider_url: "https://www.cofidis.es/es/prestamos/prestamo-proyecto.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Zopa", product: "Zopa Personal Loan", category: "loans", markets: ["UK"], headline_metric: "9.9%–29.9% APR", amount_limit: "£1,000–£25,000", term: "12–60 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Top UK digital lender", pros: "Soft eligibility check; good rates for good credit; FCA authorised.", watch_out: "High APR for poor credit; no joint loans.", provider_url: "https://www.zopa.com/loans", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-2", provider: "Lendable", product: "Lendable Personal Loan", category: "loans", markets: ["UK"], headline_metric: "12.9%–34.9% APR", amount_limit: "£1,000–£25,000", term: "12–60 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Fast UK decision", pros: "5-minute decision; same-day funding available.", watch_out: "Higher APR than bank loans; for those declined elsewhere.", provider_url: "https://www.lendable.co.uk/loans", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-3", provider: "M&S Bank", product: "M&S Personal Loan", category: "loans", markets: ["UK"], headline_metric: "6.9%–19.9% APR", amount_limit: "£1,000–£25,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "M&S points", best_for: "Loyalty + good rates", pros: "M&S Sparks points with loan; competitive mid-market APR.", watch_out: "M&S Sparks membership expected; rate varies.", provider_url: "https://bank.marksandspencer.com/loans/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "PT-1", provider: "Cofidis Portugal", product: "Crédito Pessoal", category: "loans", markets: ["PT"], headline_metric: "Variable APR", amount_limit: "€1,000–€35,000", term: "12–84 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Established PT lender", pros: "Well-known brand in Portugal; fully online application.", watch_out: "APR can be high; compare with Cetelem.", provider_url: "https://www.cofidis.pt/credito-pessoal/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "Lender&Spender", product: "Persoonlijke Lening", category: "loans", markets: ["NL"], headline_metric: "Variable APR", amount_limit: "€2,500–€75,000", term: "12–120 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Transparent NL lender", pros: "Fully online; transparent pricing; AFM authorised.", watch_out: "Rate depends on credit; not the cheapest for all profiles.", provider_url: "https://www.lenderspender.nl/persoonlijke-lening/", url_type: "PRODUCT", url_verified_at: "" },

  // ─── BNPL ─────────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Klarna", product: "Pay in 3 / Pay Later", category: "bnpl", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "0% (Pay in 3)", amount_limit: "Up to €1,000", term: "3 instalments / 30 days", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "World's largest BNPL", pros: "Accepted at 500,000+ EU retailers; smooth UX; instant approval.", watch_out: "Late fees apply; overspending risk; affects credit file in some markets.", provider_url: "https://www.klarna.com/uk/customer-service/pay-later/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-2", provider: "PayPal", product: "Pay in 3", category: "bnpl", markets: ["UK", "DE", "FR", "IT", "ES"], headline_metric: "0% interest", amount_limit: "£30–£2,000", term: "3 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "PayPal ecosystem BNPL", pros: "Available wherever PayPal is accepted; no hard credit check.", watch_out: "Only 3 instalments; limited to PayPal merchants.", provider_url: "https://www.paypal.com/uk/digital-wallet/ways-to-pay/buy-now-pay-later", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-1", provider: "Alma", product: "Pay in 3 / Pay in 4", category: "bnpl", markets: ["FR", "ES", "IT", "BE", "NL"], headline_metric: "0% (buyer-facing)", amount_limit: "€50–€30,000", term: "3–12 instalments", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "EU merchant BNPL", pros: "Merchant-funded; wide range of instalments including monthly plans.", watch_out: "Availability depends on merchant; not as widely accepted as Klarna.", provider_url: "https://www.getalma.eu/fr/paiement-fractionne", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "IT-1", provider: "Scalapay", product: "Pay in 3 / Pay in 4", category: "bnpl", markets: ["IT", "FR", "ES", "PT", "DE", "NL"], headline_metric: "0% interest", amount_limit: "Up to €1,500", term: "3–4 instalments", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Southern EU BNPL", pros: "Strong in Italy, France, Spain; 7,000+ merchants; fast checkout.", watch_out: "Limited outside listed markets; smaller network than Klarna.", provider_url: "https://www.scalapay.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "FR-2", provider: "Oney", product: "Oney 3x4x", category: "bnpl", markets: ["FR", "ES", "IT", "PT"], headline_metric: "0%–1.5% fee", amount_limit: "€100–€6,000", term: "3–4 instalments", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Retail-embedded BNPL", pros: "Deeply embedded in French and Spanish retail; BNP-owned.", watch_out: "Small service fee (not always 0%); check at checkout.", provider_url: "https://www.oney.fr/paiement-en-plusieurs-fois", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-1", provider: "Ratepay", product: "Ratepay Installments", category: "bnpl", markets: ["DE", "AT"], headline_metric: "0% (merchant-funded)", amount_limit: "-", term: "3–36 months", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "German BNPL", pros: "Dominant in DACH e-commerce; invoice and instalment options.", watch_out: "Not consumer-facing brand; dependent on merchant integration.", provider_url: "https://www.ratepay.com/zahlungsmethoden/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Clearpay", product: "Pay in 4", category: "bnpl", markets: ["UK", "FR", "IT", "ES"], headline_metric: "0% interest", amount_limit: "Up to £600", term: "4 instalments / 6 weeks", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Fashion & lifestyle UK", pros: "Strong UK brand; popular with fashion retailers; no interest ever.", watch_out: "Late fee of £6; low spending limits initially.", provider_url: "https://www.clearpay.co.uk/en-GB/how-it-works", url_type: "PRODUCT", url_verified_at: "" },

  // ─── INVESTMENTS ──────────────────────────────────────────────────────────

  { rank: "DE-1", provider: "Trade Republic", product: "ETF Savings Plans", category: "investments", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "INT"], headline_metric: "€1 minimum / €1 order fee", amount_limit: "-", term: "Flexible", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Cheapest EU investing", pros: "€1 minimum savings plan; 1 cent per trade; 8,000+ ETFs and stocks.", watch_out: "Mobile-only; no advanced charting tools.", provider_url: "https://traderepublic.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-1", provider: "DEGIRO", product: "Stocks & ETFs", category: "investments", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "UK"], headline_metric: "€1–3/trade", amount_limit: "-", term: "Flexible", fx_fee: "0.10% + €2.50", atm_fee: "-", cashback_reward: "-", best_for: "Low-cost EU brokerage", pros: "€1 per ETF order; 50+ exchanges; 18 EU countries; web + app.", watch_out: "FX fee applies; no ISA wrapper (UK); custody risk disclosure.", provider_url: "https://www.degiro.com/fees", url_type: "PRICING", url_verified_at: "" },
  { rank: "INT-2", provider: "Trading 212", product: "Invest & ISA", category: "investments", markets: ["UK", "DE", "FR", "IT", "ES", "NL"], headline_metric: "0% commission", amount_limit: "-", term: "Flexible", fx_fee: "0.15%", atm_fee: "-", cashback_reward: "-", best_for: "Commission-free EU stocks", pros: "0% commission on stocks/ETFs; ISA wrapper for UK; pie investing.", watch_out: "0.15% FX fee; CFD section not for beginners.", provider_url: "https://www.trading212.com/invest", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-2", provider: "Scalable Capital", product: "Scalable Broker", category: "investments", markets: ["DE", "AT", "FR", "IT", "ES", "NL"], headline_metric: "€0.99/trade or flat €4.99/mo", amount_limit: "-", term: "Flexible", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Robo + DIY investing DE", pros: "Commission-free on PRIME+; robo-advisory option; 2% on cash.", watch_out: "PRIME subscription needed for best deal.", provider_url: "https://de.scalable.capital/broker", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-3", provider: "eToro", product: "Stocks + ETFs + Copy Trading", category: "investments", markets: ["INT"], headline_metric: "0% commission (stocks)", amount_limit: "-", term: "Flexible", fx_fee: "1.50% USD conversion", atm_fee: "-", cashback_reward: "-", best_for: "Social/copy investing", pros: "Copy top investors automatically; 3,000+ stocks commission-free.", watch_out: "Withdrawal fee $5; 1.5% FX on USD-denominated stocks.", provider_url: "https://www.etoro.com/investing/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Hargreaves Lansdown", product: "Stocks & Shares ISA", category: "investments", markets: ["UK"], headline_metric: "0.45% platform fee", amount_limit: "£20,000/yr (ISA)", term: "Flexible", fx_fee: "1.00%", atm_fee: "-", cashback_reward: "-", best_for: "UK's trusted ISA", pros: "Best UK customer service; widest fund range; FSCS protected.", watch_out: "0.45% annual fee is expensive for large portfolios.", provider_url: "https://www.hl.co.uk/investment-services/isa", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "UK-2", provider: "Vanguard Investor", product: "Vanguard Index Funds + ETFs", category: "investments", markets: ["UK"], headline_metric: "0.15% platform cap", amount_limit: "-", term: "Flexible", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Index fund passive investing", pros: "Lowest platform cap at 0.15% (£375/yr max); own funds at 0.07%+.", watch_out: "Vanguard funds only; limited stock-picking.", provider_url: "https://www.vanguardinvestor.co.uk/investments", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-4", provider: "XTB", product: "xStation Stocks & ETFs", category: "investments", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "UK"], headline_metric: "0% commission (up to €100k/mo)", amount_limit: "-", term: "Flexible", fx_fee: "0.50%", atm_fee: "-", cashback_reward: "-", best_for: "Active EU trader", pros: "0% commission to €100k/mo; xStation 5 is excellent platform.", watch_out: "0.2% fee above €100k/mo; CFDs included — caution.", provider_url: "https://www.xtb.com/en/offer/stocks-and-etfs", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "Lightyear", product: "Stocks + ETFs + Cash", category: "investments", markets: ["UK", "DE", "FR", "IT", "ES", "NL"], headline_metric: "0% commission + 4%+ on cash", amount_limit: "-", term: "Flexible", fx_fee: "0.35%", atm_fee: "-", cashback_reward: "-", best_for: "Earn while investing", pros: "0% commission; 4%+ on uninvested cash; multi-currency accounts.", watch_out: "Newer platform; limited fund selection vs HL.", provider_url: "https://lightyear.com", url_type: "PRODUCT", url_verified_at: "" },

  // ─── TRADING ──────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Interactive Brokers", product: "IBKR Pro / Lite", category: "trading", markets: ["INT"], headline_metric: "€0.05–1.25/trade", amount_limit: "-", term: "-", fx_fee: "0.002%", atm_fee: "-", cashback_reward: "-", best_for: "Pro multi-asset trading", pros: "Lowest margin rates; 135 markets; pro-grade tools; FX at interbank.", watch_out: "Complex platform; inactivity fee on small accounts.", provider_url: "https://www.interactivebrokers.com/en/trading/tws.php", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "IG", product: "IG Trading Platform", category: "trading", markets: ["UK", "DE", "FR", "IT", "ES", "NL"], headline_metric: "Variable spread", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "CFDs + shares UK", pros: "Most established UK CFD broker; 17,000+ markets; ISA + SIPP.", watch_out: "CFDs carry high risk; 76% of retail accounts lose.", provider_url: "https://www.ig.com/uk/trading-platforms", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-2", provider: "Saxo", product: "SaxoTraderGO / Pro", category: "trading", markets: ["INT"], headline_metric: "€1+ per trade", amount_limit: "-", term: "-", fx_fee: "0.50%", atm_fee: "-", cashback_reward: "-", best_for: "Premium multi-asset", pros: "71,000+ instruments; professional-grade tools; bonds and futures.", watch_out: "High minimum deposit; expensive for small portfolios.", provider_url: "https://www.home.saxo/platforms", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-3", provider: "XTB", product: "xStation 5", category: "trading", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "0% commission (to €100k/mo)", amount_limit: "-", term: "-", fx_fee: "0.50%", atm_fee: "-", cashback_reward: "-", best_for: "Active EU trader", pros: "Award-winning platform; 0% on stocks to €100k/mo; FX + CFDs.", watch_out: "CFDs high risk; 0.2% above €100k/mo threshold.", provider_url: "https://www.xtb.com/en/platforms", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-4", provider: "eToro", product: "CopyTrader", category: "trading", markets: ["INT"], headline_metric: "0% commission (stocks)", amount_limit: "-", term: "-", fx_fee: "1.50%", atm_fee: "-", cashback_reward: "-", best_for: "Copy trading", pros: "Copy top traders automatically; social feed; 3,000+ markets.", watch_out: "Withdrawal fee $5; FX fee on USD pairs.", provider_url: "https://www.etoro.com/copytrader/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "CMC Markets", product: "CMC Next Generation", category: "trading", markets: ["UK", "DE", "FR", "IT", "ES", "NL"], headline_metric: "Variable spread", amount_limit: "-", term: "-", fx_fee: "Variable", atm_fee: "-", cashback_reward: "-", best_for: "Advanced charting", pros: "Next Gen platform rated best for charting; 12,000+ instruments.", watch_out: "CFDs only; 70%+ of retail accounts lose.", provider_url: "https://www.cmcmarkets.com/en/trading-platforms/next-generation", url_type: "PRODUCT", url_verified_at: "" },

  // ─── CRYPTO ───────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "Kraken", product: "Kraken Exchange", category: "crypto", markets: ["INT"], headline_metric: "Trading fee 0.16–0.26%", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Most trusted exchange", pros: "Top security record; 200+ assets; Pro platform for advanced trading.", watch_out: "UI can be complex for beginners; no ISA wrapper.", provider_url: "https://www.kraken.com/features/fee-schedule", url_type: "PRICING", url_verified_at: "" },
  { rank: "INT-2", provider: "Coinbase", product: "Coinbase / Advanced Trade", category: "crypto", markets: ["INT"], headline_metric: "0.6% (standard) / 0.05% (Advanced)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Easiest EU crypto onramp", pros: "Largest fiat-to-crypto gateway; regulated in EU; USDC earning.", watch_out: "Standard fees high; switch to Advanced Trade to cut cost.", provider_url: "https://www.coinbase.com/explore", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "AT-1", provider: "Bitpanda", product: "Bitpanda Crypto", category: "crypto", markets: ["DE", "FR", "IT", "ES", "NL", "PT", "INT"], headline_metric: "1.49% (Bitpanda) / 0.10% (Pro)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Best EU-regulated exchange", pros: "Austrian-regulated; stocks + ETFs + crypto + metals in one app.", watch_out: "Standard spread high; use Bitpanda Pro for serious trading.", provider_url: "https://www.bitpanda.com", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "Bitvavo", product: "Bitvavo Exchange", category: "crypto", markets: ["NL", "DE", "FR", "IT", "ES", "PT"], headline_metric: "Trading fee 0.15–0.25%", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Best EU-local exchange", pros: "Dutch-registered; strong EUR pairs; low fees; staking available.", watch_out: "Smaller liquidity than global exchanges for altcoins.", provider_url: "https://bitvavo.com/en/fees", url_type: "PRICING", url_verified_at: "" },
  { rank: "INT-3", provider: "Binance", product: "Binance Exchange", category: "crypto", markets: ["INT"], headline_metric: "Trading fee from 0.10%", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Largest exchange globally", pros: "Deepest liquidity; 350+ assets; lowest base fees; staking.", watch_out: "Regulatory challenges in some EU countries; complex for beginners.", provider_url: "https://www.binance.com/en/trade/BTC_EUR", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-4", provider: "Revolut", product: "Revolut Crypto", category: "crypto", markets: ["UK", "DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "1.49% (Standard) / 0% (Metal+)", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "In-app crypto for non-traders", pros: "No separate account needed; 100+ coins inside Revolut app.", watch_out: "High spread on Standard; not a real exchange (custody risk).", provider_url: "https://www.revolut.com/crypto/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-1", provider: "N26", product: "N26 Crypto (via Bitpanda)", category: "crypto", markets: ["DE", "FR", "IT", "ES", "NL", "PT"], headline_metric: "1.49% spread", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Crypto inside N26 app", pros: "Bitpanda-powered; convenient for existing N26 users.", watch_out: "Powered by Bitpanda with higher fees than standalone Bitpanda Pro.", provider_url: "https://n26.com/en-eu/crypto", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-5", provider: "eToro", product: "eToro Crypto", category: "crypto", markets: ["INT"], headline_metric: "1% spread", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Social crypto investing", pros: "Copy crypto traders; 70+ coins; regulated in EU (CySEC).", watch_out: "Higher spread than dedicated exchanges; $5 withdrawal fee.", provider_url: "https://www.etoro.com/crypto/", url_type: "PRODUCT", url_verified_at: "" },

  // ─── INSURANCE ────────────────────────────────────────────────────────────

  { rank: "DE-1", provider: "HUK24", product: "HUK24 Kfz-Versicherung", category: "insurance", markets: ["DE"], headline_metric: "Variable", amount_limit: "-", term: "Annual", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Best-value DE car insurance", pros: "Top-rated direct car insurer in Germany; highly competitive premium.", watch_out: "Online-only; limited for unusual risk profiles.", provider_url: "https://www.huk24.de/kfz-versicherung.html", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "DE-2", provider: "Allianz Direct", product: "Allianz Direct Auto", category: "insurance", markets: ["DE", "ES", "IT", "NL"], headline_metric: "Variable", amount_limit: "-", term: "Annual", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Digital Allianz insurance", pros: "Full Allianz brand backing; digital-first pricing; fast claims.", watch_out: "Not always cheapest; Allianz brand commands premium.", provider_url: "https://www.allianzdirect.de/autoversicherung/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "UK-1", provider: "Admiral", product: "Admiral Car Insurance", category: "insurance", markets: ["UK"], headline_metric: "Variable", amount_limit: "-", term: "Annual", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Multi-car UK", pros: "Multi-car discount up to 25%; established FCA authorised.", watch_out: "Rates vary; always compare at renewal.", provider_url: "https://www.admiral.com/car-insurance", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-1", provider: "WorldNomads", product: "Travel Insurance", category: "insurance", markets: ["INT"], headline_metric: "Variable", amount_limit: "Medical: up to $10M", term: "Per trip / Annual", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Travel insurance INT", pros: "Covers 200+ activities; buy while already travelling; widely accepted.", watch_out: "Adventure sports have exclusions; read T&Cs carefully.", provider_url: "https://www.worldnomads.com/travel-insurance/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "INT-2", provider: "AXA", product: "AXA Travel Insurance", category: "insurance", markets: ["FR", "DE", "IT", "ES", "UK"], headline_metric: "Variable", amount_limit: "-", term: "Per trip / Annual", fx_fee: "-", atm_fee: "-", cashback_reward: "-", best_for: "Blue-chip travel cover", pros: "AXA brand; strong claims handling; annual multi-trip options.", watch_out: "Not always cheapest; compare before buying.", provider_url: "https://www.axa.com/en/insurance/travel-insurance", url_type: "PRODUCT", url_verified_at: "" },

  // ─── WALLETS ──────────────────────────────────────────────────────────────

  { rank: "INT-1", provider: "PayPal", product: "PayPal Wallet", category: "wallets", markets: ["INT"], headline_metric: "0% P2P (EUR)", amount_limit: "-", term: "-", fx_fee: "3–4% international", atm_fee: "-", cashback_reward: "-", best_for: "Most accepted e-wallet", pros: "Accepted at 30M+ merchants; buyer protection; 200+ countries.", watch_out: "International FX fee 3-4%; currency conversion spread.", provider_url: "https://www.paypal.com/uk/digital-wallet/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "ES-1", provider: "Bizum", product: "Bizum", category: "wallets", markets: ["ES"], headline_metric: "0% P2P", amount_limit: "€500/transaction", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Instant Spanish P2P", pros: "Integrated into all Spanish banking apps; instant; free.", watch_out: "Spain-only; no international transfers.", provider_url: "https://bizum.es/que-es-bizum/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "IT-1", provider: "Satispay", product: "Satispay", category: "wallets", markets: ["IT"], headline_metric: "0% under €10", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "Cashback at partners", best_for: "Italian P2P & retail", pros: "Accepted in 300,000+ Italian shops; P2P free; cashback offers.", watch_out: "Italy-focused; limited use outside Italy.", provider_url: "https://www.satispay.com/it-it/uso-personale/", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-1", provider: "Tikkie", product: "Tikkie", category: "wallets", markets: ["NL"], headline_metric: "0% for consumers", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Dutch bill splitting", pros: "Most-used bill-splitting app in NL; instant iDEAL settlement.", watch_out: "NL-only; requires Dutch bank account.", provider_url: "https://www.tikkie.me/wat-is-tikkie", url_type: "PRODUCT", url_verified_at: "" },
  { rank: "NL-2", provider: "iDEAL", product: "iDEAL Checkout", category: "wallets", markets: ["NL"], headline_metric: "0% consumer fee", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Dutch online checkout", pros: "Standard Dutch online payment rail; instant settlement; universal.", watch_out: "NL only; not a standalone wallet — bank account required.", provider_url: "https://www.ideal.nl/en/consumer/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "PT-1", provider: "MB Way", product: "MB Way", category: "wallets", markets: ["PT"], headline_metric: "0% P2P", amount_limit: "€500/day", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "Portuguese P2P standard", pros: "Universal in Portugal; accepted for P2P, online, and in-store.", watch_out: "PT-only; limits apply per day.", provider_url: "https://www.mbway.pt/o-que-e/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "INT-2", provider: "Wero", product: "Wero by EPI", category: "wallets", markets: ["FR", "DE", "BE", "NL"], headline_metric: "0% P2P", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "European P2P successor", pros: "EPI-backed successor to giropay and Paylib; growing EU rollout.", watch_out: "Still rolling out; not yet universally available.", provider_url: "https://wero-wallet.eu/", url_type: "CATEGORY_LANDING", url_verified_at: "" },
  { rank: "FR-1", provider: "Lydia", product: "Lydia App", category: "wallets", markets: ["FR"], headline_metric: "0% P2P", amount_limit: "-", term: "-", fx_fee: "0%", atm_fee: "-", cashback_reward: "-", best_for: "French P2P leader", pros: "Most popular French P2P app; instant transfers; Lydia Blue/Black plans.", watch_out: "France-focused; FX fee for international transfers.", provider_url: "https://lydia-app.com/fr/", url_type: "PRODUCT", url_verified_at: "" },
];

export const providerCatalogueByCategory = (category: string): ProviderEntry[] =>
  providerCatalogue.filter((e) => e.category === category);

export const providerCatalogueByMarket = (market: string): ProviderEntry[] =>
  providerCatalogue.filter((e) => e.markets.includes(market));

export const pendingEntries = (): ProviderEntry[] =>
  providerCatalogue.filter((e) => e.provider_url === "PENDING_DEEP_LINK");
