import 'dart:async';
import 'dart:io' show Platform;

import 'package:dio/dio.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:payn_mobile/core/network/api_client.dart';

// ─── Payn push service ───────────────────────────────────────────────────────
//
// Owns the entire mobile push lifecycle:
//   1. Initialise Firebase Core (using the Dart `firebase_options.dart`
//      generated by `flutterfire configure`).
//   2. Request notification permission on iOS / Android 13+.
//   3. Acquire the FCM registration token, send it to
//      /api/admin/push/register so it shows up in the admin dashboard.
//   4. Listen for token refreshes and re-register.
//   5. Render foreground messages via flutter_local_notifications so the
//      user sees a banner without backgrounding the app (FCM only paints
//      the banner automatically when the app is backgrounded).
//
// The service is **defensive**: every step is wrapped so a missing
// GoogleService-Info.plist / google-services.json (i.e. Firebase isn't
// configured yet) doesn't crash the app — it logs a warning and stays
// idle. The mobile app keeps working; push just doesn't fire until the
// Firebase files land. This lets the codebase compile + ship before the
// Firebase project is set up.

class PushService {
  PushService({
    required ApiClient apiClient,
    String? country,
    String? locale,
  })  : _client = apiClient,
        _country = country,
        _locale = locale;

  final ApiClient _client;
  String? _country;
  String? _locale;

  bool _initialised = false;
  String? _currentToken;
  StreamSubscription<RemoteMessage>? _foregroundSub;
  StreamSubscription<RemoteMessage>? _openedAppSub;
  StreamSubscription<String>? _tokenRefreshSub;
  FlutterLocalNotificationsPlugin? _localNotifications;

  // PR-INT-01 — Tap-to-route handling. The router (GoRouter) doesn't
  // exist yet when bootstrap creates PushService — we don't have a
  // BuildContext to push from. So we accept the navigation callback
  // lazily: PaynApp calls `attachRouter()` in initState once the
  // router is mounted. Any taps that fire BEFORE that (most commonly
  // `getInitialMessage()` resolving on cold-start) get buffered in
  // `_pendingRoute` and replayed when the router attaches.
  void Function(String route)? _onOpenRoute;
  String? _pendingRoute;

  /// Wire the router callback. Safe to call once PaynApp's root
  /// widget has been built. Replays the pending cold-start route if
  /// one arrived before the router was ready.
  void attachRouter(void Function(String route) onOpenRoute) {
    _onOpenRoute = onOpenRoute;
    final pending = _pendingRoute;
    if (pending != null) {
      _pendingRoute = null;
      onOpenRoute(pending);
    }
  }

  void _handleTap(String? route) {
    if (route == null || route.isEmpty) return;
    final cb = _onOpenRoute;
    if (cb != null) {
      cb(route);
    } else {
      // Router not attached yet — buffer until attachRouter() runs.
      _pendingRoute = route;
    }
  }

  // Called from bootstrap after AppController + Firebase init. Safe to
  // call multiple times — re-init is a no-op.
  //
  // MOB.11 — Whole flow is wrapped in a single guarded block + each
  // remote call sits inside its own try/catch. Previously a missing
  // APNs entitlement (which happens any time the app is signed by a
  // free Personal Apple Team — no aps-environment plist key allowed)
  // threw `firebase_messaging/apns-token-not-set` from `getToken()`,
  // which bubbled up as an unhandled async exception. In debug that
  // shows as a console warning; in profile / release it can terminate
  // the app at startup. We now treat ANY push-init failure as "push
  // is unavailable on this build" and silently no-op, leaving the rest
  // of the app fully functional.
  Future<void> initialise() async {
    if (_initialised) return;
    _initialised = true;

    try {
      await _ensureFirebase();
    } catch (e) {
      debugPrint('[PushService] Firebase init skipped — $e');
      return;
    }

    final messaging = FirebaseMessaging.instance;

    NotificationSettings settings;
    try {
      settings = await messaging.requestPermission(
        alert: true,
        badge: true,
        sound: true,
        provisional: false,
      );
    } catch (e) {
      debugPrint('[PushService] requestPermission failed — $e');
      return;
    }
    if (settings.authorizationStatus == AuthorizationStatus.denied) {
      debugPrint('[PushService] User denied push permission — skipping.');
      return;
    }

    try {
      await _initialiseLocalNotifications();
    } catch (e) {
      debugPrint('[PushService] Local-notifications init failed — $e');
      // Continue — local UI fallback is a nice-to-have, not a blocker.
    }

    // APNs token must resolve before requesting the FCM token on iOS,
    // otherwise getToken() returns null on the first launch after grant.
    if (Platform.isIOS || Platform.isMacOS) {
      try {
        await messaging.getAPNSToken();
      } catch (_) {}
    }

    String? token;
    try {
      token = await messaging.getToken();
    } catch (e) {
      // No APNs entitlement on the active provisioning profile (most
      // common cause: signed with a free Personal team), or the
      // Firebase project doesn't have a server key yet. Either way,
      // push is unavailable for this build — bail without breaking
      // the rest of the app.
      debugPrint('[PushService] getToken failed — $e');
      return;
    }
    if (token != null && token.isNotEmpty) {
      _currentToken = token;
      unawaited(_registerToken(token));
    }

    _tokenRefreshSub?.cancel();
    try {
      _tokenRefreshSub = messaging.onTokenRefresh.listen((next) {
        _currentToken = next;
        unawaited(_registerToken(next));
      });
    } catch (e) {
      debugPrint('[PushService] onTokenRefresh subscribe failed — $e');
    }

    _foregroundSub?.cancel();
    try {
      _foregroundSub = FirebaseMessaging.onMessage.listen(_renderForeground);
    } catch (e) {
      debugPrint('[PushService] onMessage subscribe failed — $e');
    }

    // PR-INT-01 — Tap-to-open routing. Three entry points:
    //
    //   1. `getInitialMessage()` — the app was COLD-STARTED by tapping
    //      a notification. Fires once on startup; null if the user
    //      opened the app from the home screen instead.
    //
    //   2. `onMessageOpenedApp` — the app was already alive in the
    //      background and the user tapped a banner. Fires every time.
    //
    //   3. The foreground-rendered banner from flutter_local_notif —
    //      wired in `_initialiseLocalNotifications()` via the
    //      `onDidReceiveNotificationResponse` callback so a tap on
    //      our own banner ends up in the same router.
    //
    // All three funnel into `_handleTap()` which either calls the
    // router callback (if attached) or buffers the route.
    try {
      final initial = await messaging.getInitialMessage();
      if (initial != null) {
        _handleTap(initial.data['route']?.toString());
      }
    } catch (e) {
      debugPrint('[PushService] getInitialMessage failed — $e');
    }

    _openedAppSub?.cancel();
    try {
      _openedAppSub = FirebaseMessaging.onMessageOpenedApp.listen((message) {
        _handleTap(message.data['route']?.toString());
      });
    } catch (e) {
      debugPrint('[PushService] onMessageOpenedApp subscribe failed — $e');
    }
  }

  // Should be called whenever the app's locale / market changes so the
  // admin dashboard can target the device by its current country/lang.
  Future<void> updateContext({String? country, String? locale}) async {
    final changed = country != _country || locale != _locale;
    if (!changed) return;
    _country = country;
    _locale = locale;
    final token = _currentToken;
    if (token != null) {
      unawaited(_registerToken(token));
    }
  }

  Future<void> dispose() async {
    await _foregroundSub?.cancel();
    await _openedAppSub?.cancel();
    await _tokenRefreshSub?.cancel();
  }

  Future<void> _ensureFirebase() async {
    // Plain `Firebase.initializeApp()` reads native config from
    // GoogleService-Info.plist / google-services.json. When neither
    // file is present (or the app id doesn't match), the call throws
    // a FirebaseException — caught by the outer try in initialise().
    if (Firebase.apps.isNotEmpty) return;
    await Firebase.initializeApp();
  }

  Future<void> _initialiseLocalNotifications() async {
    final plugin = FlutterLocalNotificationsPlugin();
    const initSettings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
      iOS: DarwinInitializationSettings(
        requestAlertPermission: false,
        requestBadgePermission: false,
        requestSoundPermission: false,
      ),
    );
    // PR-INT-01 — `onDidReceiveNotificationResponse` fires when the
    // user taps a banner we rendered ourselves (foreground push).
    // The payload string here is the same `route` we passed to
    // `plugin.show(... payload: ...)` in `_renderForeground()`.
    await plugin.initialize(
      initSettings,
      onDidReceiveNotificationResponse: (NotificationResponse response) {
        _handleTap(response.payload);
      },
    );

    // Create the Android channel the FCM service routes notifications
    // to. iOS doesn't need this — the OS handles channels automatically.
    final androidPlugin = plugin.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await androidPlugin?.createNotificationChannel(
      const AndroidNotificationChannel(
        'payn_default',
        'Payn updates',
        description:
            'Offer alerts, rate changes, and important account notifications.',
        importance: Importance.high,
      ),
    );
    _localNotifications = plugin;
  }

  Future<void> _registerToken(String token) async {
    try {
      await _client.dio.post<dynamic>(
        '/api/admin/push/register',
        data: <String, dynamic>{
          'token': token,
          'platform': Platform.isIOS ? 'ios' : 'android',
          if (_locale != null) 'locale': _locale,
          if (_country != null) 'country': _country,
        },
        options: Options(
          headers: <String, dynamic>{'Content-Type': 'application/json'},
        ),
      );
    } on DioException catch (e) {
      debugPrint('[PushService] Token registration failed: ${e.message}');
    } catch (e) {
      debugPrint('[PushService] Token registration failed: $e');
    }
  }

  Future<void> _renderForeground(RemoteMessage message) async {
    final plugin = _localNotifications;
    if (plugin == null) return;
    final notification = message.notification;
    if (notification == null) return;
    final title = notification.title ?? 'Payn';
    final body = notification.body ?? '';

    await plugin.show(
      message.hashCode,
      title,
      body,
      const NotificationDetails(
        android: AndroidNotificationDetails(
          'payn_default',
          'Payn updates',
          channelDescription:
              'Offer alerts, rate changes, and important account notifications.',
          importance: Importance.high,
          priority: Priority.high,
        ),
        iOS: DarwinNotificationDetails(presentBanner: true, presentSound: true),
      ),
      payload: message.data['route']?.toString(),
    );
  }
}
