// Mirrors apps/web/src/features/catalog/known-logos.generated.ts.
// Regenerate by copying that file's slug list when web's logo set changes.
// We keep an explicit set on mobile (instead of just trying any URL) so we
// don't fire 302 unnecessary 404s on cold scroll through Explore.
const Set<String> kKnownProviderLogos = <String>{
  'abn-amro',
  'admiral',
  'aion-bank',
  'alan',
  'allianz',
  'allianz-care',
  'allianz-direct',
  'anna-money',
  'atlantic-money',
  'auxmoney',
  'aviva',
  'bank-norwegian',
  'barclaycard',
  'barclays',
  'bbva',
  'binance',
  'binance-eu',
  'bitpanda',
  'bnp-paribas',
  'bondora',
  'boursobank',
  'bunq',
  'bupa-global',
  'c24-bank',
  'caixabank',
  'cardif',
  'cetelem',
  'chase-uk',
  'chip',
  'cigna-global',
  'cleo',
  'cofidis',
  'coinbase',
  'credit-agricole',
  'credit-mutuel',
  'creditea',
  'currencies-direct',
  'currencyfair',
  'curve',
  'deel',
  'degiro',
  'deutsche-bank',
  'ebury',
  'emma',
  'ergo',
  'etoro',
  'ferratum',
  'fidelidade',
  'finom',
  'freetrade',
  'generali',
  'genki',
  'gohenry',
  'gosimpletax',
  'heymondo',
  'holvi',
  'ing',
  'insured-nomads',
  'interactive-brokers',
  'intesa-sanpaolo',
  'klarna',
  'kraken',
  'ledger',
  'lemonade',
  'lightyear',
  'linxea',
  'lunar',
  'mbank',
  'mettle',
  'millennium-bcp',
  'monese',
  'monex-europe',
  'moneygram',
  'monzo',
  'moss',
  'n26',
  'nationwide',
  'nickel',
  'ofx',
  'op-financial-group',
  'openbank',
  'passportcard',
  'payoneer',
  'paypal',
  'paysend',
  'paysera',
  'pixpay',
  'pko-bank-polski',
  'pleo',
  'plum',
  'plutus',
  'postbank',
  'qonto',
  'raiffeisen-bank',
  'raisin',
  'remitly',
  'remote',
  'revolut',
  'rooster-money',
  'safetywing',
  'santander',
  'saxo',
  'scalable-capital',
  'scalapay',
  'sendwave',
  'skrill',
  'small-world',
  'smava',
  'snoop',
  'sogexia',
  'soldo',
  'spendesk',
  'starling-bank',
  'starling-kite',
  'tide',
  'tomorrow-bank',
  'torfx',
  'trade-republic',
  'trading-212',
  'trezor',
  'unicredit',
  'vivid',
  'vivid-money',
  'western-union',
  'wirex',
  'wise',
  'wise-business',
  'world-nomads',
  'worldnomads',
  'worldremit',
  'xe',
  'xtb',
  'ynab',
  'younited-credit',
  'zopa',
};

String providerToSlug(String name) {
  final lower = name.trim().toLowerCase();
  final hyphenated = lower.replaceAll(RegExp(r'\s+'), '-');
  return hyphenated.replaceAll(RegExp(r'[^a-z0-9-]'), '');
}

String? providerLogoUrl(String providerName, {required String origin}) {
  final slug = providerToSlug(providerName);
  if (!kKnownProviderLogos.contains(slug)) return null;
  return '$origin/logos/$slug.png';
}
