export {
  getCategoryOffersForCountrySelection,
  getCountryCode as getResidenceCountryCode,
  getCountryCurrency as getResidenceCountryCurrency,
  getCountryOption as getResidenceCountryOption,
  getCountrySelectorOptions,
  getDefaultCountryForLocale,
  getOffersForCountrySelection,
  individualCountryOptions as residenceCountryOptions,
  isSupportedCountrySelection,
  marketScopeOptions,
  matchesOfferCountrySelection,
  normalizeCountrySelection as normalizeResidenceCountry,
  resolveCountryFromLegacyMarket,
  resolveCountryLegacyMarket as resolveResidenceCountryMarket,
  supportedCountryOptions,
  type CountryOption as ResidenceCountryOption,
  type UserProfileMarketScope,
} from "@/lib/countries";
